"""CS systems: operating systems, compilers, automata, distributed systems, formal methods,
performance, compression, debugging. Atlas-matching names where entries exist."""

from .common import CC_BY_SA, wiki

DOMAINS = {
    "operating-systems": {
        "tags": ["operating system", "os kernel", "virtual memory", "process scheduling", "os theory"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Operating_system",
            "Kernel_(operating_system)",
            "Scheduling_(computing)",
            "File_system",
            "System_call",
            "Inter-process_communication",
            "Paging",
            "Context_switch",
            "Device_driver",
            "Memory_management",
            "Page_replacement_algorithm",
            "Thrashing_(computer_science)",
        ),
    },
    "compilers-and-parsing": {
        "tags": ["compiler construction", "parser generator", "syntax analysis", "lexer", "lexical analysis", "abstract syntax tree"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Compiler",
            "Parsing",
            "Lexical_analysis",
            "Abstract_syntax_tree",
            "Context-free_grammar",
            "LL_parser",
            "LR_parser",
            "Recursive_descent_parser",
            "Code_generation_(compiler)",
            "Optimizing_compiler",
            "Just-in-time_compilation",
            "Garbage_collection_(computer_science)",
            "Intermediate_representation",
            "Linker_(computing)",
        ),
    },
    "automata-formal-languages": {
        "tags": ["automata", "automaton", "finite state machine", "formal language", "context-free grammar", "turing machine"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Automata_theory",
            "Finite-state_machine",
            "Regular_language",
            "Pushdown_automaton",
            "Turing_machine",
            "Formal_language",
            "Chomsky_hierarchy",
            "Halting_problem",
            "Deterministic_finite_automaton",
            "Nondeterministic_finite_automaton",
        ),
    },
    "distributed-systems": {
        "tags": ["distributed system", "distributed computing", "cap theorem", "consistency model", "eventual consistency"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Distributed_computing",
            "CAP_theorem",
            "Consistency_model",
            "Eventual_consistency",
            "Two-phase_commit_protocol",
            "Vector_clock",
            "Lamport_timestamp",
            "Gossip_protocol",
            "Load_balancing_(computing)",
            "Replication_(computing)",
            "MapReduce",
            "Fallacies_of_distributed_computing",
            "Idempotence",
        ),
    },
    "consensus-algorithms": {
        "tags": ["consensus algorithm", "consensus protocol", "raft", "paxos", "leader election"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Consensus_(computer_science)",
            "Paxos_(computer_science)",
            "Raft_(algorithm)",
            "Byzantine_fault",
            "State_machine_replication",
            "Leader_election",
            "Quorum_(distributed_computing)",
        ),
    },
    "complexity-theory": {
        "tags": ["complexity theory", "computational complexity", "np-complete", "np-hard", "time complexity"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Computational_complexity_theory",
            "NP-completeness",
            "P_versus_NP_problem",
            "NP-hardness",
            "Reduction_(complexity)",
            "Approximation_algorithm",
            "Randomized_algorithm",
            "Amortized_analysis",
            "Time_complexity",
            "Space_complexity",
        ),
    },
    "formal-methods": {
        "tags": ["formal verification", "model checking", "tla+", "hoare logic", "design by contract", "static analysis"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Formal_verification",
            "Formal_methods",
            "Model_checking",
            "TLA%2B",
            "Hoare_logic",
            "Formal_specification",
            "Design_by_contract",
            "Temporal_logic",
            "Static_program_analysis",
            "Abstract_interpretation",
            "Invariant_(mathematics)",
            "Satisfiability_modulo_theories",
        ),
    },
    "performance-engineering": {
        "tags": ["performance optimization", "profiling", "benchmark", "memoization", "latency", "throughput"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Program_optimization",
            "Profiling_(computer_programming)",
            "Benchmark_(computing)",
            "Cache_(computing)",
            "Memoization",
            "Lazy_evaluation",
            "Amdahl's_law",
            "Locality_of_reference",
            "Space%E2%80%93time_tradeoff",
            "Latency_(engineering)",
            "Throughput",
            "Loop_optimization",
        ),
    },
    "compression": {
        "tags": ["data compression", "huffman", "lz77", "deflate", "run-length encoding", "codec"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Data_compression",
            "Huffman_coding",
            "Lempel%E2%80%93Ziv%E2%80%93Welch",
            "LZ77_and_LZ78",
            "Deflate",
            "Run-length_encoding",
            "Arithmetic_coding",
            "Lossless_compression",
            "Lossy_compression",
            "Burrows%E2%80%93Wheeler_transform",
            "Zstd",
        ),
    },
    "gdb-debugging": {
        "tags": ["gdb", "gdb debugging", "gdb debugger", "gdb breakpoint", "core dump"],
        "license": CC_BY_SA,
        "pages": wiki(
            "GNU_Debugger",
            "Debugging",
            "Breakpoint",
            "Core_dump",
            "Valgrind",
            "AddressSanitizer",
            "Stack_trace",
            "Memory_debugger",
            "Fuzzing",
        ),
    },
}
