"""The physical-computing stack: embedded systems, IoT protocols, buses, electronics,
control theory, DSP, FPGA, industrial control, robotics, and the machine underneath."""

from .common import CC_BY_SA, WIKI, wiki

DOMAINS = {
    "embedded-systems": {
        "tags": ["embedded system", "microcontroller", "firmware", "bare metal", "bootloader", "mcu"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Embedded_system",
            "Microcontroller",
            "Firmware",
            "Booting",
            "Interrupt",
            "Interrupt_handler",
            "Direct_memory_access",
            "Watchdog_timer",
            "Memory-mapped_I/O",
            "Cross_compiler",
            "In-system_programming",
            "Flash_memory",
            "Static_random-access_memory",
            "System_on_a_chip",
        ),
    },
    "iot-protocols": {
        "tags": ["iot", "internet of things", "mqtt", "coap", "zigbee", "lora", "bluetooth low energy", "smart home"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Internet_of_things",
            "MQTT",
            "Constrained_Application_Protocol",
            "Zigbee",
            "Z-Wave",
            "Bluetooth_Low_Energy",
            "LoRa",
            "Narrowband_IoT",
            "Thread_(network_protocol)",
            "Matter_(standard)",
            "6LoWPAN",
            "Wireless_sensor_network",
            "Edge_computing",
        ),
    },
    "hardware-interfaces": {
        "tags": ["i2c", "spi bus", "uart", "can bus", "gpio", "pwm", "serial port", "jtag"],
        "license": CC_BY_SA,
        "pages": wiki(
            "I%C2%B2C",
            "Serial_Peripheral_Interface",
            "Universal_asynchronous_receiver-transmitter",
            "CAN_bus",
            "Modbus",
            "RS-232",
            "RS-485",
            "JTAG",
            "General-purpose_input/output",
            "Pulse-width_modulation",
            "USB",
            "Serial_communication",
        ),
    },
    "electronics": {
        "tags": ["electronics", "circuit", "resistor", "capacitor", "transistor", "voltage", "adc", "logic gate"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ohm's_law",
            "Voltage",
            "Electric_current",
            "Resistor",
            "Capacitor",
            "Inductor",
            "Diode",
            "Transistor",
            "MOSFET",
            "Operational_amplifier",
            "Logic_gate",
            "Flip-flop_(electronics)",
            "Analog-to-digital_converter",
            "Digital-to-analog_converter",
            "Printed_circuit_board",
            "Kirchhoff's_circuit_laws",
        ),
    },
    "control-systems": {
        "tags": ["control theory", "pid controller", "feedback loop", "control system", "kalman filter", "servo"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Control_theory",
            "PID_controller",
            "Control_system",
            "Feedback",
            "State-space_representation",
            "Kalman_filter",
            "Transfer_function",
            "Servomechanism",
            "Bang%E2%80%93bang_control",
            "Setpoint_(control_system)",
        ),
    },
    "dsp": {
        "tags": ["dsp", "digital signal processing", "fft", "fourier transform", "digital filter", "sampling rate"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Digital_signal_processing",
            "Sampling_(signal_processing)",
            "Nyquist%E2%80%93Shannon_sampling_theorem",
            "Fast_Fourier_transform",
            "Discrete_Fourier_transform",
            "Digital_filter",
            "Finite_impulse_response",
            "Infinite_impulse_response",
            "Convolution",
            "Window_function",
            "Aliasing",
            "Quantization_(signal_processing)",
        ),
    },
    "fpga-hdl": {
        "tags": ["fpga", "verilog", "vhdl", "hardware description language", "rtl design", "asic"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Field-programmable_gate_array",
            "Verilog",
            "VHDL",
            "Hardware_description_language",
            "Application-specific_integrated_circuit",
            "Register-transfer_level",
            "Logic_synthesis",
            "Lookup_table",
        ),
    },
    "plc-scada": {
        "tags": ["plc", "scada", "ladder logic", "industrial control", "iec 61131", "automation system"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Programmable_logic_controller",
            "SCADA",
            "IEC_61131-3",
            "Ladder_logic",
            "Distributed_control_system",
            "Industrial_control_system",
            "OPC_Unified_Architecture",
            "Human%E2%80%93machine_interface",
            "Automation",
        ),
    },
    "robotics": {
        "tags": ["robotics", "robot", "ros", "slam", "kinematics", "path planning", "odometry"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Robotics",
            "Robot_Operating_System",
            "Simultaneous_localization_and_mapping",
            "Inverse_kinematics",
            "Forward_kinematics",
            "Motion_planning",
            "Odometry",
            "Robot_end_effector",
            "Lidar",
            "Servomotor",
            "Stepper_motor",
        ),
    },
    "real-time-systems": {
        "tags": ["real-time", "rtos", "scheduling", "preemption", "interrupt latency", "hard real-time"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Real-time_computing",
            "Real-time_operating_system",
            "Scheduling_(computing)",
            "Preemption_(computing)",
            "Rate-monotonic_scheduling",
            "Earliest_deadline_first_scheduling",
            "Priority_inversion",
            "Interrupt_latency",
            "Jitter",
            "Time-triggered_architecture",
        ),
    },
    "freertos": {
        "tags": ["freertos", "zephyr", "task scheduler", "embedded os"],
        "license": CC_BY_SA + " / MIT (FreeRTOS docs)",
        "pages": wiki(
            "FreeRTOS",
            "Zephyr_(operating_system)",
            "VxWorks",
            "Embedded_operating_system",
            "%CE%9CClinux",
        ),
    },
    "esp32": {
        "tags": ["esp32", "esp-idf", "espressif", "esp8266"],
        "license": "Apache-2.0 (ESP-IDF docs) / " + CC_BY_SA,
        "pages": [
            "https://docs.espressif.com/projects/esp-idf/en/stable/esp32/get-started/index.html",
            "https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-guides/build-system.html",
            WIKI + "ESP32",
            WIKI + "ESP8266",
        ],
    },
    "arduino": {
        "tags": ["arduino", "arduino sketch", "arduino uno", "arduino ide", "atmega"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Arduino",
            "Arduino_Uno",
            "AVR_microcontrollers",
            "Atmel_AVR_instruction_set",
        ),
    },
    "raspberry-pi": {
        "tags": ["raspberry pi", "raspberry pi os", "raspbian", "pi pico", "rp2040"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Raspberry_Pi",
            "Raspberry_Pi_OS",
            "RP2040",
            "Single-board_computer",
        ),
    },
    "computer-architecture": {
        "tags": ["computer architecture", "cpu cache", "pipeline", "branch prediction", "virtual memory", "instruction cycle"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Computer_architecture",
            "Central_processing_unit",
            "CPU_cache",
            "Instruction_pipelining",
            "Branch_predictor",
            "Out-of-order_execution",
            "Virtual_memory",
            "Memory_management_unit",
            "Memory_hierarchy",
            "Von_Neumann_architecture",
            "Harvard_architecture",
            "Single_instruction,_multiple_data",
            "Translation_lookaside_buffer",
            "Instruction_cycle",
        ),
    },
}
