"""Physics across classical, quantum, relativistic, thermodynamic, and applied domains."""

from .common import CC_BY_SA, wiki

DOMAINS = {
    "classical-mechanics": {
        "tags": ["classical mechanics", "newtonian mechanics", "conservation of energy", "angular momentum"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Classical_mechanics",
            "Newton's_laws_of_motion",
            "Newtonian_mechanics",
            "Kinematics",
            "Conservation_of_energy",
            "Angular_momentum",
        ),
    },
    "lagrangian-mechanics": {
        "tags": ["lagrangian mechanics", "principle of least action", "generalized coordinates", "calculus of variations"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Lagrangian_mechanics",
            "Generalized_coordinates",
            "Euler%E2%80%93Lagrange_equation",
            "Principle_of_least_action",
            "D'Alembert's_principle",
            "Action_(physics)",
            "Noether's_theorem",
            "Calculus_of_variations",
        ),
    },
    "hamiltonian-mechanics": {
        "tags": ["hamiltonian mechanics", "phase space", "canonical transformation", "poisson bracket"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Hamiltonian_mechanics",
            "Hamilton's_equations",
            "Phase_space",
            "Canonical_transformation",
            "Poisson_bracket",
            "Hamilton%E2%80%93Jacobi_equation",
            "Symplectic_geometry",
            "Liouville's_theorem_(Hamiltonian)",
        ),
    },
    "rigid-body-dynamics-physics": {
        "tags": ["rigid body dynamics", "moment of inertia", "gyroscopic precession", "rotational motion"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Rigid_body",
            "Rigid_body_dynamics",
            "Moment_of_inertia",
            "Euler's_equations_(rigid_body_dynamics)",
            "Torque",
            "Precession",
            "Gyroscope",
            "Rotation_around_a_fixed_axis",
        ),
    },
    "celestial-mechanics-physics": {
        "tags": ["celestial mechanics", "orbital mechanics", "kepler's laws", "three-body problem"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Celestial_mechanics",
            "Orbital_mechanics",
            "Kepler's_laws_of_planetary_motion",
            "Two-body_problem",
            "Three-body_problem",
            "Orbit",
            "Lagrange_point",
            "Perturbation_(astronomy)",
        ),
    },
    "continuum-mechanics": {
        "tags": ["continuum mechanics", "stress tensor", "constitutive equation", "deformation gradient"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Continuum_mechanics",
            "Stress_(mechanics)",
            "Deformation_(physics)",
            "Cauchy_stress_tensor",
            "Strain_(mechanics)",
            "Constitutive_equation",
            "Navier%E2%80%93Stokes_equations",
            "Tensor",
        ),
    },
    "fluid-dynamics-physics": {
        "tags": ["fluid dynamics", "reynolds number", "boundary layer", "compressible flow"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Fluid_dynamics",
            "Bernoulli's_principle",
            "Reynolds_number",
            "Viscosity",
            "Boundary_layer",
            "Vorticity",
            "Compressible_flow",
            "Laminar_flow",
        ),
    },
    "thermodynamics": {
        "tags": ["laws of thermodynamics", "thermodynamic entropy", "free energy", "first law of thermodynamics"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Thermodynamics",
            "Laws_of_thermodynamics",
            "Entropy",
            "Enthalpy",
            "First_law_of_thermodynamics",
            "Second_law_of_thermodynamics",
            "Thermodynamic_free_energy",
            "Heat",
        ),
    },
    "kinetic-theory": {
        "tags": ["kinetic theory of gases", "mean free path", "boltzmann equation", "ideal gas law"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Kinetic_theory_of_gases",
            "Maxwell%E2%80%93Boltzmann_distribution",
            "Mean_free_path",
            "Boltzmann_equation",
            "Ideal_gas_law",
            "Molecular_diffusion",
            "Effusion",
        ),
    },
    "statistical-physics": {
        "tags": ["statistical mechanics", "partition function", "canonical ensemble", "fermi-dirac statistics"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Statistical_mechanics",
            "Partition_function_(statistical_mechanics)",
            "Boltzmann_distribution",
            "Canonical_ensemble",
            "Microcanonical_ensemble",
            "Grand_canonical_ensemble",
            "Fermi%E2%80%93Dirac_statistics",
            "Bose%E2%80%93Einstein_statistics",
        ),
    },
    "electromagnetism": {
        "tags": ["classical electromagnetism", "electromagnetic field", "lorentz force", "electromagnetic induction"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Electromagnetism",
            "Electromagnetic_field",
            "Lorentz_force",
            "Coulomb's_law",
            "Electromagnetic_induction",
            "Electric_field",
            "Magnetic_field",
        ),
    },
    "maxwell-equations": {
        "tags": ["maxwell's equations", "gauss's law", "displacement current", "electromagnetic wave equation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Maxwell's_equations",
            "Gauss's_law",
            "Faraday's_law_of_induction",
            "Amp%C3%A8re's_circuital_law",
            "Displacement_current",
            "Electromagnetic_wave_equation",
            "Electric_potential",
        ),
    },
    "electrostatics": {
        "tags": ["electrostatic field", "electric charge", "electric dipole moment", "vacuum permittivity"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Electrostatics",
            "Electric_charge",
            "Capacitance",
            "Electric_dipole_moment",
            "Permittivity",
            "Poisson's_equation",
        ),
    },
    "magnetostatics": {
        "tags": ["magnetostatic field", "biot-savart law", "magnetic dipole", "magnetic vector potential"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Magnetostatics",
            "Biot%E2%80%93Savart_law",
            "Magnetic_dipole",
            "Magnetization",
            "Permeability_(electromagnetism)",
            "Magnetic_vector_potential",
            "Ferromagnetism",
        ),
    },
    "electrodynamics": {
        "tags": ["classical electrodynamics", "poynting vector", "electromagnetic radiation", "retarded potential"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Classical_electromagnetism",
            "Li%C3%A9nard%E2%80%93Wiechert_potential",
            "Larmor_formula",
            "Poynting_vector",
            "Electromagnetic_radiation",
            "Retarded_potential",
        ),
    },
    "optics-physics": {
        "tags": ["physical optics", "optical refraction", "wave polarization", "light diffraction"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Optics",
            "Refraction",
            "Reflection_(physics)",
            "Snell's_law",
            "Lens",
            "Diffraction",
            "Polarization_(waves)",
            "Physical_optics",
        ),
    },
    "wave-optics": {
        "tags": ["wave interference", "fresnel diffraction", "fraunhofer diffraction", "diffraction grating"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Wave_interference",
            "Huygens%E2%80%93Fresnel_principle",
            "Double-slit_experiment",
            "Fresnel_diffraction",
            "Fraunhofer_diffraction",
            "Diffraction_grating",
        ),
    },
    "geometric-optics": {
        "tags": ["geometrical optics", "focal length", "optical aberration", "total internal reflection"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Geometrical_optics",
            "Ray_(optics)",
            "Focal_length",
            "Mirror",
            "Optical_aberration",
            "Total_internal_reflection",
        ),
    },
    "acoustics-physics": {
        "tags": ["acoustic wave", "standing wave", "doppler effect", "sound resonance"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Acoustics",
            "Sound",
            "Acoustic_wave",
            "Resonance",
            "Standing_wave",
            "Doppler_effect",
            "Ultrasound",
            "Timbre",
        ),
    },
    "special-relativity": {
        "tags": ["special relativity", "lorentz transformation", "time dilation", "mass-energy equivalence"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Special_relativity",
            "Lorentz_transformation",
            "Time_dilation",
            "Length_contraction",
            "Mass%E2%80%93energy_equivalence",
            "Minkowski_space",
            "Four-vector",
            "Relativity_of_simultaneity",
        ),
    },
    "general-relativity": {
        "tags": ["general relativity", "einstein field equations", "spacetime curvature", "gravitational wave"],
        "license": CC_BY_SA,
        "pages": wiki(
            "General_relativity",
            "Einstein_field_equations",
            "Spacetime",
            "Geodesic",
            "Schwarzschild_metric",
            "Gravitational_wave",
            "Equivalence_principle",
            "Curvature",
        ),
    },
    "quantum-mechanics": {
        "tags": ["quantum mechanics", "schrodinger equation", "wave function", "uncertainty principle"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Quantum_mechanics",
            "Schr%C3%B6dinger_equation",
            "Wave_function",
            "Uncertainty_principle",
            "Quantum_superposition",
            "Quantum_entanglement",
            "Wave%E2%80%93particle_duality",
            "Pauli_exclusion_principle",
        ),
    },
    "quantum-field-theory": {
        "tags": ["quantum field theory", "gauge theory", "feynman diagram", "path integral formulation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Quantum_field_theory",
            "Second_quantization",
            "Feynman_diagram",
            "Gauge_theory",
            "Renormalization",
            "Path_integral_formulation",
        ),
    },
    "quantum-electrodynamics": {
        "tags": ["quantum electrodynamics", "vacuum polarization", "compton scattering", "dirac equation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Quantum_electrodynamics",
            "Vacuum_polarization",
            "Anomalous_magnetic_dipole_moment",
            "Compton_scattering",
            "Photon",
            "Dirac_equation",
        ),
    },
    "particle-physics": {
        "tags": ["particle physics", "elementary particle", "quark confinement", "matter antimatter"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Particle_physics",
            "Elementary_particle",
            "Quark",
            "Lepton",
            "Boson",
            "Fermion",
            "Antimatter",
        ),
    },
    "standard-model": {
        "tags": ["standard model", "higgs boson", "electroweak interaction", "quantum chromodynamics"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Standard_Model",
            "Higgs_boson",
            "Electroweak_interaction",
            "Quantum_chromodynamics",
            "Weak_interaction",
            "Strong_interaction",
            "Gluon",
        ),
    },
    "nuclear-physics": {
        "tags": ["nuclear physics", "radioactive decay", "nuclear fission", "nuclear shell model"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Nuclear_physics",
            "Atomic_nucleus",
            "Radioactive_decay",
            "Nuclear_fission",
            "Nuclear_fusion",
            "Binding_energy",
            "Nuclear_reaction",
            "Nuclear_shell_model",
        ),
    },
    "atomic-physics": {
        "tags": ["atomic physics", "atomic orbital", "fine structure", "zeeman effect"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Atomic_physics",
            "Atom",
            "Atomic_orbital",
            "Bohr_model",
            "Fine_structure",
            "Zeeman_effect",
            "Hyperfine_structure",
            "Rydberg_formula",
        ),
    },
    "molecular-physics": {
        "tags": ["molecular physics", "chemical bond", "molecular orbital", "van der waals force"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Molecular_physics",
            "Molecule",
            "Chemical_bond",
            "Molecular_orbital",
            "Born%E2%80%93Oppenheimer_approximation",
            "Molecular_vibration",
            "Van_der_Waals_force",
            "Rotational_spectroscopy",
        ),
    },
    "condensed-matter-physics": {
        "tags": ["condensed matter physics", "crystal structure", "electronic band structure", "fermi surface"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Condensed_matter_physics",
            "Crystal_structure",
            "Phonon",
            "Electronic_band_structure",
            "Bloch's_theorem",
            "Fermi_surface",
            "Quasiparticle",
        ),
    },
    "solid-state-physics": {
        "tags": ["solid-state physics", "brillouin zone", "density of states", "reciprocal lattice"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Solid-state_physics",
            "Crystal_lattice",
            "Brillouin_zone",
            "Density_of_states",
            "Free_electron_model",
            "Bravais_lattice",
            "Reciprocal_lattice",
        ),
    },
    "semiconductor-physics": {
        "tags": ["semiconductor physics", "energy band gap", "semiconductor doping", "charge carrier"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Semiconductor",
            "Band_gap",
            "Doping_(semiconductor)",
            "P%E2%80%93n_junction",
            "Charge_carrier",
            "Semiconductor_device",
            "Electron_hole",
        ),
    },
    "superconductivity": {
        "tags": ["type-ii superconductivity", "cooper pair", "meissner effect", "josephson effect"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Superconductivity",
            "BCS_theory",
            "Cooper_pair",
            "Meissner_effect",
            "Josephson_effect",
            "High-temperature_superconductivity",
            "Flux_pinning",
        ),
    },
    "plasma-physics": {
        "tags": ["plasma physics", "magnetohydrodynamics simulation", "debye length", "plasma oscillation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Plasma_(physics)",
            "Magnetohydrodynamics",
            "Debye_length",
            "Plasma_oscillation",
            "Tokamak",
            "Cyclotron_resonance",
            "Fusion_power",
        ),
    },
    "astrophysics": {
        "tags": ["observational astrophysics", "neutron star", "interstellar medium", "accretion disk"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Astrophysics",
            "Star",
            "Black_hole",
            "Neutron_star",
            "Galaxy",
            "Interstellar_medium",
            "Accretion_disk",
        ),
    },
    "cosmology": {
        "tags": ["physical cosmology", "cosmic microwave background", "dark matter", "friedmann equations"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cosmology",
            "Big_Bang",
            "Cosmic_microwave_background",
            "Dark_matter",
            "Dark_energy",
            "Expansion_of_the_universe",
            "Friedmann_equations",
            "Lambda-CDM_model",
        ),
    },
    "stellar-physics": {
        "tags": ["stellar evolution", "stellar nucleosynthesis", "main sequence", "stellar structure"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Stellar_evolution",
            "Stellar_nucleosynthesis",
            "Main_sequence",
            "Supernova",
            "White_dwarf",
            "Hertzsprung%E2%80%93Russell_diagram",
            "Stellar_structure",
        ),
    },
    "gravitation": {
        "tags": ["newtonian gravitation", "gravitational field", "gravitational potential", "tidal force"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Gravity",
            "Newton's_law_of_universal_gravitation",
            "Gravitational_field",
            "Gravitational_potential",
            "Gravitational_lens",
            "Tidal_force",
            "Escape_velocity",
        ),
    },
    "thermodynamic-cycles": {
        "tags": ["thermodynamic cycle", "carnot cycle", "rankine cycle", "heat engine"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Thermodynamic_cycle",
            "Carnot_cycle",
            "Otto_cycle",
            "Rankine_cycle",
            "Brayton_cycle",
            "Diesel_cycle",
            "Heat_engine",
        ),
    },
    "heat-transfer-physics": {
        "tags": ["heat transfer", "thermal conduction", "thermal radiation", "heat equation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Heat_transfer",
            "Thermal_conduction",
            "Convection",
            "Thermal_radiation",
            "Heat_equation",
            "Nusselt_number",
            "Heat_exchanger",
        ),
    },
    "phase-transitions": {
        "tags": ["phase transition", "state of matter", "latent heat", "phase diagram"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Phase_transition",
            "State_of_matter",
            "Latent_heat",
            "Phase_diagram",
            "Order_parameter",
            "Critical_point_(thermodynamics)",
            "Ehrenfest_equations",
        ),
    },
    "critical-phenomena": {
        "tags": ["critical phenomena", "critical exponent", "renormalization group", "ising model"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Critical_phenomena",
            "Critical_exponent",
            "Universality_(dynamical_systems)",
            "Renormalization_group",
            "Ising_model",
            "Correlation_function_(statistical_mechanics)",
            "Widom_scaling",
        ),
    },
    "nonlinear-dynamics-physics": {
        "tags": ["nonlinear dynamics", "chaos theory", "bifurcation theory", "lyapunov exponent"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Nonlinear_system",
            "Chaos_theory",
            "Bifurcation_theory",
            "Attractor",
            "Lyapunov_exponent",
            "Limit_cycle",
            "Poincar%C3%A9_map",
        ),
    },
    "wave-mechanics": {
        "tags": ["wave equation", "dispersion relation", "group velocity", "wave packet"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Wave",
            "Wave_equation",
            "Dispersion_relation",
            "Group_velocity",
            "Phase_velocity",
            "Wave_packet",
            "Plane_wave",
        ),
    },
    "oscillations-resonance": {
        "tags": ["harmonic oscillator", "simple harmonic motion", "damped oscillation", "normal mode"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Oscillation",
            "Harmonic_oscillator",
            "Simple_harmonic_motion",
            "Damping",
            "Normal_mode",
            "Pendulum",
        ),
    },
    "elasticity-physics": {
        "tags": ["elasticity theory", "hooke's law", "young's modulus", "shear modulus"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Elasticity_(physics)",
            "Hooke's_law",
            "Young's_modulus",
            "Shear_modulus",
            "Bulk_modulus",
            "Poisson's_ratio",
            "Elastic_modulus",
        ),
    },
    "photonics": {
        "tags": ["integrated photonics", "optical fiber", "photonic crystal", "nonlinear optics"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Photonics",
            "Optical_fiber",
            "Photonic_crystal",
            "Nonlinear_optics",
            "Waveguide_(optics)",
            "Optical_amplifier",
        ),
    },
    "laser-physics": {
        "tags": ["laser physics", "stimulated emission", "population inversion", "optical cavity"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Laser",
            "Stimulated_emission",
            "Population_inversion",
            "Optical_cavity",
            "Laser_diode",
            "Mode_locking",
            "Q-switching",
        ),
    },
    "spectroscopy-physics": {
        "tags": ["atomic spectroscopy", "emission spectrum", "raman spectroscopy", "spectral line"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Spectroscopy",
            "Emission_spectrum",
            "Absorption_spectroscopy",
            "Raman_spectroscopy",
            "Mass_spectrometry",
            "Spectral_line",
            "Nuclear_magnetic_resonance",
        ),
    },
    "biophysics": {
        "tags": ["molecular biophysics", "protein folding", "molecular motor", "membrane potential"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Biophysics",
            "Protein_folding",
            "Molecular_motor",
            "Ion_channel",
            "Membrane_potential",
            "Single-molecule_experiment",
            "Bioenergetics",
        ),
    },
    "geophysics": {
        "tags": ["solid earth geophysics", "seismic wave", "plate tectonics", "earth's magnetic field"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Geophysics",
            "Seismology",
            "Earth's_magnetic_field",
            "Plate_tectonics",
            "Seismic_wave",
            "Gravimetry",
            "Geodynamics",
        ),
    },
    "fluid-turbulence": {
        "tags": ["fluid turbulence", "turbulence modeling", "large eddy simulation", "direct numerical simulation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Turbulence",
            "Turbulence_modeling",
            "Kolmogorov_microscales",
            "Large_eddy_simulation",
            "Reynolds-averaged_Navier%E2%80%93Stokes_equations",
            "Direct_numerical_simulation",
            "Eddy_(fluid_dynamics)",
        ),
    },
}
