"""Programming-language theory: semantics, type systems, calculi, verification."""
from .common import CC_BY_SA, wiki

DOMAINS = {
    "operational-semantics": {
        "tags": ["operational semantics", "structural operational semantics", "abstract machine", "reduction strategy"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Operational_semantics",
            "Semantics_(computer_science)",
            "Formal_semantics_of_programming_languages",
            "Structural_operational_semantics",
            "Abstract_machine",
            "Reduction_strategy",
        ),
    },
    "denotational-semantics": {
        "tags": ["denotational semantics", "domain theory", "scott domain", "semantic domain"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Denotational_semantics",
            "Domain_theory",
            "Scott_domain",
            "Dana_Scott",
            "Denotational_semantics_of_the_Actor_model",
            "Meaning_(philosophy)",
        ),
    },
    "axiomatic-semantics": {
        "tags": ["axiomatic semantics", "predicate transformer semantics", "assertion language", "program correctness"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Axiomatic_semantics",
            "Predicate_transformer_semantics",
            "Correctness_(computer_science)",
            "Assertion_(software_development)",
            "Loop_invariant",
            "Formal_verification",
        ),
    },
    "small-step-semantics": {
        "tags": ["small-step semantics", "structural operational semantics", "reduction relation", "evaluation context"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Operational_semantics#Small-step_semantics",
            "Rewriting",
            "Normal_form_(abstract_rewriting)",
            "Confluence_(abstract_rewriting)",
            "Church%E2%80%93Rosser_theorem",
            "Reduction_(abstract_rewriting)",
        ),
    },
    "big-step-semantics": {
        "tags": ["big-step semantics", "natural semantics", "evaluation relation", "inference rule"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Operational_semantics#Big-step_semantics",
            "Natural_deduction",
            "Rule_of_inference",
            "Structural_rule",
            "Sequent",
            "Judgment_(mathematical_logic)",
        ),
    },
    "lambda-cube": {
        "tags": ["lambda cube", "pure type system", "calculus of constructions", "higher-order logic"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Lambda_cube",
            "Pure_type_system",
            "Calculus_of_constructions",
            "Henk_Barendregt",
            "System_F-omega",
            "Typed_lambda_calculus",
        ),
    },
    "system-f": {
        "tags": ["System F", "polymorphic lambda calculus", "second-order lambda calculus", "impredicative polymorphism"],
        "license": CC_BY_SA,
        "pages": wiki(
            "System_F",
            "Jean-Yves_Girard",
            "Parametricity",
            "Impredicativity",
            "Type_variable",
            "Generalized_algebraic_data_type",
        ),
    },
    "simply-typed-lambda": {
        "tags": ["simply typed lambda calculus", "typing rule", "type judgment", "strong normalization"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Simply_typed_lambda_calculus",
            "Type_rule",
            "Normalization_property_(abstract_rewriting)",
            "Subject_reduction",
            "Church_encoding",
            "Combinatory_logic",
        ),
    },
    "dependent-types-pl": {
        "tags": ["dependent type", "pi type", "dependent product", "type family"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Dependent_type",
            "Calculus_of_inductive_constructions",
            "Inductive_type",
            "Type_theory",
            "Agda_(programming_language)",
            "Idris_(programming_language)",
        ),
    },
    "linear-types": {
        "tags": ["linear type system", "linear logic", "substructural type system", "resource management"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Substructural_type_system",
            "Linear_logic",
            "Uniqueness_type",
            "Resource_management_(computing)",
            "Region-based_memory_management",
            "Rust_(programming_language)",
        ),
    },
    "affine-types": {
        "tags": ["affine type system", "affine logic", "move semantics", "borrow checker"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Substructural_logic",
            "Affine_logic",
            "Object_lifetime",
            "Resource_acquisition_is_initialization",
            "Memory_safety",
            "Escape_analysis",
        ),
    },
    "refinement-types": {
        "tags": ["refinement type", "liquid types", "predicate subtyping", "dependent refinement"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Refinement_type",
            "Subtyping",
            "Satisfiability_modulo_theories",
            "Hoare_logic",
            "Design_by_contract",
            "Abstract_interpretation",
        ),
    },
    "gradual-typing": {
        "tags": ["gradual typing", "dynamic type checking", "type soundness", "blame calculus"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Gradual_typing",
            "Type_system",
            "Duck_typing",
            "Type_safety",
            "Dynamic_programming_language",
            "TypeScript",
        ),
    },
    "intersection-types": {
        "tags": ["intersection type", "union type", "type intersection", "principal typing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Intersection_type",
            "Union_type",
            "Product_type",
            "Bottom_type",
            "Top_type",
            "Type_class",
        ),
    },
    "subtyping-theory": {
        "tags": ["subtyping relation", "covariance and contravariance", "structural subtyping", "nominal typing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Subtyping",
            "Covariance_and_contravariance_(computer_science)",
            "Structural_type_system",
            "Nominal_type_system",
            "Liskov_substitution_principle",
            "Bounded_quantification",
        ),
    },
    "parametric-polymorphism": {
        "tags": ["parametric polymorphism", "type parameter", "generic programming", "type constructor"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Parametric_polymorphism",
            "Generic_programming",
            "Kind_(type_theory)",
            "Type_family",
            "Type_constructor",
            "Template_(C%2B%2B)",
        ),
    },
    "ad-hoc-polymorphism": {
        "tags": ["ad hoc polymorphism", "function overloading", "type class", "operator overloading"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ad_hoc_polymorphism",
            "Function_overloading",
            "Operator_overloading",
            "Multiple_dispatch",
            "Double_dispatch",
            "Dynamic_dispatch",
        ),
    },
    "type-inference-algorithms": {
        "tags": ["type inference", "algorithm W", "constraint-based type inference", "principal type"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Type_inference",
            "Hindley%E2%80%93Milner_type_system",
            "Programming_language_theory",
            "Let_expression",
            "Type_annotation",
            "Constraint_satisfaction",
        ),
    },
    "unification-theory": {
        "tags": ["unification algorithm", "syntactic unification", "most general unifier", "occurs check"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Unification_(computer_science)",
            "Robinson%27s_unification_algorithm",
            "Anti-unification",
            "Occurs_check",
            "Prolog",
            "Resolution_(logic)",
        ),
    },
    "hindley-milner-deep": {
        "tags": ["Hindley-Milner type system", "let-polymorphism", "type scheme", "damas-milner algorithm"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Hindley%E2%80%93Milner_type_system",
            "Robin_Milner",
            "ML_(programming_language)",
            "Standard_ML",
            "OCaml",
            "Value_restriction",
        ),
    },
    "bidirectional-typing": {
        "tags": ["bidirectional type checking", "type synthesis", "type checking mode", "local type inference"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Type_checking",
            "Type_signature",
            "Higher-order_abstract_syntax",
            "Local_variable",
            "Static_program_analysis",
            "Compile_time",
        ),
    },
    "effect-systems": {
        "tags": ["type and effect system", "computational effect", "effect inference", "side effect tracking"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Effect_system",
            "Side_effect_(computer_science)",
            "Purely_functional_programming",
            "Referential_transparency",
            "Monad_(functional_programming)",
            "Comonad",
        ),
    },
    "algebraic-effects": {
        "tags": ["algebraic effect", "effect handler", "delimited continuation", "one-shot continuation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Structured_concurrency",
            "Delimited_continuation",
            "Exception_handling",
            "Coroutine",
            "Generator_(computer_programming)",
            "Continuation",
        ),
    },
    "monad-transformers": {
        "tags": ["monad transformer", "monad stack", "kleisli category", "free monad"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Monad_transformer",
            "Monad_(functional_programming)",
            "Kleisli_category",
            "Applicative_functor",
            "Functor_(functional_programming)",
            "Natural_transformation",
        ),
    },
    "continuation-passing-style": {
        "tags": ["continuation passing style", "call-with-current-continuation", "tail call", "administrative normal form"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Continuation-passing_style",
            "Call-with-current-continuation",
            "Tail_call",
            "A-normal_form",
            "Trampoline_(computing)",
            "Direct_style",
        ),
    },
    "defunctionalization": {
        "tags": ["defunctionalization transform", "closure conversion", "higher-order function", "apply function"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Defunctionalization",
            "Higher-order_function",
            "First-class_function",
            "Currying",
            "Partial_application",
            "Lambda_lifting",
        ),
    },
    "static-single-assignment": {
        "tags": ["static single assignment", "phi function", "dominance frontier", "SSA form"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Static_single-assignment_form",
            "Dominator_(graph_theory)",
            "Intermediate_representation",
            "Register_allocation",
            "Constant_folding",
            "Dead-code_elimination",
        ),
    },
    "control-flow-analysis": {
        "tags": ["control-flow analysis", "control-flow graph", "call graph", "basic block"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Control-flow_analysis",
            "Control-flow_graph",
            "Call_graph",
            "Basic_block",
            "Interprocedural_optimization",
            "Function_inlining",
        ),
    },
    "data-flow-analysis": {
        "tags": ["data-flow analysis", "reaching definition", "live variable analysis", "available expression"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Data-flow_analysis",
            "Reaching_definition",
            "Live-variable_analysis",
            "Use-define_chain",
            "Available_expression",
            "Def-use_chain",
        ),
    },
    "abstract-interpretation": {
        "tags": ["abstract interpretation", "galois connection", "abstract domain", "widening operator"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Abstract_interpretation",
            "Galois_connection",
            "Lattice_(order)",
            "Complete_lattice",
            "Fixed-point_iteration",
            "Interval_arithmetic",
        ),
    },
    "partial-evaluation": {
        "tags": ["partial evaluation", "program specialization", "binding-time analysis", "futamura projection"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Partial_evaluation",
            "Program_optimization",
            "Just-in-time_compilation",
            "Memoization",
            "Metaprogramming",
            "Multi-stage_programming",
        ),
    },
    "supercompilation": {
        "tags": ["supercompilation technique", "program transformation", "deforestation transformation", "positive supercompilation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Supercompilation",
            "Program_transformation",
            "Deforestation_(computer_science)",
            "Loop_optimization",
            "Automatic_programming",
            "Optimizing_compiler",
        ),
    },
    "pi-calculus": {
        "tags": ["pi-calculus", "process calculus", "name passing", "mobile process"],
        "license": CC_BY_SA,
        "pages": wiki(
            "%CE%A0-calculus",
            "Ambient_calculus",
            "Join-calculus",
            "Mobile_agent",
            "Nondeterministic_algorithm",
            "Concurrency_(computer_science)",
        ),
    },
    "calculus-of-communicating-systems": {
        "tags": ["calculus of communicating systems", "labelled transition system", "process algebra", "structural congruence"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Calculus_of_communicating_systems",
            "Process_calculus",
            "Transition_system",
            "Algebra_of_Communicating_Processes",
            "Petri_net",
            "Temporal_logic",
        ),
    },
    "communicating-sequential-processes": {
        "tags": ["communicating sequential processes", "message passing", "rendezvous synchronization", "channel communication"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Communicating_sequential_processes",
            "Tony_Hoare",
            "Occam_(programming_language)",
            "Go_(programming_language)",
            "Channel_(programming)",
            "Deadlock_(computer_science)",
        ),
    },
    "session-types": {
        "tags": ["session type", "multiparty session types", "typed channel", "protocol conformance"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Session_type",
            "Communication_protocol",
            "Duality_(mathematics)",
            "Behavioral_subtyping",
            "Linearizability",
            "Protocol_(object-oriented_programming)",
        ),
    },
    "actor-semantics": {
        "tags": ["actor model", "actor semantics", "asynchronous message", "mailbox concurrency"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Actor_model",
            "Actor_model_theory",
            "History_of_the_Actor_model",
            "Carl_Hewitt",
            "Erlang_(programming_language)",
            "Message_passing",
        ),
    },
    "process-calculus": {
        "tags": ["process calculus", "bisimulation equivalence", "weak bisimulation", "observational equivalence"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ambient_calculus",
            "Robin_Milner",
            "Modal_logic",
            "Trace_theory",
            "Coalgebra",
            "Reactive_programming",
        ),
    },
    "separation-logic": {
        "tags": ["separation logic", "separating conjunction", "heap assertion", "frame rule"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Separation_logic",
            "Bunched_logic",
            "Pointer_(computer_programming)",
            "Aliasing_(computing)",
            "Concurrent_separation_logic",
            "Shape_analysis_(program_analysis)",
        ),
    },
    "hoare-logic-deep": {
        "tags": ["Hoare logic", "Hoare triple", "partial correctness", "total correctness"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Hoare_logic",
            "Precondition",
            "Postcondition",
            "Invariant_(mathematics)",
            "Termination_analysis",
            "Well-founded_relation",
        ),
    },
    "weakest-precondition": {
        "tags": ["weakest precondition", "predicate transformer semantics", "guarded command language", "verification condition"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Predicate_transformer_semantics",
            "Guarded_Command_Language",
            "Edsger_W._Dijkstra",
            "Nondeterministic_programming",
            "Symbolic_execution",
            "Automated_theorem_proving",
        ),
    },
    "denotational-domains": {
        "tags": ["domain theory", "directed-complete partial order", "continuous function", "algebraic lattice"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Domain_theory",
            "Powerdomain",
            "Way-below_relation",
            "Scott_continuity",
            "Bourbaki%E2%80%93Witt_theorem",
            "Ideal_(order_theory)",
        ),
    },
    "cpo-theory": {
        "tags": ["complete partial order", "directed-complete partial order", "chain-complete poset", "least upper bound"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Complete_partial_order",
            "Partially_ordered_set",
            "Directed_set",
            "Supremum",
            "Semilattice",
            "Order_theory",
        ),
    },
    "fixed-point-semantics": {
        "tags": ["least fixed point", "Kleene fixed-point theorem", "Knaster-Tarski theorem", "fixed-point combinator"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Least_fixed_point",
            "Kleene_fixed-point_theorem",
            "Knaster%E2%80%93Tarski_theorem",
            "Fixed-point_combinator",
            "Denotational_semantics#Meanings_of_recursive_programs",
            "Recursion_(computer_science)",
        ),
    },
    "game-semantics": {
        "tags": ["game semantics", "dialogical logic", "full abstraction", "strategy (game theory)"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Game_semantics",
            "Full_abstraction",
            "Ludics",
            "Geometry_of_interaction",
            "Programming_Computable_Functions",
            "Dialogical_logic",
        ),
    },
    "bisimulation": {
        "tags": ["bisimulation relation", "bisimulation equivalence", "coinductive proof", "labelled transition system"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Bisimulation",
            "Simulation_preorder",
            "Equivalence_relation",
            "Kripke_semantics",
            "State_transition_system",
            "Observational_equivalence",
        ),
    },
    "coinduction": {
        "tags": ["coinduction principle", "corecursion scheme", "coinductive definition", "infinite data structure"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Coinduction",
            "Corecursion",
            "F-coalgebra",
            "Stream_(abstract_data_type)",
            "Lazy_evaluation",
            "Anamorphism",
        ),
    },
    "structural-induction-pl": {
        "tags": ["structural induction", "well-founded induction", "recursive datatype", "inductive proof"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Structural_induction",
            "Mathematical_induction",
            "Recursive_data_type",
            "Well-founded_relation",
            "Term_algebra",
            "Initial_algebra",
        ),
    },
    "term-rewriting": {
        "tags": ["term rewriting system", "rewrite rule", "abstract rewriting system", "critical pair"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Rewriting",
            "Abstract_rewriting_system",
            "Critical_pair_(logic)",
            "String_rewriting_system",
            "Graph_rewriting",
            "Rewrite_order",
        ),
    },
    "confluence-rewriting": {
        "tags": ["confluence property", "Church-Rosser theorem", "local confluence", "Newman's lemma"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Confluence_(abstract_rewriting)",
            "Church%E2%80%93Rosser_theorem",
            "Newman%27s_lemma",
            "Normal_form_(abstract_rewriting)",
            "Termination_(term_rewriting)",
            "Diamond_lemma",
        ),
    },
    "knuth-bendix": {
        "tags": ["Knuth-Bendix completion", "completion algorithm", "reduction ordering", "equational theory"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Knuth%E2%80%93Bendix_completion_algorithm",
            "Word_problem_(mathematics)",
            "Equational_logic",
            "Path_ordering_(term_rewriting)",
            "Buchberger%27s_algorithm",
            "Automated_reasoning",
        ),
    },
    "graph-reduction": {
        "tags": ["graph reduction", "combinator graph reduction", "spineless tagless G-machine", "supercombinator compilation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Graph_reduction",
            "SECD_machine",
            "Krivine_machine",
            "SKI_combinator_calculus",
            "Fixed-point_combinator",
            "Categorical_abstract_machine",
        ),
    },
    "lazy-evaluation-theory": {
        "tags": ["lazy evaluation", "call by need", "call by name", "thunk (programming)"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Lazy_evaluation",
            "Evaluation_strategy",
            "Thunk",
            "Graph_reduction_machine",
            "Futures_and_promises",
            "Memoization",
        ),
    },
    "strictness-analysis": {
        "tags": ["strictness analysis", "demand analysis", "backwards analysis", "call-by-value transformation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Strict_function",
            "Strict_programming_language",
            "Divergence_(computer_science)",
            "Bottom_element",
            "Total_functional_programming",
            "Eager_evaluation",
        ),
    },
    "closure-conversion": {
        "tags": ["closure conversion", "lambda lifting", "free variable capture", "environment representation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Closure_(computer_programming)",
            "Free_variables_and_bound_variables",
            "Name_binding",
            "Variable_shadowing",
            "Lexical_scoping",
            "Call_stack",
        ),
    },
}
