"""More programming languages: array, stack, historical, and functional families."""

from .common import CC_BY_SA, wiki

DOMAINS = {
    "apl-j-k": {
        "tags": ["j language", "k language", "array programming language",
                 "iverson notation", "apl language"],
        "license": CC_BY_SA,
        "pages": wiki(
            "J_(programming_language)",
            "K_(programming_language)",
            "Array_programming",
            "APL_(programming_language)",
            "Q_(programming_language_from_Kx_Systems)",
            "Iverson_notation",
            "APL_syntax_and_symbols",
            "Rank_(J_programming_language)",
        ),
    },
    "kdb-q-lang": {
        "tags": ["kdb database", "q language", "kx systems",
                 "arthur whitney", "time series database", "column oriented dbms"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Kdb+",
            "Kx_Systems",
            "Arthur_Whitney_(computer_scientist)",
            "Time_series_database",
            "Column-oriented_DBMS",
            "In-memory_database",
            "Financial_technology",
            "Quantitative_analysis_(finance)",
        ),
    },
    "bqn-array": {
        "tags": ["bqn language", "array programming language", "tacit programming",
                 "combinatory logic", "point free programming"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Array_programming",
            "Tacit_programming",
            "Point-free_programming",
            "Combinatory_logic",
            "Combinator",
            "Higher-order_function",
            "Function-level_programming",
        ),
    },
    "factor-stack": {
        "tags": ["factor language", "concatenative programming language",
                 "stack oriented programming", "slava pestov", "reverse polish notation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Factor_(programming_language)",
            "Concatenative_programming_language",
            "Stack-oriented_programming",
            "Slava_Pestov",
            "Reverse_Polish_notation",
            "Stack_machine",
            "Stack_(abstract_data_type)",
        ),
    },
    "joy-language": {
        "tags": ["joy language", "function level programming", "manfred von thun",
                 "concatenative programming", "higher order function"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Joy_(programming_language)",
            "Function-level_programming",
            "Manfred_von_Thun",
            "Concatenative_programming",
            "Higher-order_function",
            "Currying",
            "Combinatory_logic",
        ),
    },
    "cat-language": {
        "tags": ["concatenative programming language", "stack oriented programming",
                 "type inference", "type system", "stack machine"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Concatenative_programming_language",
            "Stack-oriented_programming",
            "Type_inference",
            "Type_system",
            "Stack_machine",
            "Combinatory_logic",
            "Homoiconicity",
        ),
    },
    "postscript-lang": {
        "tags": ["postscript language", "page description language",
                 "adobe systems", "encapsulated postscript", "document structuring conventions"],
        "license": CC_BY_SA,
        "pages": wiki(
            "PostScript",
            "Page_description_language",
            "Adobe_Systems",
            "Portable_Document_Format",
            "PostScript_fonts",
            "Encapsulated_PostScript",
            "Document_Structuring_Conventions",
            "Ghostscript",
        ),
    },
    "simula-language": {
        "tags": ["simula language", "discrete event simulation",
                 "object oriented programming", "ole johan dahl", "kristen nygaard"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Simula",
            "Discrete-event_simulation",
            "Object-oriented_programming",
            "Ole-Johan_Dahl",
            "Kristen_Nygaard",
            "Coroutine",
            "Simulation",
        ),
    },
    "modula-2": {
        "tags": ["modula language", "niklaus wirth", "modular programming",
                 "pascal language", "structured programming"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Modula-2",
            "Niklaus_Wirth",
            "Modular_programming",
            "Pascal_(programming_language)",
            "Structured_programming",
            "Concurrent_Pascal",
            "Wirth_syntax_notation",
        ),
    },
    "modula-3": {
        "tags": ["modula language", "digital equipment corporation",
                 "garbage collection", "modular programming", "type system"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Modula-3",
            "Digital_Equipment_Corporation",
            "Garbage_collection_(computer_science)",
            "Modular_programming",
            "Type_system",
            "Exception_handling",
            "Generic_programming",
        ),
    },
    "oberon-language": {
        "tags": ["oberon language", "niklaus wirth", "oberon operating system",
                 "component pascal", "active oberon"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Oberon_(programming_language)",
            "Niklaus_Wirth",
            "Oberon_(operating_system)",
            "Component_Pascal",
            "Active_Oberon",
            "Modular_programming",
            "Garbage_collection_(computer_science)",
        ),
    },
    "eiffel-language": {
        "tags": ["eiffel language", "design by contract", "bertrand meyer",
                 "object oriented programming", "assertion software"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Eiffel_(programming_language)",
            "Design_by_contract",
            "Bertrand_Meyer",
            "Object-oriented_programming",
            "Assertion_(software_development)",
            "SCOOP_(software)",
            "Inheritance_(object-oriented_programming)",
        ),
    },
    "sather-language": {
        "tags": ["sather language", "iteration abstraction", "category theory",
                 "object oriented programming", "generic programming"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Sather",
            "Category_theory",
            "International_Computer_Science_Institute",
            "Object-oriented_programming",
            "Generic_programming",
            "Iterator",
            "Multiple_dispatch",
        ),
    },
    "ada-deep": {
        "tags": ["ada language", "spark language", "jean ichbiah",
                 "real time computing", "formal verification", "steelman requirements"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ada_(programming_language)",
            "SPARK_(programming_language)",
            "Jean_Ichbiah",
            "Real-time_computing",
            "Formal_verification",
            "Steelman_language_requirements",
            "Ada_Lovelace",
            "United_States_Department_of_Defense",
        ),
    },
    "pl-i-language": {
        "tags": ["pl i language", "structured programming", "mainframe computer",
                 "ibm system", "punched card"],
        "license": CC_BY_SA,
        "pages": wiki(
            "PL/I",
            "IBM",
            "Structured_programming",
            "Mainframe_computer",
            "IBM_System/360",
            "Punched_card",
            "Fortran",
        ),
    },
    "algol-family": {
        "tags": ["algol language", "john backus", "imperative programming",
                 "structured programming", "backus naur form"],
        "license": CC_BY_SA,
        "pages": wiki(
            "ALGOL",
            "ALGOL_60",
            "ALGOL_68",
            "ALGOL_W",
            "John_Backus",
            "Imperative_programming",
            "Backus%E2%80%93Naur_form",
        ),
    },
    "bcpl-b-language": {
        "tags": ["bcpl language", "b language", "martin richards",
                 "bootstrapping compilers", "systems programming"],
        "license": CC_BY_SA,
        "pages": wiki(
            "BCPL",
            "B_(programming_language)",
            "Martin_Richards_(computer_scientist)",
            "Bootstrapping_(compilers)",
            "System_programming_language",
            "Self-hosting_(compilers)",
            "Multics",
        ),
    },
    "mercury-logic": {
        "tags": ["mercury language", "logic programming", "prolog language",
                 "declarative programming", "constraint logic programming"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Mercury_(programming_language)",
            "Logic_programming",
            "Prolog",
            "Declarative_programming",
            "Constraint_logic_programming",
            "Unification_(computer_science)",
            "Horn_clause",
        ),
    },
    "curry-language": {
        "tags": ["curry language", "functional logic programming",
                 "haskell language", "lazy evaluation", "narrowing algebraic"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Curry_(programming_language)",
            "Functional_logic_programming",
            "Haskell",
            "Narrowing_of_algebraic_value_sets",
            "Lazy_evaluation",
            "Term_rewriting",
            "Backtracking",
        ),
    },
    "miranda-language": {
        "tags": ["miranda language", "david turner computer scientist",
                 "lazy evaluation", "purely functional programming", "referential transparency"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Miranda_(programming_language)",
            "David_Turner_(computer_scientist)",
            "Lazy_evaluation",
            "Purely_functional_programming",
            "Referential_transparency",
            "Pattern_matching",
            "Algebraic_data_type",
        ),
    },
    "clean-language": {
        "tags": ["clean language", "uniqueness type", "graph reduction",
                 "purely functional programming", "lazy evaluation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Clean_(programming_language)",
            "Uniqueness_type",
            "Graph_reduction",
            "Purely_functional_programming",
            "Lazy_evaluation",
            "Referential_transparency",
            "Type_system",
        ),
    },
    "unison-lang": {
        "tags": ["unison language", "content addressable storage",
                 "distributed computing", "merkle tree", "purely functional programming"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Content-addressable_storage",
            "Distributed_computing",
            "Merkle_tree",
            "Purely_functional_programming",
            "Algebraic_effect",
            "Effect_system",
            "Abstract_syntax_tree",
        ),
    },
    "roc-language": {
        "tags": ["roc language", "purely functional programming",
                 "algebraic effect", "type inference", "static single assignment"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Purely_functional_programming",
            "Algebraic_effect",
            "Effect_system",
            "Type_inference",
            "Static_single-assignment_form",
            "LLVM",
            "Pattern_matching",
        ),
    },
    "koka-language": {
        "tags": ["koka language", "effect system", "algebraic effect",
                 "microsoft research", "continuation passing style"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Effect_system",
            "Algebraic_effect",
            "Microsoft_Research",
            "Continuation-passing_style",
            "Delimited_continuation",
            "Type_inference",
            "Region-based_memory_management",
        ),
    },
    "reasonml": {
        "tags": ["reasonml language", "reason language", "ocaml language",
                 "javascript language", "source to source compiler"],
        "license": CC_BY_SA,
        "pages": wiki(
            "ReasonML",
            "Reason_(programming_language)",
            "OCaml",
            "JavaScript",
            "Source-to-source_compiler",
            "Pattern_matching",
            "Algebraic_data_type",
        ),
    },
    "rescript-lang": {
        "tags": ["rescript language", "ocaml language", "javascript language",
                 "type inference", "source to source compiler"],
        "license": CC_BY_SA,
        "pages": wiki(
            "ReScript",
            "OCaml",
            "JavaScript",
            "Type_inference",
            "Source-to-source_compiler",
            "Transpiler",
            "Type_system",
        ),
    },
    "grain-language": {
        "tags": ["grain language", "webassembly target", "type inference",
                 "algebraic data type", "pattern matching"],
        "license": CC_BY_SA,
        "pages": wiki(
            "WebAssembly",
            "Type_inference",
            "Algebraic_data_type",
            "Pattern_matching",
            "Automatic_memory_management",
            "Bytecode",
            "Compiler",
        ),
    },
    "ballerina-deep": {
        "tags": ["ballerina language", "cloud computing", "integration platform",
                 "wso2 company", "domain specific language"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ballerina_(programming_language)",
            "Cloud_computing",
            "Integration_platform",
            "WSO2",
            "Domain-specific_language",
            "Concurrent_computing",
            "Type_system",
        ),
    },
    "pony-language": {
        "tags": ["pony language", "actor model", "capability based security",
                 "reference capability", "object capability model"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Pony_(programming_language)",
            "Actor_model",
            "Capability-based_security",
            "Object-capability_model",
            "Message_passing",
            "Memory_safety",
            "Concurrent_computing",
        ),
    },
    "chapel-deep": {
        "tags": ["chapel language", "cray supercomputer", "parallel computing",
                 "partitioned global address space", "high performance computing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Chapel_(programming_language)",
            "Cray",
            "Parallel_computing",
            "Partitioned_global_address_space",
            "High-performance_computing",
            "Data_parallelism",
            "Concurrent_computing",
        ),
    },
    "x10-language": {
        "tags": ["x10 language", "high performance computing", "concurrent computing",
                 "partitioned global address space", "parallel computing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "X10_(programming_language)",
            "High-performance_computing",
            "Concurrent_computing",
            "Partitioned_global_address_space",
            "Parallel_computing",
            "IBM",
            "Green_threads",
        ),
    },
    "fortress-language": {
        "tags": ["fortress language", "sun microsystems", "guy steele",
                 "high performance computing", "parallel computing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Fortress_(programming_language)",
            "Sun_Microsystems",
            "Guy_L._Steele_Jr.",
            "High-performance_computing",
            "Parallel_computing",
            "Generic_programming",
            "Concurrent_computing",
        ),
    },
    "io-language": {
        "tags": ["io language", "prototype based programming", "message passing",
                 "actor model", "coroutine concurrency"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Io_(programming_language)",
            "Prototype-based_programming",
            "Message_passing",
            "Actor_model",
            "Coroutine",
            "Duck_typing",
            "Homoiconicity",
        ),
    },
    "rebol-red": {
        "tags": ["rebol language", "red language", "carl sassenrath",
                 "domain specific language", "homoiconic language"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Rebol",
            "Red_(programming_language)",
            "Carl_Sassenrath",
            "Domain-specific_language",
            "Homoiconicity",
            "Metaprogramming",
            "Little_language",
        ),
    },
    "tcl-tk-deep": {
        "tags": ["tcl language", "tk toolkit", "john ousterhout",
                 "scripting language", "glue language"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Tcl",
            "Tk_(software)",
            "John_Ousterhout",
            "Scripting_language",
            "Glue_language",
            "Expect",
            "Domain-specific_language",
        ),
    },
    "autoit": {
        "tags": ["autoit language", "gui testing", "windows automation",
                 "scripting language", "task automation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "AutoIt",
            "GUI_testing",
            "Automation",
            "Scripting_language",
            "Windows",
            "Command-line_interface",
            "Expect",
        ),
    },
    "applescript-deep": {
        "tags": ["applescript language", "apple events", "hypercard software",
                 "scripting language", "classic mac"],
        "license": CC_BY_SA,
        "pages": wiki(
            "AppleScript",
            "Apple_events",
            "HyperCard",
            "Scripting_language",
            "Mac_OS",
            "Automation",
            "Larry_Tesler",
        ),
    },
    "powershell-deep": {
        "tags": ["powershell language", "windows management instrumentation",
                 "cmdlet command", "command line interface", "scripting language"],
        "license": CC_BY_SA,
        "pages": wiki(
            "PowerShell",
            "Cmdlet",
            "Windows_Management_Instrumentation",
            "Command-line_interface",
            "Scripting_language",
            "Shell_(computing)",
            "Automation",
        ),
    },
    "vimscript-deep": {
        "tags": ["vim editor", "vimscript language", "bram moolenaar",
                 "text editor", "vi editor"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Vim_(text_editor)",
            "Vi",
            "Text_editor",
            "Bram_Moolenaar",
            "Scripting_language",
            "Extensible_programming",
            "Domain-specific_language",
        ),
    },
    "elisp-deep": {
        "tags": ["emacs lisp", "gnu emacs", "richard stallman",
                 "extension language", "lisp language"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Emacs_Lisp",
            "Emacs",
            "GNU_Emacs",
            "Richard_Stallman",
            "Lisp_(programming_language)",
            "Extension_language",
            "S-expression",
        ),
    },
    "guile-scheme": {
        "tags": ["guile scheme", "gnu project", "scheme language",
                 "extension language", "lisp language"],
        "license": CC_BY_SA,
        "pages": wiki(
            "GNU_Guile",
            "GNU_Project",
            "Scheme_(programming_language)",
            "Extension_language",
            "Lisp_(programming_language)",
            "Read%E2%80%93eval%E2%80%93print_loop",
            "Continuation",
        ),
    },
    "chicken-scheme": {
        "tags": ["chicken scheme", "scheme language", "compiler tooling",
                 "continuation passing style", "just in time compilation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "CHICKEN_(Scheme_implementation)",
            "Scheme_(programming_language)",
            "Compiler",
            "Continuation-passing_style",
            "Just-in-time_compilation",
            "Tail_call",
            "S-expression",
        ),
    },
    "gambit-scheme": {
        "tags": ["gambit scheme", "scheme language", "continuation control",
                 "tail call", "self hosting compilers"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Gambit_(scheme_implementation)",
            "Scheme_(programming_language)",
            "Continuation",
            "Tail_call",
            "Self-hosting_(compilers)",
            "Compiler",
            "Coroutine",
        ),
    },
    "chez-scheme": {
        "tags": ["chez scheme", "kent dybvig", "scheme language",
                 "r6rs standard", "just in time compilation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Chez_Scheme",
            "R6RS",
            "Kent_Dybvig",
            "Scheme_(programming_language)",
            "Just-in-time_compilation",
            "Macro_(computer_science)",
            "Tail_call",
        ),
    },
    "newlisp": {
        "tags": ["newlisp language", "lisp language", "scripting language",
                 "interpreter computing", "s expression"],
        "license": CC_BY_SA,
        "pages": wiki(
            "NewLisp",
            "Lisp_(programming_language)",
            "Scripting_language",
            "Interpreter_(computing)",
            "S-expression",
            "Fexpr",
            "Homoiconicity",
        ),
    },
    "picolisp": {
        "tags": ["picolisp language", "lisp language", "minimalism computing",
                 "interpreter computing", "s expression"],
        "license": CC_BY_SA,
        "pages": wiki(
            "PicoLisp",
            "Lisp_(programming_language)",
            "Minimalism_(computing)",
            "Interpreter_(computing)",
            "S-expression",
            "Fexpr",
            "Metaprogramming",
        ),
    },
    "hy-lisp": {
        "tags": ["hy language", "lisp language", "python language",
                 "abstract syntax tree", "macro computer science"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Hy_(programming_language)",
            "Lisp_(programming_language)",
            "Abstract_syntax_tree",
            "Macro_(computer_science)",
            "S-expression",
            "Homoiconicity",
            "Metaprogramming",
        ),
    },
    "fennel-lisp": {
        "tags": ["fennel language", "lua language", "lisp language",
                 "transpiler tooling", "macro computer science"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Lua_(programming_language)",
            "Lisp_(programming_language)",
            "Transpiler",
            "Macro_(computer_science)",
            "S-expression",
            "Homoiconicity",
            "Abstract_syntax_tree",
        ),
    },
    "janet-language": {
        "tags": ["janet language", "lisp language", "embeddable language",
                 "scripting language", "s expression"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Lisp_(programming_language)",
            "C_(programming_language)",
            "Scripting_language",
            "S-expression",
            "Fiber_(computer_science)",
            "Coroutine",
            "Macro_(computer_science)",
        ),
    },
    "wren-language": {
        "tags": ["wren language", "class based programming", "fiber concurrency",
                 "embeddable language", "scripting language"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Class_(computer_programming)",
            "Fiber_(computer_science)",
            "Scripting_language",
            "Bytecode",
            "Virtual_machine",
            "Object-oriented_programming",
            "Duck_typing",
        ),
    },
    "gdscript-deep": {
        "tags": ["gdscript language", "godot engine", "game engine",
                 "duck typing", "scripting language"],
        "license": CC_BY_SA,
        "pages": wiki(
            "GDScript",
            "Godot_(game_engine)",
            "Game_engine",
            "Duck_typing",
            "Scripting_language",
            "Bytecode",
            "Video_game",
        ),
    },
    "haxe-language": {
        "tags": ["haxe language", "cross platform software", "actionscript language",
                 "source to source compiler", "neko virtual machine"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Haxe",
            "Cross-platform_software",
            "ActionScript",
            "Source-to-source_compiler",
            "NekoVM",
            "Type_inference",
            "Transpiler",
        ),
    },
    "terra-language": {
        "tags": ["terra language", "lua language", "multi stage programming",
                 "llvm backend", "ahead of time compilation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Lua_(programming_language)",
            "Multi-stage_programming",
            "LLVM",
            "Ahead-of-time_compilation",
            "Metaprogramming",
            "System_programming_language",
            "Just-in-time_compilation",
        ),
    },
    "futhark-deep": {
        "tags": ["futhark language", "data parallelism", "parallel programming model",
                 "purely functional programming", "gpu computing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Futhark_(programming_language)",
            "Data_parallelism",
            "Parallel_programming_model",
            "Purely_functional_programming",
            "General-purpose_computing_on_graphics_processing_units",
            "GPU",
            "SIMD",
        ),
    },
    "dex-language": {
        "tags": ["dex language", "array programming language", "data parallelism",
                 "just in time compilation", "gpu computing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Array_programming",
            "Data_parallelism",
            "Just-in-time_compilation",
            "General-purpose_computing_on_graphics_processing_units",
            "GPU",
            "Type_inference",
            "Automatic_differentiation",
        ),
    },
}
