"""AWS managed-service catalog (deep)."""

from .common import CC_BY_SA, wiki

DOMAINS = {
    "aws-athena": {
        "tags": ["aws athena", "amazon athena", "serverless sql query", "interactive query service"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Amazon_Athena",
            "Presto_(SQL_query_engine)",
            "Trino_(SQL_query_engine)",
            "Data_lake",
            "Amazon_Web_Services",
            "SQL",
        ),
    },
    "aws-glue": {
        "tags": ["aws glue", "amazon glue", "managed etl service", "serverless data integration"],
        "license": CC_BY_SA,
        "pages": wiki(
            "AWS_Glue",
            "Extract,_transform,_load",
            "Data_integration",
            "Data_catalog",
            "Apache_Spark",
            "Amazon_Web_Services",
        ),
    },
    "aws-emr": {
        "tags": ["aws emr", "amazon emr", "managed hadoop", "big data cluster"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Amazon_EMR",
            "Apache_Hadoop",
            "Apache_Spark",
            "Big_data",
            "Distributed_computing",
            "Apache_Hive",
        ),
    },
    "aws-redshift-deep": {
        "tags": ["aws redshift", "amazon redshift", "cloud data warehouse", "columnar analytics"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Amazon_Redshift",
            "Data_warehouse",
            "Column-oriented_DBMS",
            "Online_analytical_processing",
            "Massively_parallel",
            "Business_intelligence",
        ),
    },
    "aws-aurora": {
        "tags": ["aws aurora", "amazon aurora", "managed relational database", "cloud-native database"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Amazon_Aurora",
            "Relational_database",
            "MySQL",
            "PostgreSQL",
            "Database_replication",
            "ACID",
        ),
    },
    "aws-elasticache": {
        "tags": ["aws elasticache", "amazon elasticache", "managed cache", "in-memory data store"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Amazon_ElastiCache",
            "Cache_(computing)",
            "Redis",
            "Memcached",
            "In-memory_database",
            "Latency_(engineering)",
        ),
    },
    "aws-msk": {
        "tags": ["aws msk", "managed streaming kafka", "amazon kafka", "event streaming platform"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Apache_Kafka",
            "Stream_processing",
            "Message_broker",
            "Event-driven_architecture",
            "Publish-subscribe_pattern",
            "Amazon_Web_Services",
        ),
    },
    "aws-eventbridge": {
        "tags": ["aws eventbridge", "amazon eventbridge", "serverless event bus", "event routing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Event-driven_architecture",
            "Message_broker",
            "Publish-subscribe_pattern",
            "Serverless_computing",
            "Complex_event_processing",
            "Amazon_Web_Services",
        ),
    },
    "aws-cognito": {
        "tags": ["aws cognito", "amazon cognito", "user authentication service", "identity pools"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Amazon_Cognito",
            "OpenID_Connect",
            "OAuth",
            "Federated_identity",
            "Single_sign-on",
            "Authentication",
        ),
    },
    "aws-amplify": {
        "tags": ["aws amplify", "amazon amplify", "full-stack app framework", "mobile backend"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Mobile_backend_as_a_service",
            "Front_and_back_ends",
            "Progressive_web_app",
            "Serverless_computing",
            "JavaScript",
            "Amazon_Web_Services",
        ),
    },
    "aws-appsync": {
        "tags": ["aws appsync", "amazon appsync", "managed graphql", "realtime api service"],
        "license": CC_BY_SA,
        "pages": wiki(
            "GraphQL",
            "Web_service",
            "Real-time_web",
            "WebSocket",
            "Push_technology",
            "Amazon_Web_Services",
        ),
    },
    "aws-sagemaker": {
        "tags": ["aws sagemaker", "managed machine learning", "ml training platform", "model deployment service"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Amazon_SageMaker",
            "Machine_learning",
            "MLOps",
            "Deep_learning",
            "Hyperparameter_optimization",
            "Notebook_interface",
        ),
    },
    "aws-bedrock": {
        "tags": ["aws bedrock", "amazon bedrock", "managed foundation models", "generative ai service"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Amazon_Bedrock",
            "Foundation_model",
            "Generative_artificial_intelligence",
            "Large_language_model",
            "Prompt_engineering",
            "Transformer_(deep_learning_architecture)",
        ),
    },
    "aws-fargate": {
        "tags": ["aws fargate", "serverless containers", "managed container compute", "container orchestration"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Serverless_computing",
            "Container_(virtualization)",
            "OS-level_virtualization",
            "Kubernetes",
            "Docker_(software)",
            "Microservices",
        ),
    },
    "aws-batch": {
        "tags": ["aws batch", "managed batch computing", "batch job scheduling", "compute job queue"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Batch_processing",
            "Job_scheduler",
            "High-performance_computing",
            "Parallel_computing",
            "Grid_computing",
            "Task_(computing)",
        ),
    },
    "aws-cloudtrail": {
        "tags": ["aws cloudtrail", "cloud audit logging", "api activity logging", "governance audit trail"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Information_security_audit",
            "Log_analysis",
            "Security_information_and_event_management",
            "Regulatory_compliance",
            "Governance,_risk_management,_and_compliance",
            "Amazon_Web_Services",
        ),
    },
    "aws-config": {
        "tags": ["aws config", "resource configuration tracking", "compliance configuration", "config drift detection"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Configuration_management",
            "Regulatory_compliance",
            "Infrastructure_as_code",
            "Provisioning_(technology)",
            "Governance,_risk_management,_and_compliance",
            "Amazon_Web_Services",
        ),
    },
    "aws-guardduty": {
        "tags": ["aws guardduty", "amazon guardduty", "cloud threat detection", "intelligent threat monitoring"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Intrusion_detection_system",
            "Anomaly_detection",
            "Threat_(computer)",
            "Cloud_computing_security",
            "Security_information_and_event_management",
            "User_behavior_analytics",
        ),
    },
    "aws-secrets-manager": {
        "tags": ["aws secrets manager", "secret rotation", "credential management", "cloud secrets store"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Key_management",
            "Encryption",
            "Public_key_infrastructure",
            "Hardware_security_module",
            "Access_control",
            "Amazon_Web_Services",
        ),
    },
    "aws-systems-manager": {
        "tags": ["aws systems manager", "fleet operations management", "patch management service", "operational insights"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Configuration_management",
            "Patch_(computing)",
            "Provisioning_(technology)",
            "Infrastructure_as_code",
            "Resource_management_(computing)",
            "Amazon_Web_Services",
        ),
    },
    "aws-transit-gateway": {
        "tags": ["aws transit gateway", "network transit hub", "cloud network routing", "vpc interconnect"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Software-defined_networking",
            "Network_virtualization",
            "Load_balancing_(computing)",
            "Border_Gateway_Protocol",
            "Wide_area_network",
            "Amazon_Web_Services",
        ),
    },
    "aws-direct-connect": {
        "tags": ["aws direct connect", "dedicated network connection", "private cloud link", "hybrid network"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Leased_line",
            "Dedicated_line",
            "Point-to-point_(telecommunications)",
            "Peering",
            "Internet_exchange_point",
            "Multiprotocol_Label_Switching",
        ),
    },
    "aws-global-accelerator": {
        "tags": ["aws global accelerator", "global traffic acceleration", "anycast networking", "edge routing service"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Anycast",
            "Content_delivery_network",
            "Load_balancing_(computing)",
            "Backbone_network",
            "Edge_computing",
            "Latency_(engineering)",
        ),
    },
    "aws-elastic-beanstalk": {
        "tags": ["aws elastic beanstalk", "managed app platform", "platform as a service", "app deployment service"],
        "license": CC_BY_SA,
        "pages": wiki(
            "AWS_Elastic_Beanstalk",
            "Platform_as_a_service",
            "Web_application",
            "Autoscaling",
            "Continuous_deployment",
            "Amazon_Web_Services",
        ),
    },
    "aws-lightsail": {
        "tags": ["aws lightsail", "amazon lightsail", "virtual private server", "simplified cloud hosting"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Amazon_Lightsail",
            "Virtualization",
            "Web_application",
            "Cloud_computing",
            "Cloud_management",
            "Amazon_Web_Services",
        ),
    },
    "aws-app-runner": {
        "tags": ["aws app runner", "amazon app runner", "containerized web service", "managed app hosting"],
        "license": CC_BY_SA,
        "pages": wiki(
            "AWS_App_Runner",
            "Serverless_computing",
            "Container_(virtualization)",
            "Autoscaling",
            "Web_application",
            "Microservices",
        ),
    },
    "aws-lambda-layers": {
        "tags": ["aws lambda layers", "lambda dependency packaging", "serverless code reuse", "function runtime layer"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Serverless_computing",
            "Function_as_a_service",
            "Event-driven_architecture",
            "Microservices",
            "Configuration_management",
            "Amazon_Web_Services",
        ),
    },
    "aws-efs": {
        "tags": ["aws efs", "amazon elastic file system", "managed nfs", "shared cloud file storage"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Amazon_Elastic_File_System",
            "Network_file_system",
            "Network-attached_storage",
            "Scalability",
            "High_availability",
            "Amazon_Web_Services",
        ),
    },
    "aws-fsx": {
        "tags": ["aws fsx", "amazon fsx", "managed file server", "windows file storage"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Server_Message_Block",
            "Network-attached_storage",
            "Network_file_system",
            "Storage_virtualization",
            "High-performance_computing",
            "Amazon_Web_Services",
        ),
    },
    "aws-storage-gateway": {
        "tags": ["aws storage gateway", "hybrid cloud storage", "on-premises storage bridge", "cloud storage cache"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Storage_virtualization",
            "Hierarchical_storage_management",
            "Network-attached_storage",
            "Tiered_storage",
            "Nearline_storage",
            "Amazon_Web_Services",
        ),
    },
    "aws-backup": {
        "tags": ["aws backup", "centralized backup service", "cloud backup management", "backup policy automation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Backup",
            "Disaster_recovery",
            "Snapshot_(computer_storage)",
            "Point-in-time_recovery",
            "Data_management",
            "Replication_(computing)",
        ),
    },
    "aws-datasync": {
        "tags": ["aws datasync", "data transfer service", "cloud data migration", "file synchronization service"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Data_migration",
            "File_synchronization",
            "Data_replication",
            "Network-attached_storage",
            "Throughput",
            "Amazon_Web_Services",
        ),
    },
    "aws-glacier": {
        "tags": ["aws glacier", "amazon s3 glacier", "cold archive storage", "long-term data archive"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Amazon_Glacier",
            "Nearline_storage",
            "Tiered_storage",
            "Hierarchical_storage_management",
            "Write_once_read_many",
            "Data_management",
        ),
    },
    "aws-neptune": {
        "tags": ["aws neptune", "amazon neptune", "managed graph database", "knowledge graph service"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Amazon_Neptune",
            "Graph_database",
            "Resource_Description_Framework",
            "SPARQL",
            "Knowledge_graph",
            "Triplestore",
        ),
    },
    "aws-timestream": {
        "tags": ["aws timestream", "amazon timestream", "time series database", "iot time series store"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Time_series_database",
            "Time_series",
            "Internet_of_things",
            "Telemetry",
            "Stream_processing",
            "Amazon_Web_Services",
        ),
    },
    "aws-documentdb": {
        "tags": ["aws documentdb", "amazon documentdb", "managed document database", "mongodb-compatible database"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Amazon_DocumentDB",
            "Document-oriented_database",
            "MongoDB",
            "NoSQL",
            "JSON",
            "BSON",
        ),
    },
    "aws-keyspaces": {
        "tags": ["aws keyspaces", "amazon keyspaces", "managed cassandra", "wide-column database service"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Apache_Cassandra",
            "Wide-column_store",
            "NoSQL",
            "Column_family",
            "Consistency_model",
            "Distributed_database",
        ),
    },
    "aws-memorydb": {
        "tags": ["aws memorydb", "amazon memorydb", "durable in-memory database", "redis-compatible store"],
        "license": CC_BY_SA,
        "pages": wiki(
            "In-memory_database",
            "Redis",
            "Cache_(computing)",
            "Consistency_model",
            "Fault_tolerance",
            "Amazon_Web_Services",
        ),
    },
    "aws-opensearch-service": {
        "tags": ["aws opensearch", "amazon opensearch service", "managed search cluster", "log analytics engine"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Elasticsearch",
            "Full-text_search",
            "Inverted_index",
            "Search_engine_(computing)",
            "Log_analysis",
            "Amazon_Web_Services",
        ),
    },
    "aws-quicksight": {
        "tags": ["aws quicksight", "amazon quicksight", "business intelligence service", "cloud dashboards"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Amazon_QuickSight",
            "Business_intelligence",
            "Data_visualization",
            "Dashboard_(computing)",
            "Interactive_visualization",
            "Business_reporting",
        ),
    },
    "aws-kinesis-firehose": {
        "tags": ["aws kinesis firehose", "streaming data delivery", "realtime data ingestion", "data stream loader"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Amazon_Kinesis",
            "Streaming_data",
            "Stream_processing",
            "Data_stream",
            "Real-time_data",
            "Extract,_transform,_load",
        ),
    },
    "aws-data-pipeline": {
        "tags": ["aws data pipeline", "managed workflow orchestration", "data workflow scheduling", "etl pipeline service"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Data_pipeline",
            "Workflow",
            "Directed_acyclic_graph",
            "Orchestration_(computing)",
            "Extract,_transform,_load",
            "Job_scheduler",
        ),
    },
    "aws-lake-formation": {
        "tags": ["aws lake formation", "data lake governance", "centralized data permissions", "data lake catalog"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Data_lake",
            "Data_governance",
            "Data_catalog",
            "Attribute-based_access_control",
            "Metadata",
            "Data_lakehouse",
        ),
    },
    "aws-sfn-workflows": {
        "tags": ["aws step functions", "serverless workflow orchestration", "state machine service", "workflow automation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Orchestration_(computing)",
            "Finite-state_machine",
            "State_machine",
            "Workflow",
            "Directed_acyclic_graph",
            "Serverless_computing",
        ),
    },
    "aws-cloudfront-functions": {
        "tags": ["aws cloudfront functions", "edge compute functions", "cdn edge scripting", "lightweight edge code"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Amazon_CloudFront",
            "Edge_computing",
            "Content_delivery_network",
            "Serverless_computing",
            "JavaScript",
            "Latency_(engineering)",
        ),
    },
    "aws-waf": {
        "tags": ["aws waf", "web application firewall service", "http request filtering", "cloud web protection"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Web_application_firewall",
            "Firewall_(computing)",
            "Denial-of-service_attack",
            "Web_application",
            "Network_security",
            "Cloud_computing_security",
        ),
    },
    "aws-shield": {
        "tags": ["aws shield", "ddos protection service", "denial of service mitigation", "network attack defense"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Denial-of-service_attack",
            "Cloud_computing_security",
            "Network_security",
            "Anycast",
            "Content_delivery_network",
            "Amazon_Web_Services",
        ),
    },
    "aws-macie": {
        "tags": ["aws macie", "amazon macie", "sensitive data discovery", "data privacy scanning"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Data_loss_prevention_software",
            "Data_masking",
            "Anomaly_detection",
            "Machine_learning",
            "Regulatory_compliance",
            "Cloud_computing_security",
        ),
    },
    "aws-inspector": {
        "tags": ["aws inspector", "amazon inspector", "vulnerability assessment service", "automated security scanning"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Vulnerability_scanner",
            "Vulnerability_(computing)",
            "Malware",
            "Cloud_computing_security",
            "Regulatory_compliance",
            "Endpoint_security",
        ),
    },
    "aws-security-hub": {
        "tags": ["aws security hub", "cloud security posture", "security findings aggregation", "compliance dashboard"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Security_information_and_event_management",
            "Cloud_computing_security",
            "Regulatory_compliance",
            "Governance,_risk_management,_and_compliance",
            "Threat_(computer)",
            "Vulnerability_(computing)",
        ),
    },
    "aws-organizations": {
        "tags": ["aws organizations", "multi-account management", "account governance", "consolidated billing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Governance",
            "Organizational_structure",
            "Access_control",
            "Regulatory_compliance",
            "Resource_management_(computing)",
            "Amazon_Web_Services",
        ),
    },
    "aws-control-tower": {
        "tags": ["aws control tower", "multi-account landing zone", "cloud governance automation", "account provisioning"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cloud_management",
            "Governance,_risk_management,_and_compliance",
            "Provisioning_(technology)",
            "Configuration_management",
            "Regulatory_compliance",
            "Multitenancy",
        ),
    },
    "aws-cost-explorer": {
        "tags": ["aws cost explorer", "cloud cost analysis", "billing analytics", "spend visualization"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cost_management",
            "Total_cost_of_ownership",
            "Invoice",
            "Data_visualization",
            "Predictive_analytics",
            "Amazon_Web_Services",
        ),
    },
    "aws-x-ray": {
        "tags": ["aws x-ray", "distributed request tracing", "application performance tracing", "microservice observability"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Tracing_(software)",
            "Observability",
            "Application_performance_management",
            "Microservices",
            "Performance_engineering",
            "Call_stack",
        ),
    },
}
