"""More named algorithms: flows, matching, geometry, string, graph, numeric families."""

from .common import CC_BY_SA, wiki

DOMAINS = {
    "convex-hull-algorithms": {
        "tags": ["convex hull algorithm", "graham scan", "quickhull method", "gift wrapping"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Convex_hull_algorithms",
            "Graham_scan",
            "Quickhull",
            "Gift_wrapping_algorithm",
            "Chan's_algorithm",
            "Convex_hull",
        ),
    },
    "line-segment-intersection": {
        "tags": ["line segment intersection", "bentley ottmann algorithm", "sweep line", "computational geometry"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Line_segment_intersection",
            "Bentley–Ottmann_algorithm",
            "Line–line_intersection",
            "Sweep_line_algorithm",
            "Arrangement_of_lines",
            "Intersection_(geometry)",
        ),
    },
    "voronoi-fortune": {
        "tags": ["voronoi diagram", "fortune algorithm", "beach line", "power diagram"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Fortune's_algorithm",
            "Voronoi_diagram",
            "Weighted_Voronoi_diagram",
            "Power_diagram",
            "Centroidal_Voronoi_tessellation",
            "Lloyd's_algorithm",
        ),
    },
    "delaunay-triangulation-algo": {
        "tags": ["delaunay triangulation", "bowyer watson algorithm", "empty circle", "constrained delaunay"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Delaunay_triangulation",
            "Bowyer–Watson_algorithm",
            "Constrained_Delaunay_triangulation",
            "Ruppert's_algorithm",
            "Pitteway_triangulation",
            "Delaunay_refinement",
        ),
    },
    "point-location": {
        "tags": ["point location", "planar subdivision", "trapezoidal decomposition", "slab method"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Point_location",
            "Planar_straight-line_graph",
            "Trapezoid_graph",
            "Point_in_polygon",
            "Doubly_connected_edge_list",
            "Search_data_structure",
        ),
    },
    "range-searching": {
        "tags": ["range searching", "orthogonal range query", "kd tree query", "fractional cascading"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Range_searching",
            "Range_tree",
            "K-d_tree",
            "Fractional_cascading",
            "Priority_search_tree",
            "Range_query_(data_structures)",
        ),
    },
    "nearest-neighbor-search-nns": {
        "tags": ["nearest neighbor search", "best bin first", "space partitioning", "vantage point tree"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Nearest_neighbor_search",
            "Best_bin_first",
            "Vantage-point_tree",
            "Cover_tree",
            "Fixed-radius_near_neighbors",
            "Large_margin_nearest_neighbor",
        ),
    },
    "closest-pair-algorithm": {
        "tags": ["closest pair of points", "divide and conquer geometry", "recursive splitting", "planar distance"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Closest_pair_of_points_problem",
            "Divide-and-conquer_algorithm",
            "Euclidean_distance",
            "Delaunay_triangulation",
            "K-d_tree",
            "Sweep_line_algorithm",
        ),
    },
    "rotating-calipers": {
        "tags": ["rotating calipers", "convex polygon width", "antipodal pairs", "polygon diameter"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Rotating_calipers",
            "Convex_polygon",
            "Minimum_bounding_box",
            "Diameter_(computational_geometry)",
            "Width_of_a_convex_polygon",
            "Antipodal_point",
        ),
    },
    "polygon-triangulation": {
        "tags": ["polygon triangulation", "ear clipping", "monotone polygon", "trapezoid decomposition"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Polygon_triangulation",
            "Two_ears_theorem",
            "Monotone_polygon",
            "Point_in_polygon",
            "Simple_polygon",
            "Fan_triangulation",
        ),
    },
    "minimum-enclosing-circle": {
        "tags": ["smallest enclosing circle", "welzl algorithm", "bounding sphere", "minimum enclosing ball"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Smallest-circle_problem",
            "Bounding_sphere",
            "Minimum_bounding_box",
            "Chebyshev_center",
            "1-center_problem",
            "Enclosure_(mathematics)",
        ),
    },
    "gift-wrapping": {
        "tags": ["gift wrapping algorithm", "jarvis march", "convex hull output", "beneath beyond"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Gift_wrapping_algorithm",
            "Output-sensitive_algorithm",
            "Convex_hull_of_a_simple_polygon",
            "Kirkpatrick–Seidel_algorithm",
            "Upper_and_lower_bounds",
            "Extreme_point",
        ),
    },
    "sweep-line-paradigm": {
        "tags": ["sweep line algorithm", "event queue", "plane sweep", "status structure"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Sweep_line_algorithm",
            "Event_(computing)",
            "Klee's_measure_problem",
            "Segment_tree",
            "Arrangement_(space_partition)",
            "Boolean_operations_on_polygons",
        ),
    },
    "hopcroft-karp-matching": {
        "tags": ["hopcroft karp algorithm", "bipartite matching", "augmenting path", "maximum matching"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Hopcroft–Karp_algorithm",
            "Maximum_cardinality_matching",
            "Bipartite_graph",
            "Matching_(graph_theory)",
            "Berge's_theorem",
            "König's_theorem_(graph_theory)",
        ),
    },
    "hungarian-assignment": {
        "tags": ["hungarian algorithm", "assignment problem", "kuhn munkres method", "cost matrix"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Hungarian_algorithm",
            "Assignment_problem",
            "Generalized_assignment_problem",
            "Maximum-weight_matching",
            "Combinatorial_optimization",
            "Dual_linear_program",
        ),
    },
    "blossom-edmonds-contraction": {
        "tags": ["blossom algorithm", "edmonds matching", "general graph matching", "odd cycle contraction"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Blossom_algorithm",
            "Matching_(graph_theory)",
            "Maximum_weight_matching",
            "Tutte_theorem",
            "Perfect_matching",
            "Micali–Vazirani_algorithm",
        ),
    },
    "stable-roommates": {
        "tags": ["stable roommates problem", "irving algorithm", "stable matching", "preference list"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Stable_roommates_problem",
            "Stable_marriage_problem",
            "Gale–Shapley_algorithm",
            "Lattice_of_stable_matchings",
            "Assignment_problem",
            "National_Resident_Matching_Program",
        ),
    },
    "push-relabel-maxflow": {
        "tags": ["push relabel algorithm", "preflow maximum flow", "height function", "goldberg tarjan"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Push–relabel_maximum_flow_algorithm",
            "Maximum_flow_problem",
            "Flow_network",
            "Circulation_problem",
            "Residual_graph",
            "Menger's_theorem",
        ),
    },
    "min-cost-max-flow": {
        "tags": ["minimum cost flow", "min cost max flow", "successive shortest path", "cost scaling"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Minimum-cost_flow_problem",
            "Network_simplex_algorithm",
            "Out-of-kilter_algorithm",
            "Flow_network",
            "Shortest_path_problem",
            "Transportation_theory_(mathematics)",
        ),
    },
    "gomory-hu-tree": {
        "tags": ["gomory hu tree", "all pairs min cut", "cut tree", "flow equivalent tree"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Gomory–Hu_tree",
            "Minimum_cut",
            "Max-flow_min-cut_theorem",
            "Cut_(graph_theory)",
            "Flow_network",
            "Tree_(graph_theory)",
        ),
    },
    "stoer-wagner-mincut": {
        "tags": ["stoer wagner algorithm", "global minimum cut", "maximum adjacency ordering", "undirected mincut"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Stoer–Wagner_algorithm",
            "Minimum_cut",
            "Cut_(graph_theory)",
            "Connectivity_(graph_theory)",
            "Maximum_cut",
            "Graph_partition",
        ),
    },
    "karger-randomized-cut": {
        "tags": ["karger algorithm", "randomized min cut", "edge contraction", "monte carlo method"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Karger's_algorithm",
            "Minimum_cut",
            "Edge_contraction",
            "Randomized_algorithm",
            "Monte_Carlo_algorithm",
            "Cut_(graph_theory)",
        ),
    },
    "johnson-all-pairs": {
        "tags": ["johnson algorithm", "all pairs shortest path", "reweighting technique", "sparse graph"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Johnson's_algorithm",
            "Shortest_path_problem",
            "Bellman–Ford_algorithm",
            "Dijkstra's_algorithm",
            "Reachability",
            "Sparse_graph",
        ),
    },
    "yen-k-shortest": {
        "tags": ["yen algorithm", "k shortest paths", "loopless paths", "spur node"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Yen's_algorithm",
            "K_shortest_path_routing",
            "Shortest_path_problem",
            "Eppstein's_algorithm",
            "Dijkstra's_algorithm",
            "Path_(graph_theory)",
        ),
    },
    "suurballe-disjoint-paths": {
        "tags": ["suurballe algorithm", "disjoint paths", "edge disjoint routing", "network survivability"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Suurballe's_algorithm",
            "Edge_disjoint_shortest_pair_algorithm",
            "K_shortest_path_routing",
            "Menger's_theorem",
            "Shortest_path_problem",
            "Flow_network",
        ),
    },
    "eulerian-path-traversal": {
        "tags": ["eulerian path", "eulerian circuit", "degree condition", "bridge finding"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Eulerian_path",
            "Fleury's_algorithm",
            "Seven_Bridges_of_Königsberg",
            "Bridge_(graph_theory)",
            "Handshaking_lemma",
            "Route_inspection_problem",
        ),
    },
    "hierholzer": {
        "tags": ["hierholzer algorithm", "euler tour construction", "edge traversal", "closed walk"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Hierholzer's_algorithm",
            "Eulerian_path",
            "Glossary_of_graph_theory",
            "Cycle_(graph_theory)",
            "Multigraph",
            "De_Bruijn_sequence",
        ),
    },
    "christofides-tsp": {
        "tags": ["christofides algorithm", "traveling salesman approximation", "metric tsp", "approximation ratio"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Christofides_algorithm",
            "Travelling_salesman_problem",
            "Approximation_algorithm",
            "Minimum_spanning_tree",
            "Triangle_inequality",
            "Route_inspection_problem",
        ),
    },
    "held-karp-exact": {
        "tags": ["held karp algorithm", "traveling salesman exact", "bitmask dynamic programming", "subset states"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Held–Karp_algorithm",
            "Travelling_salesman_problem",
            "Dynamic_programming",
            "Bitonic_tour",
            "Branch_and_bound",
            "Time_complexity",
        ),
    },
    "lin-kernighan": {
        "tags": ["lin kernighan heuristic", "local search tsp", "k opt move", "tour improvement"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Lin–Kernighan_heuristic",
            "2-opt",
            "3-opt",
            "Travelling_salesman_problem",
            "Local_search_(optimization)",
            "Or-opt",
        ),
    },
    "boruvka-mst": {
        "tags": ["boruvka algorithm", "minimum spanning tree", "parallel mst", "cheapest edge"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Borůvka's_algorithm",
            "Minimum_spanning_tree",
            "Spanning_tree",
            "Parallel_algorithm",
            "Cut_(graph_theory)",
            "Fractional_cascading",
        ),
    },
    "reverse-delete-pruning": {
        "tags": ["reverse delete algorithm", "minimum spanning tree", "edge removal", "greedy mst"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Reverse-delete_algorithm",
            "Minimum_spanning_tree",
            "Kruskal's_algorithm",
            "Cycle_(graph_theory)",
            "Greedy_algorithm",
            "Spanning_tree",
        ),
    },
    "heavy-light-decomposition": {
        "tags": ["heavy light decomposition", "tree path query", "chain partition", "segment tree on tree"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Heavy_path_decomposition",
            "Tree_(data_structure)",
            "Segment_tree",
            "Lowest_common_ancestor",
            "Path_(graph_theory)",
            "Link/cut_tree",
        ),
    },
    "centroid-tree-divide": {
        "tags": ["centroid decomposition", "tree centroid", "divide and conquer on trees", "path counting"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Centroid",
            "Tree_(graph_theory)",
            "Divide-and-conquer_algorithm",
            "Vertex_separator",
            "Jordan_center",
            "Graph_partition",
        ),
    },
    "lowest-common-ancestor": {
        "tags": ["lowest common ancestor", "range minimum query", "euler tour", "tarjan offline lca"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Lowest_common_ancestor",
            "Tarjan's_off-line_lowest_common_ancestors_algorithm",
            "Range_minimum_query",
            "Level_ancestor_problem",
            "Cartesian_tree",
            "Tree_(data_structure)",
        ),
    },
    "euler-tour-technique": {
        "tags": ["euler tour technique", "tree linearization", "subtree query", "parallel tree algorithm"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Euler_tour_technique",
            "Tree_traversal",
            "List_ranking",
            "Depth-first_search",
            "Fenwick_tree",
            "Parallel_algorithm",
        ),
    },
    "mo-query-ordering": {
        "tags": ["mo algorithm", "offline query ordering", "query square root blocking", "range query batching"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Range_query_(data_structures)",
            "Hilbert_curve",
            "Query_optimization",
            "Amortized_analysis",
            "Space-filling_curve",
            "Selection_algorithm",
        ),
    },
    "sqrt-block-buckets": {
        "tags": ["square root decomposition", "block decomposition", "range query buckets", "sqrt tree"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Prefix_sum",
            "Range_minimum_query",
            "Block_(data_storage)",
            "Fenwick_tree",
            "Amortized_analysis",
            "Time_complexity",
        ),
    },
    "persistent-segment-versioned": {
        "tags": ["persistent segment tree", "versioned range query", "path copying", "functional data structure"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Persistent_data_structure",
            "Segment_tree",
            "Fat_node",
            "Purely_functional_data_structure",
            "Persistent_array",
            "Range_query_(data_structures)",
        ),
    },
    "li-chao-envelope": {
        "tags": ["li chao tree", "line container query", "lower envelope", "kinetic segment tree"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Segment_tree",
            "Lower_envelope",
            "Linear_function",
            "Convex_function",
            "Dynamic_programming",
            "Davenport–Schinzel_sequence",
        ),
    },
    "convex-hull-trick": {
        "tags": ["convex hull trick", "dynamic programming optimization", "lower envelope of lines", "monotone stack"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Dynamic_programming",
            "Convex_hull",
            "Lower_envelope",
            "Linear-fractional_programming",
            "Envelope_(mathematics)",
            "Monotone_polygon",
        ),
    },
    "aho-corasick-deep": {
        "tags": ["aho corasick automaton", "multi pattern search", "failure links", "dictionary matching"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Aho–Corasick_algorithm",
            "Trie",
            "Deterministic_finite_automaton",
            "Commentz-Walter_algorithm",
            "String_searching_algorithm",
            "Finite-state_machine",
        ),
    },
    "suffix-automaton": {
        "tags": ["suffix automaton", "directed acyclic word graph", "substring recognition", "minimal automaton"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Suffix_automaton",
            "Deterministic_acyclic_finite_state_automaton",
            "Suffix_tree",
            "Generalized_suffix_tree",
            "Factor_oracle",
            "Automata_theory",
        ),
    },
    "z-function-prefix": {
        "tags": ["z algorithm", "z array", "prefix substring matching", "linear pattern search"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Z-function",
            "String-searching_algorithm",
            "Knuth–Morris–Pratt_algorithm",
            "Prefix_(computer_science)",
            "Substring",
            "Pattern_matching",
        ),
    },
    "manacher-palindrome": {
        "tags": ["manacher algorithm", "longest palindromic substring", "palindrome radius", "linear palindrome search"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Longest_palindromic_substring",
            "Palindrome",
            "Longest_common_substring",
            "String-searching_algorithm",
            "Dynamic_programming",
            "String_metric",
        ),
    },
    "burrows-wheeler-bwt": {
        "tags": ["burrows wheeler transform", "block sorting compression", "move to front", "bwt inverse"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Burrows–Wheeler_transform",
            "Move-to-front_transform",
            "FM-index",
            "Bzip2",
            "Run-length_encoding",
            "Suffix_array",
        ),
    },
    "wavelet-tree-succinct": {
        "tags": ["wavelet tree", "rank select structure", "succinct sequence", "range quantile query"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Wavelet_Tree",
            "Succinct_data_structure",
            "FM-index",
            "Bitmap_index",
            "Bitmap",
            "Range_minimum_query",
        ),
    },
    "hungarian-simplex": {
        "tags": ["transportation simplex", "network simplex method", "min cost flow simplex", "basic feasible solution"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Network_simplex_algorithm",
            "Transportation_theory_(mathematics)",
            "Minimum-cost_flow_problem",
            "Basic_feasible_solution",
            "Simplex_algorithm",
            "Linear_programming_relaxation",
        ),
    },
    "simplex-method-pivoting": {
        "tags": ["simplex method", "pivot rule", "bland rule", "revised simplex"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Simplex_algorithm",
            "Bland's_rule",
            "Revised_simplex_method",
            "Criss-cross_algorithm",
            "Klee–Minty_cube",
            "Dantzig–Wolfe_decomposition",
        ),
    },
    "karmarkar-interior-point": {
        "tags": ["karmarkar algorithm", "interior point method", "projective scaling", "polynomial linear programming"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Karmarkar's_algorithm",
            "Interior-point_method",
            "Linear_programming",
            "Affine_scaling",
            "Barrier_function",
            "Central_path_(optimization)",
        ),
    },
    "ellipsoid-method": {
        "tags": ["ellipsoid method", "khachiyan algorithm", "separation oracle", "polynomial time optimization"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ellipsoid_method",
            "Linear_programming",
            "Separation_oracle",
            "Convex_optimization",
            "Cutting-plane_method",
            "Feasible_region",
        ),
    },
    "gradient-descent-variants": {
        "tags": ["gradient descent variants", "momentum method", "nesterov acceleration", "adagrad rmsprop"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Stochastic_gradient_descent",
            "Gradient_descent",
            "Learning_rate",
            "Frank–Wolfe_algorithm",
            "Coordinate_descent",
            "Subgradient_method",
        ),
    },
    "adam-optimizer": {
        "tags": ["adam optimizer", "adaptive moment estimation", "first order optimizer", "bias correction"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Stochastic_gradient_descent",
            "Learning_rate",
            "Moment_(mathematics)",
            "Exponential_smoothing",
            "Loss_function",
            "Hyperparameter_(machine_learning)",
        ),
    },
    "quasi-newton-bfgs": {
        "tags": ["quasi newton method", "bfgs update", "limited memory bfgs", "hessian approximation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Quasi-Newton_method",
            "Broyden–Fletcher–Goldfarb–Shanno_algorithm",
            "Limited-memory_BFGS",
            "Davidon–Fletcher–Powell_formula",
            "Secant_method",
            "Symmetric_rank-one",
        ),
    },
    "levenberg-marquardt": {
        "tags": ["levenberg marquardt algorithm", "nonlinear least squares", "damped gauss newton", "trust region"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Levenberg–Marquardt_algorithm",
            "Gauss–Newton_algorithm",
            "Non-linear_least_squares",
            "Trust_region",
            "Least_squares",
            "Curve_fitting",
        ),
    },
    "expectation-maximization-inference": {
        "tags": ["expectation maximization", "baum welch algorithm", "gaussian mixture fitting", "latent variable inference"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Expectation–maximization_algorithm",
            "Baum–Welch_algorithm",
            "Gaussian_mixture_model",
            "Mixture_model",
            "Variational_Bayesian_methods",
            "Latent_variable_model",
        ),
    },
}
