"""Biotech methods, structural/synthetic biology, drug discovery, and materials characterization."""
from .common import CC_BY_SA, wiki

DOMAINS = {
    "cryo-em": {
        "tags": ["cryo-electron microscopy", "single particle analysis", "structural biology", "vitreous ice"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cryogenic_electron_microscopy",
            "Structural_biology",
            "Single_particle_analysis",
            "Electron_microscope",
            "Protein_Data_Bank",
            "Transmission_electron_microscopy",
            "Cryofixation",
        ),
    },
    "x-ray-crystallography-protein": {
        "tags": ["macromolecular crystallography", "phase problem", "diffraction pattern", "resolution"],
        "license": CC_BY_SA,
        "pages": wiki(
            "X-ray_crystallography",
            "Protein_crystallization",
            "Molecular_replacement",
            "Bragg's_law",
            "Structure_factor",
            "Anomalous_dispersion",
            "R-factor_(crystallography)",
        ),
    },
    "protein-nmr": {
        "tags": ["nuclear magnetic resonance", "protein dynamics", "chemical shift", "spin"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Nuclear_magnetic_resonance_spectroscopy_of_proteins",
            "Two-dimensional_nuclear_magnetic_resonance_spectroscopy",
            "Nuclear_Overhauser_effect",
            "Chemical_shift",
            "Protein_dynamics",
            "Residual_dipolar_coupling",
        ),
    },
    "alphafold-prediction": {
        "tags": ["protein structure prediction", "deep learning fold", "contact map", "homology"],
        "license": CC_BY_SA,
        "pages": wiki(
            "AlphaFold",
            "Protein_structure_prediction",
            "CASP",
            "Homology_modeling",
            "Threading_(protein_sequence)",
            "Protein_tertiary_structure",
        ),
    },
    "protein-design-computational": {
        "tags": ["de novo protein", "computational design", "rotamer", "energy function"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Protein_design",
            "Rosetta@home",
            "De_novo_protein_structure_prediction",
            "Foldit",
            "Coiled_coil",
            "Rational_design",
        ),
    },
    "molecular-docking-deep": {
        "tags": ["ligand docking", "binding pose", "scoring function", "conformer"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Docking_(molecular)",
            "Scoring_functions_for_docking",
            "Macromolecular_docking",
            "Binding_site",
            "Ligand_(biochemistry)",
            "Conformational_isomerism",
        ),
    },
    "virtual-screening": {
        "tags": ["in silico screening", "compound library", "hit identification", "chemical space"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Virtual_screening",
            "Chemical_library",
            "Cheminformatics",
            "Chemical_space",
            "Molecular_similarity",
            "Screening_(medicine)",
        ),
    },
    "structure-based-drug-design": {
        "tags": ["rational drug design", "target binding", "receptor pocket", "affinity"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Drug_design",
            "Structure-based_drug_design",
            "Binding_affinity",
            "Enzyme_inhibitor",
            "Allosteric_regulation",
            "Molecular_recognition",
        ),
    },
    "pharmacophore-modeling": {
        "tags": ["pharmacophore feature", "3d model", "hydrogen bond donor", "steric"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Pharmacophore",
            "Free_energy_perturbation",
            "Bioisostere",
            "Molecular_geometry",
            "Hydrogen_bond",
            "Van_der_Waals_force",
        ),
    },
    "qsar-modeling": {
        "tags": ["quantitative structure activity", "molecular descriptor", "regression", "activity cliff"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Quantitative_structure%E2%80%93activity_relationship",
            "Molecular_descriptor",
            "Partition_coefficient",
            "Lipinski's_rule_of_five",
            "QSAR",
            "Chemical_similarity",
        ),
    },
    "admet-prediction": {
        "tags": ["absorption distribution metabolism", "excretion toxicity", "bioavailability", "clearance"],
        "license": CC_BY_SA,
        "pages": wiki(
            "ADME",
            "Bioavailability",
            "Blood%E2%80%93brain_barrier",
            "Cytochrome_P450",
            "Volume_of_distribution",
            "Hepatotoxicity",
        ),
    },
    "lead-optimization": {
        "tags": ["lead compound", "medicinal chemistry", "potency improvement", "selectivity"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Lead_compound",
            "Medicinal_chemistry",
            "Structure%E2%80%93activity_relationship",
            "Drug_discovery",
            "Hit_to_lead",
            "Prodrug",
        ),
    },
    "high-throughput-screening": {
        "tags": ["assay automation", "microplate", "z factor", "compound deck"],
        "license": CC_BY_SA,
        "pages": wiki(
            "High-throughput_screening",
            "Microplate",
            "Assay",
            "Laboratory_automation",
            "Z-factor",
            "Reporter_gene",
        ),
    },
    "fragment-based-drug-discovery": {
        "tags": ["fragment library", "weak binder", "surface plasmon resonance", "growing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Fragment-based_lead_discovery",
            "Surface_plasmon_resonance",
            "Isothermal_titration_calorimetry",
            "Dissociation_constant",
            "Thermal_shift_assay",
            "Ligand_efficiency",
        ),
    },
    "antibody-engineering": {
        "tags": ["engineered antibody", "phage display", "humanization", "single chain"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Antibody_engineering",
            "Phage_display",
            "Single-chain_variable_fragment",
            "Humanized_antibody",
            "Bispecific_monoclonal_antibody",
            "Complementarity-determining_region",
        ),
    },
    "monoclonal-antibodies": {
        "tags": ["hybridoma", "therapeutic antibody", "isotype", "epitope"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Monoclonal_antibody",
            "Hybridoma_technology",
            "Immunoglobulin_G",
            "Epitope",
            "Antibody-dependent_cellular_cytotoxicity",
            "Antibody-drug_conjugate",
        ),
    },
    "car-t-therapy": {
        "tags": ["chimeric antigen receptor", "adoptive cell transfer", "t cell", "cytokine release"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Chimeric_antigen_receptor_T_cell",
            "Adoptive_cell_transfer",
            "T_cell",
            "Cytokine_release_syndrome",
            "Tumor_antigen",
            "Immunotherapy",
        ),
    },
    "mrna-vaccines": {
        "tags": ["messenger rna vaccine", "lipid nanoparticle", "nucleoside modification", "in vitro transcription"],
        "license": CC_BY_SA,
        "pages": wiki(
            "MRNA_vaccine",
            "Lipid_nanoparticle",
            "Five-prime_cap",
            "Polyadenylation",
            "Nucleoside",
            "RNA_polymerase",
        ),
    },
    "gene-therapy-vectors": {
        "tags": ["gene delivery", "viral vector", "transgene", "ex vivo"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Gene_therapy",
            "Vectors_in_gene_therapy",
            "Lentivirus",
            "Transduction_(genetics)",
            "Transgene",
            "Retrovirus",
        ),
    },
    "aav-vectors": {
        "tags": ["adeno-associated virus", "capsid serotype", "tropism", "packaging"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Adeno-associated_virus",
            "Capsid",
            "Viral_tropism",
            "Inverted_repeat",
            "Episome",
            "Dependoparvovirus",
        ),
    },
    "crispr-cas9-deep": {
        "tags": ["cas9 nuclease", "guide rna", "protospacer adjacent", "double strand break"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cas9",
            "Guide_RNA",
            "Protospacer_adjacent_motif",
            "CRISPR",
            "TracrRNA",
            "Non-homologous_end_joining",
        ),
    },
    "base-editing": {
        "tags": ["cytosine deaminase", "adenine base editor", "point mutation", "nickase"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Base_editing",
            "Deaminase",
            "APOBEC",
            "Point_mutation",
            "Uracil-DNA_glycosylase",
            "Transition_(genetics)",
        ),
    },
    "prime-editing": {
        "tags": ["prime editor", "reverse transcriptase", "pegrna", "search and replace"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Prime_editing",
            "Reverse_transcriptase",
            "Flap_endonuclease",
            "Insertion_(genetics)",
            "Deletion_(genetics)",
            "Nick_(DNA)",
        ),
    },
    "rna-interference": {
        "tags": ["small interfering rna", "gene silencing", "dicer", "argonaute"],
        "license": CC_BY_SA,
        "pages": wiki(
            "RNA_interference",
            "Small_interfering_RNA",
            "MicroRNA",
            "Dicer",
            "Argonaute",
            "RNA-induced_silencing_complex",
        ),
    },
    "antisense-oligonucleotides": {
        "tags": ["antisense oligo", "gapmer", "splice modulation", "phosphorothioate"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Antisense_therapy",
            "Oligonucleotide",
            "Morpholino",
            "RNase_H",
            "Nusinersen",
            "Phosphorothioate",
        ),
    },
    "synthetic-biology-deep": {
        "tags": ["synthetic biology", "biobrick", "chassis organism", "standardized part"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Synthetic_biology",
            "BioBrick",
            "Registry_of_Standard_Biological_Parts",
            "Minimal_genome",
            "Xenobiology",
            "Protocell",
        ),
    },
    "genetic-circuits": {
        "tags": ["synthetic gene network", "toggle switch", "logic gate biology", "oscillator"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Synthetic_biological_circuit",
            "Repressilator",
            "Gene_regulatory_network",
            "Riboswitch",
            "Promoter_(genetics)",
            "Operon",
        ),
    },
    "biosensors-synthetic": {
        "tags": ["biological sensor", "transducer element", "whole cell sensor", "aptamer"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Biosensor",
            "Aptamer",
            "Green_fluorescent_protein",
            "Bioluminescence",
            "Enzyme-linked_immunosorbent_assay",
            "Glucose_meter",
        ),
    },
    "metabolic-engineering": {
        "tags": ["metabolic pathway engineering", "flux balance", "chassis strain", "titer"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Metabolic_engineering",
            "Flux_balance_analysis",
            "Metabolic_flux_analysis",
            "Metabolic_pathway",
            "Fermentation",
            "Industrial_microbiology",
        ),
    },
    "directed-evolution": {
        "tags": ["laboratory evolution", "mutagenesis library", "selection pressure", "screening variant"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Directed_evolution",
            "Error-prone_PCR",
            "DNA_shuffling",
            "Site-directed_mutagenesis",
            "Fitness_landscape",
            "Ribosome_display",
        ),
    },
    "protein-expression-systems": {
        "tags": ["recombinant expression", "host cell", "inclusion body", "affinity tag"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Recombinant_DNA",
            "Escherichia_coli",
            "Baculovirus",
            "Inclusion_bodies",
            "Protein_purification",
            "Affinity_chromatography",
        ),
    },
    "cell-culture-methods": {
        "tags": ["tissue culture", "cell line", "passage", "growth medium"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cell_culture",
            "Immortalised_cell_line",
            "HeLa",
            "Growth_medium",
            "Trypsinization",
            "Bioreactor",
        ),
    },
    "flow-cytometry": {
        "tags": ["fluorescence activated sorting", "cell sorting", "gating", "forward scatter"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Flow_cytometry",
            "Fluorescence-activated_cell_sorting",
            "Fluorophore",
            "Immunophenotyping",
            "Side_scatter",
            "Cell_sorting",
        ),
    },
    "mass-spectrometry-proteomics": {
        "tags": ["shotgun proteomics", "peptide fragmentation", "tandem ms", "electrospray"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Proteomics",
            "Tandem_mass_spectrometry",
            "Electrospray_ionization",
            "Matrix-assisted_laser_desorption/ionization",
            "Peptide_mass_fingerprinting",
            "Isobaric_labeling",
        ),
    },
    "single-cell-sequencing": {
        "tags": ["single cell rna", "cell barcoding", "droplet microfluidics", "unique molecular identifier"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Single-cell_sequencing",
            "Single-cell_transcriptomics",
            "Microfluidics",
            "Unique_molecular_identifier",
            "Cellular_deconvolution",
            "Cell_(biology)",
        ),
    },
    "spatial-transcriptomics": {
        "tags": ["spatial gene expression", "tissue section", "in situ hybridization", "spot capture"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Spatial_transcriptomics",
            "In_situ_hybridization",
            "Fluorescence_in_situ_hybridization",
            "Immunohistochemistry",
            "Laser_capture_microdissection",
            "Tissue_microarray",
        ),
    },
    "chip-seq": {
        "tags": ["chromatin immunoprecipitation", "transcription factor binding", "peak calling", "histone mark"],
        "license": CC_BY_SA,
        "pages": wiki(
            "ChIP-sequencing",
            "Chromatin_immunoprecipitation",
            "Transcription_factor",
            "Histone",
            "Enhancer_(genetics)",
            "DNA-binding_protein",
        ),
    },
    "atac-seq": {
        "tags": ["chromatin accessibility", "transposase", "open chromatin", "nucleosome positioning"],
        "license": CC_BY_SA,
        "pages": wiki(
            "ATAC-seq",
            "Transposase",
            "Chromatin",
            "Nucleosome",
            "DNase_I_hypersensitive_site",
            "Transposable_element",
        ),
    },
    "hi-c-chromatin": {
        "tags": ["chromosome conformation", "topologically associating domain", "genome folding", "contact matrix"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Hi-C_(genomic_analysis_technique)",
            "Chromosome_conformation_capture",
            "Topologically_associating_domain",
            "Loop_extrusion",
            "Nuclear_organization",
            "CTCF",
        ),
    },
    "organoids": {
        "tags": ["organoid culture", "three dimensional tissue", "self organization", "matrigel"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Organoid",
            "Organ-on-a-chip",
            "Induced_pluripotent_stem_cell",
            "Cellular_differentiation",
            "Spheroid",
            "Extracellular_matrix",
        ),
    },
    "tissue-engineering": {
        "tags": ["regenerative medicine", "scaffold seeding", "cell scaffold", "vascularization"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Tissue_engineering",
            "Regenerative_medicine",
            "Tissue_scaffold",
            "Decellularization",
            "Bioprinting",
            "Angiogenesis",
        ),
    },
    "biomaterials": {
        "tags": ["biocompatible material", "implant", "biodegradable polymer", "foreign body response"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Biomaterial",
            "Biocompatibility",
            "Implant_(medicine)",
            "Bioceramic",
            "Titanium_biocompatibility",
            "Foreign_body_reaction",
        ),
    },
    "hydrogels-bio": {
        "tags": ["hydrogel network", "swelling", "crosslinking", "stimuli responsive"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Hydrogel",
            "Cross-link",
            "Swelling_(medical)",
            "Alginate",
            "Polyethylene_glycol",
            "Self-healing_hydrogels",
        ),
    },
    "drug-delivery-systems": {
        "tags": ["controlled release", "targeted delivery", "sustained release", "carrier"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Drug_delivery",
            "Controlled_release",
            "Liposome",
            "Transdermal_patch",
            "Sustained_release",
            "Micelle",
        ),
    },
    "nanoparticle-drug-delivery": {
        "tags": ["nanocarrier", "polymeric nanoparticle", "enhanced permeability", "surface functionalization"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Nanoparticle_drug_delivery",
            "Nanomedicine",
            "Dendrimer",
            "Enhanced_permeability_and_retention_effect",
            "Quantum_dot",
            "PEGylation",
        ),
    },
    "electron-microscopy-materials": {
        "tags": ["scanning electron", "material imaging", "backscattered electron", "energy dispersive"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Scanning_electron_microscope",
            "Energy-dispersive_X-ray_spectroscopy",
            "Electron_backscatter_diffraction",
            "Secondary_electrons",
            "Focused_ion_beam",
            "Selected_area_diffraction",
        ),
    },
    "atomic-force-microscopy": {
        "tags": ["scanning probe", "cantilever tip", "surface topography", "tapping mode"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Atomic_force_microscopy",
            "Scanning_probe_microscopy",
            "Cantilever",
            "Piezoelectricity",
            "Force_spectroscopy",
            "Surface_roughness",
        ),
    },
    "scanning-tunneling-microscopy": {
        "tags": ["quantum tunneling imaging", "atomic resolution", "tunneling current", "surface states"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Scanning_tunneling_microscope",
            "Quantum_tunnelling",
            "Work_function",
            "Density_of_states",
            "Local_density_of_states",
            "Scanning_tunneling_spectroscopy",
        ),
    },
    "x-ray-photoelectron-spectroscopy": {
        "tags": ["photoemission", "surface analysis", "binding energy", "chemical state"],
        "license": CC_BY_SA,
        "pages": wiki(
            "X-ray_photoelectron_spectroscopy",
            "Photoelectric_effect",
            "Auger_electron_spectroscopy",
            "Ultraviolet_photoelectron_spectroscopy",
            "Core_electron",
            "Inelastic_mean_free_path",
        ),
    },
    "raman-spectroscopy": {
        "tags": ["inelastic scattering", "vibrational mode", "stokes shift", "surface enhanced"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Raman_spectroscopy",
            "Raman_scattering",
            "Surface-enhanced_Raman_spectroscopy",
            "Molecular_vibration",
            "Rayleigh_scattering",
            "Confocal_microscopy",
        ),
    },
    "differential-scanning-calorimetry": {
        "tags": ["heat flow", "glass transition", "melting endotherm", "thermal transition"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Differential_scanning_calorimetry",
            "Glass_transition",
            "Enthalpy_of_fusion",
            "Crystallization",
            "Calorimetry",
            "Heat_capacity",
        ),
    },
    "thermogravimetric-analysis": {
        "tags": ["mass loss", "thermal decomposition", "volatilization", "residual mass"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Thermogravimetric_analysis",
            "Thermal_analysis",
            "Pyrolysis",
            "Thermal_decomposition",
            "Volatility_(chemistry)",
            "Thermal_stability",
        ),
    },
    "rheology-materials": {
        "tags": ["viscoelasticity", "shear stress", "flow behavior", "storage modulus"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Rheology",
            "Viscoelasticity",
            "Viscosity",
            "Shear_stress",
            "Non-Newtonian_fluid",
            "Deborah_number",
        ),
    },
}
