"""Deep statistics: regression models, GLMs, time series, survival, Bayesian, multivariate."""
from .common import CC_BY_SA, wiki

DOMAINS = {
    "linear-regression": {
        "tags": ["linear regression", "ordinary least squares", "regression coefficients", "least squares"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Linear_regression",
            "Ordinary_least_squares",
            "Simple_linear_regression",
            "Coefficient_of_determination",
            "Regression_analysis",
            "Gauss–Markov_theorem",
            "Errors_and_residuals",
            "Design_matrix",
        ),
    },
    "multiple-regression": {
        "tags": ["multiple regression", "multicollinearity", "variance inflation factor", "partial regression"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Multiple_correlation",
            "Multicollinearity",
            "Variance_inflation_factor",
            "Stepwise_regression",
            "Partial_regression_plot",
            "Interaction_(statistics)",
            "Feature_selection",
        ),
    },
    "logistic-regression": {
        "tags": ["logistic regression", "logit", "odds ratio", "probit model"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Logistic_regression",
            "Logit",
            "Odds_ratio",
            "Multinomial_logistic_regression",
            "Ordered_logit",
            "Probit_model",
            "Maximum_likelihood_estimation",
            "Deviance_(statistics)",
        ),
    },
    "poisson-regression": {
        "tags": ["poisson regression", "count data", "overdispersion", "negative binomial"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Poisson_regression",
            "Poisson_distribution",
            "Overdispersion",
            "Negative_binomial_distribution",
            "Zero-inflated_model",
            "Count_data",
        ),
    },
    "generalized-linear-models": {
        "tags": ["generalized linear model", "link function", "exponential family", "quasi-likelihood"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Generalized_linear_model",
            "Link_function",
            "Exponential_family",
            "Iteratively_reweighted_least_squares",
            "Quasi-likelihood",
            "Nuisance_parameter",
        ),
    },
    "ridge-lasso-regression": {
        "tags": ["ridge regression", "lasso regression", "shrinkage estimator", "L2 regularization"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Tikhonov_regularization",
            "Lasso_(statistics)",
            "Regularization_(mathematics)",
            "Regularized_least_squares",
            "Shrinkage_(statistics)",
            "Bias–variance_tradeoff",
        ),
    },
    "elastic-net": {
        "tags": ["elastic net", "penalized regression", "regularization path", "sparse model"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Elastic_net_regularization",
            "Regression_analysis",
            "Feature_selection",
            "Regularized_least_squares",
            "Lasso_(statistics)",
            "Tikhonov_regularization",
        ),
    },
    "quantile-regression": {
        "tags": ["quantile regression", "conditional quantile", "least absolute deviations", "percentile estimation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Quantile_regression",
            "Quantile",
            "Least_absolute_deviations",
            "Conditional_expectation",
            "Median",
            "Percentile",
        ),
    },
    "robust-regression": {
        "tags": ["robust regression", "M-estimator", "robust statistics", "influential observation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Robust_regression",
            "M-estimator",
            "Robust_statistics",
            "Least_trimmed_squares",
            "Huber_loss",
            "Outlier",
            "Influential_observation",
        ),
    },
    "nonlinear-regression": {
        "tags": ["nonlinear regression", "curve fitting", "levenberg marquardt", "gauss newton"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Nonlinear_regression",
            "Levenberg–Marquardt_algorithm",
            "Gauss–Newton_algorithm",
            "Curve_fitting",
            "Least_squares",
            "Nonlinear_least_squares",
        ),
    },
    "polynomial-regression": {
        "tags": ["polynomial regression", "orthogonal polynomials", "segmented regression", "curve fitting"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Polynomial_regression",
            "Polynomial_and_rational_function_modeling",
            "Response_modeling_methodology",
            "Segmented_regression",
            "Orthogonal_polynomials",
            "Curve_fitting",
        ),
    },
    "mixed-effects-models": {
        "tags": ["mixed model", "random effects", "fixed effects", "intraclass correlation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Mixed_model",
            "Random_effects_model",
            "Fixed_effects_model",
            "Restricted_maximum_likelihood",
            "Repeated_measures_design",
            "Intraclass_correlation",
            "Random_effect",
        ),
    },
    "hierarchical-models": {
        "tags": ["multilevel model", "hierarchical modeling", "shrinkage estimator", "hyperparameter prior"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Multilevel_model",
            "Bayesian_hierarchical_modeling",
            "Shrinkage_estimator",
            "James–Stein_estimator",
            "Hyperparameter",
            "Random_effects_model",
        ),
    },
    "generalized-additive-models": {
        "tags": ["generalized additive model", "backfitting", "smoothing spline", "kernel smoother"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Generalized_additive_model",
            "Smoothing_spline",
            "Backfitting_algorithm",
            "Additive_model",
            "Kernel_smoother",
            "Local_regression",
        ),
    },
    "splines-regression": {
        "tags": ["spline interpolation", "B-spline", "thin plate spline", "regression spline"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Spline_(mathematics)",
            "B-spline",
            "Smoothing_spline",
            "Thin_plate_spline",
            "Regression_spline",
            "Knot_(mathematics)",
            "Cubic_Hermite_spline",
        ),
    },
    "analysis-of-variance": {
        "tags": ["analysis of variance", "F-test", "sum of squares", "post hoc analysis"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Analysis_of_variance",
            "One-way_analysis_of_variance",
            "Two-way_analysis_of_variance",
            "F-test",
            "Tukey's_range_test",
            "Sum_of_squares_(statistics)",
            "Post_hoc_analysis",
        ),
    },
    "ancova": {
        "tags": ["analysis of covariance", "covariate adjustment", "confounding variable", "adjusted mean"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Analysis_of_covariance",
            "Covariate",
            "Confounding",
            "Homogeneity_(statistics)",
            "Regression_analysis",
            "Analysis_of_variance",
        ),
    },
    "manova": {
        "tags": ["multivariate analysis of variance", "Wilks lambda", "Hotelling T-squared", "Box M test"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Multivariate_analysis_of_variance",
            "Wilks's_lambda_distribution",
            "Hotelling's_T-squared_distribution",
            "Box's_M_test",
            "Multivariate_statistics",
            "Multivariate_analysis",
        ),
    },
    "experimental-design": {
        "tags": ["design of experiments", "statistical blocking", "treatment randomization", "experimental replication"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Design_of_experiments",
            "Blocking_(statistics)",
            "Randomization",
            "Replication_(statistics)",
            "Randomized_experiment",
            "Latin_square",
            "Completely_randomized_design",
        ),
    },
    "factorial-design": {
        "tags": ["factorial experiment", "fractional factorial", "main effect", "Plackett Burman"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Factorial_experiment",
            "Fractional_factorial_design",
            "Main_effect",
            "Yates_analysis",
            "Plackett–Burman_design",
            "Taguchi_methods",
        ),
    },
    "response-surface-methodology": {
        "tags": ["response surface methodology", "central composite design", "Box Behnken", "optimal design"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Response_surface_methodology",
            "Central_composite_design",
            "Box–Behnken_design",
            "Mathematical_optimization",
            "Steepest_descent",
            "Optimal_design",
        ),
    },
    "hypothesis-testing-deep": {
        "tags": ["hypothesis test", "null hypothesis", "statistical power", "likelihood ratio test"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Statistical_hypothesis_test",
            "Null_hypothesis",
            "Statistical_significance",
            "P-value",
            "Type_I_and_type_II_errors",
            "Statistical_power",
            "Likelihood-ratio_test",
            "Wald_test",
            "Score_test",
        ),
    },
    "multiple-comparisons": {
        "tags": ["multiple comparisons", "family-wise error rate", "false discovery rate", "closed testing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Multiple_comparisons_problem",
            "Family-wise_error_rate",
            "False_discovery_rate",
            "Closed_testing_procedure",
            "Post_hoc_test",
            "Data_dredging",
        ),
    },
    "bonferroni-correction": {
        "tags": ["Bonferroni correction", "Holm Bonferroni", "Sidak correction", "union bound"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Bonferroni_correction",
            "Holm–Bonferroni_method",
            "Šidák_correction",
            "Union_bound",
            "Family-wise_error_rate",
            "Multiple_comparisons_problem",
        ),
    },
    "nonparametric-tests": {
        "tags": ["nonparametric statistics", "rank correlation", "sign test", "Spearman correlation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Nonparametric_statistics",
            "Rank_correlation",
            "Sign_test",
            "Wilcoxon_signed-rank_test",
            "Spearman's_rank_correlation_coefficient",
            "Kendall_rank_correlation_coefficient",
            "Kolmogorov–Smirnov_test",
        ),
    },
    "mann-whitney": {
        "tags": ["Mann Whitney U test", "Wilcoxon rank-sum", "stochastic ordering", "order statistic"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Mann–Whitney_U_test",
            "Wilcoxon_rank-sum_test",
            "Stochastic_ordering",
            "Order_statistic",
            "Nonparametric_statistics",
            "Sign_test",
        ),
    },
    "kruskal-wallis": {
        "tags": ["Kruskal Wallis", "Friedman test", "post hoc test", "rank correlation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Kruskal–Wallis_one-way_analysis_of_variance",
            "Friedman_test",
            "Post_hoc_test",
            "Rank_correlation",
            "Nonparametric_statistics",
            "Analysis_of_variance",
        ),
    },
    "chi-squared-tests": {
        "tags": ["chi-squared test", "contingency table", "goodness of fit", "G-test"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Chi-squared_test",
            "Pearson's_chi-squared_test",
            "Contingency_table",
            "Chi-squared_distribution",
            "Goodness_of_fit",
            "G-test",
            "McNemar's_test",
        ),
    },
    "fishers-exact-test": {
        "tags": ["Fisher exact test", "hypergeometric distribution", "Barnard test", "exact test"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Fisher's_exact_test",
            "Hypergeometric_distribution",
            "Barnard's_test",
            "Exact_test",
            "Contingency_table",
            "Chi-squared_test",
        ),
    },
    "permutation-tests": {
        "tags": ["permutation test", "resampling method", "exchangeability", "randomization test"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Permutation_test",
            "Resampling_(statistics)",
            "Exchangeability",
            "Randomization_test",
            "Monte_Carlo_method",
            "Nonparametric_statistics",
        ),
    },
    "bootstrap-resampling": {
        "tags": ["bootstrapping statistics", "confidence interval", "empirical distribution", "standard error"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Bootstrapping_(statistics)",
            "Confidence_interval",
            "Empirical_distribution_function",
            "Standard_error",
            "Resampling_(statistics)",
            "Empirical_probability",
        ),
    },
    "jackknife-resampling": {
        "tags": ["jackknife resampling", "bias estimator", "standard error", "resampling method"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Jackknife_resampling",
            "Bias_of_an_estimator",
            "Standard_error",
            "Resampling_(statistics)",
            "Bootstrapping_(statistics)",
            "Estimator",
        ),
    },
    "cross-validation-stats": {
        "tags": ["cross-validation", "model overfitting", "model selection", "hyperparameter optimization"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cross-validation_(statistics)",
            "Overfitting",
            "Model_selection",
            "Hyperparameter_optimization",
            "Training,_validation,_and_test_data_sets",
            "Bias–variance_tradeoff",
        ),
    },
    "survival-analysis": {
        "tags": ["survival analysis", "survival function", "data censoring", "hazard function"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Survival_analysis",
            "Survival_function",
            "Censoring_(statistics)",
            "Failure_rate",
            "Life_table",
            "Accelerated_failure_time_model",
        ),
    },
    "kaplan-meier": {
        "tags": ["Kaplan Meier estimator", "Nelson Aalen", "logrank test", "survival function"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Kaplan–Meier_estimator",
            "Nelson–Aalen_estimator",
            "Logrank_test",
            "Survival_function",
            "Censoring_(statistics)",
            "Nonparametric_regression",
        ),
    },
    "cox-proportional-hazards": {
        "tags": ["proportional hazards model", "Cox regression", "partial likelihood", "hazard ratio"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Proportional_hazards_model",
            "Cox_regression",
            "Partial_likelihood",
            "Hazard_ratio",
            "Time-varying_covariate",
            "Survival_analysis",
        ),
    },
    "hazard-models": {
        "tags": ["failure rate", "hazard function", "accelerated failure time", "life table"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Failure_rate",
            "Accelerated_failure_time_model",
            "Life_table",
            "Survival_function",
            "Hazard_ratio",
            "Proportional_hazards_model",
        ),
    },
    "time-series-arima": {
        "tags": ["ARIMA", "autoregressive model", "moving-average model", "Box Jenkins"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Autoregressive_integrated_moving_average",
            "Autoregressive_model",
            "Moving-average_model",
            "Box–Jenkins_method",
            "Stationary_process",
            "Autocorrelation",
            "Partial_autocorrelation_function",
        ),
    },
    "garch-models": {
        "tags": ["ARCH model", "GARCH", "conditional variance", "volatility clustering"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Autoregressive_conditional_heteroskedasticity",
            "Volatility_(finance)",
            "Heteroscedasticity",
            "Conditional_variance",
            "GARCH",
            "Stationary_process",
        ),
    },
    "state-space-models": {
        "tags": ["state-space model", "hidden Markov model", "dynamic linear model", "recursive estimation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "State-space_representation",
            "Hidden_Markov_model",
            "Recursive_Bayesian_estimation",
            "Latent_variable_model",
            "Smoothing",
            "Autoregressive_model",
        ),
    },
    "kalman-filter-stats": {
        "tags": ["Kalman filter", "extended Kalman filter", "unscented transform", "particle filter"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Kalman_filter",
            "Extended_Kalman_filter",
            "Unscented_transform",
            "Particle_filter",
            "Recursive_Bayesian_estimation",
            "State-space_representation",
        ),
    },
    "vector-autoregression": {
        "tags": ["vector autoregression", "Granger causality", "impulse response", "structural VAR"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Vector_autoregression",
            "Granger_causality",
            "Impulse_response",
            "Structural_vector_autoregression",
            "Stationary_process",
            "Autoregressive_model",
        ),
    },
    "cointegration": {
        "tags": ["cointegration", "error correction model", "unit root", "spurious relationship"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cointegration",
            "Error_correction_model",
            "Unit_root",
            "Augmented_Dickey–Fuller_test",
            "Spurious_relationship",
            "Johansen_test",
        ),
    },
    "spectral-analysis-stats": {
        "tags": ["spectral density", "periodogram", "cross-spectral density", "wavelet transform"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Spectral_density",
            "Periodogram",
            "Fourier_analysis",
            "Wavelet",
            "Cross-spectral_density",
            "Discrete-time_Fourier_transform",
        ),
    },
    "multivariate-statistics": {
        "tags": ["multivariate statistics", "covariance matrix", "Mahalanobis distance", "multivariate normal"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Multivariate_statistics",
            "Covariance_matrix",
            "Multivariate_normal_distribution",
            "Mahalanobis_distance",
            "Hotelling's_T-squared_distribution",
            "Correlation",
        ),
    },
    "factor-analysis": {
        "tags": ["factor analysis", "exploratory factor analysis", "varimax rotation", "latent variable"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Factor_analysis",
            "Exploratory_factor_analysis",
            "Confirmatory_factor_analysis",
            "Varimax_rotation",
            "Latent_variable",
            "Latent_variable_model",
        ),
    },
    "canonical-correlation": {
        "tags": ["canonical correlation", "cross-covariance", "angles between flats", "multivariate statistics"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Canonical_correlation",
            "Cross-covariance",
            "Angles_between_flats",
            "Correlation",
            "Covariance_matrix",
            "Multivariate_statistics",
        ),
    },
    "discriminant-analysis": {
        "tags": ["linear discriminant analysis", "discriminant function", "linear classifier", "multiclass classification"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Linear_discriminant_analysis",
            "Discriminant_function_analysis",
            "Linear_classifier",
            "Kernel_Fisher_discriminant_analysis",
            "Multiclass_classification",
            "Quadratic_classifier",
        ),
    },
    "cluster-analysis-stats": {
        "tags": ["cluster analysis", "k-means clustering", "hierarchical clustering", "silhouette score"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cluster_analysis",
            "K-means_clustering",
            "Hierarchical_clustering",
            "DBSCAN",
            "Silhouette_(clustering)",
            "Determining_the_number_of_clusters_in_a_data_set",
        ),
    },
    "mixture-models-em": {
        "tags": ["mixture model", "expectation maximization", "Gaussian mixture model", "latent class model"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Mixture_model",
            "Expectation–maximization_algorithm",
            "Latent_class_model",
            "Gaussian_mixture_model",
            "Model-based_clustering",
            "Mixture_distribution",
        ),
    },
    "markov-chain-monte-carlo-deep": {
        "tags": ["Markov chain Monte Carlo", "detailed balance", "ergodicity", "burn-in"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Markov_chain_Monte_Carlo",
            "Detailed_balance",
            "Ergodicity",
            "Burn-in",
            "Autocorrelation",
            "Monte_Carlo_method",
        ),
    },
    "gibbs-sampling": {
        "tags": ["Gibbs sampling", "conjugate prior", "slice sampling", "conditional probability distribution"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Gibbs_sampling",
            "Conditional_probability_distribution",
            "Conjugate_prior",
            "Slice_sampling",
            "Markov_chain_Monte_Carlo",
            "Detailed_balance",
        ),
    },
    "metropolis-hastings": {
        "tags": ["Metropolis Hastings", "rejection sampling", "importance sampling", "random walk"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Metropolis–Hastings_algorithm",
            "Rejection_sampling",
            "Importance_sampling",
            "Random_walk",
            "Markov_chain_Monte_Carlo",
            "Detailed_balance",
        ),
    },
    "hamiltonian-monte-carlo": {
        "tags": ["Hamiltonian Monte Carlo", "leapfrog integration", "Hamiltonian mechanics", "detailed balance"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Hamiltonian_Monte_Carlo",
            "Leapfrog_integration",
            "Hamiltonian_mechanics",
            "Detailed_balance",
            "Markov_chain_Monte_Carlo",
            "Metropolis–Hastings_algorithm",
        ),
    },
    "variational-bayes": {
        "tags": ["variational Bayesian methods", "evidence lower bound", "Kullback Leibler divergence", "mean field"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Variational_Bayesian_methods",
            "Kullback–Leibler_divergence",
            "Evidence_lower_bound",
            "Mean_field_theory",
            "Variational_inference",
            "Conjugate_prior",
        ),
    },
    "empirical-bayes": {
        "tags": ["empirical Bayes method", "prior probability", "posterior probability", "Bayes estimator"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Empirical_Bayes_method",
            "Prior_probability",
            "Posterior_probability",
            "Bayes_estimator",
            "Hyperprior",
            "Conjugate_prior",
        ),
    },
}
