"""The named-data-structure catalog: balanced trees, heaps, hashing, probabilistic, spatial, persistent."""

from .common import CC_BY_SA, wiki

DOMAINS = {
    "red-black-tree": {
        "tags": ["red-black tree", "balanced binary tree", "self-balancing tree", "left-leaning red-black tree"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Red–black_tree",
            "Self-balancing_binary_search_tree",
            "Binary_search_tree",
            "Tree_rotation",
            "2–3–4_tree",
            "Left-leaning_red–black_tree",
            "WAVL_tree",
        ),
    },
    "avl-tree": {
        "tags": ["avl tree", "height-balanced tree", "balanced binary tree", "tree rotation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "AVL_tree",
            "Tree_rotation",
            "Self-balancing_binary_search_tree",
            "Binary_search_tree",
            "Binary_tree",
            "Order_statistic_tree",
        ),
    },
    "splay-tree": {
        "tags": ["splay tree", "self-adjusting tree", "amortized analysis", "tango tree"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Splay_tree",
            "Tango_tree",
            "Amortized_analysis",
            "Potential_method",
            "Binary_search_tree",
            "Tree_rotation",
        ),
    },
    "b-tree-structure": {
        "tags": ["b-tree", "multiway search tree", "disk-based index", "database index tree"],
        "license": CC_BY_SA,
        "pages": wiki(
            "B-tree",
            "2–3_tree",
            "2–3–4_tree",
            "UB-tree",
            "Fractional_cascading",
            "Fusion_tree",
        ),
    },
    "b-plus-tree": {
        "tags": ["b+ tree", "leaf-linked b-tree", "database index tree", "disk-based index"],
        "license": CC_BY_SA,
        "pages": wiki(
            "B+_tree",
            "B-tree",
            "Inverted_index",
            "Bitmap_index",
            "Point_access_method",
            "Log-structured_merge-tree",
        ),
    },
    "b-star-tree": {
        "tags": ["b* tree", "multiway search tree", "disk-based index", "high-fanout tree"],
        "license": CC_BY_SA,
        "pages": wiki(
            "B*-tree",
            "B-tree",
            "B+_tree",
            "2–3_tree",
            "Order_statistic_tree",
            "Search_data_structure",
        ),
    },
    "two-three-tree": {
        "tags": ["2-3 tree", "balanced search tree", "multiway search tree", "b-tree family"],
        "license": CC_BY_SA,
        "pages": wiki(
            "2–3_tree",
            "2–3–4_tree",
            "B-tree",
            "Self-balancing_binary_search_tree",
            "Tree_rotation",
            "Binary_search_tree",
        ),
    },
    "scapegoat-tree": {
        "tags": ["scapegoat tree", "self-balancing tree", "amortized analysis", "weight-balanced tree"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Scapegoat_tree",
            "Weight-balanced_tree",
            "Amortized_analysis",
            "Self-balancing_binary_search_tree",
            "Binary_search_tree",
            "Tree_rotation",
        ),
    },
    "treap-structure": {
        "tags": ["treap", "randomized binary search tree", "cartesian tree", "zip tree"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Treap",
            "Randomized_binary_search_tree",
            "Cartesian_tree",
            "Zip_tree",
            "Binary_search_tree",
            "Tree_rotation",
        ),
    },
    "weight-balanced-tree": {
        "tags": ["weight-balanced tree", "self-balancing tree", "augmented search tree", "order statistic tree"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Weight-balanced_tree",
            "Order_statistic_tree",
            "Augmented_map",
            "Self-balancing_binary_search_tree",
            "Binary_search_tree",
            "Tree_rotation",
        ),
    },
    "finger-tree": {
        "tags": ["finger tree", "functional data structure", "persistent sequence", "amortized analysis"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Finger_tree",
            "Persistent_data_structure",
            "Rope_(data_structure)",
            "Zipper_(data_structure)",
            "Amortized_analysis",
            "Cache-oblivious_algorithm",
        ),
    },
    "binary-heap": {
        "tags": ["binary heap", "priority queue", "implicit heap", "d-ary heap"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Binary_heap",
            "Heap_(data_structure)",
            "Priority_queue",
            "D-ary_heap",
            "Implicit_data_structure",
            "Min-max_heap",
        ),
    },
    "binomial-heap": {
        "tags": ["binomial heap", "mergeable heap", "priority queue", "meldable heap"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Binomial_heap",
            "Heap_(data_structure)",
            "Priority_queue",
            "Fibonacci_heap",
            "Brodal_queue",
            "Amortized_analysis",
        ),
    },
    "fibonacci-heap": {
        "tags": ["fibonacci heap", "amortized heap", "priority queue", "mergeable heap"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Fibonacci_heap",
            "Amortized_analysis",
            "Potential_method",
            "Pairing_heap",
            "Brodal_queue",
            "Priority_queue",
        ),
    },
    "pairing-heap": {
        "tags": ["pairing heap", "self-adjusting heap", "priority queue", "mergeable heap"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Pairing_heap",
            "Fibonacci_heap",
            "Heap_(data_structure)",
            "Priority_queue",
            "Amortized_analysis",
            "Soft_heap",
        ),
    },
    "leftist-heap": {
        "tags": ["leftist tree", "meldable heap", "priority queue", "skew heap"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Leftist_tree",
            "Skew_heap",
            "Heap_(data_structure)",
            "Priority_queue",
            "Binomial_heap",
            "Weak_heap",
        ),
    },
    "skew-heap": {
        "tags": ["skew heap", "self-adjusting heap", "mergeable heap", "leftist tree"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Skew_heap",
            "Leftist_tree",
            "Amortized_analysis",
            "Heap_(data_structure)",
            "Priority_queue",
            "Pairing_heap",
        ),
    },
    "d-ary-heap": {
        "tags": ["d-ary heap", "implicit heap", "priority queue", "radix heap"],
        "license": CC_BY_SA,
        "pages": wiki(
            "D-ary_heap",
            "Binary_heap",
            "Radix_heap",
            "Bucket_queue",
            "Priority_queue",
            "Beap",
        ),
    },
    "specialty-heap-zoo": {
        "tags": ["soft heap", "kinetic heap", "weak heap", "mergeable heap", "calendar queue"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Soft_heap",
            "Kinetic_heap",
            "Weak_heap",
            "Beap",
            "Calendar_queue",
            "Bucket_queue",
            "Brodal_queue",
        ),
    },
    "hash-table-structure": {
        "tags": ["hash table", "hash function", "hash collision", "separate chaining"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Hash_table",
            "Hash_function",
            "Hash_collision",
            "Open_addressing",
            "Associative_array",
            "Symbol_table",
        ),
    },
    "open-addressing-probing": {
        "tags": ["open addressing", "linear probing", "quadratic probing", "double hashing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Open_addressing",
            "Linear_probing",
            "Quadratic_probing",
            "Double_hashing",
            "Hash_table",
            "2-choice_hashing",
        ),
    },
    "cuckoo-hashing": {
        "tags": ["cuckoo hashing", "open addressing", "hash collision", "hopscotch hashing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cuckoo_hashing",
            "Hopscotch_hashing",
            "Open_addressing",
            "Hash_table",
            "2-choice_hashing",
            "Hash_collision",
        ),
    },
    "hopscotch-hashing": {
        "tags": ["hopscotch hashing", "open addressing", "cache-aware hashing", "hash collision"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Hopscotch_hashing",
            "Cuckoo_hashing",
            "Linear_probing",
            "Open_addressing",
            "Hash_table",
            "Hash_collision",
        ),
    },
    "robin-hood-hashing": {
        "tags": ["robin hood hashing", "open addressing", "linear probing", "probe sequence"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Robin_Hood_hashing",
            "Linear_probing",
            "Open_addressing",
            "Hash_table",
            "Hash_function",
            "Quadratic_probing",
        ),
    },
    "perfect-hashing": {
        "tags": ["perfect hash function", "minimal perfect hashing", "static hashing", "collision-free hashing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Perfect_hash_function",
            "Dynamic_perfect_hashing",
            "Static_hashing",
            "Universal_hashing",
            "Tabulation_hashing",
            "Hash_function",
        ),
    },
    "consistent-hashing-structure": {
        "tags": ["consistent hashing", "rendezvous hashing", "distributed hash table", "hash ring"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Consistent_hashing",
            "Rendezvous_hashing",
            "Distributed_hash_table",
            "Chord_(peer-to-peer)",
            "Kademlia",
            "Hash_function",
        ),
    },
    "dynamic-hash-index": {
        "tags": ["extendible hashing", "linear hashing", "spiral hashing", "dynamic hash index"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Extendible_hashing",
            "Linear_hashing",
            "Spiral_hashing",
            "Static_hashing",
            "Hash_table",
            "Grid_file",
        ),
    },
    "locality-sensitive-hashing": {
        "tags": ["locality-sensitive hashing", "minhash sketch", "feature hashing", "tabulation hashing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Locality-sensitive_hashing",
            "MinHash",
            "Feature_hashing",
            "Tabulation_hashing",
            "Universal_hashing",
            "Nearest_neighbor_search",
        ),
    },
    "bloom-filter-structure": {
        "tags": ["bloom filter", "probabilistic set", "approximate membership", "false positive rate"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Bloom_filter",
            "Counting_Bloom_filter",
            "Cuckoo_filter",
            "Quotient_filter",
            "Hash_function",
            "Streaming_algorithm",
        ),
    },
    "counting-bloom-filter": {
        "tags": ["counting bloom filter", "probabilistic set", "approximate membership", "deletable filter"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Counting_Bloom_filter",
            "Bloom_filter",
            "Cuckoo_filter",
            "Quotient_filter",
            "Streaming_algorithm",
            "Hash_function",
        ),
    },
    "cuckoo-filter": {
        "tags": ["cuckoo filter", "approximate membership", "probabilistic set", "quotient filter"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cuckoo_filter",
            "Quotient_filter",
            "Bloom_filter",
            "Cuckoo_hashing",
            "Counting_Bloom_filter",
            "Streaming_algorithm",
        ),
    },
    "count-min-sketch": {
        "tags": ["count-min sketch", "frequency sketch", "streaming algorithm", "misra-gries summary"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Count–min_sketch",
            "Misra–Gries_summary",
            "Streaming_algorithm",
            "Reservoir_sampling",
            "Data_stream_management_system",
            "Hash_function",
        ),
    },
    "cardinality-sketch": {
        "tags": ["hyperloglog", "cardinality estimation", "flajolet-martin algorithm", "streaming algorithm"],
        "license": CC_BY_SA,
        "pages": wiki(
            "HyperLogLog",
            "Flajolet–Martin_algorithm",
            "Streaming_algorithm",
            "MinHash",
            "Reservoir_sampling",
            "Data_stream_management_system",
        ),
    },
    "skip-list": {
        "tags": ["skip list", "probabilistic list", "ordered list structure", "skip graph"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Skip_list",
            "Skip_graph",
            "Linked_list",
            "Binary_search_tree",
            "Randomized_binary_search_tree",
            "Search_data_structure",
        ),
    },
    "unrolled-linked-list": {
        "tags": ["unrolled linked list", "cache-friendly list", "linked list variant", "block list"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Unrolled_linked_list",
            "Linked_list",
            "Free_list",
            "Dynamic_array",
            "Hashed_array_tree",
            "Cache-oblivious_algorithm",
        ),
    },
    "xor-linked-list": {
        "tags": ["xor linked list", "linked list variant", "doubly linked list", "memory-efficient list"],
        "license": CC_BY_SA,
        "pages": wiki(
            "XOR_linked_list",
            "Linked_list",
            "Double-ended_queue",
            "Free_list",
            "Circular_buffer",
            "Bit_array",
        ),
    },
    "trie-structure": {
        "tags": ["prefix trie", "digital tree", "ternary search tree", "radix tree"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Trie",
            "Radix_tree",
            "Ternary_search_tree",
            "HAT-trie",
            "Deterministic_acyclic_finite_state_automaton",
            "Hash_array_mapped_trie",
        ),
    },
    "radix-patricia-tree": {
        "tags": ["radix tree", "patricia trie", "compressed trie", "bitwise trie"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Radix_tree",
            "Trie",
            "Hash_array_mapped_trie",
            "Judy_array",
            "Deterministic_acyclic_finite_state_automaton",
            "HAT-trie",
        ),
    },
    "ternary-search-tree": {
        "tags": ["ternary search tree", "prefix trie", "string dictionary", "digital tree"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ternary_search_tree",
            "Trie",
            "Radix_tree",
            "Binary_search_tree",
            "Suffix_tree",
            "Search_data_structure",
        ),
    },
    "suffix-tree": {
        "tags": ["suffix tree", "suffix automaton", "generalized suffix tree", "string index structure"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Suffix_tree",
            "Generalized_suffix_tree",
            "Suffix_automaton",
            "Ukkonen's_algorithm",
            "Suffix_array",
            "Trie",
        ),
    },
    "suffix-array-index": {
        "tags": ["suffix array", "lcp array", "fm-index", "burrows-wheeler transform"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Suffix_array",
            "LCP_array",
            "FM-index",
            "Burrows–Wheeler_transform",
            "Wavelet_Tree",
            "Suffix_tree",
        ),
    },
    "succinct-index-structure": {
        "tags": ["succinct data structure", "wavelet tree", "range minimum query", "compact index"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Succinct_data_structure",
            "Wavelet_Tree",
            "Range_minimum_query",
            "FM-index",
            "Bit_array",
            "Implicit_data_structure",
        ),
    },
    "fenwick-tree": {
        "tags": ["fenwick tree", "binary indexed tree", "prefix sum structure", "cumulative frequency table"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Fenwick_tree",
            "Segment_tree",
            "Range_minimum_query",
            "Prefix_sum",
            "Order_statistic_tree",
            "Bit_array",
        ),
    },
    "segment-tree": {
        "tags": ["segment tree", "range query structure", "interval tree", "range minimum query"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Segment_tree",
            "Interval_tree",
            "Fenwick_tree",
            "Range_minimum_query",
            "Range_tree",
            "Priority_search_tree",
        ),
    },
    "interval-tree": {
        "tags": ["interval tree", "range query structure", "priority search tree", "augmented search tree"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Interval_tree",
            "Segment_tree",
            "Priority_search_tree",
            "Range_tree",
            "Order_statistic_tree",
            "Augmented_map",
        ),
    },
    "kd-tree": {
        "tags": ["k-d tree", "space partitioning tree", "nearest neighbor search", "implicit k-d tree"],
        "license": CC_BY_SA,
        "pages": wiki(
            "K-d_tree",
            "Implicit_k-d_tree",
            "Space_partitioning",
            "Nearest_neighbor_search",
            "Best_bin_first",
            "Ball_tree",
        ),
    },
    "r-tree": {
        "tags": ["r-tree", "spatial index tree", "bounding box index", "hilbert r-tree"],
        "license": CC_BY_SA,
        "pages": wiki(
            "R-tree",
            "R*_tree",
            "Hilbert_R-tree",
            "Priority_R-tree",
            "Point_access_method",
            "Bounding_volume_hierarchy",
        ),
    },
    "quadtree": {
        "tags": ["quadtree structure", "space partitioning tree", "spatial index", "z-order curve"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Quadtree",
            "Octree",
            "Space_partitioning",
            "Z-order_curve",
            "Hilbert_curve",
            "Grid_file",
        ),
    },
    "octree": {
        "tags": ["octree structure", "space partitioning tree", "spatial index", "bounding volume hierarchy"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Octree",
            "Quadtree",
            "Binary_space_partitioning",
            "Bounding_volume_hierarchy",
            "Space_partitioning",
            "K-d_tree",
        ),
    },
    "metric-space-tree": {
        "tags": ["ball tree", "vantage-point tree", "metric tree", "cover tree", "nearest neighbor search"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ball_tree",
            "Vantage-point_tree",
            "Metric_tree",
            "Cover_tree",
            "M-tree",
            "BK-tree",
            "Nearest_neighbor_search",
        ),
    },
    "advanced-spatial-index": {
        "tags": ["ub-tree", "x-tree structure", "bx-tree", "space-filling curve", "point access method"],
        "license": CC_BY_SA,
        "pages": wiki(
            "UB-tree",
            "X-tree",
            "Bx-tree",
            "Space-filling_curve",
            "Point_access_method",
            "GiST",
        ),
    },
    "mesh-connectivity-structure": {
        "tags": ["half-edge mesh", "winged edge", "quad-edge", "doubly connected edge list"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Half-edge_mesh",
            "Winged_edge",
            "Quad-edge",
            "Doubly_connected_edge_list",
            "Bounding_volume_hierarchy",
            "Binary_space_partitioning",
        ),
    },
    "disjoint-set-forest": {
        "tags": ["disjoint-set data structure", "union-find forest", "connected components structure", "path compression"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Disjoint-set_data_structure",
            "Dynamic_connectivity",
            "Link/cut_tree",
            "Euler_tour_technique",
            "Top_tree",
            "Amortized_analysis",
        ),
    },
    "dynamic-tree-structure": {
        "tags": ["link/cut tree", "top tree", "euler tour technique", "dynamic connectivity"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Link/cut_tree",
            "Top_tree",
            "Euler_tour_technique",
            "Dynamic_connectivity",
            "Splay_tree",
            "Disjoint-set_data_structure",
        ),
    },
    "editable-text-buffer": {
        "tags": ["rope data structure", "gap buffer", "piece table", "text sequence structure"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Rope_(data_structure)",
            "Gap_buffer",
            "Piece_table",
            "Zipper_(data_structure)",
            "Circular_buffer",
            "Finger_tree",
        ),
    },
    "persistent-data-structure": {
        "tags": ["persistent data structure", "fat node method", "retroactive data structure", "immutable structure"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Persistent_data_structure",
            "Fat_node",
            "Retroactive_data_structure",
            "Persistent_array",
            "Merkle_tree",
            "Finger_tree",
        ),
    },
    "van-emde-boas-tree": {
        "tags": ["van emde boas tree", "integer priority queue", "y-fast trie", "x-fast trie"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Van_Emde_Boas_tree",
            "Y-fast_trie",
            "X-fast_trie",
            "Fusion_tree",
            "Priority_queue",
            "Bitwise_trie_with_bitmap",
        ),
    },
    "y-fast-trie": {
        "tags": ["y-fast trie", "integer search structure", "x-fast trie", "van emde boas tree"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Y-fast_trie",
            "X-fast_trie",
            "Van_Emde_Boas_tree",
            "Fusion_tree",
            "Radix_tree",
            "Bit_array",
        ),
    },
    "dancing-links": {
        "tags": ["dancing links", "exact cover solver", "doubly linked list", "circular buffer"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Dancing_Links",
            "Doubly_connected_edge_list",
            "Linked_list",
            "Circular_buffer",
            "Free_list",
            "Double-ended_queue",
        ),
    },
    "compact-bitmap-structure": {
        "tags": ["bit array", "roaring bitmap", "bitmap index", "compressed bitmap set"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Bit_array",
            "Roaring_bitmap",
            "Bitmap_index",
            "Bitboard",
            "Succinct_data_structure",
            "Judy_array",
        ),
    },
    "resizable-array-structure": {
        "tags": ["dynamic array", "hashed array tree", "sparse matrix", "array data structure"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Dynamic_array",
            "Hashed_array_tree",
            "Array_(data_structure)",
            "Sparse_matrix",
            "Circular_buffer",
            "Double-ended_queue",
        ),
    },
    "vector-search-index": {
        "tags": ["vector database", "nearest neighbor search", "cover tree", "metric tree", "best bin first"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Vector_database",
            "Nearest_neighbor_search",
            "Cover_tree",
            "Ball_tree",
            "Best_bin_first",
            "Locality-sensitive_hashing",
        ),
    },
}
