"""Cloud platforms, managed services, and cloud-native concepts."""

from .common import CC_BY_SA, WIKI, wiki

DOMAINS = {
    "aws-s3": {
        "tags": ["aws s3", "amazon s3", "object storage", "cloud bucket"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Amazon_S3",
            "Object_storage",
            "Amazon_Web_Services",
            "Cloud_storage",
            "Data_lake",
            "Data_management",
        ),
    },
    "aws-ec2": {
        "tags": ["aws ec2", "amazon ec2", "elastic compute", "cloud virtual machine"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Amazon_Elastic_Compute_Cloud",
            "Virtual_machine",
            "Infrastructure_as_a_service",
            "Hypervisor",
            "Cloud_computing_architecture",
            "Elastic_computing",
        ),
    },
    "aws-lambda": {
        "tags": ["aws lambda", "serverless function", "lambda function", "function as a service"],
        "license": CC_BY_SA,
        "pages": wiki(
            "AWS_Lambda",
            "Serverless_computing",
            "Function_as_a_service",
            "Event-driven_programming",
            "Microservices",
            "Anonymous_function",
        ),
    },
    "aws-iam": {
        "tags": ["aws iam", "identity and access management", "access control", "least privilege"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Identity_management",
            "Access_control",
            "Role-based_access_control",
            "Attribute-based_access_control",
            "Principle_of_least_privilege",
            "Authentication",
            "Authorization",
        ),
    },
    "aws-vpc": {
        "tags": ["aws vpc", "virtual private cloud", "cloud subnet", "cloud networking"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Amazon_Virtual_Private_Cloud",
            "Virtual_private_cloud",
            "Subnetwork",
            "Network_address_translation",
            "Classless_Inter-Domain_Routing",
            "Virtual_private_network",
        ),
    },
    "aws-dynamodb": {
        "tags": ["aws dynamodb", "amazon dynamodb", "nosql database", "key-value store"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Amazon_DynamoDB",
            "NoSQL",
            "Key-value_database",
            "Document-oriented_database",
            "Distributed_database",
            "Eventual_consistency",
        ),
    },
    "aws-rds": {
        "tags": ["aws rds", "relational database service", "managed database", "cloud database"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Amazon_Relational_Database_Service",
            "Relational_database",
            "Database",
            "Replication_(computing)",
            "Database_transaction",
            "Managed_services",
        ),
    },
    "aws-sqs": {
        "tags": ["aws sqs", "simple queue service", "message queue", "event-driven"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Amazon_Simple_Queue_Service",
            "Message_queue",
            "Event-driven_architecture",
            "Publish–subscribe_pattern",
            "Message-oriented_middleware",
            "Dead_letter_queue",
        ),
    },
    "aws-sns": {
        "tags": ["aws sns", "simple notification service", "push notification", "pub sub"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Amazon_Simple_Notification_Service",
            "Push_technology",
            "Notification_system",
            "Enterprise_service_bus",
            "Webhook",
            "Short_Message_Service",
        ),
    },
    "aws-cloudformation": {
        "tags": ["aws cloudformation", "infrastructure as code", "cloud provisioning", "stack template"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Infrastructure_as_code",
            "Provisioning_(technology)",
            "Declarative_programming",
            "Configuration_management",
            "Software_deployment",
            "DevOps",
        ),
    },
    "aws-ecs": {
        "tags": ["aws ecs", "elastic container service", "container orchestration", "cloud containers"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Docker_(software)",
            "OS-level_virtualization",
            "Container_(virtualization)",
            "Orchestration_(computing)",
            "Microservices",
            "Serverless_computing",
        ),
    },
    "aws-eks": {
        "tags": ["aws eks", "elastic kubernetes service", "managed kubernetes", "cloud native"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Kubernetes",
            "Container_orchestration",
            "OS-level_virtualization",
            "Cloud_native_computing",
            "Microservices",
            "Amazon_Web_Services",
        ),
    },
    "aws-cloudwatch": {
        "tags": ["aws cloudwatch", "cloud monitoring", "cloud observability", "cloud metrics"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Observability",
            "System_monitor",
            "Log_file",
            "Telemetry",
            "Application_performance_management",
            "Alarm_device",
        ),
    },
    "aws-route53": {
        "tags": ["aws route53", "cloud dns", "managed dns", "dns resolution"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Domain_Name_System",
            "Name_server",
            "Anycast",
            "DNS_zone",
            "Round-robin_DNS",
            "Time_to_live",
        ),
    },
    "aws-cloudfront": {
        "tags": ["aws cloudfront", "cloud cdn", "content delivery", "edge cache"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Content_delivery_network",
            "Edge_computing",
            "Web_cache",
            "Point_of_presence",
            "HTTP_ETag",
            "Transport_Layer_Security",
        ),
    },
    "aws-api-gateway": {
        "tags": ["aws api gateway", "api gateway", "rest api", "api rate limiting"],
        "license": CC_BY_SA,
        "pages": wiki(
            "API_gateway",
            "Application_programming_interface",
            "Representational_state_transfer",
            "Web_API",
            "Rate_limiting",
            "OpenAPI_Specification",
        ),
    },
    "aws-kinesis": {
        "tags": ["aws kinesis", "stream processing", "data stream", "real-time streaming"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Stream_processing",
            "Data_stream",
            "Event_stream_processing",
            "Real-time_computing",
            "Apache_Kafka",
            "Complex_event_processing",
        ),
    },
    "aws-step-functions": {
        "tags": ["aws step functions", "workflow orchestration", "state machine", "workflow engine"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Workflow_engine",
            "Finite-state_machine",
            "Business_process_automation",
            "Orchestration_(computing)",
            "Directed_acyclic_graph",
            "State_diagram",
        ),
    },
    "azure-overview": {
        "tags": ["microsoft azure", "azure cloud", "azure platform", "azure paas"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Microsoft_Azure",
            "Cloud_computing",
            "Platform_as_a_service",
            "Microsoft",
            "Data_center",
            "Hybrid_cloud",
        ),
    },
    "azure-functions": {
        "tags": ["azure functions", "azure serverless", "function as a service", "event trigger"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Serverless_computing",
            "Function_as_a_service",
            "Event-driven_programming",
            "Microsoft_Azure",
            "Webhook",
            "Trigger_(computing)",
        ),
    },
    "azure-blob-storage": {
        "tags": ["azure blob storage", "azure storage", "blob object", "cloud object storage"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Object_storage",
            "Cloud_storage",
            "Binary_large_object",
            "Microsoft_Azure",
            "Data_lake",
            "Immutable_object",
        ),
    },
    "azure-devops": {
        "tags": ["azure devops", "azure pipelines", "ci cd", "continuous integration"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Azure_DevOps_Server",
            "DevOps",
            "Continuous_integration",
            "Continuous_delivery",
            "Version_control",
            "CI/CD",
        ),
    },
    "azure-cosmos-db": {
        "tags": ["azure cosmos db", "cosmos db", "multi-model database", "distributed nosql"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cosmos_DB",
            "NoSQL",
            "Distributed_database",
            "Multi-model_database",
            "Partition_(database)",
            "Consistency_model",
        ),
    },
    "gcp-compute-engine": {
        "tags": ["gcp compute engine", "google compute engine", "cloud virtual machine", "gcp vm"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Google_Compute_Engine",
            "Google_Cloud_Platform",
            "Virtual_machine",
            "Infrastructure_as_a_service",
            "Live_migration",
            "Hypervisor",
        ),
    },
    "gcp-cloud-storage": {
        "tags": ["gcp cloud storage", "google cloud storage", "gcp object storage", "cloud bucket"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Google_Cloud_Storage",
            "Object_storage",
            "Cloud_storage",
            "Google_Cloud_Platform",
            "Data_lake",
            "Erasure_code",
        ),
    },
    "gcp-cloud-functions": {
        "tags": ["gcp cloud functions", "google cloud functions", "gcp serverless", "function as a service"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Serverless_computing",
            "Function_as_a_service",
            "Google_Cloud_Platform",
            "Event-driven_programming",
            "Idempotence",
            "Trigger_(computing)",
        ),
    },
    "gcp-bigquery": {
        "tags": ["gcp bigquery", "google bigquery", "data warehouse", "analytics database"],
        "license": CC_BY_SA,
        "pages": wiki(
            "BigQuery",
            "Data_warehouse",
            "Online_analytical_processing",
            "Column-oriented_DBMS",
            "Structured_Query_Language",
            "Big_data",
        ),
    },
    "gcp-pubsub": {
        "tags": ["gcp pubsub", "google pub sub", "message queue", "event-driven messaging"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Publish–subscribe_pattern",
            "Message_queue",
            "Event-driven_architecture",
            "Message-oriented_middleware",
            "Google_Cloud_Platform",
            "Idempotence",
        ),
    },
    "cloudflare-workers": {
        "tags": ["cloudflare workers", "edge functions", "edge serverless", "workers runtime"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cloudflare",
            "Edge_computing",
            "Serverless_computing",
            "JavaScript_engine",
            "WebAssembly",
            "V8_(JavaScript_engine)",
        ),
    },
    "cloudflare-r2": {
        "tags": ["cloudflare r2", "r2 storage", "edge object storage", "s3 compatible storage"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cloudflare",
            "Object_storage",
            "Cloud_storage",
            "Amazon_S3",
            "Bandwidth_(computing)",
            "Content_delivery_network",
        ),
    },
    "cloudflare-d1": {
        "tags": ["cloudflare d1", "d1 database", "edge sqlite", "serverless sql"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cloudflare",
            "SQLite",
            "Relational_database",
            "Serverless_computing",
            "Edge_computing",
            "Database",
        ),
    },
    "cloudflare-kv": {
        "tags": ["cloudflare kv", "workers kv", "edge key-value", "distributed key-value store"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cloudflare",
            "Key-value_database",
            "Eventual_consistency",
            "Edge_computing",
            "Distributed_data_store",
            "Cache_(computing)",
        ),
    },
    "cloudflare-durable-objects": {
        "tags": ["cloudflare durable objects", "durable objects", "stateful edge", "actor model"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cloudflare",
            "Actor_model",
            "Stateful_firewall",
            "Strong_consistency",
            "Edge_computing",
            "Distributed_computing",
        ),
    },
    "cloudflare-pages": {
        "tags": ["cloudflare pages", "static site hosting", "jamstack hosting", "edge deployment"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cloudflare",
            "Static_web_page",
            "Jamstack",
            "Content_delivery_network",
            "Continuous_deployment",
            "Web_hosting_service",
        ),
    },
    "vercel-platform": {
        "tags": ["vercel platform", "vercel deployment", "frontend hosting", "next.js hosting"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Vercel",
            "Serverless_computing",
            "Jamstack",
            "Next.js",
            "Edge_computing",
            "Web_hosting_service",
        ),
    },
    "netlify-platform": {
        "tags": ["netlify platform", "netlify deployment", "jamstack hosting", "static hosting"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Netlify",
            "Jamstack",
            "Static_web_page",
            "Continuous_deployment",
            "Content_delivery_network",
            "Serverless_computing",
        ),
    },
    "fly-io": {
        "tags": ["fly io", "fly.io platform", "edge deployment", "distributed app hosting"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cloud_computing",
            "Edge_computing",
            "Virtual_machine",
            "Anycast",
            "Platform_as_a_service",
            "Content_delivery_network",
        ),
    },
    "heroku-platform": {
        "tags": ["heroku platform", "heroku dyno", "platform as a service", "app deployment"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Heroku",
            "Platform_as_a_service",
            "Cloud_computing",
            "Twelve-Factor_App_methodology",
            "Autoscaling",
            "Software_deployment",
        ),
    },
    "digitalocean": {
        "tags": ["digitalocean", "cloud droplet", "cloud vps", "developer cloud"],
        "license": CC_BY_SA,
        "pages": wiki(
            "DigitalOcean",
            "Virtual_private_server",
            "Cloud_computing",
            "Infrastructure_as_a_service",
            "Solid-state_drive",
            "Data_center",
        ),
    },
    "serverless-framework": {
        "tags": ["serverless framework", "serverless deployment", "function as a service", "iac framework"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Serverless_computing",
            "Function_as_a_service",
            "Infrastructure_as_code",
            "AWS_Lambda",
            "Software_framework",
            "YAML",
        ),
    },
    "aws-well-architected": {
        "tags": ["well-architected framework", "cloud architecture", "reliability engineering", "high availability"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Software_architecture",
            "Reliability_engineering",
            "Scalability",
            "Operational_excellence",
            "High_availability",
            "Fault_tolerance",
        ),
    },
    "cloud-cost-optimization": {
        "tags": ["cloud cost optimization", "cloud spend", "cloud budgeting", "pay as you go"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cloud_computing",
            "Total_cost_of_ownership",
            "Pay-as-you-go",
            "Capacity_planning",
            "Autoscaling",
            "Cost_accounting",
        ),
    },
    "multi-cloud": {
        "tags": ["multi cloud", "multicloud strategy", "vendor lock-in", "cloud interoperability"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Multicloud",
            "Hybrid_cloud",
            "Vendor_lock-in",
            "Cloud_computing",
            "Interoperability",
            "Cloud_management",
        ),
    },
    "cloud-edge-computing": {
        "tags": ["cloud edge computing", "edge computing", "fog computing", "edge latency"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Edge_computing",
            "Fog_computing",
            "Content_delivery_network",
            "Internet_of_things",
            "Latency_(engineering)",
            "Mobile_edge_computing",
        ),
    },
    "object-storage": {
        "tags": ["object storage", "blob storage", "cloud object store", "storage bucket"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Object_storage",
            "Cloud_storage",
            "Amazon_S3",
            "Data_lake",
            "Erasure_code",
            "Storage_area_network",
        ),
    },
    "block-storage": {
        "tags": ["block storage", "block-level storage", "cloud volumes", "disk array"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Block-level_storage",
            "Storage_area_network",
            "Logical_volume_management",
            "Disk_array",
            "RAID",
            "Solid-state_drive",
        ),
    },
    "cloud-load-balancing": {
        "tags": ["cloud load balancing", "load balancer", "reverse proxy", "traffic distribution"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Load_balancing_(computing)",
            "Reverse_proxy",
            "Round-robin_scheduling",
            "Failover",
            "High_availability",
            "Server_farm",
        ),
    },
    "cloud-cdn": {
        "tags": ["cloud cdn", "content delivery network", "edge cache", "cdn point of presence"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Content_delivery_network",
            "Web_cache",
            "Point_of_presence",
            "Edge_computing",
            "HTTP_caching",
            "Anycast",
        ),
    },
    "cloud-vpn": {
        "tags": ["cloud vpn", "site-to-site vpn", "ipsec tunnel", "vpn gateway"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Virtual_private_network",
            "IPsec",
            "Tunneling_protocol",
            "WireGuard",
            "OpenVPN",
            "Transport_Layer_Security",
        ),
    },
    "managed-kubernetes": {
        "tags": ["managed kubernetes", "kubernetes as a service", "container orchestration", "k8s control plane"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Kubernetes",
            "Container_orchestration",
            "Cloud_native_computing",
            "Control_plane",
            "Microservices",
            "OS-level_virtualization",
        ),
    },
}
