"""Advanced defensive security: detection engineering, DFIR, and applied cryptography."""

from .common import CC_BY_SA, wiki

# Non-Wikipedia static sources, each verified live (HTTP 200) at authoring time.
# MITRE reference knowledge bases serve static HTML under public terms of use:
#   D3FEND (defensive countermeasures) -> d3fend.mitre.org
#   CAPEC  (attack pattern catalog)    -> capec.mitre.org
#   CWE    (weakness enumeration)       -> cwe.mitre.org
#   ATT&CK (adversary behavior model)   -> attack.mitre.org
D3FEND = "https://d3fend.mitre.org/"
CAPEC = "https://capec.mitre.org/"
CWE = "https://cwe.mitre.org/"
ATTACK = "https://attack.mitre.org/"

DOMAINS = {
    "yara-rules": {
        "tags": [
            "yara rules",
            "malware signature",
            "pattern matching detection",
            "antivirus engine",
            "signature based detection",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "YARA",
            "Malware_analysis",
            "Antivirus_software",
            "Signature-based_detection",
            "Pattern_matching",
            "VirusTotal",
        ),
    },
    "sigma-detection-rules": {
        "tags": [
            "sigma detection rules",
            "log detection format",
            "detection engineering",
            "rule based system",
            "security event correlation",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Rule-based_system",
            "Log_analysis",
            "Security_information_and_event_management",
            "Correlation",
            "Event_log",
            "Signature-based_detection",
        ),
    },
    "suricata-ids": {
        "tags": [
            "suricata ids",
            "network intrusion detection",
            "deep packet inspection",
            "intrusion prevention system",
            "packet capture analysis",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Suricata_(software)",
            "Intrusion_detection_system",
            "Intrusion_prevention_system",
            "Deep_packet_inspection",
            "Network_packet",
            "Pcap",
        ),
    },
    "snort-ids": {
        "tags": [
            "snort ids",
            "network intrusion detection",
            "packet analyzer",
            "signature based detection",
            "intrusion prevention system",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Snort_(software)",
            "Intrusion_detection_system",
            "Packet_analyzer",
            "Signature-based_detection",
            "Deep_content_inspection",
            "Host-based_intrusion_detection_system",
        ),
    },
    "zeek-network-monitor": {
        "tags": [
            "zeek network monitor",
            "network security monitoring",
            "traffic analysis",
            "netflow telemetry",
            "packet capture analysis",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Zeek",
            "Network_monitoring",
            "Traffic_analysis",
            "NetFlow",
            "Packet_analyzer",
            "Wireshark",
        ),
    },
    "osquery-endpoint": {
        "tags": [
            "osquery endpoint",
            "endpoint telemetry query",
            "host based intrusion detection",
            "file integrity monitoring",
            "endpoint security",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Endpoint_security",
            "SQL",
            "Host-based_intrusion_detection_system",
            "File_integrity_monitoring",
            "Sysmon",
            "Query_language",
        ),
    },
    "wazuh-monitoring": {
        "tags": [
            "wazuh monitoring",
            "host intrusion detection",
            "file integrity monitoring",
            "security log management",
            "endpoint security agent",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "OSSEC",
            "Host-based_intrusion_detection_system",
            "File_integrity_monitoring",
            "Log_management",
            "Syslog",
            "Endpoint_security",
        ),
    },
    "elastic-security": {
        "tags": [
            "elastic security stack",
            "log search indexing",
            "full text search engine",
            "security dashboard visualization",
            "security event correlation",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Elasticsearch",
            "Elastic_NV",
            "Kibana",
            "Full-text_search",
            "Dashboard_(computing)",
            "Log_management",
        ),
    },
    "splunk-spl": {
        "tags": [
            "splunk spl query",
            "machine data indexing",
            "security search query language",
            "log analytics platform",
            "security dashboard visualization",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Splunk",
            "Query_language",
            "Log_analysis",
            "Dashboard_(computing)",
            "Full-text_search",
            "Correlation",
        ),
    },
    "security-orchestration-soar": {
        "tags": [
            "security orchestration automation",
            "soar playbook automation",
            "incident response runbook",
            "workflow automation engine",
            "security operations center",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Security_orchestration",
            "Workflow_engine",
            "Runbook",
            "Business_process_automation",
            "Automation",
            "Managed_security_service",
        ),
    },
    "user-entity-behavior-analytics": {
        "tags": [
            "user entity behavior analytics",
            "insider threat detection",
            "anomaly detection baseline",
            "behavioral analytics model",
            "security event correlation",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "User_behavior_analytics",
            "Anomaly_detection",
            "Insider_threat",
            "Behavioral_analytics",
            "Correlation",
            "Security_information_and_event_management",
        ),
    },
    "threat-hunting": {
        "tags": [
            "cyber threat hunting",
            "proactive threat detection",
            "indicator of compromise",
            "advanced persistent threat",
            "hypothesis driven investigation",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cyber_threat_hunting",
            "Threat_(computer_security)",
            "Indicator_of_compromise",
            "Advanced_persistent_threat",
            "Managed_detection_and_response",
            "Anomaly_detection",
        ),
    },
    "mitre-d3fend": {
        "tags": [
            "mitre d3fend",
            "defensive countermeasure knowledge graph",
            "cyber defense technique",
            "att&ck countermeasure mapping",
            "security knowledge graph",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Countermeasure_(computer)",
            "MITRE_Corporation",
            "Knowledge_graph",
            "Extended_detection_and_response",
        )
        + [
            D3FEND,
            D3FEND + "about/",
        ],
    },
    "mitre-capec": {
        "tags": [
            "mitre capec catalog",
            "common attack pattern enumeration",
            "attack pattern taxonomy",
            "common weakness enumeration",
            "adversary technique classification",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Attack_patterns",
            "Common_Weakness_Enumeration",
            "Vulnerability_(computing)",
            "Attack_pattern",
        )
        + [
            CAPEC,
            CAPEC + "about/index.html",
            CAPEC + "data/definitions/1000.html",
            CWE,
        ],
    },
    "cyber-kill-chain": {
        "tags": [
            "cyber kill chain",
            "intrusion kill chain phases",
            "adversary attack lifecycle",
            "advanced persistent threat",
            "attack reconnaissance stage",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cyber_kill_chain",
            "Lockheed_Martin",
            "Advanced_persistent_threat",
            "Reconnaissance",
            "Threat_(computer_security)",
        )
        + [ATTACK + "tactics/enterprise/"],
    },
    "diamond-model-intrusion": {
        "tags": [
            "diamond model intrusion analysis",
            "adversary victim infrastructure",
            "threat actor attribution",
            "intrusion event modeling",
            "cyber threat intelligence",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Diamond_model",
            "Cyber_threat_intelligence",
            "Advanced_persistent_threat",
            "Indicator_of_compromise",
            "Threat_(computer_security)",
            "STIX",
        ),
    },
    "memory-forensics-volatility": {
        "tags": [
            "memory forensics volatility",
            "volatile memory acquisition",
            "process memory dump analysis",
            "core dump inspection",
            "digital evidence recovery",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Memory_forensics",
            "Volatility_(memory_forensics)",
            "Random-access_memory",
            "Core_dump",
            "Data_remanence",
            "Volatile_memory",
        ),
    },
    "disk-forensics-sleuthkit": {
        "tags": [
            "disk forensics sleuth kit",
            "file system forensic analysis",
            "forensic disk imaging",
            "file carving recovery",
            "write blocker acquisition",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "The_Sleuth_Kit",
            "Computer_forensics",
            "File_system",
            "Disk_image",
            "File_carving",
            "Write_blocker",
        ),
    },
    "network-forensics": {
        "tags": [
            "network forensics investigation",
            "packet capture reconstruction",
            "traffic flow analysis",
            "network evidence collection",
            "deep packet inspection",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Network_forensics",
            "Pcap",
            "Wireshark",
            "Traffic_analysis",
            "Deep_packet_inspection",
            "NetFlow",
        ),
    },
    "log-analysis-detection": {
        "tags": [
            "security log analysis",
            "audit event logging",
            "syslog aggregation",
            "log correlation detection",
            "centralized log management",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Log_analysis",
            "Event_log",
            "Syslog",
            "Log_management",
            "Correlation",
            "Security_information_and_event_management",
        ),
    },
    "indicators-of-compromise": {
        "tags": [
            "indicators of compromise",
            "structured threat information",
            "cyber threat intelligence feed",
            "malware artifact detection",
            "threat intelligence sharing",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Indicator_of_compromise",
            "STIX",
            "Cyber_threat_intelligence",
            "Threat_intelligence",
            "Malware",
            "Advanced_persistent_threat",
        ),
    },
    "malware-sandboxing": {
        "tags": [
            "malware sandbox analysis",
            "dynamic malware analysis",
            "sandbox detonation environment",
            "behavioral malware emulation",
            "isolated execution environment",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Sandbox_(computer_security)",
            "Dynamic_program_analysis",
            "Emulator",
            "Malware",
            "VirusTotal",
            "Antivirus_software",
        ),
    },
    "reverse-engineering-ghidra": {
        "tags": [
            "ghidra reverse engineering",
            "software reverse engineering",
            "binary decompiler analysis",
            "disassembly workflow",
            "malware code analysis",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ghidra",
            "Reverse_engineering",
            "Disassembler",
            "Decompiler",
            "National_Security_Agency",
            "Machine_code",
        ),
    },
    "radare2-analysis": {
        "tags": [
            "radare2 analysis framework",
            "command line reverse engineering",
            "binary debugger toolkit",
            "hex editor inspection",
            "disassembly workflow",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Radare2",
            "Debugger",
            "Hex_editor",
            "Disassembler",
            "Reverse_engineering",
            "Program_analysis",
        ),
    },
    "binary-analysis": {
        "tags": [
            "static binary analysis",
            "executable format inspection",
            "control flow graph recovery",
            "symbol table analysis",
            "machine code inspection",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Binary_file",
            "Executable",
            "Executable_and_Linkable_Format",
            "Portable_Executable",
            "Symbol_table",
            "Control-flow_graph",
        ),
    },
    "disassembly-analysis": {
        "tags": [
            "disassembly analysis",
            "interactive disassembler workflow",
            "assembly instruction decoding",
            "opcode instruction set",
            "binary code inspection",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Interactive_Disassembler",
            "Binary_Ninja",
            "Assembly_language",
            "Instruction_set_architecture",
            "Opcode",
            "Binary_code",
        ),
    },
    "control-flow-integrity": {
        "tags": [
            "control flow integrity",
            "return oriented programming defense",
            "shadow stack protection",
            "indirect branch validation",
            "exploit mitigation technique",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Control-flow_integrity",
            "Return-oriented_programming",
            "Shadow_stack",
            "Return-to-libc_attack",
            "Control-flow_graph",
            "Static_program_analysis",
        ),
    },
    "address-space-layout-randomization": {
        "tags": [
            "address space layout randomization",
            "position independent code",
            "memory layout randomization",
            "exploit mitigation technique",
            "memory safety defense",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Address_space_layout_randomization",
            "Position-independent_code",
            "Memory_safety",
            "Data_segment",
            "Pointer_(computer_programming)",
            "Buffer_overflow",
        ),
    },
    "data-execution-prevention": {
        "tags": [
            "data execution prevention",
            "non executable memory",
            "executable space protection",
            "write xor execute policy",
            "buffer overflow defense",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Data_execution_prevention",
            "Executable_space_protection",
            "NX_bit",
            "W%5EX",
            "Buffer_overflow",
            "Return-to-libc_attack",
        ),
    },
    "stack-canary": {
        "tags": [
            "stack canary protection",
            "stack buffer overflow defense",
            "buffer overflow protection",
            "stack smashing detection",
            "compiler hardening feature",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Buffer_overflow_protection",
            "Stack_buffer_overflow",
            "Stack_smashing",
            "Stack_(abstract_data_type)",
            "Uncontrolled_format_string",
            "Memory_safety",
        ),
    },
    "exploit-mitigation": {
        "tags": [
            "exploit mitigation techniques",
            "memory corruption defense",
            "executable space protection",
            "control flow integrity",
            "attack surface reduction",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Executable_space_protection",
            "Address_space_layout_randomization",
            "Control-flow_integrity",
            "Buffer_overflow_protection",
            "Shadow_stack",
            "Memory_safety",
        ),
    },
    "trusted-execution-environment": {
        "tags": [
            "trusted execution environment",
            "secure enclave isolation",
            "trusted computing base",
            "hardware root of trust",
            "isolated execution environment",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Trusted_execution_environment",
            "Trusted_computing_base",
            "Hardware_security",
            "Protection_ring",
            "Remote_attestation",
            "Side-channel_attack",
        ),
    },
    "intel-sgx": {
        "tags": [
            "intel sgx enclave",
            "software guard extensions",
            "confidential enclave memory",
            "side channel attack resistance",
            "remote attestation",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Software_Guard_Extensions",
            "Trusted_execution_environment",
            "Side-channel_attack",
            "Central_processing_unit",
            "Cache_(computing)",
            "Remote_attestation",
        ),
    },
    "arm-trustzone": {
        "tags": [
            "arm trustzone",
            "secure world isolation",
            "system on chip security",
            "trusted execution environment",
            "hardware isolation boundary",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "ARM_TrustZone",
            "ARM_architecture_family",
            "System_on_a_chip",
            "Trusted_execution_environment",
            "Protection_ring",
            "Hardware_security",
        ),
    },
    "confidential-computing": {
        "tags": [
            "confidential computing",
            "data in use protection",
            "trusted execution environment",
            "encrypted memory enclave",
            "hardware attestation",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Confidential_computing",
            "Data_in_use",
            "Trusted_execution_environment",
            "Software_Guard_Extensions",
            "Remote_attestation",
            "Homomorphic_encryption",
        ),
    },
    "hardware-security-module": {
        "tags": [
            "hardware security module",
            "cryptographic key management",
            "tamper resistant hardware",
            "secure cryptoprocessor",
            "fips validated cryptography",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Hardware_security_module",
            "Key_management",
            "Secure_cryptoprocessor",
            "Tamper_resistance",
            "FIPS_140-2",
            "Cryptographic_hash_function",
        ),
    },
    "secure-boot-chain": {
        "tags": [
            "secure boot chain",
            "verified boot process",
            "uefi firmware security",
            "chain of trust verification",
            "firmware integrity measurement",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Unified_Extensible_Firmware_Interface",
            "Booting",
            "Chain_of_trust",
            "Firmware",
            "Trusted_Platform_Module",
            "Digital_signature",
        ),
    },
    "tpm-module": {
        "tags": [
            "trusted platform module",
            "hardware root of trust",
            "platform integrity measurement",
            "remote attestation protocol",
            "secure cryptoprocessor",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Trusted_Platform_Module",
            "Secure_cryptoprocessor",
            "Remote_attestation",
            "Chain_of_trust",
            "Key_management",
            "Tamper_resistance",
        ),
    },
    "post-quantum-cryptography": {
        "tags": [
            "post quantum cryptography",
            "quantum resistant algorithm",
            "shor algorithm threat",
            "nist pqc standardization",
            "quantum safe encryption",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Post-quantum_cryptography",
            "Quantum_computing",
            "Shor%27s_algorithm",
            "NIST_Post-Quantum_Cryptography_Standardization",
            "Lattice-based_cryptography",
            "Public-key_cryptography",
        ),
    },
    "lattice-cryptography": {
        "tags": [
            "lattice based cryptography",
            "learning with errors problem",
            "shortest vector problem",
            "quantum resistant key exchange",
            "ntru lattice scheme",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Lattice-based_cryptography",
            "Learning_with_errors",
            "Lattice_problem",
            "Kyber",
            "NTRU",
            "Post-quantum_cryptography",
        ),
    },
    "homomorphic-encryption": {
        "tags": [
            "homomorphic encryption",
            "computation on ciphertext",
            "fully homomorphic scheme",
            "privacy preserving computation",
            "encrypted data processing",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Homomorphic_encryption",
            "Fully_homomorphic_encryption",
            "Data_in_use",
            "Homomorphism",
            "RSA_(cryptosystem)",
            "Lattice-based_cryptography",
        ),
    },
    "secure-multiparty-computation": {
        "tags": [
            "secure multiparty computation",
            "garbled circuit protocol",
            "oblivious transfer primitive",
            "secret sharing scheme",
            "privacy preserving computation",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Secure_multi-party_computation",
            "Garbled_circuit",
            "Oblivious_transfer",
            "Secret_sharing",
            "Zero-knowledge_proof",
            "Homomorphic_encryption",
        ),
    },
    "differential-privacy": {
        "tags": [
            "differential privacy",
            "privacy preserving statistics",
            "data anonymization noise",
            "k anonymity model",
            "statistical disclosure control",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Differential_privacy",
            "Data_anonymization",
            "K-anonymity",
            "Statistical_disclosure_control",
            "Information_privacy",
            "Pseudonymization",
        ),
    },
    "zero-knowledge-authentication": {
        "tags": [
            "zero knowledge proof",
            "challenge response authentication",
            "non interactive proof",
            "privacy preserving authentication",
            "cryptographic proof protocol",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Zero-knowledge_proof",
            "Challenge%E2%80%93response_authentication",
            "Non-interactive_zero-knowledge_proof",
            "Authentication",
            "Digital_signature",
            "Public-key_cryptography",
        ),
    },
    "certificate-transparency": {
        "tags": [
            "certificate transparency log",
            "merkle tree audit log",
            "public key certificate monitoring",
            "certificate authority accountability",
            "misissued certificate detection",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Certificate_Transparency",
            "Merkle_tree",
            "Public_key_certificate",
            "Certificate_authority",
            "Public_key_fingerprint",
            "Public_key_infrastructure",
        ),
    },
    "dnssec": {
        "tags": [
            "dnssec dns security extensions",
            "dns record signing",
            "dns cache poisoning defense",
            "dns spoofing mitigation",
            "chain of trust validation",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Domain_Name_System_Security_Extensions",
            "Domain_Name_System",
            "DNS_spoofing",
            "Cache_poisoning",
            "Root_name_server",
            "Digital_signature",
        ),
    },
    "dmarc-email-security": {
        "tags": [
            "dmarc email authentication",
            "email spoofing defense",
            "sender policy alignment",
            "domain based message authentication",
            "phishing email prevention",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "DMARC",
            "Email_authentication",
            "Email_spoofing",
            "Sender_Policy_Framework",
            "DomainKeys_Identified_Mail",
            "Domain_name",
        ),
    },
    "spf-email": {
        "tags": [
            "sender policy framework",
            "spf record validation",
            "email sender authorization",
            "envelope sender verification",
            "email spoofing defense",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Sender_Policy_Framework",
            "Email_authentication",
            "Bounce_address",
            "Email_spoofing",
            "Domain_Name_System",
            "DMARC",
        ),
    },
    "dkim-signing": {
        "tags": [
            "domainkeys identified mail",
            "dkim signature signing",
            "email cryptographic signature",
            "message integrity verification",
            "email sender authentication",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "DomainKeys_Identified_Mail",
            "Digital_signature",
            "Email_authentication",
            "Public-key_cryptography",
            "Cryptographic_hash_function",
            "DMARC",
        ),
    },
    "container-image-scanning": {
        "tags": [
            "container image scanning",
            "image vulnerability scanner",
            "software composition analysis",
            "container supply chain security",
            "oci image inspection",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Docker_(software)",
            "Image_scanner",
            "Vulnerability_scanner",
            "Software_composition_analysis",
            "Open_Container_Initiative",
            "Container_(virtualization)",
        ),
    },
    "runtime-security-falco": {
        "tags": [
            "runtime container security",
            "runtime threat detection",
            "system call monitoring",
            "runtime application self protection",
            "kubernetes runtime security",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Runtime_application_self-protection",
            "System_call",
            "Berkeley_Packet_Filter",
            "Kubernetes",
            "Container_(virtualization)",
            "Seccomp",
        ),
    },
    "ebpf-security-monitoring": {
        "tags": [
            "ebpf security monitoring",
            "kernel event tracing",
            "system call observability",
            "kernel level instrumentation",
            "runtime threat detection",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "EBPF",
            "Berkeley_Packet_Filter",
            "Linux_kernel",
            "System_call",
            "Kernel_(operating_system)",
            "Seccomp",
        ),
    },
    "deception-technology-honeynets": {
        "tags": [
            "deception technology honeynet",
            "honeypot decoy system",
            "honeynet research project",
            "adversary engagement decoy",
            "intrusion deception defense",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Honeypot_(computing)",
            "Honeynet_Project",
            "Deception_technology",
            "Intrusion_detection_system",
            "Threat_(computer_security)",
            "Malware",
        ),
    },
}
