"""Advanced mathematics and scientific/quantum/bio computing."""

from .common import CC_BY_SA, WIKI, wiki

DOMAINS = {
    "abstract-algebra": {
        "tags": ["abstract algebra", "algebraic structure", "group homomorphism", "quotient structure"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Abstract_algebra",
            "Algebraic_structure",
            "Monoid",
            "Homomorphism",
            "Isomorphism",
            "Quotient_group",
            "Galois_theory",
            "Module_(mathematics)",
        ),
    },
    "group-theory": {
        "tags": ["group theory", "abstract algebra", "symmetry group", "abelian group"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Group_(mathematics)",
            "Group_theory",
            "Abelian_group",
            "Symmetric_group",
            "Cyclic_group",
            "Lie_group",
            "Group_action",
            "Group_representation",
        ),
    },
    "ring-theory": {
        "tags": ["ring theory", "commutative ring", "ring ideal", "polynomial ring"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ring_(mathematics)",
            "Ring_theory",
            "Ideal_(ring_theory)",
            "Integral_domain",
            "Polynomial_ring",
            "Commutative_ring",
        ),
    },
    "field-theory": {
        "tags": ["field theory", "finite field", "field extension", "number field"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Field_(mathematics)",
            "Field_theory_(mathematics)",
            "Finite_field",
            "Field_extension",
            "Algebraic_number_field",
            "Splitting_field",
            "Vector_space",
        ),
    },
    "topology": {
        "tags": ["point-set topology", "topological space", "continuous function", "compact space"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Topology",
            "Topological_space",
            "Continuous_function",
            "Homeomorphism",
            "Compact_space",
            "Connected_space",
            "Homotopy",
            "Fundamental_group",
            "Manifold",
        ),
    },
    "differential-geometry": {
        "tags": ["differential geometry", "smooth manifold", "riemannian manifold", "curvature tensor"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Differential_geometry",
            "Differentiable_manifold",
            "Riemannian_manifold",
            "Curvature",
            "Geodesic",
            "Tangent_space",
            "Differential_form",
            "Connection_(mathematics)",
        ),
    },
    "real-analysis": {
        "tags": ["real analysis", "uniform convergence", "riemann integral", "metric space"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Real_analysis",
            "Limit_of_a_sequence",
            "Cauchy_sequence",
            "Uniform_convergence",
            "Series_(mathematics)",
            "Riemann_integral",
            "Metric_space",
            "Bounded_function",
        ),
    },
    "complex-analysis": {
        "tags": ["complex analysis", "holomorphic function", "residue theorem", "conformal map"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Complex_analysis",
            "Holomorphic_function",
            "Cauchy%27s_integral_theorem",
            "Residue_theorem",
            "Analytic_function",
            "Conformal_map",
            "Laurent_series",
            "Riemann_surface",
        ),
    },
    "functional-analysis": {
        "tags": ["functional analysis", "hilbert space", "banach space", "linear operator"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Functional_analysis",
            "Hilbert_space",
            "Banach_space",
            "Normed_vector_space",
            "Linear_operator",
            "Spectral_theorem",
            "Inner_product_space",
            "Dual_space",
        ),
    },
    "measure-theory": {
        "tags": ["measure theory", "lebesgue integration", "lebesgue measure", "borel set"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Measure_(mathematics)",
            "Measure_theory",
            "Lebesgue_integration",
            "Sigma-algebra",
            "Lebesgue_measure",
            "Borel_set",
            "Almost_everywhere",
            "Radon%E2%80%93Nikodym_theorem",
        ),
    },
    "probability-theory": {
        "tags": ["probability theory", "random variable", "probability space", "law of large numbers"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Probability_theory",
            "Random_variable",
            "Probability_space",
            "Conditional_probability",
            "Expected_value",
            "Law_of_large_numbers",
            "Moment_(mathematics)",
            "Characteristic_function_(probability_theory)",
        ),
    },
    "stochastic-processes": {
        "tags": ["stochastic process", "wiener process", "brownian motion", "stochastic calculus"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Stochastic_process",
            "Wiener_process",
            "Martingale_(probability_theory)",
            "Poisson_point_process",
            "Brownian_motion",
            "It%C3%B4_calculus",
            "Stochastic_differential_equation",
            "Gaussian_process",
        ),
    },
    "markov-chains": {
        "tags": ["markov chain", "markov property", "stochastic matrix", "hidden markov model"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Markov_chain",
            "Markov_property",
            "Stochastic_matrix",
            "Hidden_Markov_model",
            "Markov_decision_process",
            "Markov_chain_Monte_Carlo",
            "Absorbing_Markov_chain",
        ),
    },
    "ordinary-differential-equations": {
        "tags": ["ordinary differential equation", "initial value problem", "boundary value problem", "laplace transform"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ordinary_differential_equation",
            "Linear_differential_equation",
            "Initial_value_problem",
            "Boundary_value_problem",
            "Sturm%E2%80%93Liouville_theory",
            "Laplace_transform",
            "Phase_portrait",
        ),
    },
    "partial-differential-equations": {
        "tags": ["partial differential equation", "heat equation", "wave equation", "method of characteristics"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Partial_differential_equation",
            "Heat_equation",
            "Wave_equation",
            "Laplace%27s_equation",
            "Navier%E2%80%93Stokes_equations",
            "Method_of_characteristics",
            "Separation_of_variables",
            "Green%27s_function",
        ),
    },
    "fourier-analysis": {
        "tags": ["fourier analysis", "fourier transform", "fourier series", "fast fourier transform"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Fourier_analysis",
            "Fourier_transform",
            "Fourier_series",
            "Discrete_Fourier_transform",
            "Fast_Fourier_transform",
            "Convolution",
        ),
    },
    "wavelet-transform": {
        "tags": ["wavelet transform", "discrete wavelet transform", "haar wavelet", "multiresolution analysis"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Wavelet",
            "Wavelet_transform",
            "Discrete_wavelet_transform",
            "Continuous_wavelet_transform",
            "Haar_wavelet",
            "Daubechies_wavelet",
            "Multiresolution_analysis",
        ),
    },
    "tensor-calculus": {
        "tags": ["tensor calculus", "tensor field", "einstein notation", "metric tensor"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Tensor",
            "Tensor_calculus",
            "Tensor_field",
            "Covariance_and_contravariance_of_vectors",
            "Einstein_notation",
            "Metric_tensor",
            "Christoffel_symbols",
            "Ricci_calculus",
        ),
    },
    "game-theory": {
        "tags": ["game theory", "nash equilibrium", "zero-sum game", "cooperative game"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Game_theory",
            "Nash_equilibrium",
            "Zero-sum_game",
            "Prisoner%27s_dilemma",
            "Minimax",
            "Cooperative_game_theory",
            "Evolutionarily_stable_strategy",
            "Shapley_value",
        ),
    },
    "operations-research": {
        "tags": ["operations research", "linear programming", "integer programming", "network flow"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Operations_research",
            "Linear_programming",
            "Integer_programming",
            "Dynamic_programming",
            "Network_flow_problem",
            "Assignment_problem",
            "Scheduling_(computing)",
        ),
    },
    "queueing-theory": {
        "tags": ["queueing theory", "birth-death process", "kendall notation", "little's law"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Queueing_theory",
            "M/M/1_queue",
            "Little%27s_law",
            "Poisson_distribution",
            "Kendall%27s_notation",
            "Birth%E2%80%93death_process",
            "Erlang_(unit)",
        ),
    },
    "quantum-computing": {
        "tags": ["quantum computing", "quantum logic gate", "quantum entanglement", "quantum circuit"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Quantum_computing",
            "Qubit",
            "Quantum_logic_gate",
            "Quantum_entanglement",
            "Quantum_circuit",
            "Bloch_sphere",
            "Quantum_superposition",
            "No-cloning_theorem",
        ),
    },
    "qiskit": {
        "tags": ["qiskit sdk", "quantum sdk", "quantum primitives", "quantum circuit library"],
        "license": "Apache-2.0",
        "pages": [
            "https://en.wikipedia.org/wiki/Qiskit",
            "https://docs.quantum.ibm.com/guides",
            "https://docs.quantum.ibm.com/guides/hello-world",
            "https://docs.quantum.ibm.com/guides/setup-channel",
            "https://docs.quantum.ibm.com/guides/build-noise-models",
            "https://docs.quantum.ibm.com/guides/circuit-library",
            "https://docs.quantum.ibm.com/guides/primitives",
        ],
    },
    "quantum-algorithms": {
        "tags": ["quantum algorithm", "shor's algorithm", "grover's algorithm", "quantum fourier transform"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Quantum_algorithm",
            "Shor%27s_algorithm",
            "Grover%27s_algorithm",
            "Quantum_Fourier_transform",
            "Deutsch%E2%80%93Jozsa_algorithm",
            "Quantum_phase_estimation_algorithm",
            "Variational_quantum_eigensolver",
            "Quantum_teleportation",
        ),
    },
    "bioinformatics": {
        "tags": ["bioinformatics", "sequence analysis", "phylogenetic tree", "protein structure prediction"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Bioinformatics",
            "Sequence_analysis",
            "BLAST_(biotechnology)",
            "Phylogenetic_tree",
            "Protein_structure_prediction",
            "Gene_prediction",
            "FASTA_format",
        ),
    },
    "sequence-alignment": {
        "tags": ["sequence alignment", "multiple sequence alignment", "substitution matrix", "gap penalty"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Sequence_alignment",
            "Needleman%E2%80%93Wunsch_algorithm",
            "Smith%E2%80%93Waterman_algorithm",
            "Multiple_sequence_alignment",
            "Substitution_matrix",
            "Hirschberg%27s_algorithm",
            "Gap_penalty",
        ),
    },
    "genomics-computing": {
        "tags": ["genomics computing", "dna sequencing", "genome assembly", "de bruijn graph"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Genomics",
            "DNA_sequencing",
            "Genome_assembly",
            "Variant_Call_Format",
            "De_Bruijn_graph",
            "Burrows%E2%80%93Wheeler_transform",
            "Single-nucleotide_polymorphism",
        ),
    },
    "computational-physics": {
        "tags": ["computational physics", "verlet integration", "n-body simulation", "ising model"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Computational_physics",
            "Numerical_integration",
            "Verlet_integration",
            "N-body_simulation",
            "Lattice_Boltzmann_methods",
            "Ising_model",
        ),
    },
    "computational-fluid-dynamics": {
        "tags": ["computational fluid dynamics", "finite volume method", "turbulence modeling", "reynolds number"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Computational_fluid_dynamics",
            "Finite_volume_method",
            "Turbulence_modeling",
            "Reynolds_number",
            "Boundary_layer",
            "Large_eddy_simulation",
            "Courant%E2%80%93Friedrichs%E2%80%93Lewy_condition",
        ),
    },
    "finite-element-method": {
        "tags": ["finite element method", "galerkin method", "stiffness matrix", "weak formulation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Finite_element_method",
            "Galerkin_method",
            "Stiffness_matrix",
            "Weak_formulation",
            "Mesh_generation",
            "Basis_function",
        ),
    },
    "molecular-dynamics": {
        "tags": ["molecular dynamics", "force field chemistry", "lennard-jones potential", "periodic boundary conditions"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Molecular_dynamics",
            "Force_field_(chemistry)",
            "Lennard-Jones_potential",
            "Periodic_boundary_conditions",
            "Berendsen_thermostat",
            "Nos%C3%A9%E2%80%93Hoover_thermostat",
            "Ergodic_hypothesis",
        ),
    },
    "monte-carlo-simulation": {
        "tags": ["monte carlo simulation", "importance sampling", "rejection sampling", "variance reduction"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Monte_Carlo_method",
            "Monte_Carlo_integration",
            "Importance_sampling",
            "Metropolis%E2%80%93Hastings_algorithm",
            "Rejection_sampling",
            "Variance_reduction",
            "Quasi-Monte_Carlo_method",
        ),
    },
    "computational-chemistry": {
        "tags": ["computational chemistry", "density functional theory", "hartree-fock method", "molecular orbital"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Computational_chemistry",
            "Density_functional_theory",
            "Hartree%E2%80%93Fock_method",
            "Molecular_orbital",
            "Basis_set_(chemistry)",
            "Schr%C3%B6dinger_equation",
            "Born%E2%80%93Oppenheimer_approximation",
        ),
    },
    "coding-theory": {
        "tags": ["coding theory", "linear code", "hamming distance", "convolutional code"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Coding_theory",
            "Linear_code",
            "Hamming_distance",
            "BCH_code",
            "Low-density_parity-check_code",
            "Convolutional_code",
            "Turbo_code",
        ),
    },
    "elliptic-curve-cryptography": {
        "tags": ["elliptic curve cryptography", "elliptic curve", "discrete logarithm", "digital signature algorithm"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Elliptic-curve_cryptography",
            "Elliptic_curve",
            "Elliptic-curve_Diffie%E2%80%93Hellman",
            "Elliptic_Curve_Digital_Signature_Algorithm",
            "Curve25519",
            "Discrete_logarithm",
            "Montgomery_curve",
        ),
    },
    "graph-algorithms": {
        "tags": ["graph algorithms", "breadth-first search", "shortest path", "minimum spanning tree"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Graph_(abstract_data_type)",
            "Breadth-first_search",
            "Depth-first_search",
            "Dijkstra%27s_algorithm",
            "Bellman%E2%80%93Ford_algorithm",
            "Minimum_spanning_tree",
            "Topological_sorting",
            "Maximum_flow_problem",
            "Strongly_connected_component",
        ),
    },
    "string-algorithms": {
        "tags": ["string algorithms", "string searching", "suffix tree", "suffix array"],
        "license": CC_BY_SA,
        "pages": wiki(
            "String-searching_algorithm",
            "Knuth%E2%80%93Morris%E2%80%93Pratt_algorithm",
            "Boyer%E2%80%93Moore_string-search_algorithm",
            "Rabin%E2%80%93Karp_algorithm",
            "Suffix_tree",
            "Suffix_array",
            "Aho%E2%80%93Corasick_algorithm",
            "Trie",
        ),
    },
    "set-theory": {
        "tags": ["set theory", "set cardinality", "ordinal number", "axiom of choice"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Set_theory",
            "Naive_set_theory",
            "Zermelo%E2%80%93Fraenkel_set_theory",
            "Cardinality",
            "Ordinal_number",
            "Axiom_of_choice",
            "Cantor%27s_theorem",
            "Continuum_hypothesis",
        ),
    },
    "proof-theory": {
        "tags": ["proof theory", "natural deduction", "sequent calculus", "formal proof"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Proof_theory",
            "Natural_deduction",
            "Sequent_calculus",
            "Formal_proof",
            "Cut-elimination_theorem",
            "Proof_calculus",
            "Hilbert_system",
        ),
    },
    "computability-theory": {
        "tags": ["computability theory", "turing machine", "halting problem", "church-turing thesis"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Computability_theory",
            "Turing_machine",
            "Halting_problem",
            "Recursively_enumerable_set",
            "Church%E2%80%93Turing_thesis",
            "Decision_problem",
            "Undecidable_problem",
        ),
    },
    "chaos-theory": {
        "tags": ["chaos theory", "butterfly effect", "lyapunov exponent", "strange attractor"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Chaos_theory",
            "Butterfly_effect",
            "Lyapunov_exponent",
            "Logistic_map",
            "Lorenz_system",
            "Bifurcation_theory",
            "Strange_attractor",
        ),
    },
    "fractals": {
        "tags": ["fractal geometry", "mandelbrot set", "julia set", "fractal dimension"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Fractal",
            "Mandelbrot_set",
            "Julia_set",
            "Fractal_dimension",
            "Sierpi%C5%84ski_triangle",
            "Koch_snowflake",
            "Iterated_function_system",
        ),
    },
    "cellular-automata": {
        "tags": ["cellular automaton", "game of life", "elementary cellular automaton", "rule 110"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cellular_automaton",
            "Conway%27s_Game_of_Life",
            "Rule_110",
            "Elementary_cellular_automaton",
            "Von_Neumann_cellular_automaton",
            "Wireworld",
        ),
    },
    "dynamical-systems": {
        "tags": ["dynamical system", "phase space", "limit cycle", "ergodic theory"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Dynamical_system",
            "Attractor",
            "Phase_space",
            "Fixed_point_(mathematics)",
            "Limit_cycle",
            "Ergodic_theory",
            "Hamiltonian_mechanics",
        ),
    },
    "decision-theory": {
        "tags": ["decision theory", "expected utility", "bayesian inference", "loss function"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Decision_theory",
            "Expected_utility_hypothesis",
            "Bayesian_inference",
            "Loss_function",
            "Utility",
            "Multi-armed_bandit",
            "Value_of_information",
        ),
    },
    "combinatorial-optimization": {
        "tags": ["combinatorial optimization", "branch and bound", "simulated annealing", "genetic algorithm"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Combinatorial_optimization",
            "Branch_and_bound",
            "Simulated_annealing",
            "Genetic_algorithm",
            "Local_search_(optimization)",
            "Ant_colony_optimization_algorithms",
            "Cutting-plane_method",
        ),
    },
    "numerical-linear-algebra": {
        "tags": ["numerical linear algebra", "matrix decomposition", "conjugate gradient method", "krylov subspace"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Numerical_linear_algebra",
            "LU_decomposition",
            "QR_decomposition",
            "Cholesky_decomposition",
            "Singular_value_decomposition",
            "Conjugate_gradient_method",
            "Power_iteration",
            "Krylov_subspace",
        ),
    },
    "symbolic-computation": {
        "tags": ["symbolic computation", "computer algebra system", "grobner basis", "symbolic integration"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Symbolic_computation",
            "Computer_algebra_system",
            "Gr%C3%B6bner_basis",
            "Symbolic_integration",
            "Polynomial_greatest_common_divisor",
            "Risch_algorithm",
            "Buchberger%27s_algorithm",
        ),
    },
    "statistical-mechanics": {
        "tags": ["statistical mechanics", "partition function", "boltzmann distribution", "canonical ensemble"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Statistical_mechanics",
            "Partition_function_(statistical_mechanics)",
            "Boltzmann_distribution",
            "Entropy",
            "Canonical_ensemble",
            "Maxwell%E2%80%93Boltzmann_distribution",
            "Phase_transition",
        ),
    },
    "signal-estimation": {
        "tags": ["estimation theory", "kalman filter", "maximum likelihood estimation", "particle filter"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Estimation_theory",
            "Kalman_filter",
            "Maximum_likelihood_estimation",
            "Least_squares",
            "Cram%C3%A9r%E2%80%93Rao_bound",
            "Wiener_filter",
            "Particle_filter",
        ),
    },
}
