"""Scientific computing across physics, chemistry, biology, and quantitative fields."""

from .common import CC_BY_SA, WIKI, wiki

DOMAINS = {
    "scipy-library": {
        "tags": ["scipy library", "scientific python", "numerical routines", "signal processing scipy"],
        "license": "BSD-3-Clause",
        "pages": wiki(
            "SciPy",
            "NumPy",
            "Numerical_analysis",
            "Interpolation",
            "Numerical_integration",
        ) + [
            "https://docs.scipy.org/doc/scipy/tutorial/index.html",
            "https://docs.scipy.org/doc/scipy/reference/optimize.html",
        ],
    },
    "sympy-symbolic": {
        "tags": ["sympy symbolic", "computer algebra", "symbolic integration", "equation solving"],
        "license": "BSD-3-Clause",
        "pages": wiki(
            "SymPy",
            "Computer_algebra",
            "Symbolic_integration",
            "Polynomial",
            "Equation_solving",
            "Term_rewriting",
        ) + [
            "https://docs.sympy.org/latest/tutorials/intro-tutorial/index.html",
        ],
    },
    "statsmodels": {
        "tags": ["statsmodels library", "regression analysis", "generalized linear model", "analysis of variance"],
        "license": "BSD-3-Clause",
        "pages": wiki(
            "Regression_analysis",
            "Generalized_linear_model",
            "Analysis_of_variance",
            "Ordinary_least_squares",
            "Logistic_regression",
        ) + [
            "https://www.statsmodels.org/stable/index.html",
            "https://www.statsmodels.org/stable/regression.html",
        ],
    },
    "scikit-image": {
        "tags": ["scikit-image library", "image segmentation", "edge detection", "mathematical morphology"],
        "license": "BSD-3-Clause",
        "pages": wiki(
            "Image_segmentation",
            "Edge_detection",
            "Digital_image_processing",
            "Mathematical_morphology",
            "Image_registration",
            "Corner_detection",
        ) + [
            "https://scikit-image.org/docs/stable/",
            "https://scikit-image.org/docs/stable/auto_examples/index.html",
        ],
    },
    "numba-jit": {
        "tags": ["numba compiler", "just-in-time compilation", "automatic vectorization", "llvm backend"],
        "license": "BSD-3-Clause",
        "pages": wiki(
            "Numba",
            "Just-in-time_compilation",
            "LLVM",
            "Automatic_vectorization",
            "Vectorization_(mathematics)",
        ) + [
            "https://numba.readthedocs.io/en/stable/",
            "https://numba.readthedocs.io/en/stable/user/5minguide.html",
        ],
    },
    "cython": {
        "tags": ["cython language", "foreign function interface", "global interpreter lock", "compiled extension"],
        "license": "Apache-2.0",
        "pages": wiki(
            "Cython",
            "Foreign_function_interface",
            "Global_interpreter_lock",
            "Compiled_language",
        ) + [
            "https://cython.readthedocs.io/en/latest/",
            "https://cython.readthedocs.io/en/latest/src/tutorial/cython_tutorial.html",
        ],
    },
    "computational-electromagnetics": {
        "tags": ["computational electromagnetics", "method of moments", "boundary element method", "electromagnetic scattering"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Computational_electromagnetics",
            "Method_of_moments_(electromagnetics)",
            "Boundary_element_method",
            "Maxwell%27s_equations",
            "Perfectly_matched_layer",
            "Radiative_transfer",
        ),
    },
    "finite-difference-time-domain": {
        "tags": ["finite-difference time-domain", "yee lattice", "absorbing boundary condition", "numerical dispersion"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Finite-difference_time-domain_method",
            "Yee_lattice",
            "Absorbing_boundary_condition",
            "Numerical_dispersion",
            "Perfectly_matched_layer",
            "Courant%E2%80%93Friedrichs%E2%80%93Lewy_condition",
        ),
    },
    "spectral-methods": {
        "tags": ["spectral method", "pseudo-spectral method", "chebyshev polynomials", "collocation method"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Spectral_method",
            "Pseudo-spectral_method",
            "Chebyshev_polynomials",
            "Collocation_method",
            "Spectral_element_method",
            "Orthogonal_polynomials",
            "Galerkin_method",
        ),
    },
    "lattice-boltzmann": {
        "tags": ["lattice boltzmann method", "boltzmann equation", "kinetic theory of gases", "lattice gas automaton"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Lattice_Boltzmann_methods",
            "Boltzmann_equation",
            "Bhatnagar%E2%80%93Gross%E2%80%93Krook_operator",
            "Kinetic_theory_of_gases",
            "Knudsen_number",
            "Lattice_gas_automaton",
        ),
    },
    "smoothed-particle-hydrodynamics": {
        "tags": ["smoothed-particle hydrodynamics", "meshfree methods", "fluid simulation", "multiphase flow"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Smoothed-particle_hydrodynamics",
            "Meshfree_methods",
            "Fluid_simulation",
            "Multiphase_flow",
            "Immersed_boundary_method",
            "Kernel_(statistics)",
        ),
    },
    "n-body-simulation": {
        "tags": ["n-body simulation", "barnes-hut simulation", "fast multipole method", "astrophysical plasma"],
        "license": CC_BY_SA,
        "pages": wiki(
            "N-body_simulation",
            "Barnes%E2%80%93Hut_simulation",
            "Fast_multipole_method",
            "Astrophysical_plasma",
            "Symplectic_integrator",
            "Gravitational_potential",
        ),
    },
    "celestial-mechanics": {
        "tags": ["celestial mechanics", "two-body problem", "osculating orbit", "tidal force"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Celestial_mechanics",
            "Two-body_problem",
            "Kepler%27s_laws_of_planetary_motion",
            "Three-body_problem",
            "Osculating_orbit",
            "Tidal_force",
            "Roche_limit",
        ),
    },
    "orbital-mechanics": {
        "tags": ["orbital mechanics", "hohmann transfer orbit", "orbital elements", "rocket equation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Orbital_mechanics",
            "Kepler_orbit",
            "Hohmann_transfer_orbit",
            "Orbital_elements",
            "Tsiolkovsky_rocket_equation",
            "Escape_velocity",
            "Gravity_assist",
        ),
    },
    "general-relativity-numerics": {
        "tags": ["numerical relativity", "einstein field equations", "adm formalism", "gravitational wave modeling"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Numerical_relativity",
            "Einstein_field_equations",
            "ADM_formalism",
            "Schwarzschild_metric",
            "Gravitational_wave",
            "Christoffel_symbols",
            "Geodesics_in_general_relativity",
            "Post-Newtonian_expansion",
        ),
    },
    "quantum-chemistry-dft": {
        "tags": ["quantum chemistry", "electronic structure", "coupled cluster", "configuration interaction"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Quantum_chemistry",
            "Electronic_structure",
            "Configuration_interaction",
            "Coupled_cluster",
            "Post-Hartree%E2%80%93Fock",
            "M%C3%B8ller%E2%80%93Plesset_perturbation_theory",
            "Electron_correlation",
        ),
    },
    "hartree-fock": {
        "tags": ["hartree-fock method", "self-consistent field", "slater determinant", "roothaan equations"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Hartree%E2%80%93Fock_method",
            "Self-consistent_field_method",
            "Slater_determinant",
            "Roothaan_equations",
            "Fock_matrix",
            "Basis_set_(chemistry)",
        ),
    },
    "ab-initio-methods": {
        "tags": ["ab initio quantum chemistry", "complete active space", "multi-configurational scf", "variational method chemistry"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ab_initio_quantum_chemistry_methods",
            "Complete_active_space",
            "Multi-configurational_self-consistent_field",
            "Variational_method_(quantum_mechanics)",
            "Density_matrix",
            "Configuration_interaction",
        ),
    },
    "density-functional-theory": {
        "tags": ["density functional theory", "kohn-sham equations", "hohenberg-kohn theorems", "pseudopotential"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Density_functional_theory",
            "Kohn%E2%80%93Sham_equations",
            "Hohenberg%E2%80%93Kohn_theorems",
            "Local-density_approximation",
            "Generalized_gradient_approximation",
            "Plane_wave",
            "Pseudopotential",
        ),
    },
    "protein-folding": {
        "tags": ["protein folding", "protein structure prediction", "levinthal paradox", "anfinsen dogma"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Protein_folding",
            "Protein_structure_prediction",
            "Levinthal%27s_paradox",
            "Anfinsen%27s_dogma",
            "Protein_secondary_structure",
            "AlphaFold",
        ),
    },
    "molecular-docking": {
        "tags": ["molecular docking", "virtual screening", "structure-based drug design", "scoring function docking"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Docking_(molecular)",
            "Virtual_screening",
            "Scoring_functions_for_docking",
            "Structure-based_drug_design",
            "Binding_site",
            "Pharmacophore",
            "Ligand_(biochemistry)",
        ),
    },
    "cheminformatics-rdkit": {
        "tags": ["cheminformatics rdkit", "molecular descriptor", "smiles notation", "chemical fingerprint"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cheminformatics",
            "Simplified_molecular-input_line-entry_system",
            "Molecular_descriptor",
            "International_Chemical_Identifier",
            "Quantitative_structure%E2%80%93activity_relationship",
            "Chemical_file_format",
        ) + [
            "https://www.rdkit.org/docs/index.html",
            "https://www.rdkit.org/docs/GettingStartedInPython.html",
        ],
    },
    "mass-spectrometry-analysis": {
        "tags": ["mass spectrometry analysis", "tandem mass spectrometry", "peptide mass fingerprinting", "de novo peptide sequencing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Mass_spectrometry",
            "Tandem_mass_spectrometry",
            "Peptide_mass_fingerprinting",
            "De_novo_peptide_sequencing",
            "Selected_reaction_monitoring",
            "Proteomics",
            "Isotopic_labeling",
        ),
    },
    "phylogenetics": {
        "tags": ["computational phylogenetics", "phylogenetic tree", "maximum parsimony", "neighbor joining"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Computational_phylogenetics",
            "Phylogenetic_tree",
            "Maximum_parsimony_(phylogenetics)",
            "Neighbor_joining",
            "Molecular_clock",
            "Bayesian_inference_in_phylogeny",
            "UPGMA",
        ),
    },
    "population-genetics": {
        "tags": ["population genetics", "hardy-weinberg principle", "coalescent theory", "linkage disequilibrium"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Population_genetics",
            "Hardy%E2%80%93Weinberg_principle",
            "Genetic_drift",
            "Coalescent_theory",
            "Fixation_index",
            "Effective_population_size",
            "Linkage_disequilibrium",
        ),
    },
    "systems-biology": {
        "tags": ["systems biology", "flux balance analysis", "gene regulatory network", "metabolic network modelling"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Systems_biology",
            "Metabolic_network_modelling",
            "Flux_balance_analysis",
            "Gene_regulatory_network",
            "Biological_network",
            "Boolean_network",
            "Metabolic_pathway",
        ),
    },
    "gene-expression-analysis": {
        "tags": ["gene expression profiling", "dna microarray", "differential gene expression", "rna sequencing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Gene_expression_profiling",
            "DNA_microarray",
            "RNA-Seq",
            "Gene_set_enrichment_analysis",
            "Volcano_plot_(statistics)",
            "Fold_change",
            "Transcriptomics_technologies",
        ),
    },
    "blast-sequence-search": {
        "tags": ["blast sequence search", "substitution matrix", "sequence database", "expectation value blast"],
        "license": CC_BY_SA,
        "pages": wiki(
            "BLAST_(biotechnology)",
            "Sequence_database",
            "E-value",
            "Smith%E2%80%93Waterman_algorithm",
            "Substitution_matrix",
            "FASTA",
        ),
    },
    "variant-calling-gatk": {
        "tags": ["variant calling", "single-nucleotide polymorphism", "variant call format", "base calling"],
        "license": CC_BY_SA,
        "pages": wiki(
            "SNV_calling_from_NGS_data",
            "Variant_Call_Format",
            "Single-nucleotide_polymorphism",
            "Indel",
            "Base_calling",
        ) + [
            "https://gatk.broadinstitute.org/hc/en-us",
        ],
    },
    "samtools-bam": {
        "tags": ["samtools toolkit", "sequence alignment map", "binary alignment map", "pileup format"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Samtools",
            "SAM_(file_format)",
            "Binary_Alignment_Map",
            "Pileup_format",
            "FASTQ_format",
            "Phred_quality_score",
        ) + [
            "http://www.htslib.org/doc/samtools.html",
        ],
    },
    "climate-modeling": {
        "tags": ["climate model", "general circulation model", "radiative transfer", "model intercomparison"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Climate_model",
            "General_circulation_model",
            "Radiative_transfer",
            "Parametrization_(atmospheric_modeling)",
            "Coupled_Model_Intercomparison_Project",
            "Primitive_equations",
        ),
    },
    "weather-forecasting-nwp": {
        "tags": ["numerical weather prediction", "data assimilation", "ensemble forecasting", "primitive equations"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Numerical_weather_prediction",
            "Weather_forecasting",
            "Data_assimilation",
            "Ensemble_forecasting",
            "Primitive_equations",
            "Spectral_method",
        ),
    },
    "ocean-modeling": {
        "tags": ["ocean general circulation model", "physical oceanography", "thermohaline circulation", "ekman transport"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ocean_general_circulation_model",
            "Physical_oceanography",
            "Thermohaline_circulation",
            "Ekman_transport",
            "Boussinesq_approximation_(buoyancy)",
            "Sea_surface_temperature",
        ),
    },
    "remote-sensing-analysis": {
        "tags": ["remote sensing analysis", "multispectral imaging", "vegetation index", "synthetic-aperture radar"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Remote_sensing",
            "Multispectral_imaging",
            "Hyperspectral_imaging",
            "Normalized_difference_vegetation_index",
            "Synthetic-aperture_radar",
            "Georeferencing",
            "Pansharpening",
        ),
    },
    "econometrics": {
        "tags": ["econometrics", "instrumental variables", "panel data", "gauss-markov theorem"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Econometrics",
            "Ordinary_least_squares",
            "Instrumental_variables_estimation",
            "Panel_data",
            "Heteroscedasticity",
            "Endogeneity_(econometrics)",
            "Gauss%E2%80%93Markov_theorem",
        ),
    },
    "time-series-econometrics": {
        "tags": ["time series econometrics", "autoregressive model", "cointegration analysis", "volatility clustering"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Autoregressive_integrated_moving_average",
            "Autoregressive_model",
            "Vector_autoregression",
            "Cointegration",
            "Autoregressive_conditional_heteroskedasticity",
            "Unit_root",
            "Dickey%E2%80%93Fuller_test",
            "Granger_causality",
        ),
    },
    "agent-based-modeling": {
        "tags": ["agent-based model", "complex adaptive system", "swarm intelligence", "segregation model"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Agent-based_model",
            "Complex_adaptive_system",
            "Emergence",
            "Schelling%27s_model_of_segregation",
            "NetLogo",
            "Swarm_intelligence",
        ),
    },
    "discrete-event-simulation": {
        "tags": ["discrete-event simulation", "stochastic simulation", "poisson point process", "queueing theory"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Discrete-event_simulation",
            "Queueing_theory",
            "Monte_Carlo_method",
            "Poisson_point_process",
            "Stochastic_simulation",
            "Simulation",
        ),
    },
    "network-science": {
        "tags": ["network science", "scale-free network", "small-world network", "community structure"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Network_science",
            "Complex_network",
            "Scale-free_network",
            "Small-world_network",
            "Community_structure",
            "Barab%C3%A1si%E2%80%93Albert_model",
            "Erd%C5%91s%E2%80%93R%C3%A9nyi_model",
            "Betweenness_centrality",
        ),
    },
    "complex-systems": {
        "tags": ["complex systems", "self-organization", "power law", "percolation theory"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Complex_system",
            "Self-organization",
            "Nonlinear_system",
            "Phase_transition",
            "Power_law",
            "Percolation_theory",
            "Bifurcation_theory",
        ),
    },
    "epidemiological-modeling": {
        "tags": ["epidemiological modeling", "compartmental models epidemiology", "basic reproduction number", "next-generation matrix"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Compartmental_models_in_epidemiology",
            "Basic_reproduction_number",
            "Mathematical_modelling_of_infectious_diseases",
            "SIR_model",
            "Effective_reproduction_number",
            "Force_of_infection",
            "Serial_interval",
            "Next-generation_matrix",
        ),
    },
    "computational-neuroscience": {
        "tags": ["computational neuroscience", "hodgkin-huxley model", "biological neuron model", "cable theory"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Computational_neuroscience",
            "Hodgkin%E2%80%93Huxley_model",
            "Biological_neuron_model",
            "Neural_coding",
            "Cable_theory",
            "Spiking_neural_network",
            "Neuronal_noise",
        ),
    },
    "neural-simulation": {
        "tags": ["neural simulation software", "leaky integrate-and-fire", "dendrite compartmental modelling", "blue brain project"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Neuron_(software)",
            "GENESIS_(software)",
            "Brian_(software)",
            "Leaky_integrate-and-fire",
            "Compartmental_modelling_of_dendrites",
            "Blue_Brain_Project",
            "Neural_network_software",
        ),
    },
    "bayesian-statistics": {
        "tags": ["bayesian statistics", "conjugate prior", "posterior probability", "credible interval"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Bayesian_statistics",
            "Bayes%27_theorem",
            "Prior_probability",
            "Posterior_probability",
            "Conjugate_prior",
            "Credible_interval",
            "Bayes_factor",
            "Bayesian_network",
        ),
    },
    "markov-chain-monte-carlo": {
        "tags": ["markov chain monte carlo", "metropolis-hastings algorithm", "gibbs sampling", "hamiltonian monte carlo"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Markov_chain_Monte_Carlo",
            "Metropolis%E2%80%93Hastings_algorithm",
            "Gibbs_sampling",
            "Hamiltonian_Monte_Carlo",
            "Monte_Carlo_method",
            "Kernel_density_estimation",
        ),
    },
    "gaussian-processes-sci": {
        "tags": ["gaussian process regression", "covariance function", "bayesian optimization", "radial basis kernel"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Gaussian_process",
            "Kriging",
            "Covariance_function",
            "Radial_basis_function_kernel",
            "Bayesian_optimization",
            "Nonlinear_regression",
        ),
    },
    "optimization-scipy": {
        "tags": ["mathematical optimization", "nelder-mead method", "sequential quadratic programming", "interior-point method"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Mathematical_optimization",
            "Gradient_descent",
            "Newton%27s_method_in_optimization",
            "Nelder%E2%80%93Mead_method",
            "Sequential_quadratic_programming",
            "Interior-point_method",
            "Broyden%E2%80%93Fletcher%E2%80%93Goldfarb%E2%80%93Shanno_algorithm",
            "Trust_region",
        ),
    },
    "sparse-linear-algebra": {
        "tags": ["sparse matrix", "iterative method solver", "preconditioner", "conjugate gradient method"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Sparse_matrix",
            "Sparse_matrix%E2%80%93vector_multiplication",
            "Iterative_method",
            "Preconditioner",
            "Conjugate_gradient_method",
            "Generalized_minimal_residual_method",
            "Band_matrix",
            "Skyline_matrix",
        ),
    },
    "eigenvalue-solvers": {
        "tags": ["eigenvalue algorithm", "lanczos algorithm", "arnoldi iteration", "qr algorithm"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Eigenvalue_algorithm",
            "QR_algorithm",
            "Lanczos_algorithm",
            "Arnoldi_iteration",
            "Jacobi_eigenvalue_algorithm",
            "Divide-and-conquer_eigenvalue_algorithm",
        ),
    },
    "automatic-differentiation": {
        "tags": ["automatic differentiation", "dual number", "differentiable programming", "reverse-mode autodiff"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Automatic_differentiation",
            "Dual_number",
            "Backpropagation",
            "Chain_rule",
            "Differentiable_programming",
            "Directed_acyclic_graph",
        ),
    },
    "high-performance-computing": {
        "tags": ["high-performance computing", "parallel computing", "amdahl law", "gpu general-purpose computing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "High-performance_computing",
            "Supercomputer",
            "Parallel_computing",
            "Amdahl%27s_law",
            "CUDA",
            "General-purpose_computing_on_graphics_processing_units",
            "Distributed_memory",
        ),
    },
    "mpi-parallel-computing": {
        "tags": ["message passing interface", "distributed memory parallelism", "process communication mpi", "collective communication"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Message_Passing_Interface",
            "Distributed_memory",
            "Parallel_computing",
            "Supercomputer",
        ) + [
            "https://mpi4py.readthedocs.io/en/stable/",
            "https://www.open-mpi.org/doc/",
        ],
    },
    "openmp-parallelism": {
        "tags": ["openmp parallelism", "shared memory parallelism", "loop-level parallelism", "fork-join model"],
        "license": CC_BY_SA,
        "pages": wiki(
            "OpenMP",
            "Shared_memory_(interprocess_communication)",
            "Thread_(computing)",
            "Fork%E2%80%93join_model",
            "Loop-level_parallelism",
            "Data_parallelism",
        ) + [
            "https://www.openmp.org/specifications/",
        ],
    },
}
