"""Defensive security, cryptography practice, identity, and compliance frameworks."""

from .common import CC_BY_SA, OWASP, PD, wiki

# Non-Wikipedia static sources, each verified live (HTTP 200) at authoring time:
#   OWASP Cheat Sheet Series -> cheatsheetseries.owasp.org (static HTML, CC-BY-SA)
#   MITRE ATT&CK / CWE       -> attack.mitre.org, cwe.mitre.org (public reference)
OWASP_CS = "https://cheatsheetseries.owasp.org/cheatsheets/"
ATTACK = "https://attack.mitre.org/"
CWE = "https://cwe.mitre.org/"

DOMAINS = {
    "mitre-attack": {
        "tags": [
            "mitre att&ck",
            "adversary tactics techniques",
            "att&ck framework",
            "cyber kill chain",
            "threat actor behavior",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "MITRE_ATT%26CK",
            "Cyber_kill_chain",
            "Advanced_persistent_threat",
            "Cyberattack",
            "Threat_actor",
            "Open-source_intelligence",
        )
        + [
            ATTACK + "groups/",
            ATTACK + "software/",
        ],
    },
    "nist-cybersecurity-framework": {
        "tags": [
            "nist cybersecurity framework",
            "risk management framework",
            "security controls catalog",
            "cyber risk management",
            "information security governance",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "NIST_Cybersecurity_Framework",
            "Risk_management_framework",
            "National_Institute_of_Standards_and_Technology",
            "Information_security",
            "Security_controls",
            "IT_risk",
            "Security_policy",
        ),
    },
    "cis-benchmarks": {
        "tags": [
            "cis benchmarks",
            "cis critical security controls",
            "security configuration baseline",
            "center for internet security",
            "system hardening guide",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "The_CIS_Critical_Security_Controls_for_Effective_Cyber_Defense",
            "Center_for_Internet_Security",
            "Hardening_(computing)",
            "Benchmark_(computing)",
            "Configuration_management",
            "Baseline_(configuration_management)",
        ),
    },
    "threat-modeling": {
        "tags": [
            "threat modeling",
            "attack surface analysis",
            "attack tree",
            "data flow diagram",
            "stride threat model",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Threat_model",
            "STRIDE_(security)",
            "DREAD_(risk_assessment_model)",
            "Attack_tree",
            "Attack_surface",
            "Data_flow_diagram",
        )
        + [
            OWASP_CS + "Threat_Modeling_Cheat_Sheet.html",
            OWASP_CS + "Attack_Surface_Analysis_Cheat_Sheet.html",
        ],
    },
    "zero-trust": {
        "tags": [
            "zero trust",
            "zero trust architecture",
            "never trust always verify",
            "principle of least privilege",
            "software defined perimeter",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Zero_trust_architecture",
            "Network_security",
            "Principle_of_least_privilege",
            "Defense_in_depth_(computing)",
            "Software-defined_perimeter",
            "BeyondCorp",
        ),
    },
    "siem-logging": {
        "tags": [
            "security information and event management",
            "siem",
            "log management",
            "audit trail",
            "security event correlation",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Security_information_and_event_management",
            "Log_management",
            "Syslog",
            "Audit_trail",
            "Security_event_manager",
            "Netflow",
        )
        + [OWASP_CS + "Logging_Cheat_Sheet.html"],
    },
    "intrusion-detection": {
        "tags": [
            "intrusion detection system",
            "host based intrusion detection",
            "network intrusion detection",
            "intrusion prevention system",
            "anomaly detection",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Intrusion_detection_system",
            "Intrusion_detection_system_evasion_techniques",
            "Host-based_intrusion_detection_system",
            "Intrusion_prevention_system",
            "Snort_(software)",
            "Suricata_(software)",
            "Zeek",
            "Signature-based_detection",
        ),
    },
    "web-application-firewall": {
        "tags": [
            "web application firewall",
            "application firewall",
            "modsecurity waf",
            "reverse proxy filtering",
            "http request smuggling",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Web_application_firewall",
            "Application_firewall",
            "ModSecurity",
            "Reverse_proxy",
            "HTTP_request_smuggling",
            "OWASP",
        )
        + [OWASP_CS + "Web_Service_Security_Cheat_Sheet.html"],
    },
    "ddos-defense": {
        "tags": [
            "ddos mitigation",
            "denial of service attack",
            "distributed denial of service",
            "rate limiting",
            "syn flood defense",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "DDoS_mitigation",
            "Denial-of-service_attack",
            "Content_delivery_network",
            "Rate_limiting",
            "Anycast",
            "SYN_flood",
        )
        + [OWASP_CS + "Denial_of_Service_Cheat_Sheet.html"],
    },
    "malware-analysis": {
        "tags": [
            "malware analysis",
            "malware reverse engineering",
            "antivirus software",
            "malware sandboxing",
            "yara rules",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Malware_analysis",
            "Malware",
            "Sandbox_(computer_security)",
            "Reverse_engineering",
            "Antivirus_software",
            "Disassembler",
            "YARA",
            "Computer_virus",
        ),
    },
    "incident-response": {
        "tags": [
            "incident response",
            "computer security incident",
            "computer emergency response team",
            "business continuity planning",
            "root cause analysis",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Incident_response",
            "Computer_security_incident_management",
            "Computer_emergency_response_team",
            "Business_continuity_planning",
            "Disaster_recovery",
            "Root_cause_analysis",
        ),
    },
    "digital-forensics": {
        "tags": [
            "digital forensics",
            "computer forensics",
            "forensic data recovery",
            "memory forensics",
            "chain of custody",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Digital_forensics",
            "Computer_forensics",
            "Data_recovery",
            "Memory_forensics",
            "File_carving",
            "Write_blocker",
        ),
    },
    "public-key-infrastructure": {
        "tags": [
            "public key infrastructure",
            "certificate authority",
            "certificate revocation list",
            "online certificate status protocol",
            "trust service provider",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Public_key_infrastructure",
            "Certificate_authority",
            "Public_key_certificate",
            "Certificate_revocation_list",
            "Online_Certificate_Status_Protocol",
            "Root_certificate",
            "Trust_service_provider",
        ),
    },
    "x509-certificates": {
        "tags": [
            "x.509 certificate",
            "certificate signing request",
            "certificate transparency",
            "extended validation certificate",
            "wildcard certificate",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "X.509",
            "Certificate_signing_request",
            "Certificate_Transparency",
            "Extended_Validation_Certificate",
            "Wildcard_certificate",
            "Self-signed_certificate",
        ),
    },
    "webauthn-fido2": {
        "tags": [
            "webauthn",
            "fido2 authentication",
            "fido alliance",
            "client to authenticator protocol",
            "hardware security key",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "WebAuthn",
            "FIDO_Alliance",
            "Universal_2nd_Factor",
            "Client_to_Authenticator_Protocol",
            "YubiKey",
            "Biometrics",
        ),
    },
    "passkeys": {
        "tags": [
            "passkey authentication",
            "passwordless authentication",
            "webauthn credential",
            "fido alliance",
            "public key credential",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Passkey",
            "Passwordless_authentication",
            "WebAuthn",
            "FIDO_Alliance",
            "Public_key_certificate",
            "Password",
        ),
    },
    "ldap-directory": {
        "tags": [
            "lightweight directory access protocol",
            "directory service",
            "x.500 directory",
            "openldap server",
            "ldap injection prevention",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Lightweight_Directory_Access_Protocol",
            "Directory_service",
            "X.500",
            "OpenLDAP",
            "Identity_and_access_management",
        )
        + [OWASP_CS + "LDAP_Injection_Prevention_Cheat_Sheet.html"],
    },
    "kerberos-authentication": {
        "tags": [
            "kerberos protocol",
            "ticket granting ticket",
            "needham schroeder protocol",
            "network authentication protocol",
            "mutual authentication",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Kerberos_(protocol)",
            "Ticket_Granting_Ticket",
            "Needham%E2%80%93Schroeder_protocol",
            "Authentication",
            "Mutual_authentication",
            "Single_sign-on",
        ),
    },
    "active-directory": {
        "tags": [
            "active directory",
            "domain controller",
            "group policy",
            "directory service",
            "identity and access management",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Active_Directory",
            "Group_Policy",
            "Domain_controller",
            "Directory_service",
            "Identity_and_access_management",
            "Kerberos_(protocol)",
        ),
    },
    "rbac-access-control": {
        "tags": [
            "role based access control",
            "access control list",
            "least privilege access",
            "computing privilege",
            "identity and access management",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Role-based_access_control",
            "Access_control",
            "Access_control_list",
            "Privilege_(computing)",
            "Principle_of_least_privilege",
            "Identity_and_access_management",
        )
        + [OWASP_CS + "Access_Control_Cheat_Sheet.html"],
    },
    "abac-access-control": {
        "tags": [
            "attribute based access control",
            "xacml policy language",
            "access control policy",
            "authorization model",
            "provisioning technology",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Attribute-based_access_control",
            "XACML",
            "Access_control",
            "Role-based_access_control",
            "Provisioning_(technology)",
            "System_for_Cross-domain_Identity_Management",
        ),
    },
    "secrets-management": {
        "tags": [
            "secrets management",
            "key management",
            "hardware security module",
            "secret sharing",
            "password manager",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Key_management",
            "Hardware_security_module",
            "Secret_sharing",
            "Password_manager",
            "Trusted_Platform_Module",
            "Key_derivation_function",
        )
        + [OWASP_CS + "Secrets_Management_Cheat_Sheet.html"],
    },
    "software-supply-chain-security": {
        "tags": [
            "software supply chain security",
            "supply chain attack",
            "code signing",
            "reproducible builds",
            "dependency typosquatting",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Software_supply_chain",
            "Supply_chain_attack",
            "Code_signing",
            "Reproducible_builds",
            "Typosquatting",
            "DevSecOps",
        )
        + [OWASP_CS + "Vulnerable_Dependency_Management_Cheat_Sheet.html"],
    },
    "sbom": {
        "tags": [
            "software bill of materials",
            "software composition analysis",
            "software package data exchange",
            "package manager",
            "dependency management",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Software_bill_of_materials",
            "Software_composition_analysis",
            "Software_Package_Data_Exchange",
            "Package_manager",
            "Dependency_hell",
            "Continuous_integration",
        ),
    },
    "cvss-scoring": {
        "tags": [
            "common vulnerability scoring system",
            "cvss score",
            "common vulnerabilities and exposures",
            "common weakness enumeration",
            "vulnerability severity",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Common_Vulnerability_Scoring_System",
            "Common_Vulnerabilities_and_Exposures",
            "Common_Weakness_Enumeration",
            "Vulnerability_(computing)",
            "Exploit_(computer_security)",
        )
        + [CWE + "top25/"],
    },
    "fuzz-testing": {
        "tags": [
            "fuzz testing",
            "coverage guided fuzzing",
            "american fuzzy lop",
            "code coverage",
            "static program analysis",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Fuzzing",
            "American_fuzzy_lop_(fuzzer)",
            "Code_coverage",
            "Test_case",
            "Static_program_analysis",
            "Buffer_overflow",
        ),
    },
    "penetration-testing-methodology": {
        "tags": [
            "penetration testing",
            "red team assessment",
            "vulnerability scanner",
            "security exploit",
            "open source intelligence",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Penetration_test",
            "Red_team",
            "Vulnerability_scanner",
            "Exploit_(computer_security)",
            "Open-source_intelligence",
            "Attack_surface",
        ),
    },
    "vulnerability-management": {
        "tags": [
            "vulnerability management",
            "patch management",
            "common weakness enumeration",
            "vulnerability disclosure",
            "vulnerability scanning",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Vulnerability_management",
            "Patch_(computing)",
            "Common_Weakness_Enumeration",
            "Vulnerability_(computing)",
            "Vulnerability_scanner",
        )
        + [OWASP_CS + "Vulnerability_Disclosure_Cheat_Sheet.html"],
    },
    "security-operations-center": {
        "tags": [
            "security operations center",
            "managed security service",
            "security orchestration",
            "cyber threat hunting",
            "extended detection and response",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Security_operations_center",
            "Managed_security_service",
            "Security_orchestration",
            "Cyber_threat_hunting",
            "Extended_detection_and_response",
            "Anomaly_detection",
        ),
    },
    "endpoint-detection-response": {
        "tags": [
            "endpoint detection and response",
            "endpoint security",
            "extended detection and response",
            "mobile device management",
            "bring your own device",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Endpoint_detection_and_response",
            "Endpoint_security",
            "Extended_detection_and_response",
            "Bring_your_own_device",
            "Mobile_device_management",
            "Antimalware",
        ),
    },
    "data-loss-prevention": {
        "tags": [
            "data loss prevention",
            "data exfiltration",
            "information sensitivity",
            "data classification",
            "sensitive data protection",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Data_loss_prevention_software",
            "Data_exfiltration",
            "Information_sensitivity",
            "Data_classification_(data_management)",
            "Content-control_software",
            "Egress_filtering",
        ),
    },
    "honeypot": {
        "tags": [
            "honeypot computing",
            "deception technology",
            "honeynet project",
            "intrusion detection system",
            "network deception",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Honeypot_(computing)",
            "Honeynet_Project",
            "Deception_technology",
            "Intrusion_detection_system",
            "Threat_actor",
            "Malware",
        ),
    },
    "network-segmentation": {
        "tags": [
            "network segmentation",
            "network microsegmentation",
            "demilitarized zone network",
            "air gap network",
            "network access control",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Network_segmentation",
            "Microsegmentation_(network_security)",
            "DMZ_(computing)",
            "Virtual_LAN",
            "Air_gap_(networking)",
            "Network_access_control",
            "Bastion_host",
        )
        + [OWASP_CS + "Network_Segmentation_Cheat_Sheet.html"],
    },
    "secure-coding-practices": {
        "tags": [
            "secure coding practices",
            "static application security testing",
            "dynamic application security testing",
            "secure by design",
            "input validation",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Static_application_security_testing",
            "Dynamic_application_security_testing",
            "Secure_by_design",
            "Input_validation",
            "Code_review",
            "Common_Weakness_Enumeration",
        )
        + [CWE + "data/definitions/1000.html"],
    },
    "threat-intelligence": {
        "tags": [
            "cyber threat intelligence",
            "indicator of compromise",
            "structured threat information",
            "threat intelligence platform",
            "open source intelligence",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cyber_threat_intelligence",
            "Indicator_of_compromise",
            "STIX",
            "Threat_(computer_security)",
            "Threat_Intelligence_Platform",
            "Open-source_intelligence",
        ),
    },
    "phishing-defense": {
        "tags": [
            "phishing defense",
            "email authentication",
            "sender policy framework",
            "domainkeys identified mail",
            "dmarc policy",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Phishing",
            "Email_authentication",
            "Sender_Policy_Framework",
            "DomainKeys_Identified_Mail",
            "DMARC",
            "Anti-phishing_software",
        ),
    },
    "social-engineering-awareness": {
        "tags": [
            "social engineering security",
            "security awareness training",
            "pretexting attack",
            "psychological manipulation",
            "phishing awareness",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Social_engineering_(security)",
            "Pretexting",
            "Security_awareness",
            "Psychological_manipulation",
            "Phishing",
            "Data_breach",
        ),
    },
    "ransomware-defense": {
        "tags": [
            "ransomware defense",
            "backup and recovery",
            "immutable backup rotation",
            "data recovery",
            "malware defense",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ransomware",
            "Backup",
            "Data_recovery",
            "Malware",
            "Backup_rotation_scheme",
            "Disaster_recovery",
        ),
    },
    "encryption-at-rest": {
        "tags": [
            "encryption at rest",
            "full disk encryption",
            "data at rest",
            "linux unified key setup",
            "database encryption",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Data_at_rest",
            "Disk_encryption",
            "Full_disk_encryption",
            "BitLocker",
            "Linux_Unified_Key_Setup",
            "Database_encryption",
            "VeraCrypt",
        )
        + [OWASP_CS + "Cryptographic_Storage_Cheat_Sheet.html"],
    },
    "transport-layer-security": {
        "tags": [
            "transport layer security",
            "https protocol",
            "http strict transport security",
            "perfect forward secrecy",
            "server name indication",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Transport_Layer_Security",
            "HTTPS",
            "HTTP_Strict_Transport_Security",
            "Cipher_suite",
            "Perfect_forward_secrecy",
            "Server_Name_Indication",
        )
        + [OWASP_CS + "Transport_Layer_Security_Cheat_Sheet.html"],
    },
    "vpn-security": {
        "tags": [
            "virtual private network",
            "vpn tunneling protocol",
            "ipsec vpn",
            "wireguard protocol",
            "split tunneling",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Virtual_private_network",
            "IPsec",
            "WireGuard",
            "OpenVPN",
            "Tunneling_protocol",
            "Split_tunneling",
        ),
    },
    "firewall-concepts": {
        "tags": [
            "firewall computing",
            "stateful firewall",
            "network address translation",
            "deep packet inspection",
            "packet analyzer",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Firewall_(computing)",
            "Stateful_firewall",
            "Network_address_translation",
            "Deep_packet_inspection",
            "Packet_analyzer",
            "Proxy_server",
            "Port_forwarding",
        ),
    },
    "application-sandboxing": {
        "tags": [
            "application sandboxing",
            "seccomp filtering",
            "apparmor profile",
            "security enhanced linux",
            "capability based security",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Sandbox_(software_development)",
            "Seccomp",
            "AppArmor",
            "Security-Enhanced_Linux",
            "Capability-based_security",
            "Address_space_layout_randomization",
        ),
    },
    "container-security": {
        "tags": [
            "container security",
            "docker security",
            "kubernetes security",
            "linux namespaces",
            "hypervisor isolation",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Container_(virtualization)",
            "Docker_(software)",
            "Kubernetes",
            "Linux_namespaces",
            "Hypervisor",
        )
        + [
            OWASP_CS + "Docker_Security_Cheat_Sheet.html",
            OWASP_CS + "Kubernetes_Security_Cheat_Sheet.html",
        ],
    },
    "cloud-security-posture": {
        "tags": [
            "cloud computing security",
            "cloud access security broker",
            "infrastructure as code",
            "cloud workload protection",
            "shared responsibility model",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cloud_computing_security",
            "Cloud_access_security_broker",
            "Infrastructure_as_code",
            "Cloud_workload_protection_platform",
            "Shared_responsibility_model",
            "FedRAMP",
            "Virtual_machine",
        ),
    },
    "multi-factor-authentication": {
        "tags": [
            "multi factor authentication",
            "time based one time password",
            "hmac based one time password",
            "hardware security token",
            "smart card authentication",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Multi-factor_authentication",
            "Time-based_one-time_password",
            "HMAC-based_one-time_password",
            "Security_token",
            "Smart_card",
            "Biometrics",
        )
        + [OWASP_CS + "Multifactor_Authentication_Cheat_Sheet.html"],
    },
    "single-sign-on": {
        "tags": [
            "single sign on",
            "security assertion markup language",
            "openid connect",
            "federated identity",
            "oauth authorization",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Single_sign-on",
            "Security_Assertion_Markup_Language",
            "OpenID_Connect",
            "Federated_identity",
            "OAuth",
            "JSON_Web_Token",
        )
        + [OWASP_CS + "SAML_Security_Cheat_Sheet.html"],
    },
    "audit-logging": {
        "tags": [
            "audit logging",
            "audit trail",
            "log management",
            "non repudiation",
            "information security audit",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Audit_trail",
            "Log_management",
            "Syslog",
            "Nonrepudiation",
            "Information_security_audit",
            "Internal_control",
        )
        + [OWASP_CS + "Logging_Cheat_Sheet.html"],
    },
    "gdpr-compliance": {
        "tags": [
            "gdpr compliance",
            "general data protection regulation",
            "right to be forgotten",
            "personal data protection",
            "data protection officer",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "General_Data_Protection_Regulation",
            "Data_Protection_Directive",
            "Personal_data",
            "Right_to_be_forgotten",
            "Data_Protection_Officer",
            "Privacy_by_design",
            "Pseudonymization",
        ),
    },
    "hipaa-compliance": {
        "tags": [
            "hipaa compliance",
            "protected health information",
            "medical privacy",
            "personally identifiable information",
            "health data protection",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Health_Insurance_Portability_and_Accountability_Act",
            "Protected_health_information",
            "Medical_privacy",
            "Personally_identifiable_information",
            "Information_privacy",
            "Data_anonymization",
        ),
    },
    "pci-dss": {
        "tags": [
            "pci dss",
            "payment card industry data security standard",
            "data tokenization",
            "card security code",
            "data masking",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Payment_Card_Industry_Data_Security_Standard",
            "Tokenization_(data_security)",
            "Card_security_code",
            "Data_masking",
            "Regulatory_compliance",
            "Encryption",
        ),
    },
    "iso-27001": {
        "tags": [
            "iso 27001",
            "iso 27002 controls",
            "information security management",
            "isms certification",
            "common criteria evaluation",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "ISO/IEC_27001",
            "ISO/IEC_27002",
            "Information_security_management",
            "ISO/IEC_27000-series",
            "Common_Criteria",
            "Certified_Information_Systems_Security_Professional",
        ),
    },
    "soc2-compliance": {
        "tags": [
            "soc 2 compliance",
            "system and organization controls",
            "service organization audit",
            "regulatory compliance",
            "internal control framework",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "System_and_Organization_Controls",
            "American_Institute_of_Certified_Public_Accountants",
            "Regulatory_compliance",
            "Internal_control",
            "Information_security_audit",
            "Governance,_risk_management,_and_compliance",
        ),
    },
    "security-hardening": {
        "tags": [
            "security hardening",
            "system hardening baseline",
            "defense in depth",
            "attack surface reduction",
            "data execution prevention",
        ],
        "license": CC_BY_SA,
        "pages": wiki(
            "Hardening_(computing)",
            "Defense_in_depth_(computing)",
            "Attack_surface",
            "Principle_of_least_privilege",
            "Data_execution_prevention",
            "Address_space_layout_randomization",
        ),
    },
}

# License constants imported for registry consistency; OWASP cheat-sheet pages
# carry OWASP == CC-BY-SA-4.0. PD kept available for future public-domain refs.
_ = (OWASP, PD)
