"""Advanced real-time rendering, codecs, audio DSP, and 3D geometry."""

from .common import CC_BY_SA, wiki

DOMAINS = {
    "temporal-antialiasing": {
        "tags": ["temporal antialiasing", "taa rendering", "temporal reprojection", "motion vector rendering"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Temporal_anti-aliasing",
            "Spatial_anti-aliasing",
            "Supersampling",
            "Rendering_(computer_graphics)",
            "Motion_vector",
            "Deferred_shading",
            "Motion_estimation",
        ),
    },
    "screen-space-reflections": {
        "tags": ["screen space reflections", "ssr rendering", "screen space raymarching", "reflection rendering"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Screen_space_reflections",
            "Screen_space",
            "Reflection_(computer_graphics)",
            "Cube_mapping",
            "Fresnel_equations",
            "Ray_marching",
            "Deferred_shading",
        ),
    },
    "screen-space-ao": {
        "tags": ["screen space ambient occlusion", "ssao rendering", "contact shadow ao", "depth buffer occlusion"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Screen_space_ambient_occlusion",
            "Ambient_occlusion",
            "Depth_map",
            "Global_illumination",
            "Z-buffering",
            "Shader",
        ),
    },
    "voxel-global-illumination": {
        "tags": ["voxel global illumination", "voxel cone tracing", "sparse voxel octree gi", "voxel radiance"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cone_tracing",
            "Voxel",
            "Sparse_voxel_octree",
            "Global_illumination",
            "Radiosity_(computer_graphics)",
            "Light_transport_theory",
            "Octree",
        ),
    },
    "light-probes": {
        "tags": ["light probe capture", "spherical harmonic lighting", "irradiance probe", "precomputed radiance transfer"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Spherical_harmonic_lighting",
            "Spherical_harmonics",
            "Irradiance",
            "Precomputed_Radiance_Transfer",
            "Environment_mapping",
            "Cube_map",
        ),
    },
    "irradiance-volumes": {
        "tags": ["irradiance volume", "volumetric light grid", "diffuse global illumination cache", "light field probe"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Light_field",
            "Volume_rendering",
            "Global_illumination",
            "Interpolation",
            "Trilinear_interpolation",
            "Spherical_harmonics",
        ),
    },
    "clustered-shading": {
        "tags": ["clustered shading", "tiled deferred shading", "light culling clusters", "clustered forward shading"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Tiled_rendering",
            "Deferred_shading",
            "G-buffer",
            "Frustum_culling",
            "Viewing_frustum",
            "Rendering_(computer_graphics)",
        ),
    },
    "forward-plus-rendering": {
        "tags": ["forward plus rendering", "tiled forward rendering", "light culling forward", "depth prepass rendering"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Tiled_rendering",
            "Hidden-surface_determination",
            "Z-buffering",
            "Frustum_culling",
            "Fixed-function",
            "Rendering_(computer_graphics)",
        ),
    },
    "gpu-driven-rendering": {
        "tags": ["gpu driven rendering", "indirect draw call", "gpu culling pipeline", "compute shader culling"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Frustum_culling",
            "Viewing_frustum",
            "Rasterisation",
            "Primitive_(geometry)",
            "Rendering_(computer_graphics)",
            "Shader",
        ),
    },
    "mesh-shaders": {
        "tags": ["mesh shader pipeline", "meshlet rendering", "amplification shader", "task shader geometry"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Mesh_shader",
            "Geometry_shader",
            "Vertex_shader",
            "Primitive_(geometry)",
            "Rasterisation",
            "Polygon_mesh",
        ),
    },
    "virtual-geometry-nanite": {
        "tags": ["virtual geometry rendering", "nanite virtualized geometry", "cluster level of detail", "micropolygon rendering"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Level_of_detail_(computer_graphics)",
            "Polygon_mesh",
            "Impostor_(computer_graphics)",
            "Rasterisation",
            "Rendering_(computer_graphics)",
            "Primitive_(geometry)",
        ),
    },
    "virtual-texturing": {
        "tags": ["virtual texturing", "megatexture streaming", "sparse texture residency", "texture streaming pipeline"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Texture_streaming",
            "Megatexture",
            "Texture_mapping",
            "Clipmap",
            "Mipmap",
            "Depth_map",
        ),
    },
    "sparse-voxel-octree": {
        "tags": ["sparse voxel octree", "svo raytracing", "voxel octree traversal", "hierarchical voxel structure"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Sparse_voxel_octree",
            "Octree",
            "Voxel",
            "Ray_casting",
            "Volume_rendering",
            "Cone_tracing",
        ),
    },
    "signed-distance-fields": {
        "tags": ["signed distance field", "sdf raymarching", "distance transform rendering", "sdf isosurface"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Signed_distance_function",
            "Distance_transform",
            "Isosurface",
            "Marching_cubes",
            "Ray_marching",
            "Ray_casting",
        ),
    },
    "volumetric-rendering": {
        "tags": ["volumetric rendering", "volume ray marching", "participating media rendering", "radiative transfer volume"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Volume_rendering",
            "Radiative_transfer",
            "Ray_marching",
            "Ray_casting",
            "Isosurface",
            "Rendering_(computer_graphics)",
        ),
    },
    "subsurface-scattering": {
        "tags": ["subsurface scattering", "translucent material rendering", "skin shading scattering", "diffusion profile rendering"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Subsurface_scattering",
            "Bidirectional_scattering_distribution_function",
            "Skin",
            "Translucency",
            "Radiative_transfer",
            "Refraction",
        ),
    },
    "image-based-lighting": {
        "tags": ["image based lighting", "environment map lighting", "reflection probe ibl", "hdr environment map"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Image-based_lighting",
            "Reflection_mapping",
            "Environment_mapping",
            "Cube_map",
            "High-dynamic-range_rendering",
            "Radiance",
        ),
    },
    "tone-mapping-hdr": {
        "tags": ["hdr tone mapping", "tone mapping operator", "perceptual quantizer hdr", "hdr display mapping"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Tone_mapping",
            "High-dynamic-range_rendering",
            "Perceptual_quantizer",
            "Rec._2100",
            "Radiance",
            "Display_device",
            "Exposure_(photography)",
        ),
    },
    "bloom-effect": {
        "tags": ["bloom shader effect", "light bloom rendering", "gaussian blur bloom", "glare post-processing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Bloom_(shader_effect)",
            "Gaussian_blur",
            "Convolution",
            "Glare_(vision)",
            "High-dynamic-range_rendering",
            "Radiance",
        ),
    },
    "motion-blur-rendering": {
        "tags": ["motion blur rendering", "per-object motion blur", "shutter speed blur", "velocity buffer blur"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Motion_blur",
            "Shutter_speed",
            "Rolling_shutter",
            "Motion_vector",
            "Gaussian_blur",
            "Exposure_(photography)",
        ),
    },
    "depth-of-field-rendering": {
        "tags": ["depth of field rendering", "bokeh depth of field", "circle of confusion blur", "lens defocus rendering"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Depth_of_field",
            "Circle_of_confusion",
            "Bokeh",
            "Focus_(optics)",
            "Gaussian_blur",
            "Exposure_(photography)",
        ),
    },
    "denoising-raytracing": {
        "tags": ["ray tracing denoising", "monte carlo denoiser", "spatiotemporal denoising", "noise reduction rendering"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Denoising",
            "Noise_reduction",
            "Total_variation_denoising",
            "Monte_Carlo_method",
            "Importance_sampling",
            "Convolution",
        ),
    },
    "dlss-upscaling": {
        "tags": ["deep learning super sampling", "dlss upscaling", "neural image upscaling", "temporal upscaling reconstruction"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Deep_learning_super_sampling",
            "Video_scaler",
            "Image_scaling",
            "Convolutional_neural_network",
            "Supersampling",
            "Temporal_anti-aliasing",
        ),
    },
    "fsr-upscaling": {
        "tags": ["fidelityfx super resolution", "fsr upscaling", "spatial image upscaling", "lanczos resampling upscale"],
        "license": CC_BY_SA,
        "pages": wiki(
            "FidelityFX",
            "Image_scaling",
            "Lanczos_resampling",
            "Anti-aliasing",
            "Supersampling",
            "Video_scaler",
        ),
    },
    "variable-rate-shading": {
        "tags": ["variable rate shading", "foveated shading rate", "coarse pixel shading", "adaptive shading rate"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Foveated_rendering",
            "Shader",
            "Rasterisation",
            "Fixed-function",
            "Rendering_(computer_graphics)",
            "Mipmap",
        ),
    },
    "order-independent-transparency": {
        "tags": ["order independent transparency", "depth peeling transparency", "alpha blending order", "per-pixel linked list transparency"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Order-independent_transparency",
            "Alpha_compositing",
            "Transparency_and_translucency",
            "Painter%27s_algorithm",
            "Z-buffering",
            "Translucency",
        ),
    },
    "decal-rendering": {
        "tags": ["decal rendering", "deferred decal projection", "texture splatting decal", "screen space decal"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Decal",
            "Texture_splatting",
            "Texture_mapping",
            "Deferred_shading",
            "G-buffer",
            "Alpha_compositing",
        ),
    },
    "terrain-rendering": {
        "tags": ["terrain rendering", "heightmap terrain", "geometry clipmap terrain", "displacement terrain mesh"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Terrain_rendering",
            "Heightmap",
            "Digital_elevation_model",
            "Displacement_mapping",
            "Clipmap",
            "Level_of_detail_(computer_graphics)",
        ),
    },
    "ocean-rendering": {
        "tags": ["ocean rendering", "gerstner wave ocean", "fft ocean simulation", "ocean water surface"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ocean_dynamics",
            "Gerstner_wave",
            "Wind_wave",
            "Fast_Fourier_transform",
            "Fluid_animation",
            "Displacement_mapping",
        ),
    },
    "cloud-rendering-volumetric": {
        "tags": ["volumetric cloud rendering", "cloud raymarching", "atmospheric scattering cloud", "volumetric lighting cloud"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Volumetric_lighting",
            "Cloud",
            "Radiative_transfer",
            "Ray_marching",
            "Perlin_noise",
            "Ray_tracing_hardware",
        ),
    },
    "vvc-h266": {
        "tags": ["versatile video coding", "h.266 codec", "vvc coding tree unit", "vvc video compression"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Versatile_Video_Coding",
            "Coding_tree_unit",
            "High_Efficiency_Video_Coding",
            "Motion_compensation",
            "Inter_frame",
            "Intra-frame_coding",
        ),
    },
    "av2-codec": {
        "tags": ["aomedia av2", "av2 codec", "av1 successor codec", "royalty-free video coding"],
        "license": CC_BY_SA,
        "pages": wiki(
            "AV1",
            "AOMedia",
            "VP9",
            "Video_coding_format",
            "Motion_compensation",
            "Transform_coding",
        ),
    },
    "prores-codec": {
        "tags": ["apple prores codec", "prores intra-frame", "intermediate video codec", "prores digital intermediate"],
        "license": CC_BY_SA,
        "pages": wiki(
            "ProRes",
            "Apple_ProRes",
            "Intra-frame_coding",
            "Discrete_cosine_transform",
            "Chroma_subsampling",
            "Digital_intermediate",
        ),
    },
    "jpeg-xl": {
        "tags": ["jpeg xl image", "jxl codec", "jpeg xl lossless", "next-generation image codec"],
        "license": CC_BY_SA,
        "pages": wiki(
            "JPEG_XL",
            "JPEG",
            "Lossless_compression",
            "Lossy_compression",
            "Discrete_cosine_transform",
            "Image_file_format",
        ),
    },
    "audio-reverb-algorithms": {
        "tags": ["audio reverb algorithm", "artificial reverberation", "comb filter reverb", "reverberation dsp"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Reverberation",
            "Comb_filter",
            "All-pass_filter",
            "Delay_(audio_effect)",
            "Room_acoustics",
            "Reverberation_mapping",
        ),
    },
    "audio-equalization": {
        "tags": ["audio equalization", "parametric equalizer", "iir filter eq", "audio filter dsp"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Equalization_(audio)",
            "Filter_(signal_processing)",
            "Parametric_equalizer",
            "Infinite_impulse_response",
            "Q_factor",
            "Low-pass_filter",
        ),
    },
    "dynamic-range-compression": {
        "tags": ["dynamic range compression", "audio compressor dsp", "sidechain compression", "attack release envelope"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Dynamic_range_compression",
            "Audio_signal_processing",
            "Attack_time",
            "Sidechain",
            "Loudness",
            "Gain_(electronics)",
        ),
    },
    "audio-limiter": {
        "tags": ["audio limiter", "brickwall limiter", "peak limiting dsp", "audio clipping prevention"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Limiter",
            "Clipping_(audio)",
            "Loudness",
            "Peak_programme_meter",
            "Gain_(electronics)",
            "Dynamic_range_compression",
        ),
    },
    "convolution-reverb": {
        "tags": ["convolution reverb", "impulse response reverb", "fir convolution audio", "overlap add convolution"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Convolution_reverb",
            "Impulse_response",
            "Convolution",
            "Finite_impulse_response",
            "Overlap%E2%80%93add_method",
            "Room_acoustics",
        ),
    },
    "spatial-audio-hrtf": {
        "tags": ["hrtf spatial audio", "head related transfer function", "binaural audio rendering", "3d sound localization"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Head-related_transfer_function",
            "Sound_localization",
            "3D_audio_effect",
            "Binaural_recording",
            "Interaural_time_difference",
            "Sound_pressure",
        ),
    },
    "ambisonics": {
        "tags": ["ambisonics audio", "ambisonic sound field", "surround sound ambisonics", "spherical harmonic audio"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ambisonics",
            "Ambisonic_reproduction_systems",
            "Surround_sound",
            "Spherical_harmonics",
            "Sound_localization",
            "3D_audio_effect",
        ),
    },
    "wavetable-synthesis": {
        "tags": ["wavetable synthesis", "table lookup synthesis", "wavetable oscillator", "single-cycle waveform synthesis"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Wavetable_synthesis",
            "Table-lookup_synthesis",
            "Sound_synthesis",
            "Additive_synthesis",
            "Oscillator",
            "Aliasing",
        ),
    },
    "fm-synthesis": {
        "tags": ["fm synthesis", "frequency modulation synthesis", "phase modulation synthesis", "fm operator synthesis"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Frequency_modulation_synthesis",
            "Frequency_modulation",
            "Yamaha_DX7",
            "Phase_modulation",
            "Sound_synthesis",
            "Oscillator",
        ),
    },
    "granular-synthesis": {
        "tags": ["granular synthesis", "grain sound synthesis", "micromontage granular", "granular time stretching"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Granular_synthesis",
            "Micromontage",
            "Time_stretching",
            "Sound_synthesis",
            "Envelope_(music)",
            "Sampling_(signal_processing)",
        ),
    },
    "physical-modeling-synthesis": {
        "tags": ["physical modeling synthesis", "karplus strong synthesis", "digital waveguide synthesis", "string physical model"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Physical_modelling_synthesis",
            "Karplus%E2%80%93Strong_string_synthesis",
            "Digital_waveguide_synthesis",
            "Finite_difference",
            "Waveguide",
            "Sound_synthesis",
        ),
    },
    "midi-2": {
        "tags": ["midi 2.0 protocol", "midi 2 bidirectional", "midi capability inquiry", "general midi protocol"],
        "license": CC_BY_SA,
        "pages": wiki(
            "MIDI_2.0",
            "MIDI",
            "General_MIDI",
            "Musical_note",
            "Sequencer",
            "Waveform",
        ),
    },
    "audio-time-stretching": {
        "tags": ["audio time stretching", "phase vocoder stretching", "stft time stretch", "time scale modification audio"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Audio_time_stretching_and_pitch_scaling",
            "Phase_vocoder",
            "Short-time_Fourier_transform",
            "Time_stretching",
            "Waveform",
            "Sampling_(signal_processing)",
        ),
    },
    "pitch-shifting": {
        "tags": ["audio pitch shifting", "pitch shift dsp", "autotune pitch correction", "formant preserving pitch shift"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Pitch_shift",
            "Pitch_(music)",
            "Phase_vocoder",
            "Autotune",
            "Formant",
            "Short-time_Fourier_transform",
        ),
    },
    "nurbs-surfaces": {
        "tags": ["nurbs surface", "non-uniform rational b-spline", "nurbs control point", "b-spline surface modeling"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Non-uniform_rational_B-spline",
            "B-spline",
            "B%C3%A9zier_curve",
            "Spline_(mathematics)",
            "Control_point_(mathematics)",
            "Surface_(mathematics)",
        ),
    },
    "subdivision-surfaces": {
        "tags": ["subdivision surface", "catmull clark subdivision", "loop subdivision surface", "doo sabin subdivision"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Subdivision_surface",
            "Catmull%E2%80%93Clark_subdivision_surface",
            "Loop_subdivision_surface",
            "Doo%E2%80%93Sabin_subdivision_surface",
            "Polygon_mesh",
            "Spline_(mathematics)",
        ),
    },
    "voxel-modeling": {
        "tags": ["voxel modeling", "voxel volume element", "constructive solid geometry voxel", "voxel grid representation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Voxel",
            "Volume_element",
            "Constructive_solid_geometry",
            "3D_modeling",
            "Octree",
            "Volume_rendering",
        ),
    },
    "point-cloud-processing": {
        "tags": ["point cloud processing", "point cloud registration", "iterative closest point", "lidar point cloud"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Point_cloud",
            "Point_Cloud_Library",
            "Iterative_closest_point",
            "Lidar",
            "3D_scanning",
            "Marching_cubes",
        ),
    },
    "photogrammetry-3d": {
        "tags": ["photogrammetry 3d", "structure from motion", "bundle adjustment reconstruction", "epipolar geometry photogrammetry"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Photogrammetry",
            "Structure_from_motion",
            "Bundle_adjustment",
            "Epipolar_geometry",
            "Camera_resectioning",
            "Feature_(computer_vision)",
        ),
    },
    "marching-cubes": {
        "tags": ["marching cubes algorithm", "isosurface extraction", "scalar field polygonization", "level set surface extraction"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Marching_cubes",
            "Isosurface",
            "Scalar_field",
            "Contour_line",
            "Level_set",
            "Signed_distance_function",
        ),
    },
}
