"""Machine-learning frameworks, LLM tooling, and modern ML techniques."""

from .common import CC_BY_SA, WIKI, wiki

DOMAINS = {
    "tensorflow": {
        "tags": ["tensorflow framework", "deep learning framework", "google brain", "dataflow graph", "tpu accelerator"],
        "license": CC_BY_SA,
        "pages": wiki(
            "TensorFlow",
            "Google_Brain",
            "Deep_learning",
            "Tensor_processing_unit",
            "Automatic_differentiation",
            "Dataflow_programming",
            "Graphics_processing_unit",
        ),
    },
    "keras": {
        "tags": ["keras api", "neural network library", "high level api", "model training"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Keras",
            "Artificial_neural_network",
            "TensorFlow",
            "Deep_learning",
            "Transfer_learning",
            "Backpropagation",
        ),
    },
    "jax-ml": {
        "tags": ["jax library", "autograd differentiation", "just in time compilation", "numpy vectorization", "accelerator computing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "JAX_(software)",
            "Automatic_differentiation",
            "Just-in-time_compilation",
            "NumPy",
            "Vectorization_(mathematics)",
            "Tensor_processing_unit",
        ),
    },
    "huggingface-transformers": {
        "tags": ["hugging face", "transformers library", "pretrained model", "language model hub"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Hugging_Face",
            "Transformer_(deep_learning_architecture)",
            "Large_language_model",
            "BERT_(language_model)",
            "Generative_pre-trained_transformer",
            "Fine-tuning_(deep_learning)",
        ),
    },
    "langchain": {
        "tags": ["langchain framework", "llm application", "retrieval augmented generation", "prompt chaining", "ai agent"],
        "license": CC_BY_SA,
        "pages": wiki(
            "LangChain",
            "Large_language_model",
            "Prompt_engineering",
            "Retrieval-augmented_generation",
            "Software_agent",
            "Vector_database",
        ),
    },
    "llamaindex": {
        "tags": ["llamaindex framework", "data indexing", "retrieval augmented generation", "document retrieval", "knowledge base"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Retrieval-augmented_generation",
            "Large_language_model",
            "Vector_database",
            "Semantic_search",
            "Word_embedding",
            "Nearest_neighbor_search",
        ),
    },
    "onnx": {
        "tags": ["onnx format", "model interoperability", "inference engine", "neural network exchange"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Open_Neural_Network_Exchange",
            "Interoperability",
            "Inference_engine",
            "Deep_learning",
            "Artificial_neural_network",
            "Machine_learning",
        ),
    },
    "opencv": {
        "tags": ["opencv library", "computer vision", "image processing", "feature detection", "optical flow"],
        "license": CC_BY_SA,
        "pages": wiki(
            "OpenCV",
            "Computer_vision",
            "Digital_image_processing",
            "Feature_detection_(computer_vision)",
            "Optical_flow",
            "Camera_resectioning",
        ),
    },
    "spacy-nlp": {
        "tags": ["spacy library", "natural language processing", "named entity recognition", "dependency parsing", "part of speech"],
        "license": CC_BY_SA,
        "pages": wiki(
            "SpaCy",
            "Natural_language_processing",
            "Named-entity_recognition",
            "Part-of-speech_tagging",
            "Dependency_grammar",
            "Lemmatisation",
        ),
    },
    "nltk": {
        "tags": ["nltk toolkit", "text processing", "tokenization nlp", "stemming words", "wordnet lexicon"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Natural_Language_Toolkit",
            "Tokenization_(lexical_analysis)",
            "Stemming",
            "N-gram",
            "Bag-of-words_model",
            "WordNet",
            "Text_corpus",
        ),
    },
    "gensim": {
        "tags": ["gensim library", "topic modeling", "word embeddings", "latent semantic analysis", "document similarity"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Gensim",
            "Word2vec",
            "Latent_Dirichlet_allocation",
            "Topic_model",
            "Tf-idf",
            "Latent_semantic_analysis",
        ),
    },
    "xgboost": {
        "tags": ["xgboost library", "gradient boosting", "decision tree ensemble", "boosted trees", "tabular learning"],
        "license": CC_BY_SA,
        "pages": wiki(
            "XGBoost",
            "Gradient_boosting",
            "Decision_tree_learning",
            "Ensemble_learning",
            "Random_forest",
            "Boosting_(machine_learning)",
        ),
    },
    "lightgbm": {
        "tags": ["lightgbm library", "gradient boosting", "histogram binning", "leaf wise growth", "tabular learning"],
        "license": CC_BY_SA,
        "pages": wiki(
            "LightGBM",
            "Gradient_boosting",
            "Decision_tree_learning",
            "Histogram",
            "Feature_(machine_learning)",
            "Ensemble_learning",
        ),
    },
    "catboost": {
        "tags": ["catboost library", "gradient boosting", "categorical features", "ordered boosting", "tabular learning"],
        "license": CC_BY_SA,
        "pages": wiki(
            "CatBoost",
            "Gradient_boosting",
            "Categorical_variable",
            "Decision_tree_learning",
            "Overfitting",
            "Boosting_(machine_learning)",
        ),
    },
    "ray-framework": {
        "tags": ["ray framework", "distributed computing", "parallel execution", "distributed training", "task scheduling"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Distributed_computing",
            "Parallel_computing",
            "Reinforcement_learning",
            "Hyperparameter_optimization",
            "Orchestration_(computing)",
            "Message_passing",
        ),
    },
    "mlflow": {
        "tags": ["mlflow platform", "experiment tracking", "model registry", "ml lifecycle", "reproducible experiments"],
        "license": CC_BY_SA,
        "pages": wiki(
            "MLOps",
            "Reproducibility",
            "Experiment",
            "Version_control",
            "Pipeline_(computing)",
            "Hyperparameter_optimization",
        ),
    },
    "weights-and-biases": {
        "tags": ["weights and biases", "experiment tracking", "training visualization", "model monitoring", "hyperparameter sweep"],
        "license": CC_BY_SA,
        "pages": wiki(
            "MLOps",
            "Experiment",
            "Reproducibility",
            "Hyperparameter_optimization",
            "Data_visualization",
            "Machine_learning",
        ),
    },
    "dvc-versioning": {
        "tags": ["dvc tool", "data version control", "dataset versioning", "ml pipeline", "reproducible datasets"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Data_version_control",
            "Version_control",
            "Git",
            "Reproducibility",
            "Data_lineage",
            "Pipeline_(computing)",
        ),
    },
    "kubeflow": {
        "tags": ["kubeflow platform", "kubernetes orchestration", "ml pipeline", "model serving", "mlops workflow"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Kubeflow",
            "Kubernetes",
            "MLOps",
            "Orchestration_(computing)",
            "Pipeline_(computing)",
            "Distributed_computing",
        ),
    },
    "vllm": {
        "tags": ["vllm engine", "llm inference", "paged attention", "throughput serving", "gpu batching"],
        "license": CC_BY_SA,
        "pages": wiki(
            "VLLM",
            "Large_language_model",
            "Inference_engine",
            "Graphics_processing_unit",
            "Attention_(machine_learning)",
            "Transformer_(deep_learning_architecture)",
        ),
    },
    "ollama": {
        "tags": ["ollama runner", "local llm", "model quantization", "on device inference", "open weights model"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ollama",
            "Large_language_model",
            "Llama_(language_model)",
            "Quantization_(signal_processing)",
            "Inference_engine",
            "Open-source_artificial_intelligence",
        ),
    },
    "llama-cpp": {
        "tags": ["llama cpp", "gguf quantization", "cpu inference", "local llm", "ggml tensor"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Llama.cpp",
            "Llama_(language_model)",
            "Quantization_(signal_processing)",
            "Large_language_model",
            "Inference_engine",
            "Half-precision_floating-point_format",
        ),
    },
    "stable-diffusion": {
        "tags": ["stable diffusion", "text to image", "latent diffusion", "image generation", "generative model"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Stable_Diffusion",
            "Diffusion_model",
            "Text-to-image_model",
            "Latent_space",
            "Generative_artificial_intelligence",
            "U-Net",
        ),
    },
    "diffusers-library": {
        "tags": ["diffusers pipeline", "diffusion model", "noise scheduler", "denoising process", "generative imaging"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Diffusion_model",
            "Text-to-image_model",
            "Latent_space",
            "U-Net",
            "Autoencoder",
            "Generative_artificial_intelligence",
        ),
    },
    "pytorch-lightning": {
        "tags": ["pytorch lightning", "training loop", "boilerplate abstraction", "distributed training", "deep learning framework"],
        "license": CC_BY_SA,
        "pages": wiki(
            "PyTorch_Lightning",
            "PyTorch",
            "Backpropagation",
            "Deep_learning",
            "Distributed_computing",
            "Automatic_differentiation",
        ),
    },
    "fastai": {
        "tags": ["fastai library", "transfer learning", "high level api", "training deep networks", "pytorch wrapper"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Fast.ai",
            "PyTorch",
            "Transfer_learning",
            "Deep_learning",
            "Convolutional_neural_network",
            "Fine-tuning_(deep_learning)",
        ),
    },
    "yolo-detection": {
        "tags": ["yolo detection", "object detection", "single stage detector", "bounding box", "real time vision"],
        "license": CC_BY_SA,
        "pages": wiki(
            "You_Only_Look_Once",
            "Object_detection",
            "Convolutional_neural_network",
            "Region_Based_Convolutional_Neural_Networks",
            "Computer_vision",
            "Feature_detection_(computer_vision)",
        ),
    },
    "mediapipe": {
        "tags": ["mediapipe framework", "pose estimation", "gesture recognition", "on device vision", "real time perception"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Pose_(computer_vision)",
            "Gesture_recognition",
            "Computer_vision",
            "Facial_recognition_system",
            "Optical_flow",
            "Edge_computing",
        ),
    },
    "cuda-programming": {
        "tags": ["cuda programming", "gpu computing", "parallel kernel", "nvidia accelerator", "gpgpu"],
        "license": CC_BY_SA,
        "pages": wiki(
            "CUDA",
            "General-purpose_computing_on_graphics_processing_units",
            "Graphics_processing_unit",
            "Nvidia",
            "Parallel_algorithm",
            "SIMD",
        ),
    },
    "tensorrt": {
        "tags": ["tensorrt runtime", "inference optimization", "gpu acceleration", "model quantization", "low latency serving"],
        "license": CC_BY_SA,
        "pages": wiki(
            "TensorRT",
            "Inference_engine",
            "Graphics_processing_unit",
            "Quantization_(signal_processing)",
            "Nvidia",
            "CUDA",
        ),
    },
    "triton-inference": {
        "tags": ["triton server", "model serving", "inference deployment", "gpu batching", "multi model"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Inference_engine",
            "Graphics_processing_unit",
            "Deep_learning",
            "Orchestration_(computing)",
            "Distributed_computing",
            "CUDA",
        ),
    },
    "prompt-engineering": {
        "tags": ["prompt engineering", "in context learning", "chain of thought", "few shot prompting", "instruction tuning"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Prompt_engineering",
            "Language_model",
            "Chain-of-thought",
            "Large_language_model",
            "Few-shot_learning",
            "Zero-shot_learning",
        ),
    },
    "rag-systems": {
        "tags": ["rag pipeline", "retrieval augmented generation", "vector retrieval", "semantic search", "grounded generation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Retrieval-augmented_generation",
            "Vector_database",
            "Semantic_search",
            "Nearest_neighbor_search",
            "Cosine_similarity",
            "Sentence_embedding",
        ),
    },
    "llm-fine-tuning": {
        "tags": ["fine tuning llm", "parameter efficient", "instruction tuning", "domain adaptation", "supervised finetuning"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Fine-tuning_(deep_learning)",
            "Large_language_model",
            "Transfer_learning",
            "Foundation_model",
            "Self-supervised_learning",
            "Overfitting",
        ),
    },
    "model-quantization": {
        "tags": ["model quantization", "low precision", "integer inference", "post training quantization", "weight compression"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Quantization_(signal_processing)",
            "Half-precision_floating-point_format",
            "Bfloat16_floating-point_format",
            "Fixed-point_arithmetic",
            "Model_compression",
            "Inference_engine",
        ),
    },
    "model-embeddings": {
        "tags": ["vector embeddings", "word embedding", "sentence embedding", "representation learning", "latent vector"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Word_embedding",
            "Sentence_embedding",
            "Word2vec",
            "Latent_space",
            "Cosine_similarity",
            "Dimensionality_reduction",
        ),
    },
    "vector-search": {
        "tags": ["vector search", "nearest neighbor", "approximate search", "similarity search", "vector database"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Nearest_neighbor_search",
            "Vector_database",
            "Cosine_similarity",
            "Locality-sensitive_hashing",
            "Curse_of_dimensionality",
            "Semantic_search",
        ),
    },
    "rlhf": {
        "tags": ["rlhf alignment", "human feedback", "reward model", "policy optimization", "preference learning"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Reinforcement_learning_from_human_feedback",
            "Reinforcement_learning",
            "Proximal_policy_optimization",
            "Markov_decision_process",
            "Large_language_model",
            "Q-learning",
        ),
    },
    "gan-networks": {
        "tags": ["gan network", "generative adversarial", "discriminator generator", "adversarial training", "image synthesis"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Generative_adversarial_network",
            "Generative_artificial_intelligence",
            "Deep_learning",
            "Convolutional_neural_network",
            "Latent_space",
            "Unsupervised_learning",
        ),
    },
    "variational-autoencoder": {
        "tags": ["variational autoencoder", "latent variable", "encoder decoder", "generative model", "representation learning"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Variational_autoencoder",
            "Autoencoder",
            "Latent_space",
            "Dimensionality_reduction",
            "Generative_artificial_intelligence",
            "Unsupervised_learning",
        ),
    },
    "image-recognition": {
        "tags": ["image recognition", "image classification", "visual recognition", "convolutional network", "feature learning"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Computer_vision",
            "Statistical_classification",
            "Convolutional_neural_network",
            "Optical_character_recognition",
            "Facial_recognition_system",
            "Feature_detection_(computer_vision)",
        ),
    },
    "semantic-segmentation": {
        "tags": ["semantic segmentation", "pixel labeling", "scene parsing", "dense prediction", "image mask"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Image_segmentation",
            "Computer_vision",
            "U-Net",
            "Convolutional_neural_network",
            "Region_Based_Convolutional_Neural_Networks",
            "Digital_image_processing",
        ),
    },
    "object-detection": {
        "tags": ["object detection", "bounding box", "region proposal", "detection network", "localization vision"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Object_detection",
            "Region_Based_Convolutional_Neural_Networks",
            "You_Only_Look_Once",
            "Convolutional_neural_network",
            "Computer_vision",
            "Feature_detection_(computer_vision)",
        ),
    },
    "speech-recognition-ml": {
        "tags": ["speech recognition", "acoustic model", "voice transcription", "audio features", "spoken language"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Speech_recognition",
            "Whisper_(speech_recognition_system)",
            "Hidden_Markov_model",
            "Connectionist_temporal_classification",
            "Mel-frequency_cepstrum",
            "Spectrogram",
        ),
    },
    "recommender-systems": {
        "tags": ["recommender system", "collaborative filtering", "matrix factorization", "personalization", "cold start"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Recommender_system",
            "Collaborative_filtering",
            "Matrix_factorization_(recommender_systems)",
            "Cold_start_(recommender_systems)",
            "Cosine_similarity",
            "Dimensionality_reduction",
        ),
    },
    "time-series-forecasting": {
        "tags": ["time series", "forecasting model", "arima model", "seasonality trend", "exponential smoothing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Time_series",
            "Forecasting",
            "Autoregressive_integrated_moving_average",
            "Seasonality",
            "Exponential_smoothing",
            "Long_short-term_memory",
        ),
    },
    "anomaly-detection": {
        "tags": ["anomaly detection", "outlier detection", "novelty detection", "isolation forest", "fraud detection"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Anomaly_detection",
            "Outlier",
            "Novelty_detection",
            "Isolation_forest",
            "Local_outlier_factor",
            "Support_vector_machine",
        ),
    },
    "feature-engineering": {
        "tags": ["feature engineering", "feature selection", "feature scaling", "data preprocessing", "one hot encoding"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Feature_engineering",
            "Feature_selection",
            "Feature_scaling",
            "Data_preprocessing",
            "One-hot",
            "Dimensionality_reduction",
        ),
    },
    "model-evaluation": {
        "tags": ["model evaluation", "cross validation", "confusion matrix", "precision recall", "roc curve"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cross-validation_(statistics)",
            "Precision_and_recall",
            "Confusion_matrix",
            "Receiver_operating_characteristic",
            "F-score",
            "Mean_squared_error",
        ),
    },
    "hyperparameter-tuning": {
        "tags": ["hyperparameter tuning", "grid search", "random search", "bayesian optimization", "model selection"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Hyperparameter_optimization",
            "Hyperparameter_(machine_learning)",
            "Bayesian_optimization",
            "Random_search",
            "Cross-validation_(statistics)",
            "Gaussian_process",
        ),
    },
    "automl": {
        "tags": ["automl pipeline", "automated machine learning", "neural architecture search", "model selection", "auto tuning"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Automated_machine_learning",
            "Neural_architecture_search",
            "Hyperparameter_optimization",
            "Feature_selection",
            "Bayesian_optimization",
            "Model_selection",
        ),
    },
    "federated-learning": {
        "tags": ["federated learning", "decentralized training", "privacy preserving", "differential privacy", "edge training"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Federated_learning",
            "Differential_privacy",
            "Distributed_computing",
            "Edge_computing",
            "Data_anonymization",
            "Machine_learning",
        ),
    },
    "graph-neural-networks": {
        "tags": ["graph neural network", "message passing", "node embedding", "graph representation", "relational learning"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Graph_neural_network",
            "Graph_(abstract_data_type)",
            "Message_passing",
            "Adjacency_matrix",
            "Graph_theory",
            "Spectral_clustering",
        ),
    },
    "knowledge-distillation": {
        "tags": ["knowledge distillation", "teacher student", "model compression", "soft labels", "network pruning"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Knowledge_distillation",
            "Model_compression",
            "Pruning_(artificial_neural_network)",
            "Softmax_function",
            "Deep_learning",
            "Transfer_learning",
        ),
    },
    "mixture-of-experts": {
        "tags": ["mixture of experts", "sparse activation", "expert routing", "gating network", "conditional compute"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Mixture_of_experts",
            "Ensemble_learning",
            "Transformer_(deep_learning_architecture)",
            "Large_language_model",
            "Softmax_function",
            "Sparse_matrix",
        ),
    },
}
