"""Popular libraries across Rust, Go, Java, C++, and .NET ecosystems."""

from .common import CC_BY_SA, wiki

DOMAINS = {
    # ---- Rust ----------------------------------------------------------
    "tokio-async-rust": {
        "tags": ["tokio runtime", "rust async runtime", "async i/o rust", "tokio tasks"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Rust_(programming_language)",
            "Asynchronous_I/O",
            "Futures_and_promises",
            "Non-blocking_algorithm",
            "Event_loop",
            "Green_thread",
            "Coroutine",
        ) + ["https://docs.rs/tokio/latest/tokio/"],
    },
    "serde-rust": {
        "tags": ["serde serialization", "rust serde", "serde deserialize", "rust data format"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Rust_(programming_language)",
            "Serialization",
            "JSON",
            "Marshalling_(computer_science)",
            "Data_transformation",
            "Type_system",
            "Reflection_(computer_programming)",
        ) + ["https://docs.rs/serde/latest/serde/"],
    },
    "rayon-parallel": {
        "tags": ["rayon parallelism", "rust data parallelism", "rayon work stealing", "parallel iterator rust"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Rust_(programming_language)",
            "Parallel_computing",
            "Data_parallelism",
            "Work_stealing",
            "Thread_(computing)",
            "Multi-core_processor",
            "Loop-level_parallelism",
        ) + ["https://docs.rs/rayon/latest/rayon/"],
    },
    "clap-cli-rust": {
        "tags": ["clap cli", "rust argument parser", "command line parsing rust", "clap derive api"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Rust_(programming_language)",
            "Command-line_interface",
            "Command-line_argument_parsing",
            "Usage_message",
            "Getopt",
            "Standard_streams",
        ) + ["https://docs.rs/clap/latest/clap/"],
    },
    "reqwest-rust": {
        "tags": ["reqwest client", "rust http client", "reqwest requests", "reqwest async client"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Rust_(programming_language)",
            "Hypertext_Transfer_Protocol",
            "HTTP_client",
            "Representational_state_transfer",
            "URL",
            "Transport_Layer_Security",
            "Client%E2%80%93server_model",
        ) + ["https://docs.rs/reqwest/latest/reqwest/"],
    },
    "hyper-rust": {
        "tags": ["hyper http rust", "rust web server library", "http2 rust", "hyper http library"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Rust_(programming_language)",
            "Web_server",
            "HTTP/2",
            "Persistent_connection",
            "Network_socket",
            "Wire_protocol",
            "Web_API",
        ) + ["https://docs.rs/hyper/latest/hyper/"],
    },
    "diesel-orm-rust": {
        "tags": ["diesel orm", "rust orm library", "diesel query builder", "rust database schema"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Rust_(programming_language)",
            "Object%E2%80%93relational_mapping",
            "Relational_database",
            "SQL",
            "Query_language",
            "Prepared_statement",
            "Type_safety",
        ) + ["https://docs.rs/diesel/latest/diesel/"],
    },
    "sqlx-rust": {
        "tags": ["sqlx rust", "rust async database", "compile-time sql rust", "sqlx query macro"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Rust_(programming_language)",
            "Database",
            "Database_connection",
            "Connection_pool",
            "SQL",
            "Asynchronous_I/O",
            "Prepared_statement",
        ) + ["https://docs.rs/sqlx/latest/sqlx/"],
    },
    "anyhow-error-rust": {
        "tags": ["anyhow error handling", "rust error library", "anyhow context", "rust error propagation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Rust_(programming_language)",
            "Exception_handling",
            "Error_code",
            "Result_type",
            "Stack_trace",
            "Robustness_(computer_science)",
        ) + ["https://docs.rs/anyhow/latest/anyhow/"],
    },
    "thiserror-rust": {
        "tags": ["thiserror derive", "rust custom errors", "error enum rust", "thiserror macro"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Rust_(programming_language)",
            "Exception_handling",
            "Result_type",
            "Metaprogramming",
            "Code_generation_(compiler)",
            "Type_system",
        ) + ["https://docs.rs/thiserror/latest/thiserror/"],
    },
    "tonic-grpc-rust": {
        "tags": ["tonic grpc", "rust grpc library", "protobuf rust", "tonic service"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Rust_(programming_language)",
            "GRPC",
            "Remote_procedure_call",
            "Protocol_Buffers",
            "Interface_description_language",
            "HTTP/2",
        ) + ["https://docs.rs/tonic/latest/tonic/"],
    },
    "tracing-rust": {
        "tags": ["tracing rust", "rust structured logging", "async instrumentation rust", "tracing spans"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Rust_(programming_language)",
            "Tracing_(software)",
            "Logging_(computing)",
            "Observability_(software)",
            "Instrumentation_(computer_programming)",
            "Profiling_(computer_programming)",
        ) + ["https://docs.rs/tracing/latest/tracing/"],
    },
    "crossbeam-rust": {
        "tags": ["crossbeam concurrency", "rust lock-free", "concurrent channels rust", "crossbeam channel"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Rust_(programming_language)",
            "Lock-free_and_wait-free_algorithms",
            "Concurrent_data_structure",
            "Memory_barrier",
            "Message_passing",
            "Channel_(programming)",
        ) + ["https://docs.rs/crossbeam/latest/crossbeam/"],
    },
    "nom-parser-rust": {
        "tags": ["nom parser", "rust parser combinator", "byte parsing rust", "nom combinator library"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Rust_(programming_language)",
            "Parsing",
            "Parser_combinator",
            "Formal_grammar",
            "Recursive_descent_parser",
            "Lexical_analysis",
            "Backtracking",
        ) + ["https://docs.rs/nom/latest/nom/"],
    },
    "bevy-ecs-rust": {
        "tags": ["bevy engine", "rust ecs", "entity component system rust", "bevy game engine"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Rust_(programming_language)",
            "Entity_component_system",
            "Game_engine",
            "Data-oriented_design",
            "Scene_graph",
            "Game_programming",
        ) + ["https://docs.rs/bevy/latest/bevy/"],
    },

    # ---- Go ------------------------------------------------------------
    "gorilla-mux-go": {
        "tags": ["gorilla mux", "go http router", "url routing go", "gorilla toolkit"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Go_(programming_language)",
            "Router_(computing)",
            "URL_normalization",
            "Middleware",
            "Hypertext_Transfer_Protocol",
            "Web_framework",
        ),
    },
    "cobra-cli-go": {
        "tags": ["cobra cli", "go command line", "cobra subcommands", "cobra command tree"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Go_(programming_language)",
            "Command-line_interface",
            "Command-line_argument_parsing",
            "Usage_message",
            "Standard_streams",
            "Getopt",
        ),
    },
    "gin-web-go": {
        "tags": ["gin web framework", "go http framework", "gin middleware", "gin router go"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Go_(programming_language)",
            "Web_framework",
            "Middleware",
            "Representational_state_transfer",
            "Model%E2%80%93view%E2%80%93controller",
            "Web_API",
        ),
    },
    "echo-web-go": {
        "tags": ["echo framework", "go web server library", "echo routing", "echo http handler"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Go_(programming_language)",
            "Web_server",
            "Router_(computing)",
            "Hypertext_Transfer_Protocol",
            "Middleware",
            "Client%E2%80%93server_model",
        ),
    },
    "gorm-orm-go": {
        "tags": ["gorm orm", "go orm library", "gorm database", "gorm model struct"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Go_(programming_language)",
            "Object%E2%80%93relational_mapping",
            "Relational_database",
            "SQL",
            "Active_record_pattern",
            "Database_connection",
        ),
    },
    "viper-config-go": {
        "tags": ["viper config", "go configuration library", "config file go", "viper settings loader"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Go_(programming_language)",
            "Configuration_file",
            "Environment_variable",
            "YAML",
            "Software_configuration_management",
            "JSON",
        ),
    },
    "zap-logging-go": {
        "tags": ["zap logging", "go structured logging", "fast logger go", "zap logger go"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Go_(programming_language)",
            "Logging_(computing)",
            "Log_file",
            "Observability_(software)",
            "Log_management",
            "Data_logger",
        ),
    },
    "testify-go": {
        "tags": ["testify assertions", "go testing library", "mock testify", "testify suite"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Go_(programming_language)",
            "Unit_testing",
            "Assertion_(software_development)",
            "Mock_object",
            "Test_automation",
            "Test-driven_development",
        ),
    },
    "grpc-go-lib": {
        "tags": ["grpc go", "go rpc library", "protobuf go", "grpc streaming go"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Go_(programming_language)",
            "GRPC",
            "Remote_procedure_call",
            "Protocol_Buffers",
            "Interface_description_language",
            "HTTP/2",
        ),
    },
    "fasthttp-go": {
        "tags": ["fasthttp go", "go high performance http", "fasthttp server", "fasthttp request handler"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Go_(programming_language)",
            "Web_server_benchmarking",
            "Hypertext_Transfer_Protocol",
            "Persistent_connection",
            "Network_socket",
            "Non-blocking_algorithm",
        ),
    },

    # ---- Java ----------------------------------------------------------
    "spring-framework-lib": {
        "tags": ["spring framework", "java dependency injection", "spring ioc container", "spring bean container"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Java_(programming_language)",
            "Dependency_injection",
            "Inversion_of_control",
            "Aspect-oriented_programming",
            "Software_framework",
            "Enterprise_application_integration",
        ),
    },
    "jackson-json-java": {
        "tags": ["jackson json", "java json binding", "jackson databind", "jackson object mapper"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Java_(programming_language)",
            "JSON",
            "Serialization",
            "Data_binding",
            "Marshalling_(computer_science)",
            "Java_annotation",
        ),
    },
    "gson-json-java": {
        "tags": ["gson json", "java json library", "gson serialization", "gson type adapter"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Java_(programming_language)",
            "JSON",
            "Data_serialization",
            "Reflection_(computer_programming)",
            "Type_system",
            "Data_transfer_object",
        ),
    },
    "guava-java-lib": {
        "tags": ["guava library", "java core utilities", "guava collections", "guava immutable collections"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Java_(programming_language)",
            "Java_collections_framework",
            "Immutable_object",
            "Cache_(computing)",
            "Utility_software",
            "Library_(computing)",
        ),
    },
    "apache-commons-java": {
        "tags": ["apache commons", "java reusable components", "commons lang", "commons utilities java"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Java_(programming_language)",
            "Library_(computing)",
            "Utility_software",
            "String_(computer_science)",
            "Software_framework",
            "Boilerplate_code",
        ),
    },
    "junit5-java-lib": {
        "tags": ["junit5 testing", "java unit test framework", "junit jupiter", "junit jupiter api"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Java_(programming_language)",
            "Unit_testing",
            "XUnit",
            "Test_automation",
            "Assertion_(software_development)",
            "Test_fixture",
        ),
    },
    "mockito-java-lib": {
        "tags": ["mockito mocking", "java mock framework", "mockito stub", "mockito verify java"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Java_(programming_language)",
            "Mock_object",
            "Unit_testing",
            "Test-driven_development",
            "Software_testing",
            "Reflection_(computer_programming)",
        ),
    },
    "lombok-java-lib": {
        "tags": ["lombok annotations", "java boilerplate reduction", "lombok getter setter", "lombok data annotation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Java_(programming_language)",
            "Boilerplate_code",
            "Java_annotation",
            "Code_generation_(compiler)",
            "Accessor",
            "Mutator_method",
        ),
    },
    "netty-java-lib": {
        "tags": ["netty framework", "java async networking", "netty event loop", "netty channel pipeline"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Netty",
            "Java_(programming_language)",
            "Asynchronous_I/O",
            "Event_loop",
            "Network_socket",
            "Non-blocking_algorithm",
        ),
    },
    "okhttp-java-lib": {
        "tags": ["okhttp client", "java http client library", "okhttp connection pool", "okhttp interceptor"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Java_(programming_language)",
            "HTTP_client",
            "Hypertext_Transfer_Protocol",
            "Persistent_connection",
            "Connection_pool",
            "Transport_Layer_Security",
        ),
    },
    "retrofit-java-lib": {
        "tags": ["retrofit client", "java type-safe http", "retrofit rest", "retrofit service interface"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Java_(programming_language)",
            "Representational_state_transfer",
            "Web_API",
            "Client%E2%80%93server_model",
            "Java_annotation",
            "Interface_description_language",
        ),
    },
    "log4j-logging-java": {
        "tags": ["log4j logging", "java logging framework", "log4j appender", "log4j configuration"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Log4j",
            "Java_logging_framework",
            "Logging_(computing)",
            "Log_file",
            "Structured_data",
            "Observability_(software)",
        ),
    },
    "slf4j-logging-java": {
        "tags": ["slf4j facade", "java logging abstraction", "slf4j binding", "slf4j logger factory"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Java_(programming_language)",
            "Java_logging_framework",
            "Abstraction_layer",
            "Facade_pattern",
            "Logging_(computing)",
            "Log_management",
        ),
    },
    "micrometer-metrics-java": {
        "tags": ["micrometer metrics", "java application metrics", "micrometer meter registry", "micrometer registry"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Java_(programming_language)",
            "Software_metric",
            "Observability_(software)",
            "Performance_indicator",
            "Time_series",
            "Dashboard_(computing)",
        ),
    },

    # ---- C++ -----------------------------------------------------------
    "boost-cpp-lib": {
        "tags": ["boost libraries", "cpp peer-reviewed library", "boost header only", "boost smart pointers"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Boost_(C%2B%2B_libraries)",
            "C%2B%2B",
            "C%2B%2B_Standard_Library",
            "Generic_programming",
            "Template_(C%2B%2B)",
            "Smart_pointer",
        ),
    },
    "eigen-cpp-lib": {
        "tags": ["eigen library", "cpp linear algebra", "eigen matrix template", "eigen dense matrix"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Eigen_(C%2B%2B_library)",
            "C%2B%2B",
            "Linear_algebra",
            "Matrix_(mathematics)",
            "Numerical_linear_algebra",
            "Vector_space",
        ),
    },
    "opencv-cpp-lib": {
        "tags": ["opencv library", "cpp computer vision", "opencv image processing", "opencv feature detection"],
        "license": CC_BY_SA,
        "pages": wiki(
            "OpenCV",
            "C%2B%2B",
            "Computer_vision",
            "Digital_image_processing",
            "Feature_detection_(computer_vision)",
            "Object_detection",
        ),
    },
    "protobuf-cpp-lib": {
        "tags": ["protobuf cpp", "cpp serialization library", "protocol buffers cpp", "protobuf message schema"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Protocol_Buffers",
            "C%2B%2B",
            "Serialization",
            "Interface_description_language",
            "Wire_protocol",
            "Data_structure_alignment",
        ),
    },
    "grpc-cpp-lib": {
        "tags": ["grpc cpp", "cpp rpc framework", "grpc core", "grpc channel cpp"],
        "license": CC_BY_SA,
        "pages": wiki(
            "GRPC",
            "C%2B%2B",
            "Remote_procedure_call",
            "HTTP/2",
            "Inter-process_communication",
            "Interface_description_language",
        ),
    },
    "fmt-cpp-lib": {
        "tags": ["fmt library", "cpp string formatting", "fmt format spec", "fmt print library"],
        "license": CC_BY_SA,
        "pages": wiki(
            "C%2B%2B",
            "Printf_format_string",
            "String_interpolation",
            "Type_safety",
            "C%2B%2B_Standard_Library",
            "Generic_programming",
        ),
    },
    "spdlog-cpp-lib": {
        "tags": ["spdlog logging", "cpp fast logger", "header-only logging cpp", "spdlog sink"],
        "license": CC_BY_SA,
        "pages": wiki(
            "C%2B%2B",
            "Logging_(computing)",
            "Log_file",
            "Template_(C%2B%2B)",
            "Data_logger",
            "Structured_data",
        ),
    },
    "catch2-cpp-lib": {
        "tags": ["catch2 testing", "cpp test framework", "catch2 header only", "catch2 test cases"],
        "license": CC_BY_SA,
        "pages": wiki(
            "C%2B%2B",
            "Unit_testing",
            "Test_automation",
            "Assertion_(software_development)",
            "Test-driven_development",
            "C%2B%2B11",
        ),
    },
    "googletest-cpp-lib": {
        "tags": ["googletest framework", "cpp test suite", "gtest fixtures", "gtest assertions"],
        "license": CC_BY_SA,
        "pages": wiki(
            "C%2B%2B",
            "Software_testing",
            "Test_fixture",
            "Mock_object",
            "Code_coverage",
            "Regression_testing",
        ),
    },
    "abseil-cpp-lib": {
        "tags": ["abseil library", "cpp common libraries", "abseil augmented standard library", "abseil flat hash map"],
        "license": CC_BY_SA,
        "pages": wiki(
            "C%2B%2B",
            "C%2B%2B_Standard_Library",
            "Standard_library",
            "Hash_table",
            "String_(computer_science)",
            "C%2B%2B14",
        ),
    },
    "poco-cpp-lib": {
        "tags": ["poco libraries", "cpp portable components", "poco networking", "poco http server"],
        "license": CC_BY_SA,
        "pages": wiki(
            "C%2B%2B",
            "Network_programming",
            "Hypertext_Transfer_Protocol",
            "Network_socket",
            "Cross-platform_software",
            "Library_(computing)",
        ),
    },

    # ---- .NET ----------------------------------------------------------
    "aspnet-libs-dotnet": {
        "tags": ["aspnet core", "dotnet web framework", "aspnet middleware", "aspnet request pipeline"],
        "license": CC_BY_SA,
        "pages": wiki(
            "ASP.NET_Core",
            ".NET",
            "Web_application",
            "Model%E2%80%93view%E2%80%93controller",
            "Middleware",
            "Web_API",
        ),
    },
    "newtonsoft-json-dotnet": {
        "tags": ["newtonsoft json", "dotnet json library", "json.net serialization", "json.net converter"],
        "license": CC_BY_SA,
        "pages": wiki(
            ".NET",
            "JSON",
            "Serialization",
            "Data_binding",
            "Reflection_(computer_programming)",
            "C_Sharp_(programming_language)",
        ),
    },
    "dapper-orm-dotnet": {
        "tags": ["dapper micro-orm", "dotnet data mapper", "dapper query", "dapper sql mapper"],
        "license": CC_BY_SA,
        "pages": wiki(
            ".NET",
            "Data_mapper_pattern",
            "Object%E2%80%93relational_mapping",
            "SQL",
            "Prepared_statement",
            "Relational_database",
        ),
    },
    "serilog-dotnet-lib": {
        "tags": ["serilog logging", "dotnet structured logging", "serilog sink", "serilog structured events"],
        "license": CC_BY_SA,
        "pages": wiki(
            ".NET",
            "Logging_(computing)",
            "Log_file",
            "Structured_data",
            "Observability_(software)",
            "Log_management",
        ),
    },
    "automapper-dotnet-lib": {
        "tags": ["automapper mapping", "dotnet object mapping", "automapper dto", "automapper profile config"],
        "license": CC_BY_SA,
        "pages": wiki(
            ".NET",
            "Data_transfer_object",
            "Data_binding",
            "Convention_over_configuration",
            "Reflection_(computer_programming)",
            "C_Sharp_(programming_language)",
        ),
    },
    "mediatr-dotnet-lib": {
        "tags": ["mediatr library", "dotnet mediator pattern", "mediatr request handler", "mediatr notification"],
        "license": CC_BY_SA,
        "pages": wiki(
            ".NET",
            "Mediator_pattern",
            "Command_pattern",
            "Publish%E2%80%93subscribe_pattern",
            "Loose_coupling",
            "Software_design_pattern",
        ),
    },
    "xunit-dotnet-lib": {
        "tags": ["xunit testing", "dotnet unit test framework", "xunit fact theory", "xunit test collection"],
        "license": CC_BY_SA,
        "pages": wiki(
            ".NET",
            "XUnit",
            "Unit_testing",
            "Test_automation",
            "Assertion_(software_development)",
            "Test-driven_development",
        ),
    },
}
