"""Data visualization: chart types, visualization techniques, perception, and cartography."""

from .common import CC_BY_SA, wiki

DOMAINS = {
    "statistical-charts": {
        "tags": ["box plot", "violin plot", "statistical graphics", "distribution chart"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Box_plot",
            "Violin_plot",
            "Histogram",
            "Scatter_plot",
            "Statistical_graphics",
            "Bar_chart",
        ),
    },
    "bar-charts-variants": {
        "tags": ["bar chart", "grouped bars", "stacked bars", "pareto chart"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Grouped_bar_chart",
            "Stacked_bar_chart",
            "Pareto_chart",
            "Population_pyramid",
            "Bar_chart",
            "Marimekko",
        ),
    },
    "line-area-charts": {
        "tags": ["line chart", "area chart", "spline curve", "step chart"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Line_chart",
            "Area_chart",
            "Spline_interpolation",
            "Step_function",
            "Fan_chart_(statistics)",
            "Time_series",
        ),
    },
    "scatter-bubble-charts": {
        "tags": ["scatter plot", "bubble chart", "scatterplot smoothing", "local regression"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Scatterplot",
            "Bubble_chart",
            "Scatterplot_smoothing",
            "Local_regression",
            "Correlation",
            "Two-dimensional_space",
        ),
    },
    "pie-donut-charts": {
        "tags": ["pie chart", "donut chart", "circular layout", "part-to-whole"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Pie_chart",
            "Donut_chart",
            "Circular_layout",
            "Polar_coordinate_system",
            "Radial_tree",
            "Infographic",
        ),
    },
    "histogram-density": {
        "tags": ["kernel density", "density estimation", "probability density", "rug plot"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Kernel_density_estimation",
            "Density_estimation",
            "Probability_density_function",
            "Empirical_distribution_function",
            "Rug_plot",
            "Histogram",
        ),
    },
    "box-violin-plots": {
        "tags": ["box plot", "violin plot", "bagplot", "strip plot"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Bagplot",
            "Strip_plot",
            "Box_plot",
            "Violin_plot",
            "Cluster_analysis",
            "Ranking_(statistics)",
        ),
    },
    "heatmap-viz": {
        "tags": ["heat map", "cluster analysis", "dendrogram", "correlation matrix"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Heat_map",
            "Cluster_analysis",
            "Dendrogram",
            "Correlation",
            "Contingency_table",
            "Lookup_table",
        ),
    },
    "contour-plots": {
        "tags": ["contour line", "level set", "isosurface", "marching squares"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Contour_line",
            "Level_set",
            "Isosurface",
            "Marching_squares",
            "Isoline_retrieval",
            "Two-dimensional_space",
        ),
    },
    "parallel-coordinates": {
        "tags": ["parallel coordinates", "andrews plot", "high dimensional", "multivariate plot"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Parallel_coordinates",
            "Andrews_plot",
            "Multidimensional_scaling",
            "Dimensionality_reduction",
            "Visual_variable",
            "Star_plot",
        ),
    },
    "radar-spider-charts": {
        "tags": ["radar chart", "star plot", "polar chart", "circular axes"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Radar_chart",
            "Star_plot",
            "Polar_coordinate_system",
            "Circular_layout",
            "Kite_(geometry)",
            "Visual_variable",
        ),
    },
    "treemap-viz": {
        "tags": ["treemapping", "nested rectangles", "voronoi treemap", "space filling"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Treemapping",
            "Nested_set_model",
            "Hierarchical_clustering",
            "Tree_structure",
            "Tree_(graph_theory)",
            "Cluster_analysis",
        ),
    },
    "sunburst-icicle": {
        "tags": ["sunburst chart", "icicle diagram", "radial hierarchy", "nested rings"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Sunburst_chart",
            "Radial_tree",
            "Nested_set_model",
            "Tree_structure",
            "Circular_layout",
            "Hierarchical_clustering",
        ),
    },
    "sankey-diagrams": {
        "tags": ["sankey diagram", "alluvial diagram", "flow diagram", "flux visualization"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Sankey_diagram",
            "Alluvial_diagram",
            "Flow_diagram",
            "Nested_set_model",
            "Directed_graph",
            "Graph_drawing",
        ),
    },
    "chord-diagrams": {
        "tags": ["chord diagram", "circos plot", "circular layout", "relationship matrix"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Chord_diagram_(information_visualization)",
            "Circos",
            "Circular_layout",
            "Adjacency_matrix",
            "RAWGraphs",
            "Radial_tree",
        ),
    },
    "network-graph-viz": {
        "tags": ["graph drawing", "vertex layout", "graph theory", "network diagram"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Graph_drawing",
            "Graph_theory",
            "Vertex_(graph_theory)",
            "Graph_(abstract_data_type)",
            "Directed_graph",
            "Influence_diagram",
        ),
    },
    "force-directed-layout": {
        "tags": ["force directed", "spring embedder", "force field", "physical simulation layout"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Force-directed_graph_drawing",
            "Force_field_(chemistry)",
            "Layered_graph_drawing",
            "Graph_drawing",
            "Vertex_(graph_theory)",
            "Tree_(graph_theory)",
        ),
    },
    "node-link-diagrams": {
        "tags": ["node link", "tree structure", "influence diagram", "vertex edge"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Tree_structure",
            "Influence_diagram",
            "Directed_graph",
            "Graph_(abstract_data_type)",
            "Vertex_(graph_theory)",
            "Layered_graph_drawing",
        ),
    },
    "adjacency-matrix-viz": {
        "tags": ["adjacency matrix", "contingency table", "matrix layout", "graph matrix"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Adjacency_matrix",
            "Contingency_table",
            "Correlation",
            "Heat_map",
            "Graph_theory",
            "Lookup_table",
        ),
    },
    "arc-diagrams": {
        "tags": ["arc diagram", "one dimensional layout", "circular layout", "node ordering"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Arc_diagram",
            "Circular_layout",
            "Layered_graph_drawing",
            "Graph_drawing",
            "Directed_graph",
            "Adjacency_matrix",
        ),
    },
    "dendrogram-viz": {
        "tags": ["dendrogram", "hierarchical clustering", "neighbor joining", "tree diagram"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Dendrogram",
            "Hierarchical_clustering",
            "Neighbor_joining",
            "Cluster_analysis",
            "Tree_(graph_theory)",
            "Radial_tree",
        ),
    },
    "hierarchical-edge-bundling": {
        "tags": ["edge bundling", "hierarchical layout", "radial tree", "circular layout"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Radial_tree",
            "Circular_layout",
            "Layered_graph_drawing",
            "Chord_diagram_(information_visualization)",
            "Force-directed_graph_drawing",
            "Tree_(graph_theory)",
        ),
    },
    "streamgraph": {
        "tags": ["streamgraph", "stacked area", "theme river", "flowing bands"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Streamgraph",
            "Area_chart",
            "Stacked_bar_chart",
            "Time_series",
            "Fan_chart_(statistics)",
            "Visual_variable",
        ),
    },
    "ridgeline-plots": {
        "tags": ["ridgeline plot", "joyplot", "overlapping density", "stacked distributions"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ridgeline_plot",
            "Kernel_density_estimation",
            "Density_estimation",
            "Small_multiple",
            "Probability_density_function",
            "Time_series",
        ),
    },
    "small-multiples": {
        "tags": ["small multiple", "trellis graph", "faceting", "panel chart"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Small_multiple",
            "Trellis_(graph)",
            "Faceting",
            "Visual_variable",
            "Data_visualization",
            "Statistical_graphics",
        ),
    },
    "choropleth-maps": {
        "tags": ["choropleth map", "thematic map", "shaded regions", "areal data"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Choropleth_map",
            "Thematic_map",
            "Cartography",
            "Statistical_graphics",
            "Color_scheme",
            "Data_binning",
        ),
    },
    "cartograms": {
        "tags": ["cartogram", "area distortion", "map deformation", "value by area"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cartogram",
            "Thematic_map",
            "Map_projection",
            "Choropleth_map",
            "Cartography",
            "Statistical_graphics",
        ),
    },
    "dot-density-maps": {
        "tags": ["dot distribution", "dasymetric map", "point density", "areal interpolation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Dot_distribution_map",
            "Dasymetric_map",
            "Thematic_map",
            "Cartography",
            "Choropleth_map",
            "Density_estimation",
        ),
    },
    "flow-maps": {
        "tags": ["flow map", "movement visualization", "origin destination", "geographic flow"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Flow_map",
            "Sankey_diagram",
            "Thematic_map",
            "Cartography",
            "Directed_graph",
            "Flow_diagram",
        ),
    },
    "proportional-symbol-maps": {
        "tags": ["proportional symbol", "graduated circles", "symbol scaling", "point symbol map"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Proportional_symbol_map",
            "Thematic_map",
            "Bubble_chart",
            "Cartography",
            "Visual_variable",
            "Choropleth_map",
        ),
    },
    "map-projections-viz": {
        "tags": ["map projection", "tissot indicatrix", "robinson projection", "winkel tripel"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Map_projection",
            "Tissot%27s_indicatrix",
            "Robinson_projection",
            "Winkel_tripel_projection",
            "Mercator_projection",
            "Cartography",
        ),
    },
    "hexbin-maps": {
        "tags": ["hexagonal binning", "data binning", "aggregate bins", "density gridding"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Data_binning",
            "RAWGraphs",
            "Two-dimensional_space",
            "Kernel_density_estimation",
            "Heat_map",
            "Choropleth_map",
        ),
    },
    "isopleth-maps": {
        "tags": ["isarithmic map", "isoline retrieval", "isopleth", "contour mapping"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Isarithmic_map",
            "Isoline_retrieval",
            "Isopleth",
            "Contour_line",
            "Thematic_map",
            "Level_set",
        ),
    },
    "gantt-charts-viz": {
        "tags": ["gantt chart", "project schedule", "pert chart", "task timeline"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Gantt_chart",
            "Program_evaluation_and_review_technique",
            "Timeline",
            "Chronology",
            "Directed_graph",
            "Time_series",
        ),
    },
    "timeline-viz": {
        "tags": ["timeline chart", "chronology", "temporal sequence", "event timeline"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Timeline",
            "Chronology",
            "Time_series",
            "Gantt_chart",
            "Infographic",
            "Data_visualization",
        ),
    },
    "calendar-heatmaps": {
        "tags": ["calendar heatmap", "temporal heat map", "daily grid", "seasonal pattern"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Heat_map",
            "Time_series",
            "Chronology",
            "Color_gradient",
            "Small_multiple",
            "Data_binning",
        ),
    },
    "waterfall-charts": {
        "tags": ["waterfall chart", "bridge chart", "cumulative contribution", "running total"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Waterfall_chart",
            "Bar_chart",
            "Stacked_bar_chart",
            "Time_series",
            "Statistical_graphics",
            "Visual_variable",
        ),
    },
    "funnel-charts": {
        "tags": ["funnel chart", "conversion stages", "pipeline visualization", "stage dropoff"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Funnel_chart",
            "Bar_chart",
            "Pareto_chart",
            "Infographic",
            "Statistical_graphics",
            "Visual_variable",
        ),
    },
    "bullet-graphs": {
        "tags": ["bullet graph", "kpi indicator", "gauge alternative", "target comparison"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Bullet_graph",
            "Bar_chart",
            "Dashboard_(business)",
            "Sparkline",
            "Data-ink_ratio",
            "Visual_variable",
        ),
    },
    "sparklines": {
        "tags": ["sparkline", "inline chart", "word sized graphic", "trend indicator"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Sparkline",
            "Line_chart",
            "Edward_Tufte",
            "Data-ink_ratio",
            "Time_series",
            "Small_multiple",
        ),
    },
    "candlestick-charts": {
        "tags": ["candlestick chart", "kagi chart", "price action", "financial ohlc"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Candlestick_chart",
            "Open-high-low-close_chart",
            "Kagi_chart",
            "Time_series",
            "Line_chart",
            "Bar_chart",
        ),
    },
    "ohlc-charts": {
        "tags": ["ohlc chart", "open high low close", "price bar", "financial time series"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Open-high-low-close_chart",
            "Kagi_chart",
            "Candlestick_chart",
            "Fan_chart_(statistics)",
            "Time_series",
            "Statistical_graphics",
        ),
    },
    "marimekko-charts": {
        "tags": ["marimekko chart", "mosaic plot", "contingency table", "variable width bars"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Marimekko",
            "Mosaic_plot",
            "Contingency_table",
            "Stacked_bar_chart",
            "Pareto_chart",
            "Statistical_graphics",
        ),
    },
    "slope-charts": {
        "tags": ["slope chart", "slope graph", "before after", "paired comparison"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Slope_chart",
            "Line_chart",
            "Rank_correlation",
            "Ranking_(statistics)",
            "Grade_(slope)",
            "Time_series",
        ),
    },
    "bump-charts": {
        "tags": ["bump chart", "rank correlation", "ranked positions", "ranking over time"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Rank_correlation",
            "Ranking_(statistics)",
            "Slope_chart",
            "Line_chart",
            "Time_series",
            "Parallel_coordinates",
        ),
    },
    "grammar-of-graphics": {
        "tags": ["grammar of graphics", "ggplot2", "semiology of graphics", "layered grammar"],
        "license": CC_BY_SA,
        "pages": wiki(
            "The_Grammar_of_Graphics",
            "Ggplot2",
            "Semiology_of_Graphics",
            "Jacques_Bertin",
            "Visual_variable",
            "Statistical_graphics",
        ),
    },
    "visual-encoding": {
        "tags": ["visual variable", "retinal variables", "graphic encoding", "bertin semiology"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Visual_variable",
            "Semiology_of_Graphics",
            "Jacques_Bertin",
            "Pre-attentive_processing",
            "Information_visualization",
            "Data_visualization",
        ),
    },
    "color-scales-viz": {
        "tags": ["color scheme", "color gradient", "color mapping", "false color"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Color_scheme",
            "Color_gradient",
            "Color_mapping",
            "False_color",
            "Lookup_table",
            "Colorfulness",
        ),
    },
    "sequential-diverging-palettes": {
        "tags": ["sequential palette", "diverging palette", "color scheme", "quantitative color"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Color_scheme",
            "Color_gradient",
            "CIELAB_color_space",
            "Color_space",
            "Choropleth_map",
            "False_color",
        ),
    },
    "perceptually-uniform-colormaps": {
        "tags": ["viridis colormap", "perceptual uniformity", "cielab space", "rainbow colormap"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Viridis",
            "CIELAB_color_space",
            "Color_space",
            "Rainbow",
            "Colorfulness",
            "Color_mapping",
        ),
    },
    "data-ink-ratio": {
        "tags": ["data ink ratio", "edward tufte", "chartjunk", "graphical excellence"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Data-ink_ratio",
            "Edward_Tufte",
            "Chartjunk",
            "Sparkline",
            "Misleading_graph",
            "Information_visualization",
        ),
    },
    "chart-junk": {
        "tags": ["chartjunk", "misleading graph", "lie factor", "graphical integrity"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Chartjunk",
            "Misleading_graph",
            "Edward_Tufte",
            "Data-ink_ratio",
            "Statistical_graphics",
            "Infographic",
        ),
    },
    "preattentive-attributes": {
        "tags": ["pre-attentive processing", "visual search", "feature integration", "preattentive cues"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Pre-attentive_processing",
            "Visual_search",
            "Feature_integration_theory",
            "Gestalt_psychology",
            "Information_visualization",
            "Visual_variable",
        ),
    },
    "gestalt-visualization": {
        "tags": ["gestalt psychology", "principles of grouping", "visual perception", "law of proximity"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Gestalt_psychology",
            "Principles_of_grouping",
            "Feature_integration_theory",
            "Visual_search",
            "Pre-attentive_processing",
            "Information_visualization",
        ),
    },
    "dashboard-design": {
        "tags": ["information dashboard", "business dashboard", "kpi display", "bullet graph"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Dashboard_(business)",
            "Bullet_graph",
            "Sparkline",
            "Data-ink_ratio",
            "Infographic",
            "Interactive_visualization",
        ),
    },
    "interactive-visualization": {
        "tags": ["interactive visualization", "interaction technique", "direct manipulation", "dynamic charts"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Interactive_visualization",
            "Interaction_technique",
            "Brushing_and_linking",
            "Information_visualization",
            "Data_visualization",
            "Fisheye_lens",
        ),
    },
    "brushing-linking": {
        "tags": ["brushing and linking", "coordinated views", "linked selection", "cross filtering"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Brushing_and_linking",
            "Interaction_technique",
            "Interactive_visualization",
            "Scatterplot",
            "Small_multiple",
            "Information_visualization",
        ),
    },
    "focus-plus-context": {
        "tags": ["focus plus context", "fisheye distortion", "hyperbolic tree", "detail overview"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Focus-plus-context_screen",
            "Fisheye_lens",
            "Hyperbolic_tree",
            "Interaction_technique",
            "Interactive_visualization",
            "Radial_tree",
        ),
    },
    "scatterplot-matrix": {
        "tags": ["scatterplot matrix", "pairwise plots", "correlation grid", "multivariate scatter"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Scatterplot",
            "Correlation",
            "Small_multiple",
            "Parallel_coordinates",
            "Multidimensional_scaling",
            "Rank_correlation",
        ),
    },
    "dimensionality-reduction-viz": {
        "tags": ["dimensionality reduction", "stochastic neighbor embedding", "principal component", "manifold projection"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Dimensionality_reduction",
            "T-distributed_stochastic_neighbor_embedding",
            "Principal_component_analysis",
            "Nonlinear_dimensionality_reduction",
            "Multidimensional_scaling",
            "Andrews_plot",
        ),
    },
}
