"""Hardware design, EDA, chip design, and microarchitecture."""
from .common import CC_BY_SA, WIKI, wiki

DOMAINS = {
    "systemverilog": {
        "tags": ["systemverilog language", "hardware verification language", "rtl verification", "hardware description language"],
        "license": CC_BY_SA,
        "pages": wiki("SystemVerilog", "Hardware_description_language", "Register-transfer_level",
                      "SystemVerilog_DPI", "Assertion_(software_development)", "Verilog"),
    },
    "uvm-verification": {
        "tags": ["uvm methodology", "universal verification methodology", "functional verification", "constrained random testing"],
        "license": CC_BY_SA,
        "pages": wiki("Universal_Verification_Methodology", "Functional_verification",
                      "Hardware_verification_language", "Random_testing", "Test_bench", "Fuzzing"),
    },
    "vhdl-design": {
        "tags": ["vhdl language", "vhdl design", "hardware description language", "rtl design"],
        "license": CC_BY_SA,
        "pages": wiki("VHDL", "IEEE_1076", "VHDL-AMS", "Register-transfer_level",
                      "Hardware_description_language", "Sequential_logic"),
    },
    "chisel-hdl": {
        "tags": ["chisel hardware language", "scala hardware", "risc-v cores", "rtl generation"],
        "license": CC_BY_SA,
        "pages": wiki("Chisel_(programming_language)", "Scala_(programming_language)",
                      "RISC-V", "Hardware_description_language", "Register-transfer_level",
                      "Reconfigurable_computing"),
    },
    "rtl-synthesis": {
        "tags": ["rtl synthesis", "logic synthesis", "technology mapping", "gate netlist"],
        "license": CC_BY_SA,
        "pages": wiki("Logic_synthesis", "Register-transfer_level", "Netlist",
                      "Gate_equivalent", "Standard_cell", "NAND_gate"),
    },
    "logic-synthesis": {
        "tags": ["logic minimization", "boolean function synthesis", "karnaugh map", "two-level logic"],
        "license": CC_BY_SA,
        "pages": wiki("Boolean_function", "Karnaugh_map", "Quine%E2%80%93McCluskey_algorithm",
                      "Espresso_heuristic_logic_minimizer", "Logic_synthesis",
                      "Combinational_logic"),
    },
    "place-and-route": {
        "tags": ["place and route", "chip placement", "detailed routing", "physical implementation"],
        "license": CC_BY_SA,
        "pages": wiki("Place_and_route", "Placement_(electronic_design_automation)",
                      "Routing_(electronic_design_automation)", "Floorplan_(microelectronics)",
                      "LEF/DEF", "Netlist"),
    },
    "static-timing-analysis": {
        "tags": ["static timing analysis", "timing closure", "clock skew", "propagation delay"],
        "license": CC_BY_SA,
        "pages": wiki("Static_timing_analysis", "Timing_closure", "Clock_skew",
                      "Propagation_delay", "Critical_path_method",
                      "Standard_Delay_Format"),
    },
    "clock-domain-crossing": {
        "tags": ["clock domain crossing", "flip-flop metastability", "synchronizer circuit", "asynchronous circuit"],
        "license": CC_BY_SA,
        "pages": wiki("Clock_domain_crossing", "Metastability_(electronics)",
                      "Synchronizer_(disambiguation)", "Asynchronous_circuit",
                      "Flip-flop_(electronics)", "Race_condition"),
    },
    "design-for-test": {
        "tags": ["design for test", "test pattern generation", "fault model", "built-in self-test"],
        "license": CC_BY_SA,
        "pages": wiki("Design_for_testing", "Automatic_test_pattern_generation",
                      "Fault_model", "Built-in_self-test", "Boundary_scan", "JTAG"),
    },
    "scan-chain": {
        "tags": ["scan chain", "scan flip-flop", "boundary scan", "jtag test access"],
        "license": CC_BY_SA,
        "pages": wiki("Scan_chain", "Flip-flop_(electronics)", "Boundary_scan",
                      "JTAG", "Design_for_testing", "Stuck-at_fault"),
    },
    "formal-equivalence-checking": {
        "tags": ["formal equivalence checking", "formal verification", "model checking", "boolean satisfiability"],
        "license": CC_BY_SA,
        "pages": wiki("Formal_equivalence_checking", "Formal_verification", "Model_checking",
                      "Binary_decision_diagram", "Boolean_satisfiability_problem",
                      "Counterexample"),
    },
    "gate-level-simulation": {
        "tags": ["gate-level simulation", "logic simulation", "discrete event simulation", "standard delay format"],
        "license": CC_BY_SA,
        "pages": wiki("Logic_simulation", "Discrete_event_simulation",
                      "Standard_Delay_Format", "Register-transfer_level", "Netlist",
                      "Timing_diagram"),
    },
    "standard-cell-library": {
        "tags": ["standard cell library", "liberty timing library", "gate equivalent", "cell characterization"],
        "license": CC_BY_SA,
        "pages": wiki("Standard_cell", "Gate_equivalent", "NAND_gate",
                      "Logic_synthesis", "Netlist", "Logic_gate"),
    },
    "physical-design-vlsi": {
        "tags": ["physical design flow", "vlsi layout", "integrated circuit layout", "design rule checking"],
        "license": CC_BY_SA,
        "pages": wiki("Physical_design_(electronics)", "Very_Large_Scale_Integration",
                      "Integrated_circuit_layout", "Design_rule_checking",
                      "Layout_versus_schematic", "GDSII"),
    },
    "floorplanning": {
        "tags": ["chip floorplanning", "die floorplan", "vlsi partitioning", "block placement"],
        "license": CC_BY_SA,
        "pages": wiki("Floorplan_(microelectronics)", "Physical_design_(electronics)",
                      "Placement_(electronic_design_automation)", "Integrated_circuit_layout",
                      "Very_Large_Scale_Integration", "Aspect_ratio_(image)"),
    },
    "power-analysis-vlsi": {
        "tags": ["power analysis vlsi", "clock gating", "power gating", "leakage power"],
        "license": CC_BY_SA,
        "pages": wiki("Clock_gating", "Power_gating", "Leakage_(electronics)",
                      "Dynamic_voltage_scaling", "CPU_power_dissipation",
                      "Power_optimization_(EDA)"),
    },
    "clock-tree-synthesis": {
        "tags": ["clock tree synthesis", "clock distribution network", "clock skew balancing", "h-tree topology"],
        "license": CC_BY_SA,
        "pages": wiki("Clock_distribution_network", "Clock_signal", "H_tree",
                      "Clock_skew", "Propagation_delay", "Delay_calculation"),
    },
    "spice-simulation": {
        "tags": ["spice simulation", "circuit simulation", "netlist analysis", "transistor modeling"],
        "license": CC_BY_SA,
        "pages": wiki("SPICE", "Circuit_simulation", "Netlist",
                      "Semiconductor_process_simulation", "Analogue_electronics",
                      "Nonlinear_system"),
    },
    "analog-circuit-design": {
        "tags": ["analog circuit design", "operational amplifier", "current mirror", "differential amplifier"],
        "license": CC_BY_SA,
        "pages": wiki("Analogue_electronics", "Operational_amplifier", "Current_mirror",
                      "Differential_amplifier", "Bandgap_voltage_reference",
                      "Analog_signal_processing"),
    },
    "mixed-signal-design": {
        "tags": ["mixed-signal design", "analog-to-digital converter", "digital-to-analog converter", "phase-locked loop"],
        "license": CC_BY_SA,
        "pages": wiki("Mixed-signal_integrated_circuit", "Analog-to-digital_converter",
                      "Digital-to-analog_converter", "Phase-locked_loop", "VHDL-AMS",
                      "Delta-sigma_modulation"),
    },
    "pcb-design": {
        "tags": ["pcb design", "printed circuit board", "surface-mount technology", "solder mask"],
        "license": CC_BY_SA,
        "pages": wiki("Printed_circuit_board", "Surface-mount_technology",
                      "Through-hole_technology", "Via_(electronics)", "Solder_mask",
                      "Gerber_format"),
    },
    "kicad-eda": {
        "tags": ["kicad software", "schematic capture", "gerber output", "open-source eda"],
        "license": CC_BY_SA,
        "pages": wiki("KiCad", "Schematic_capture", "Gerber_format",
                      "Comparison_of_EDA_software", "Printed_circuit_board",
                      "Electronic_design_automation"),
    },
    "altium-designer": {
        "tags": ["altium designer", "schematic capture", "pcb layout tool", "eda software comparison"],
        "license": CC_BY_SA,
        "pages": wiki("Altium_Designer", "Altium", "Schematic_capture",
                      "Comparison_of_EDA_software", "Printed_circuit_board",
                      "Surface-mount_technology"),
    },
    "signal-integrity": {
        "tags": ["signal integrity", "crosstalk noise", "eye diagram", "transmission line effects"],
        "license": CC_BY_SA,
        "pages": wiki("Signal_integrity", "Crosstalk", "Eye_pattern",
                      "Transmission_line", "Impedance_matching", "Reflection_(electrical)"),
    },
    "power-integrity": {
        "tags": ["power integrity", "decoupling capacitor", "ground bounce", "voltage regulator module"],
        "license": CC_BY_SA,
        "pages": wiki("Power_integrity", "Decoupling_capacitor", "Ground_bounce",
                      "Voltage_regulator_module", "Signal_integrity", "Return_loss"),
    },
    "emc-emi": {
        "tags": ["electromagnetic compatibility", "electromagnetic interference", "electromagnetic shielding", "ferrite bead"],
        "license": CC_BY_SA,
        "pages": wiki("Electromagnetic_compatibility", "Electromagnetic_interference",
                      "Electromagnetic_shielding", "Ferrite_bead", "Faraday_cage",
                      "Crosstalk"),
    },
    "high-speed-serdes": {
        "tags": ["high-speed serdes", "line encoding", "channel equalization", "clock data recovery"],
        "license": CC_BY_SA,
        "pages": wiki("SerDes", "8b/10b_encoding", "64b/66b_encoding",
                      "Equalization_(communications)", "Clock_recovery",
                      "Pulse-amplitude_modulation"),
    },
    "ddr-memory-interface": {
        "tags": ["ddr memory interface", "double data rate", "dram memory controller", "ddr5 sdram"],
        "license": CC_BY_SA,
        "pages": wiki("DDR_SDRAM", "Double_data_rate", "Dynamic_random-access_memory",
                      "Memory_controller", "DDR5_SDRAM", "DDR4_SDRAM"),
    },
    "pcie-interface": {
        "tags": ["pci express", "pcie root complex", "message signaled interrupts", "serial expansion bus"],
        "license": CC_BY_SA,
        "pages": wiki("PCI_Express", "Conventional_PCI", "Root_complex",
                      "Message_Signaled_Interrupts", "SerDes", "Serial_communication"),
    },
    "asic-design-flow": {
        "tags": ["asic design flow", "chip tape-out", "semiconductor ip core", "eda sign-off"],
        "license": CC_BY_SA,
        "pages": wiki("Application-specific_integrated_circuit", "Integrated_circuit_design",
                      "Semiconductor_intellectual_property_core", "Tape-out",
                      "Electronic_design_automation", "Multi-project_wafer_service"),
    },
    "chiplet-architecture": {
        "tags": ["chiplet architecture", "multi-chip module", "die-to-die interconnect", "2.5d integration"],
        "license": CC_BY_SA,
        "pages": wiki("Chiplet", "Multi-chip_module", "2.5D_integrated_circuit",
                      "Interposer", "Through-silicon_via", "Package_on_package"),
    },
    "system-in-package": {
        "tags": ["system in package", "wafer-level packaging", "ball grid array", "flip chip bonding"],
        "license": CC_BY_SA,
        "pages": wiki("System_in_package", "Wafer-level_packaging", "Ball_grid_array",
                      "Flip_chip", "Wire_bonding", "Multi-chip_module"),
    },
    "tsmc-process-node": {
        "tags": ["tsmc foundry", "semiconductor process node", "5 nm process", "pure-play foundry"],
        "license": CC_BY_SA,
        "pages": wiki("TSMC", "5_nm_process", "7_nm_process",
                      "Foundry_model", "Multi-project_wafer_service",
                      "Semiconductor_fabrication_plant"),
    },
    "semiconductor-fabrication": {
        "tags": ["semiconductor fabrication", "wafer fabrication plant", "silicon wafer processing", "chip manufacturing"],
        "license": CC_BY_SA,
        "pages": wiki("Semiconductor_device_fabrication", "Semiconductor_fabrication_plant",
                      "Wafer_(electronics)", "Etching_(microfabrication)",
                      "Semiconductor_process_simulation", "Chemical-mechanical_polishing",
                      "Ion_implantation"),
    },
    "photolithography": {
        "tags": ["semiconductor photolithography", "extreme ultraviolet lithography", "photomask fabrication", "photoresist patterning"],
        "license": CC_BY_SA,
        "pages": wiki("Photolithography", "Extreme_ultraviolet_lithography",
                      "Photomask", "Photoresist", "Etching_(microfabrication)",
                      "Immersion_lithography", "Deep_ultraviolet"),
    },
    "cmos-technology": {
        "tags": ["cmos technology", "mosfet transistor", "finfet device", "threshold voltage"],
        "license": CC_BY_SA,
        "pages": wiki("CMOS", "MOSFET", "FinFET", "Multigate_device",
                      "Threshold_voltage", "Silicon-on-insulator"),
    },
    "transistor-scaling": {
        "tags": ["transistor scaling", "dennard scaling", "moore's law", "gate-all-around transistor"],
        "license": CC_BY_SA,
        "pages": wiki("Dennard_scaling", "Moore%27s_law", "Die_shrink",
                      "Transistor_count", "Gate_all_around", "Transistor"),
    },
    "memory-hierarchy-design": {
        "tags": ["memory hierarchy design", "cpu cache levels", "translation lookaside buffer", "locality of reference"],
        "license": CC_BY_SA,
        "pages": wiki("Memory_hierarchy", "CPU_cache", "Cache_(computing)",
                      "Translation_lookaside_buffer", "Locality_of_reference",
                      "Memory_wall", "Cache_replacement_policies"),
    },
    "cpu-microarchitecture": {
        "tags": ["cpu microarchitecture", "instruction pipelining", "risc pipeline stages", "processor datapath"],
        "license": CC_BY_SA,
        "pages": wiki("Microarchitecture", "Instruction_pipelining", "Classic_RISC_pipeline",
                      "Register_renaming", "Reorder_buffer", "Instruction_cycle",
                      "Hazard_(computer_architecture)"),
    },
    "superscalar-execution": {
        "tags": ["superscalar execution", "out-of-order execution", "instruction-level parallelism", "tomasulo algorithm"],
        "license": CC_BY_SA,
        "pages": wiki("Superscalar_processor", "Out-of-order_execution",
                      "Instruction-level_parallelism", "Tomasulo%27s_algorithm",
                      "Very_long_instruction_word", "Scoreboarding"),
    },
    "branch-prediction-hw": {
        "tags": ["hardware branch prediction", "branch target predictor", "speculative execution", "branch misprediction penalty"],
        "license": CC_BY_SA,
        "pages": wiki("Branch_predictor", "Branch_prediction", "Branch_target_predictor",
                      "Speculative_execution", "Branch_misprediction", "Instruction_pipelining"),
    },
    "cache-coherence-protocol": {
        "tags": ["cache coherence protocol", "mesi protocol", "directory-based coherence", "bus snooping"],
        "license": CC_BY_SA,
        "pages": wiki("Cache_coherence", "MESI_protocol", "MOESI_protocol",
                      "Directory-based_cache_coherence", "Bus_snooping", "Memory_barrier"),
    },
    "gpu-microarchitecture": {
        "tags": ["gpu microarchitecture", "stream processing", "single instruction multiple threads", "shader cores"],
        "license": CC_BY_SA,
        "pages": wiki("Graphics_processing_unit", "Stream_processing",
                      "Single_instruction,_multiple_threads", "Shader", "CUDA",
                      "General-purpose_computing_on_graphics_processing_units"),
    },
    "tensor-processing-unit": {
        "tags": ["tensor processing unit", "ai accelerator hardware", "matrix multiplication engine", "hardware acceleration"],
        "license": CC_BY_SA,
        "pages": wiki("Tensor_Processing_Unit", "AI_accelerator", "Matrix_multiplication",
                      "Hardware_acceleration", "Systolic_array", "Deep_learning_processor",
                      "Multiply%E2%80%93accumulate_operation"),
    },
    "systolic-array": {
        "tags": ["systolic array", "dataflow architecture", "matrix multiplication hardware", "array processing"],
        "license": CC_BY_SA,
        "pages": wiki("Systolic_array", "Dataflow_architecture", "Array_processing",
                      "Parallel_computing", "Matrix_multiplication", "Convolutional_neural_network"),
    },
    "vector-processor": {
        "tags": ["vector processor", "array processing hardware", "cray supercomputer", "parallel computing"],
        "license": CC_BY_SA,
        "pages": wiki("Vector_processor", "Array_processing", "Cray-1",
                      "Parallel_computing", "Stream_processing", "Supercomputer"),
    },
    "simd-hardware": {
        "tags": ["simd hardware", "streaming simd extensions", "advanced vector extensions", "data parallelism"],
        "license": CC_BY_SA,
        "pages": wiki("SIMD", "Streaming_SIMD_Extensions", "Advanced_Vector_Extensions",
                      "ARM_architecture_family", "Parallel_computing", "Flynn%27s_taxonomy"),
    },
    "high-level-synthesis": {
        "tags": ["high-level synthesis", "systemc modeling", "behavioral synthesis", "c to hdl"],
        "license": CC_BY_SA,
        "pages": wiki("High-level_synthesis", "SystemC", "Behavioral_synthesis",
                      "C_to_HDL", "Logic_synthesis", "Register-transfer_level"),
    },
    "hardware-accelerator-design": {
        "tags": ["hardware accelerator design", "coprocessor architecture", "fpga acceleration", "digital signal processor"],
        "license": CC_BY_SA,
        "pages": wiki("Hardware_acceleration", "Coprocessor",
                      "Field-programmable_gate_array", "Digital_signal_processor",
                      "AI_accelerator", "Application-specific_instruction_set_processor"),
    },
    "network-on-chip": {
        "tags": ["network on chip", "on-chip interconnect", "router topology", "flow control hardware"],
        "license": CC_BY_SA,
        "pages": wiki("Network_on_a_chip", "Interconnect_(integrated_circuits)",
                      "Router_(computing)", "Network_topology", "Flow_control_(data)",
                      "Non-uniform_memory_access"),
    },
    "hbm-memory": {
        "tags": ["high bandwidth memory", "stacked dram", "through-silicon via", "silicon interposer"],
        "license": CC_BY_SA,
        "pages": wiki("High_Bandwidth_Memory", "HBM3", "Through-silicon_via",
                      "Memory_stack", "GDDR_SDRAM", "GDDR6_SDRAM"),
    },
}
