"""Molecular/cell biology, bioinformatics methods, neuroscience, and medical informatics."""
from .common import CC_BY_SA, wiki

DOMAINS = {
    "molecular-biology": {
        "tags": ["molecular biology", "dna replication", "gene expression", "central dogma"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Molecular_biology",
            "DNA_replication",
            "Transcription_(biology)",
            "Translation_(biology)",
            "Gene_expression",
            "Central_dogma_of_molecular_biology",
            "Messenger_RNA",
        ),
    },
    "cell-biology": {
        "tags": ["cell biology", "cell membrane", "cell cycle", "organelle structure"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cell_biology",
            "Cell_membrane",
            "Cell_nucleus",
            "Mitochondrion",
            "Endoplasmic_reticulum",
            "Cell_cycle",
            "Cytoskeleton",
        ),
    },
    "genetics-fundamentals": {
        "tags": ["genetics fundamentals", "mendelian inheritance", "genetic linkage", "allele frequency"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Genetics",
            "Mendelian_inheritance",
            "Allele",
            "Genotype",
            "Genetic_linkage",
            "Dominance_(genetics)",
            "Punnett_square",
        ),
    },
    "biochemistry": {
        "tags": ["biochemistry pathways", "metabolic pathway", "citric acid cycle", "amino acid structure"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Biochemistry",
            "Metabolism",
            "Citric_acid_cycle",
            "Glycolysis",
            "Amino_acid",
            "Adenosine_triphosphate",
            "Carbohydrate",
        ),
    },
    "enzymology": {
        "tags": ["enzyme kinetics", "michaelis menten", "enzyme catalysis", "enzyme inhibitor"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Enzyme",
            "Enzyme_kinetics",
            "Michaelis%E2%80%93Menten_kinetics",
            "Enzyme_catalysis",
            "Enzyme_inhibitor",
            "Cofactor_(biochemistry)",
            "Active_site",
        ),
    },
    "protein-structure": {
        "tags": ["protein structure", "secondary structure", "alpha helix", "beta sheet"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Protein_structure",
            "Protein_secondary_structure",
            "Alpha_helix",
            "Beta_sheet",
            "Protein_tertiary_structure",
            "Protein_domain",
            "Ramachandran_plot",
        ),
    },
    "protein-folding-bio": {
        "tags": ["protein folding", "levinthal paradox", "molecular chaperone", "protein misfolding"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Protein_folding",
            "Levinthal%27s_paradox",
            "Chaperone_(protein)",
            "Anfinsen%27s_dogma",
            "Molten_globule",
            "Proteopathy",
            "Hydrophobic_effect",
        ),
    },
    "genomics-biology": {
        "tags": ["genome organization", "human genome", "genome annotation", "noncoding dna"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Genome",
            "Human_genome",
            "Genome_project",
            "Non-coding_DNA",
            "Structural_variation",
            "Comparative_genomics",
            "Chromosome",
        ),
    },
    "transcriptomics": {
        "tags": ["transcriptome analysis", "gene expression profiling", "alternative splicing", "microarray analysis"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Transcriptome",
            "Transcriptomics_technologies",
            "Alternative_splicing",
            "DNA_microarray",
            "Expressed_sequence_tag",
            "Spliceosome",
            "Untranslated_region",
        ),
    },
    "proteomics-bio": {
        "tags": ["proteomics analysis", "mass spectrometry proteomics", "protein identification", "two dimensional gel"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Proteomics",
            "Mass_spectrometry",
            "Two-dimensional_gel_electrophoresis",
            "Tandem_mass_spectrometry",
            "Protein_mass_spectrometry",
            "Peptide_mass_fingerprinting",
            "Isotope-coded_affinity_tag",
        ),
    },
    "metabolomics": {
        "tags": ["metabolomics profiling", "metabolome analysis", "metabolic profiling", "small molecule metabolite"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Metabolomics",
            "Metabolome",
            "Metabolite",
            "Nuclear_magnetic_resonance_spectroscopy",
            "Metabolic_network",
            "Flux_(metabolism)",
            "Lipidomics",
        ),
    },
    "epigenetics": {
        "tags": ["epigenetic regulation", "dna methylation", "histone modification", "chromatin remodeling"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Epigenetics",
            "DNA_methylation",
            "Histone",
            "Chromatin",
            "Genomic_imprinting",
            "Histone_modification",
            "X-inactivation",
        ),
    },
    "crispr-gene-editing": {
        "tags": ["crispr gene editing", "cas9 nuclease", "guide rna", "genome editing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "CRISPR",
            "CRISPR_gene_editing",
            "Cas9",
            "Guide_RNA",
            "Genome_editing",
            "Zinc_finger_nuclease",
            "TALEN",
        ),
    },
    "pcr-amplification": {
        "tags": ["polymerase chain reaction", "pcr amplification", "reverse transcription pcr", "quantitative pcr"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Polymerase_chain_reaction",
            "Real-time_polymerase_chain_reaction",
            "Reverse_transcription_polymerase_chain_reaction",
            "DNA_polymerase",
            "Taq_polymerase",
            "Primer_(molecular_biology)",
            "Thermal_cycler",
        ),
    },
    "dna-sequencing-methods": {
        "tags": ["dna sequencing methods", "sanger sequencing", "chain termination", "shotgun sequencing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "DNA_sequencing",
            "Sanger_sequencing",
            "Shotgun_sequencing",
            "Maxam%E2%80%93Gilbert_sequencing",
            "Nucleic_acid_sequence",
            "Gel_electrophoresis",
            "Dideoxynucleotide",
        ),
    },
    "next-gen-sequencing": {
        "tags": ["next generation sequencing", "massively parallel sequencing", "sequencing by synthesis", "nanopore sequencing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Massive_parallel_sequencing",
            "Illumina_dye_sequencing",
            "Nanopore_sequencing",
            "Single-molecule_real-time_sequencing",
            "Pyrosequencing",
            "Coverage_(genetics)",
            "Read_(biology)",
        ),
    },
    "rna-sequencing": {
        "tags": ["rna sequencing", "single cell rna", "transcript quantification", "differential expression"],
        "license": CC_BY_SA,
        "pages": wiki(
            "RNA-Seq",
            "Single-cell_transcriptomics",
            "Small_RNA_sequencing",
            "Ribosome_profiling",
            "Complementary_DNA",
            "FPKM",
            "RNA_spike-in",
        ),
    },
    "gene-regulation": {
        "tags": ["gene regulation", "transcription factor", "promoter region", "operon control"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Regulation_of_gene_expression",
            "Transcription_factor",
            "Promoter_(genetics)",
            "Enhancer_(genetics)",
            "Operon",
            "Repressor",
            "Lac_operon",
        ),
    },
    "signal-transduction": {
        "tags": ["signal transduction", "cell signaling", "second messenger", "receptor kinase"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Signal_transduction",
            "Cell_signaling",
            "Second_messenger_system",
            "G_protein-coupled_receptor",
            "Protein_kinase",
            "MAPK/ERK_pathway",
            "Cyclic_adenosine_monophosphate",
        ),
    },
    "immunology": {
        "tags": ["immune system", "innate immunity", "immune response", "inflammation biology"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Immunology",
            "Immune_system",
            "Innate_immune_system",
            "Inflammation",
            "Complement_system",
            "Cytokine",
            "Phagocytosis",
        ),
    },
    "adaptive-immunity": {
        "tags": ["adaptive immunity", "t cell receptor", "b lymphocyte", "clonal selection"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Adaptive_immune_system",
            "T_cell",
            "B_cell",
            "Major_histocompatibility_complex",
            "Clonal_selection",
            "Immunological_memory",
            "Antigen_presentation",
        ),
    },
    "antibody-structure": {
        "tags": ["antibody structure", "immunoglobulin fold", "monoclonal antibody", "antigen binding"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Antibody",
            "Immunoglobulin_G",
            "Monoclonal_antibody",
            "Fragment_antigen-binding",
            "Complementarity-determining_region",
            "Isotype_(immunology)",
            "Epitope",
        ),
    },
    "virology": {
        "tags": ["virology fundamentals", "viral replication", "viral genome", "bacteriophage biology"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Virology",
            "Virus",
            "Viral_replication",
            "Bacteriophage",
            "Retrovirus",
            "Capsid",
            "Viral_envelope",
        ),
    },
    "microbiology": {
        "tags": ["microbiology fundamentals", "bacterial cell", "microbial growth", "gram staining"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Microbiology",
            "Bacteria",
            "Prokaryote",
            "Gram_stain",
            "Bacterial_cell_structure",
            "Biofilm",
            "Microbial_metabolism",
        ),
    },
    "bacterial-genetics": {
        "tags": ["bacterial genetics", "horizontal gene transfer", "bacterial conjugation", "plasmid biology"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Bacterial_genetics",
            "Horizontal_gene_transfer",
            "Bacterial_conjugation",
            "Plasmid",
            "Transformation_(genetics)",
            "Transduction_(genetics)",
            "Transposable_element",
        ),
    },
    "developmental-biology": {
        "tags": ["developmental biology", "embryonic development", "morphogen gradient", "body plan patterning"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Developmental_biology",
            "Embryonic_development",
            "Morphogen",
            "Gastrulation",
            "Homeobox",
            "Cell_differentiation",
            "Pattern_formation",
        ),
    },
    "stem-cell-biology": {
        "tags": ["stem cell biology", "pluripotent stem cell", "cellular reprogramming", "cell potency"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Stem_cell",
            "Embryonic_stem_cell",
            "Induced_pluripotent_stem_cell",
            "Cell_potency",
            "Adult_stem_cell",
            "Stem-cell_niche",
            "Regenerative_medicine",
        ),
    },
    "cancer-biology": {
        "tags": ["cancer biology", "tumor microenvironment", "metastasis biology", "hallmarks of cancer"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cancer",
            "Carcinogenesis",
            "Metastasis",
            "Tumor_microenvironment",
            "The_Hallmarks_of_Cancer",
            "Angiogenesis",
            "Neoplasm",
        ),
    },
    "oncogenes": {
        "tags": ["oncogene activation", "tumor suppressor", "proto oncogene", "cell cycle checkpoint"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Oncogene",
            "Tumor_suppressor_gene",
            "P53",
            "Ras_(protein)",
            "Retinoblastoma_protein",
            "Myc",
            "Cell_cycle_checkpoint",
        ),
    },
    "apoptosis": {
        "tags": ["programmed cell death", "apoptosis pathway", "caspase cascade", "cell death regulation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Apoptosis",
            "Programmed_cell_death",
            "Caspase",
            "Bcl-2_family",
            "Cytochrome_c",
            "Necrosis",
            "Autophagy",
        ),
    },
    "neuroscience-fundamentals": {
        "tags": ["neuroscience fundamentals", "nervous system", "central nervous system", "glial cell"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Neuroscience",
            "Nervous_system",
            "Central_nervous_system",
            "Peripheral_nervous_system",
            "Neuroglia",
            "Blood%E2%80%93brain_barrier",
            "Reflex_arc",
        ),
    },
    "neuron-biology": {
        "tags": ["neuron biology", "axon structure", "dendrite morphology", "myelin sheath"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Neuron",
            "Axon",
            "Dendrite",
            "Myelin",
            "Soma_(biology)",
            "Node_of_Ranvier",
            "Axon_terminal",
        ),
    },
    "synaptic-transmission": {
        "tags": ["synaptic transmission", "chemical synapse", "neurotransmitter release", "synaptic plasticity"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Synapse",
            "Chemical_synapse",
            "Neurotransmission",
            "Synaptic_vesicle",
            "Long-term_potentiation",
            "Excitatory_postsynaptic_potential",
            "Electrical_synapse",
        ),
    },
    "action-potential": {
        "tags": ["action potential", "membrane potential", "voltage gated channel", "ion channel gating"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Action_potential",
            "Membrane_potential",
            "Voltage-gated_ion_channel",
            "Resting_potential",
            "Depolarization",
            "Sodium_channel",
            "Hodgkin%E2%80%93Huxley_model",
        ),
    },
    "neural-circuits": {
        "tags": ["neural circuit", "neuronal network", "central pattern generator", "feedback inhibition"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Neural_circuit",
            "Central_pattern_generator",
            "Neural_pathway",
            "Lateral_inhibition",
            "Connectome",
            "Cortical_column",
            "Neuromodulation",
        ),
    },
    "neuroanatomy": {
        "tags": ["neuroanatomy structures", "cerebral cortex", "basal ganglia", "limbic system"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Neuroanatomy",
            "Cerebral_cortex",
            "Basal_ganglia",
            "Limbic_system",
            "Cerebellum",
            "Thalamus",
            "Hippocampus",
        ),
    },
    "neurotransmitters": {
        "tags": ["neurotransmitter systems", "dopamine signaling", "glutamate receptor", "gaba receptor"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Neurotransmitter",
            "Dopamine",
            "Serotonin",
            "Glutamate_(neurotransmitter)",
            "Gamma-Aminobutyric_acid",
            "Acetylcholine",
            "Norepinephrine",
        ),
    },
    "pharmacology": {
        "tags": ["pharmacology principles", "drug receptor", "dose response", "receptor agonist"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Pharmacology",
            "Pharmacodynamics",
            "Agonist",
            "Receptor_antagonist",
            "Dose%E2%80%93response_relationship",
            "Drug_metabolism",
            "Half-life",
        ),
    },
    "pharmacokinetics": {
        "tags": ["pharmacokinetics modeling", "drug absorption", "compartment model", "clearance rate"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Pharmacokinetics",
            "Absorption_(pharmacology)",
            "Volume_of_distribution",
            "Clearance_(pharmacology)",
            "Bioavailability",
            "First_pass_effect",
            "Elimination_(pharmacology)",
        ),
    },
    "drug-metabolism": {
        "tags": ["drug metabolism", "cytochrome p450", "phase i metabolism", "hepatic clearance"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Drug_metabolism",
            "Cytochrome_P450",
            "Phase_I_metabolism",
            "Glucuronidation",
            "First-pass_metabolism",
            "Enzyme_induction_and_inhibition",
            "Prodrug",
        ),
    },
    "toxicology": {
        "tags": ["toxicology principles", "dose response toxicity", "median lethal dose", "toxicokinetics analysis"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Toxicology",
            "Toxicity",
            "Median_lethal_dose",
            "Toxin",
            "Toxicokinetics",
            "Hepatotoxicity",
            "Poison",
        ),
    },
    "medical-imaging-modalities": {
        "tags": ["medical imaging", "diagnostic radiology", "image reconstruction", "digital imaging communications"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Medical_imaging",
            "Radiography",
            "DICOM",
            "Tomographic_reconstruction",
            "Fluoroscopy",
            "Contrast_agent",
            "Picture_archiving_and_communication_system",
        ),
    },
    "mri-physics": {
        "tags": ["magnetic resonance imaging", "mri physics", "spin relaxation", "pulse sequence"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Magnetic_resonance_imaging",
            "Physics_of_magnetic_resonance_imaging",
            "Relaxation_(NMR)",
            "MRI_pulse_sequence",
            "Functional_magnetic_resonance_imaging",
            "Diffusion_MRI",
            "Larmor_precession",
        ),
    },
    "ct-imaging": {
        "tags": ["computed tomography", "ct scan", "hounsfield unit", "filtered back projection"],
        "license": CC_BY_SA,
        "pages": wiki(
            "CT_scan",
            "Operation_of_computed_tomography",
            "Hounsfield_scale",
            "Radon_transform",
            "Cone_beam_computed_tomography",
            "Iterative_reconstruction",
            "X-ray",
        ),
    },
    "ultrasound-imaging": {
        "tags": ["medical ultrasonography", "ultrasound imaging", "doppler ultrasound", "acoustic impedance"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Medical_ultrasound",
            "Ultrasound",
            "Doppler_ultrasonography",
            "Acoustic_impedance",
            "Echocardiography",
            "Transducer",
            "Ultrasound_transducer",
        ),
    },
    "pet-imaging": {
        "tags": ["positron emission tomography", "pet imaging", "radiotracer imaging", "single photon emission"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Positron_emission_tomography",
            "Single-photon_emission_computed_tomography",
            "Radioactive_tracer",
            "Fluorodeoxyglucose_(18F)",
            "Nuclear_medicine",
            "Scintillator",
            "Positron",
        ),
    },
    "radiology-informatics": {
        "tags": ["radiology informatics", "imaging informatics", "radiology reporting", "computer aided diagnosis"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Medical_image_computing",
            "Computer-aided_diagnosis",
            "Image_registration",
            "Image_segmentation",
            "Radiomics",
            "Teleradiology",
            "Voxel",
        ),
    },
    "clinical-decision-support": {
        "tags": ["clinical decision support", "diagnostic decision", "medical expert system", "clinical guideline"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Clinical_decision_support_system",
            "Expert_system",
            "Medical_guideline",
            "Diagnosis",
            "Evidence-based_medicine",
            "Computerized_physician_order_entry",
            "Medical_algorithm",
        ),
    },
    "electronic-health-informatics": {
        "tags": ["electronic health record", "health informatics", "clinical data standard", "health information exchange"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Electronic_health_record",
            "Health_informatics",
            "Health_Level_7",
            "Fast_Healthcare_Interoperability_Resources",
            "Health_information_exchange",
            "SNOMED_CT",
            "Nursing_informatics",
        ),
    },
    "epidemiology-methods": {
        "tags": ["epidemiology methods", "cohort study", "case control study", "confidence interval"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Epidemiology",
            "Cohort_study",
            "Case%E2%80%93control_study",
            "Incidence_(epidemiology)",
            "Prevalence",
            "Relative_risk",
            "Confounding",
        ),
    },
    "biostatistics": {
        "tags": ["biostatistics methods", "survival analysis", "hypothesis testing", "statistical power"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Biostatistics",
            "Survival_analysis",
            "Statistical_hypothesis_testing",
            "Kaplan%E2%80%93Meier_estimator",
            "Statistical_power",
            "P-value",
            "Bonferroni_correction",
        ),
    },
    "clinical-trials-design": {
        "tags": ["clinical trial design", "randomized controlled trial", "double blind study", "trial endpoint"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Clinical_trial",
            "Randomized_controlled_trial",
            "Blinded_experiment",
            "Placebo",
            "Clinical_endpoint",
            "Phases_of_clinical_research",
            "Intention-to-treat_analysis",
        ),
    },
    "public-health-informatics": {
        "tags": ["public health informatics", "disease surveillance", "syndromic surveillance", "health data reporting"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Public_health_informatics",
            "Public_health_surveillance",
            "Syndromic_surveillance",
            "Notifiable_disease",
            "Global_Public_Health_Intelligence_Network",
            "Vaccination_policy",
            "Contact_tracing",
        ),
    },
    "genome-wide-association": {
        "tags": ["genome wide association", "gwas study", "single nucleotide polymorphism", "linkage disequilibrium"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Genome-wide_association_study",
            "Single-nucleotide_polymorphism",
            "Linkage_disequilibrium",
            "Manhattan_plot",
            "Polygenic_score",
            "Quantitative_trait_locus",
            "Haplotype",
        ),
    },
}
