"""Applied mathematics: special functions, transforms, numerical PDE, mathematical physics."""
from .common import CC_BY_SA, wiki

DOMAINS = {
    "special-functions": {
        "tags": ["special functions", "bessel functions", "gamma function", "error function"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Special_functions",
            "Bessel_function",
            "Gamma_function",
            "Legendre_polynomials",
            "Hypergeometric_function",
            "Error_function",
            "Airy_function",
            "Beta_function",
        ),
    },
    "orthogonal-polynomials": {
        "tags": ["orthogonal polynomials", "hermite polynomials", "chebyshev polynomials", "jacobi polynomials"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Orthogonal_polynomials",
            "Hermite_polynomials",
            "Laguerre_polynomials",
            "Chebyshev_polynomials",
            "Jacobi_polynomials",
            "Gegenbauer_polynomials",
            "Classical_orthogonal_polynomials",
            "Zernike_polynomials",
        ),
    },
    "bessel-functions": {
        "tags": ["bessel function", "spherical bessel function", "modified bessel function", "kelvin functions"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Bessel_function",
            "Spherical_Bessel_function",
            "Modified_Bessel_function",
            "Struve_function",
            "Kelvin_functions",
            "Neumann_series",
            "Sonine_formula",
            "Fourier%E2%80%93Bessel_series",
        ),
    },
    "gamma-beta-functions": {
        "tags": ["gamma function", "beta function", "digamma function", "incomplete gamma function"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Gamma_function",
            "Beta_function",
            "Incomplete_gamma_function",
            "Digamma_function",
            "Polygamma_function",
            "Stirling%27s_approximation",
            "Lanczos_approximation",
            "Multivariate_gamma_function",
        ),
    },
    "elliptic-functions": {
        "tags": ["elliptic function", "jacobi elliptic functions", "weierstrass elliptic function", "theta function"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Elliptic_function",
            "Jacobi_elliptic_functions",
            "Weierstrass_elliptic_function",
            "Elliptic_integral",
            "Theta_function",
            "Modular_lambda_function",
            "Dedekind_eta_function",
            "Lemniscate_elliptic_functions",
        ),
    },
    "hypergeometric-functions": {
        "tags": ["hypergeometric function", "confluent hypergeometric function", "pochhammer symbol", "hypergeometric series"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Hypergeometric_function",
            "Confluent_hypergeometric_function",
            "Generalized_hypergeometric_function",
            "Basic_hypergeometric_series",
            "Appell_series",
            "Pochhammer_symbol",
            "Meijer_G-function",
            "Barnes_integral",
        ),
    },
    "spherical-harmonics": {
        "tags": ["spherical harmonics", "associated legendre polynomials", "multipole expansion", "wigner d-matrix"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Spherical_harmonics",
            "Associated_Legendre_polynomials",
            "Vector_spherical_harmonics",
            "Solid_harmonics",
            "Wigner_D-matrix",
            "Clebsch%E2%80%93Gordan_coefficients",
            "Multipole_expansion",
            "Spherical_harmonic_lighting",
        ),
    },
    "laplace-transform": {
        "tags": ["laplace transform", "inverse laplace transform", "transfer function", "final value theorem"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Laplace_transform",
            "Inverse_Laplace_transform",
            "Two-sided_Laplace_transform",
            "Mellin%27s_inverse_formula",
            "Laplace%E2%80%93Stieltjes_transform",
            "Final_value_theorem",
            "Initial_value_theorem",
            "Transfer_function",
        ),
    },
    "z-transform": {
        "tags": ["z-transform", "bilinear transform", "region of convergence", "digital filter"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Z-transform",
            "Advanced_Z-transform",
            "Bilinear_transform",
            "Region_of_convergence",
            "Star_transform",
            "Discrete-time_Fourier_transform",
            "Digital_filter",
            "Zeros_and_poles",
        ),
    },
    "mellin-transform": {
        "tags": ["mellin transform", "mellin inversion theorem", "dirichlet series", "harmonic sum"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Mellin_transform",
            "Mellin_inversion_theorem",
            "Perron%27s_formula",
            "Ramanujan%27s_master_theorem",
            "Nachbin%27s_theorem",
            "Dirichlet_series",
            "Harmonic_sum",
        ),
    },
    "hankel-transform": {
        "tags": ["hankel transform", "abel transform", "struve function", "neumann series"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Hankel_transform",
            "Fourier%E2%80%93Bessel_series",
            "Struve_function",
            "Abel_transform",
            "Neumann_series",
            "Sonine_formula",
        ),
    },
    "radon-transform": {
        "tags": ["radon transform", "filtered back projection", "tomographic reconstruction", "projection-slice theorem"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Radon_transform",
            "Filtered_back_projection",
            "Tomographic_reconstruction",
            "X-ray_transform",
            "Projection-slice_theorem",
            "Funk_transform",
            "Cone_beam_reconstruction",
        ),
    },
    "integral-transforms": {
        "tags": ["integral transform", "hilbert transform", "hartley transform", "convolution theorem"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Integral_transform",
            "Fourier_transform",
            "Hilbert_transform",
            "Hartley_transform",
            "Wavelet_transform",
            "Stieltjes_transformation",
            "Convolution_theorem",
            "Kernel_(integral_operator)",
        ),
    },
    "generating-functions-deep": {
        "tags": ["generating function", "formal power series", "umbral calculus", "lagrange inversion theorem"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Generating_function",
            "Generating_function_transformation",
            "Formal_power_series",
            "Lagrange_inversion_theorem",
            "Symbolic_method_(combinatorics)",
            "Bell_polynomials",
            "Umbral_calculus",
            "Dirichlet_series",
        ),
    },
    "asymptotic-analysis": {
        "tags": ["asymptotic analysis", "asymptotic expansion", "steepest descent", "borel summation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Asymptotic_analysis",
            "Asymptotic_expansion",
            "Big_O_notation",
            "Watson%27s_lemma",
            "Method_of_steepest_descent",
            "Laplace%27s_method",
            "Borel_summation",
            "Method_of_dominant_balance",
        ),
    },
    "perturbation-theory": {
        "tags": ["perturbation theory", "method of averaging", "multiple-scale analysis", "adiabatic theorem"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Perturbation_theory",
            "Perturbation_theory_(quantum_mechanics)",
            "Method_of_averaging",
            "Poincar%C3%A9%E2%80%93Lindstedt_method",
            "Multiple-scale_analysis",
            "Secular_variation",
            "Adiabatic_theorem",
        ),
    },
    "singular-perturbation": {
        "tags": ["singular perturbation", "boundary layer", "matched asymptotic expansions", "relaxation oscillator"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Singular_perturbation",
            "Boundary_layer",
            "Method_of_matched_asymptotic_expansions",
            "Slowly_varying_envelope_approximation",
            "Relaxation_oscillator",
            "Van_der_Pol_oscillator",
        ),
    },
    "wkb-approximation": {
        "tags": ["wkb approximation", "eikonal equation", "semiclassical physics", "stokes phenomenon"],
        "license": CC_BY_SA,
        "pages": wiki(
            "WKB_approximation",
            "Airy_function",
            "Eikonal_equation",
            "Stokes_phenomenon",
            "Semiclassical_physics",
            "Geometrical_acoustics",
            "Bohr%E2%80%93Sommerfeld_quantization",
        ),
    },
    "calculus-of-variations-deep": {
        "tags": ["calculus of variations", "euler-lagrange equation", "beltrami identity", "hamilton principle"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Calculus_of_variations",
            "Euler%E2%80%93Lagrange_equation",
            "Hamilton%27s_principle",
            "Legendre_transformation",
            "Direct_method_in_the_calculus_of_variations",
            "Geodesic",
            "Beltrami_identity",
            "Weierstrass%E2%80%93Erdmann_condition",
        ),
    },
    "sturm-liouville-theory": {
        "tags": ["sturm-liouville theory", "eigenfunction expansion", "oscillation theory", "rayleigh quotient"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Sturm%E2%80%93Liouville_theory",
            "Eigenfunction",
            "Self-adjoint_operator",
            "Oscillation_theory",
            "Orthogonal_functions",
            "Spectral_theory_of_ordinary_differential_equations",
            "Rayleigh_quotient",
        ),
    },
    "greens-functions": {
        "tags": ["green's function", "fundamental solution", "method of images", "propagator function"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Green%27s_function",
            "Green%27s_function_(many-body_theory)",
            "Fundamental_solution",
            "Dirichlet_problem",
            "Method_of_images",
            "Propagator",
            "Resolvent_formalism",
        ),
    },
    "boundary-value-problems": {
        "tags": ["boundary value problem", "dirichlet boundary condition", "neumann boundary condition", "shooting method"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Boundary_value_problem",
            "Dirichlet_boundary_condition",
            "Neumann_boundary_condition",
            "Robin_boundary_condition",
            "Cauchy_boundary_condition",
            "Mixed_boundary_condition",
            "Shooting_method",
            "Poisson%27s_equation",
        ),
    },
    "finite-difference-methods": {
        "tags": ["finite difference method", "crank-nicolson method", "upwind scheme", "von neumann stability analysis"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Finite_difference_method",
            "Finite_difference",
            "Crank%E2%80%93Nicolson_method",
            "Lax%E2%80%93Wendroff_method",
            "Upwind_scheme",
            "Courant%E2%80%93Friedrichs%E2%80%93Lewy_condition",
            "Von_Neumann_stability_analysis",
            "Five-point_stencil",
        ),
    },
    "finite-volume-method": {
        "tags": ["finite volume method", "godunov scheme", "riemann solver", "flux limiter"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Finite_volume_method",
            "Godunov%27s_scheme",
            "Riemann_solver",
            "Total_variation_diminishing",
            "MUSCL_scheme",
            "Flux_limiter",
            "Roe_solver",
        ),
    },
    "spectral-methods-numerical": {
        "tags": ["spectral method", "pseudo-spectral method", "galerkin method", "collocation method"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Spectral_method",
            "Pseudo-spectral_method",
            "Galerkin_method",
            "Collocation_method",
            "Chebyshev_pseudospectral_method",
            "Spectral_element_method",
            "Fast_Fourier_transform",
        ),
    },
    "multigrid-methods": {
        "tags": ["multigrid method", "gauss-seidel method", "successive over-relaxation", "domain decomposition"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Multigrid_method",
            "Iterative_method",
            "Gauss%E2%80%93Seidel_method",
            "Successive_over-relaxation",
            "Domain_decomposition_methods",
            "Algebraic_multigrid_method",
            "Relaxation_(iterative_method)",
        ),
    },
    "krylov-subspace-methods": {
        "tags": ["krylov subspace", "generalized minimal residual method", "arnoldi iteration", "lanczos algorithm"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Krylov_subspace",
            "Generalized_minimal_residual_method",
            "Biconjugate_gradient_stabilized_method",
            "Arnoldi_iteration",
            "Lanczos_algorithm",
            "Minimal_residual_method",
            "Conjugate_residual_method",
        ),
    },
    "conjugate-gradient-method": {
        "tags": ["conjugate gradient method", "nonlinear conjugate gradient", "line search", "steepest descent"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Conjugate_gradient_method",
            "Nonlinear_conjugate_gradient_method",
            "Preconditioner",
            "Line_search",
            "Steepest_descent",
            "Biconjugate_gradient_method",
        ),
    },
    "preconditioning-numerical": {
        "tags": ["preconditioner matrix", "incomplete lu factorization", "condition number", "schur complement"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Preconditioner",
            "Incomplete_LU_factorization",
            "Incomplete_Cholesky_factorization",
            "Condition_number",
            "Sparse_matrix",
            "Diagonally_dominant_matrix",
            "Schur_complement",
        ),
    },
    "eigenvalue-algorithms": {
        "tags": ["eigenvalue algorithm", "power iteration", "rayleigh quotient iteration", "jacobi eigenvalue algorithm"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Eigenvalue_algorithm",
            "Power_iteration",
            "Inverse_iteration",
            "Rayleigh_quotient_iteration",
            "Jacobi_eigenvalue_algorithm",
            "Divide-and-conquer_eigenvalue_algorithm",
            "Householder_transformation",
        ),
    },
    "qr-algorithm": {
        "tags": ["qr algorithm", "qr decomposition", "hessenberg matrix", "givens rotation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "QR_algorithm",
            "QR_decomposition",
            "Hessenberg_matrix",
            "Givens_rotation",
            "Gram%E2%80%93Schmidt_process",
            "Schur_decomposition",
            "Francis_algorithm",
        ),
    },
    "singular-value-decomposition-deep": {
        "tags": ["singular value decomposition", "moore-penrose inverse", "low-rank approximation", "polar decomposition"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Singular_value_decomposition",
            "Singular_value",
            "Moore%E2%80%93Penrose_inverse",
            "Principal_component_analysis",
            "Low-rank_approximation",
            "Polar_decomposition",
            "Rank_(linear_algebra)",
        ),
    },
    "tensor-decomposition": {
        "tags": ["tensor decomposition", "tucker decomposition", "canonical polyadic decomposition", "tensor rank"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Tensor_decomposition",
            "Tensor_rank_decomposition",
            "Tucker_decomposition",
            "Higher-order_singular_value_decomposition",
            "Matrix_product_state",
            "Multilinear_subspace_learning",
            "Canonical_polyadic_decomposition",
        ),
    },
    "tensor-networks": {
        "tags": ["tensor network", "tensor contraction", "density matrix renormalization group", "penrose graphical notation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Tensor_network",
            "Matrix_product_state",
            "Tensor_contraction",
            "Density_matrix_renormalization_group",
            "Penrose_graphical_notation",
            "Quantum_circuit",
            "Trace_(linear_algebra)",
        ),
    },
    "interpolation-methods": {
        "tags": ["polynomial interpolation", "lagrange polynomial", "newton polynomial", "runge phenomenon"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Interpolation",
            "Polynomial_interpolation",
            "Lagrange_polynomial",
            "Newton_polynomial",
            "Bilinear_interpolation",
            "Barycentric_coordinate_system",
            "Runge%27s_phenomenon",
            "Trigonometric_interpolation",
        ),
    },
    "spline-interpolation": {
        "tags": ["spline interpolation", "cubic hermite spline", "smoothing spline", "thin plate spline"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Spline_interpolation",
            "Spline_(mathematics)",
            "B-spline",
            "Cubic_Hermite_spline",
            "Non-uniform_rational_B-spline",
            "Bezier_curve",
            "Smoothing_spline",
            "Thin_plate_spline",
        ),
    },
    "approximation-theory": {
        "tags": ["approximation theory", "remez algorithm", "pade approximant", "minimax approximation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Approximation_theory",
            "Weierstrass_approximation_theorem",
            "Remez_algorithm",
            "Pad%C3%A9_approximant",
            "Minimax_approximation_algorithm",
            "Bernstein_polynomial",
            "Modulus_of_continuity",
        ),
    },
    "chebyshev-approximation": {
        "tags": ["chebyshev approximation", "clenshaw algorithm", "chebyshev nodes", "equioscillation theorem"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Chebyshev_polynomials",
            "Approximation_error",
            "Clenshaw_algorithm",
            "Chebyshev_nodes",
            "Equioscillation_theorem",
            "Chebyshev_filter",
            "Discrete_Chebyshev_transform",
        ),
    },
    "numerical-quadrature": {
        "tags": ["numerical integration", "simpson's rule", "romberg method", "adaptive quadrature"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Numerical_integration",
            "Simpson%27s_rule",
            "Trapezoidal_rule",
            "Romberg%27s_method",
            "Newton%E2%80%93Cotes_formulas",
            "Adaptive_quadrature",
            "Tanh-sinh_quadrature",
        ),
    },
    "gaussian-quadrature": {
        "tags": ["gaussian quadrature", "gauss-legendre quadrature", "gauss-kronrod quadrature", "clenshaw-curtis quadrature"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Gaussian_quadrature",
            "Gauss%E2%80%93Legendre_quadrature",
            "Gauss%E2%80%93Kronrod_quadrature_formula",
            "Gauss%E2%80%93Hermite_quadrature",
            "Gauss%E2%80%93Laguerre_quadrature",
            "Chebyshev%E2%80%93Gauss_quadrature",
            "Clenshaw%E2%80%93Curtis_quadrature",
        ),
    },
    "root-finding-methods": {
        "tags": ["root-finding algorithm", "bisection method", "secant method", "brent's method"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Root-finding_algorithm",
            "Newton%27s_method",
            "Bisection_method",
            "Secant_method",
            "Regula_falsi",
            "Brent%27s_method",
            "Halley%27s_method",
            "Durand%E2%80%93Kerner_method",
        ),
    },
    "fixed-point-iteration": {
        "tags": ["fixed-point iteration", "banach fixed-point theorem", "contraction mapping", "anderson acceleration"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Fixed-point_iteration",
            "Banach_fixed-point_theorem",
            "Brouwer_fixed-point_theorem",
            "Contraction_mapping",
            "Aitken%27s_delta-squared_process",
            "Anderson_acceleration",
            "Kantorovich_theorem",
        ),
    },
    "continuation-methods": {
        "tags": ["numerical continuation", "homotopy continuation", "bifurcation theory", "predictor-corrector method"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Numerical_continuation",
            "Homotopy",
            "Bifurcation_theory",
            "Arc_length",
            "Predictor%E2%80%93corrector_method",
            "Homotopy_analysis_method",
            "Saddle-node_bifurcation",
        ),
    },
    "differential-algebraic-equations": {
        "tags": ["differential-algebraic equations", "backward differentiation formula", "method of lines", "runge-kutta methods"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Differential-algebraic_system_of_equations",
            "Backward_differentiation_formula",
            "Constraint_(computational_chemistry)",
            "Runge%E2%80%93Kutta_methods",
            "Method_of_lines",
            "Implicit_function",
        ),
    },
    "stochastic-differential-equations": {
        "tags": ["stochastic differential equation", "euler-maruyama method", "milstein method", "langevin equation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Stochastic_differential_equation",
            "Euler%E2%80%93Maruyama_method",
            "Milstein_method",
            "Runge%E2%80%93Kutta_method_(SDE)",
            "Langevin_equation",
            "Numerical_methods_for_ordinary_differential_equations",
            "Kolmogorov_backward_equations_(diffusion)",
        ),
    },
    "ito-stratonovich": {
        "tags": ["ito calculus", "stratonovich integral", "quadratic variation", "wiener process"],
        "license": CC_BY_SA,
        "pages": wiki(
            "It%C3%B4_calculus",
            "Stratonovich_integral",
            "It%C3%B4%27s_lemma",
            "Wiener_process",
            "Quadratic_variation",
            "Semimartingale",
            "Doob%E2%80%93Meyer_decomposition_theorem",
        ),
    },
    "variational-inference-math": {
        "tags": ["variational bayesian methods", "evidence lower bound", "mean field theory", "kullback-leibler divergence"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Variational_Bayesian_methods",
            "Evidence_lower_bound",
            "Kullback%E2%80%93Leibler_divergence",
            "Expectation%E2%80%93maximization_algorithm",
            "Mean_field_theory",
            "Calculus_of_variations",
            "Laplace%27s_approximation",
        ),
    },
    "information-geometry": {
        "tags": ["information geometry", "fisher information metric", "statistical manifold", "bregman divergence"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Information_geometry",
            "Fisher_information_metric",
            "Statistical_manifold",
            "Bregman_divergence",
            "Cram%C3%A9r%E2%80%93Rao_bound",
            "Natural_gradient",
            "Divergence_(statistics)",
        ),
    },
    "optimal-transport": {
        "tags": ["optimal transport", "wasserstein metric", "earth mover's distance", "kantorovich metric"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Transportation_theory_(mathematics)",
            "Wasserstein_metric",
            "Earth_mover%27s_distance",
            "Kantorovich_metric",
            "Monge_problem",
            "Wasserstein_GAN",
        ),
    },
    "convex-analysis": {
        "tags": ["convex analysis", "convex conjugate", "proximal operator", "fenchel duality"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Convex_analysis",
            "Convex_function",
            "Convex_conjugate",
            "Subderivative",
            "Fenchel%27s_duality_theorem",
            "Proximal_operator",
            "Legendre%E2%80%93Fenchel_transformation",
            "Epigraph_(mathematics)",
        ),
    },
    "nonlinear-optimization-methods": {
        "tags": ["nonlinear programming", "sequential quadratic programming", "trust region", "gauss-newton algorithm"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Nonlinear_programming",
            "Sequential_quadratic_programming",
            "Trust_region",
            "Gauss%E2%80%93Newton_algorithm",
            "Levenberg%E2%80%93Marquardt_algorithm",
            "Broyden%E2%80%93Fletcher%E2%80%93Goldfarb%E2%80%93Shanno_algorithm",
            "Augmented_Lagrangian_method",
        ),
    },
    "interior-point-methods": {
        "tags": ["interior-point method", "karmarkar algorithm", "barrier function", "ellipsoid method"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Interior-point_method",
            "Karmarkar%27s_algorithm",
            "Barrier_function",
            "Logarithmic_barrier_function",
            "Karush%E2%80%93Kuhn%E2%80%93Tucker_conditions",
            "Ellipsoid_method",
            "Affine_scaling",
        ),
    },
    "semidefinite-programming": {
        "tags": ["semidefinite programming", "conic optimization", "linear matrix inequality", "sum-of-squares optimization"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Semidefinite_programming",
            "Definite_matrix",
            "Conic_optimization",
            "Linear_matrix_inequality",
            "Sum-of-squares_optimization",
            "Second-order_cone_programming",
            "Spectrahedron",
        ),
    },
}
