"""Modern ML/LLM techniques and computer-vision/NLP task families."""

from .common import CC_BY_SA, wiki

DOMAINS = {
    "flash-attention": {
        "tags": ["flash attention", "efficient attention", "gpu attention kernel", "memory bandwidth bound", "fused softmax kernel"],
        "license": CC_BY_SA,
        "pages": wiki(
            "FlashAttention",
            "Attention_(machine_learning)",
            "Transformer_(deep_learning_architecture)",
            "Graphics_processing_unit",
            "Memory_hierarchy",
            "High_Bandwidth_Memory",
            "Softmax_function",
            "Compute_kernel",
        ),
    },
    "kv-cache-optimization": {
        "tags": ["key value cache", "autoregressive decoding", "attention cache reuse", "inference memory footprint", "transformer decoding speedup"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cache_(computing)",
            "Autoregressive_model",
            "Attention_(machine_learning)",
            "Transformer_(deep_learning_architecture)",
            "Large_language_model",
            "Memory_hierarchy",
            "Decoding_methods",
        ),
    },
    "rotary-position-embedding": {
        "tags": ["rotary position embedding", "relative positional encoding", "token position rotation", "attention position bias"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Attention_(machine_learning)",
            "Transformer_(deep_learning_architecture)",
            "Word_embedding",
            "Attention_Is_All_You_Need",
            "Large_language_model",
            "Rotation_matrix",
            "Sequence_alignment",
        ),
    },
    "alibi-attention": {
        "tags": ["attention linear bias", "attention length extrapolation", "positional attention bias", "context window extension"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Attention_(machine_learning)",
            "Transformer_(deep_learning_architecture)",
            "Large_language_model",
            "Attention_Is_All_You_Need",
            "Softmax_function",
            "Extrapolation",
            "Word_embedding",
        ),
    },
    "grouped-query-attention": {
        "tags": ["grouped query attention", "multi query attention", "attention head sharing", "kv head reduction", "inference memory saving"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Grouped-query_attention",
            "Attention_(machine_learning)",
            "Transformer_(deep_learning_architecture)",
            "Large_language_model",
            "Softmax_function",
            "Cache_(computing)",
        ),
    },
    "sliding-window-attention": {
        "tags": ["sliding window attention", "local attention span", "sparse attention pattern", "long context transformer", "windowed self attention"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Attention_(machine_learning)",
            "Sliding_window_protocol",
            "Transformer_(deep_learning_architecture)",
            "Large_language_model",
            "Sparse_matrix",
            "Softmax_function",
        ),
    },
    "speculative-decoding": {
        "tags": ["speculative decoding", "draft model verification", "llm inference acceleration", "parallel token proposal", "assisted generation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Speculative_decoding",
            "Decoding_methods",
            "Large_language_model",
            "Autoregressive_model",
            "Beam_search",
            "Nucleus_sampling",
        ),
    },
    "gptq-quantization": {
        "tags": ["post training quantization", "weight only quantization", "layer wise quantization", "gptq method", "low bit inference"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Quantization_(signal_processing)",
            "Model_compression",
            "Large_language_model",
            "Half-precision_floating-point_format",
            "8-bit_computing",
            "Round-off_error",
        ),
    },
    "awq-quantization": {
        "tags": ["activation aware quantization", "weight quantization scaling", "awq method", "salient weight preservation", "low bit llm"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Model_compression",
            "Quantization_(signal_processing)",
            "Large_language_model",
            "Bfloat16_floating-point_format",
            "Rounding",
            "Floating-point_arithmetic",
        ),
    },
    "gguf-format": {
        "tags": ["gguf file format", "model weight serialization", "quantized model container", "local llm packaging", "single file model"],
        "license": CC_BY_SA,
        "pages": wiki(
            "File_format",
            "Serialization",
            "Binary_file",
            "Memory-mapped_file",
            "Data_compression",
            "Quantization_(signal_processing)",
            "Large_language_model",
        ),
    },
    "model-pruning-ml": {
        "tags": ["neural network pruning", "weight sparsification", "structured pruning", "lottery ticket hypothesis", "network sparsity"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Pruning_(artificial_neural_network)",
            "Lottery_ticket_hypothesis",
            "Model_compression",
            "Sparse_matrix",
            "Regularization_(mathematics)",
            "Overfitting",
            "Deep_learning",
        ),
    },
    "neural-architecture-search": {
        "tags": ["neural architecture search", "automated model design", "architecture optimization", "search space exploration", "auto ml search"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Neural_architecture_search",
            "Automated_machine_learning",
            "Hyperparameter_optimization",
            "Reinforcement_learning",
            "Bayesian_optimization",
            "Deep_learning",
        ),
    },
    "mixture-of-depths": {
        "tags": ["conditional compute allocation", "dynamic layer routing", "token level routing", "adaptive depth network", "sparse activation transformer"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Mixture_of_experts",
            "Transformer_(deep_learning_architecture)",
            "Large_language_model",
            "Sparse_matrix",
            "Softmax_function",
            "Deep_learning",
        ),
    },
    "retrieval-rerankers": {
        "tags": ["retrieval reranking", "learning to rank", "cross encoder scoring", "relevance reordering", "search result reranking"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Learning_to_rank",
            "Semantic_search",
            "Nearest_neighbor_search",
            "Cosine_similarity",
            "Sentence_embedding",
            "Vector_database",
        ),
    },
    "document-chunking": {
        "tags": ["document chunking", "text segmentation strategy", "passage splitting", "retrieval context window", "overlapping chunk windows"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Chunking_(computing)",
            "Text_segmentation",
            "Semantic_search",
            "Sentence_embedding",
            "Tokenization_(lexical_analysis)",
            "Vector_database",
        ),
    },
    "react-agent-prompting": {
        "tags": ["react agent prompting", "reason and act loop", "tool augmented reasoning", "interleaved thought action", "llm agent loop"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Software_agent",
            "Prompt_engineering",
            "Chain-of-thought_prompting",
            "Large_language_model",
            "Automated_planning_and_scheduling",
            "Multi-agent_system",
        ),
    },
    "chain-of-thought-prompting": {
        "tags": ["chain of thought prompting", "step by step reasoning", "intermediate reasoning steps", "reasoning trace elicitation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Chain-of-thought_prompting",
            "Prompt_engineering",
            "Large_language_model",
            "In-context_learning",
            "Few-shot_learning",
            "Language_model",
        ),
    },
    "tree-of-thoughts": {
        "tags": ["tree of thoughts", "deliberate search reasoning", "branching reasoning paths", "reasoning tree exploration", "lookahead prompting"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Tree_of_thoughts",
            "Chain-of-thought_prompting",
            "Prompt_engineering",
            "Large_language_model",
            "Greedy_algorithm",
            "Beam_search",
        ),
    },
    "self-consistency-decoding": {
        "tags": ["self consistency decoding", "majority vote reasoning", "sampled reasoning paths", "answer aggregation prompting", "diverse reasoning sampling"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Chain-of-thought_prompting",
            "Decoding_methods",
            "Nucleus_sampling",
            "Prompt_engineering",
            "Large_language_model",
            "Beam_search",
        ),
    },
    "constitutional-ai": {
        "tags": ["constitutional ai", "ai feedback alignment", "self critique training", "principle guided alignment", "harmlessness training"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Constitutional_AI",
            "AI_alignment",
            "Reinforcement_learning_from_AI_feedback",
            "Reinforcement_learning_from_human_feedback",
            "Large_language_model",
            "Instruction_tuning",
        ),
    },
    "instruction-tuning": {
        "tags": ["instruction tuning", "supervised finetuning", "instruction following", "task generalization tuning", "aligned response training"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Instruction_tuning",
            "Fine-tuning_(deep_learning)",
            "Large_language_model",
            "Reinforcement_learning_from_human_feedback",
            "Foundation_model",
            "Transfer_learning",
        ),
    },
    "in-context-learning": {
        "tags": ["in context learning", "prompt conditioned learning", "no weight update learning", "demonstration based prompting", "emergent few shot ability"],
        "license": CC_BY_SA,
        "pages": wiki(
            "In-context_learning",
            "Large_language_model",
            "Prompt_engineering",
            "Few-shot_learning",
            "Foundation_model",
            "Language_model",
        ),
    },
    "few-shot-learning": {
        "tags": ["few shot learning", "low data generalization", "meta learning approach", "example conditioned inference", "support set adaptation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Few-shot_learning",
            "Transfer_learning",
            "In-context_learning",
            "Contrastive_learning",
            "Statistical_classification",
            "Prompt_engineering",
        ),
    },
    "zero-shot-learning": {
        "tags": ["zero shot learning", "unseen class inference", "attribute based transfer", "semantic label embedding", "no example generalization"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Zero-shot_learning",
            "Transfer_learning",
            "Word_embedding",
            "Statistical_classification",
            "In-context_learning",
            "Semantic_search",
        ),
    },
    "chain-of-density": {
        "tags": ["chain of density summarization", "iterative summary refinement", "entity dense summary", "progressive abstraction prompting", "information dense output"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Automatic_summarization",
            "Prompt_engineering",
            "Large_language_model",
            "Named-entity_recognition",
            "Text_segmentation",
            "Chain-of-thought_prompting",
        ),
    },
    "guided-decoding": {
        "tags": ["guided decoding", "grammar constrained decoding", "logit masking generation", "schema constrained output", "token filtering decode"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Decoding_methods",
            "Formal_grammar",
            "Context-free_grammar",
            "Regular_expression",
            "Beam_search",
            "Large_language_model",
        ),
    },
    "structured-generation": {
        "tags": ["structured generation", "json schema output", "constrained text generation", "typed output enforcement", "parseable model output"],
        "license": CC_BY_SA,
        "pages": wiki(
            "JSON",
            "Formal_grammar",
            "Context-free_grammar",
            "Serialization",
            "Regular_expression",
            "Large_language_model",
        ),
    },
    "function-calling-llm": {
        "tags": ["llm function calling", "structured tool invocation", "api schema binding", "argument extraction generation", "json tool arguments"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Function_(computer_programming)",
            "Application_programming_interface",
            "JSON",
            "Large_language_model",
            "Software_agent",
            "Serialization",
        ),
    },
    "tool-use-agents": {
        "tags": ["tool using agent", "external tool augmentation", "api calling agent", "action tool selection", "environment interaction loop"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Software_agent",
            "Application_programming_interface",
            "Automated_planning_and_scheduling",
            "Large_language_model",
            "Reinforcement_learning",
            "Multi-agent_system",
        ),
    },
    "multi-agent-systems-ai": {
        "tags": ["multi agent system", "agent coordination protocol", "cooperative agent planning", "distributed problem solving", "agent communication"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Multi-agent_system",
            "Software_agent",
            "Swarm_intelligence",
            "Agent-based_model",
            "Blackboard_system",
            "Distributed_computing",
        ),
    },
    "object-tracking-cv": {
        "tags": ["visual object tracking", "multi object tracking", "motion state estimation", "kalman filter tracking", "video target following"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Video_tracking",
            "Kalman_filter",
            "Optical_flow",
            "Object_detection",
            "Computer_vision",
            "Motion_capture",
        ),
    },
    "pose-estimation": {
        "tags": ["human pose estimation", "keypoint detection", "skeleton joint tracking", "articulated body pose", "body landmark detection"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Articulated_body_pose_estimation",
            "Pose_(computer_vision)",
            "Computer_vision",
            "Convolutional_neural_network",
            "Motion_capture",
            "Structure_from_motion",
        ),
    },
    "optical-character-recognition": {
        "tags": ["optical character recognition", "text digitization", "handwriting recognition", "document text extraction", "scanned page reading"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Optical_character_recognition",
            "Computer_vision",
            "Image_segmentation",
            "Convolutional_neural_network",
            "Connectionist_temporal_classification",
            "Feature_extraction",
        ),
    },
    "face-recognition-cv": {
        "tags": ["facial recognition system", "face verification", "face embedding matching", "biometric identification", "face landmark alignment"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Facial_recognition_system",
            "Computer_vision",
            "Convolutional_neural_network",
            "Feature_extraction",
            "Cosine_similarity",
            "Contrastive_learning",
        ),
    },
    "image-captioning": {
        "tags": ["image captioning", "automatic image annotation", "visual description generation", "image to text model", "scene caption synthesis"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Automatic_image_annotation",
            "Computer_vision",
            "Encoder-decoder_model",
            "Convolutional_neural_network",
            "Attention_(machine_learning)",
            "Natural_language_generation",
        ),
    },
    "visual-question-answering": {
        "tags": ["visual question answering", "multimodal reasoning", "image grounded answering", "vision language model", "cross modal fusion"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Visual_question_answering",
            "Computer_vision",
            "Question_answering",
            "Attention_(machine_learning)",
            "Multimodal_learning",
            "Convolutional_neural_network",
        ),
    },
    "depth-estimation": {
        "tags": ["monocular depth estimation", "depth map prediction", "stereo depth reconstruction", "scene geometry inference", "dense depth prediction"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Depth_map",
            "Stereopsis",
            "Depth_perception",
            "Structure_from_motion",
            "Computer_vision",
            "Convolutional_neural_network",
        ),
    },
    "image-super-resolution": {
        "tags": ["image super resolution", "single image upscaling", "detail reconstruction", "high resolution synthesis", "learned upsampling"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Super-resolution_imaging",
            "Image_scaling",
            "Upsampling",
            "Generative_adversarial_network",
            "Convolutional_neural_network",
            "Digital_image_processing",
        ),
    },
    "style-transfer-cv": {
        "tags": ["neural style transfer", "artistic image stylization", "content style separation", "feature statistics matching", "texture synthesis transfer"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Neural_style_transfer",
            "Convolutional_neural_network",
            "Generative_adversarial_network",
            "Computer_vision",
            "Feature_extraction",
            "Latent_space",
        ),
    },
    "named-entity-recognition": {
        "tags": ["named entity recognition", "entity span tagging", "sequence labeling task", "person location tagging", "entity type classification"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Named-entity_recognition",
            "Part-of-speech_tagging",
            "Statistical_classification",
            "Conditional_random_field",
            "Text_corpus",
            "Natural_language_processing",
        ),
    },
    "coreference-resolution": {
        "tags": ["coreference resolution", "anaphora linking", "mention clustering", "pronoun antecedent resolution", "entity mention grouping"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Coreference",
            "Coreference_resolution",
            "Parsing",
            "Named-entity_recognition",
            "Dependency_grammar",
            "Natural_language_processing",
        ),
    },
    "text-summarization": {
        "tags": ["text summarization", "abstractive summarization", "extractive summarization", "document condensation", "salient sentence selection"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Automatic_summarization",
            "Encoder-decoder_model",
            "Seq2seq",
            "Attention_(machine_learning)",
            "Text_segmentation",
            "Natural_language_processing",
        ),
    },
    "machine-translation-nlp": {
        "tags": ["neural machine translation", "sequence to sequence translation", "cross lingual generation", "attention alignment translation", "bilingual corpus training"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Machine_translation",
            "Seq2seq",
            "Encoder-decoder_model",
            "Attention_(machine_learning)",
            "Beam_search",
            "Transformer_(deep_learning_architecture)",
        ),
    },
    "question-answering-nlp": {
        "tags": ["question answering system", "extractive answer span", "reading comprehension model", "open domain qa", "answer retrieval reader"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Question_answering",
            "Semantic_search",
            "Named-entity_recognition",
            "Encoder-decoder_model",
            "Text_corpus",
            "Natural_language_processing",
        ),
    },
    "sentiment-analysis-nlp": {
        "tags": ["sentiment analysis", "opinion polarity classification", "affective text mining", "aspect based sentiment", "emotion detection text"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Sentiment_analysis",
            "Document_classification",
            "Statistical_classification",
            "Naive_Bayes_classifier",
            "Bag-of-words_model",
            "Natural_language_processing",
        ),
    },
    "topic-modeling": {
        "tags": ["topic modeling", "latent dirichlet allocation", "document topic discovery", "unsupervised text clustering", "word topic distribution"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Topic_model",
            "Latent_Dirichlet_allocation",
            "Tf-idf",
            "Hierarchical_clustering",
            "Vector_space_model",
            "Text_corpus",
        ),
    },
    "text-classification": {
        "tags": ["text classification", "document categorization", "supervised text labeling", "bag of words features", "class probability scoring"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Document_classification",
            "Statistical_classification",
            "Naive_Bayes_classifier",
            "Support_vector_machine",
            "Bag-of-words_model",
            "Tf-idf",
        ),
    },
    "dependency-parsing-nlp": {
        "tags": ["dependency parsing", "syntactic dependency tree", "grammatical relation extraction", "head modifier structure", "transition based parsing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Dependency_grammar",
            "Parsing",
            "Part-of-speech_tagging",
            "Lexical_analysis",
            "Context-free_grammar",
            "Natural_language_processing",
        ),
    },
    "word-sense-disambiguation": {
        "tags": ["word sense disambiguation", "lexical ambiguity resolution", "context sense selection", "polysemy resolution", "sense inventory mapping"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Word-sense_disambiguation",
            "WordNet",
            "Word_embedding",
            "Lexical_analysis",
            "N-gram",
            "Natural_language_processing",
        ),
    },
    "relation-extraction": {
        "tags": ["relation extraction", "entity relationship mining", "semantic triple extraction", "knowledge graph population", "distant supervision extraction"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Relationship_extraction",
            "Named-entity_recognition",
            "Dependency_grammar",
            "Coreference_resolution",
            "Statistical_classification",
            "Natural_language_processing",
        ),
    },
    "keyphrase-extraction": {
        "tags": ["keyphrase extraction", "keyword extraction", "salient term ranking", "graph based keyword ranking", "document indexing terms"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Keyword_extraction",
            "Tf-idf",
            "N-gram",
            "Part-of-speech_tagging",
            "Feature_extraction",
            "Text_segmentation",
        ),
    },
    "language-identification": {
        "tags": ["language identification", "written language detection", "character n gram profiling", "script detection", "code switching detection"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Language_identification",
            "N-gram",
            "Statistical_classification",
            "Naive_Bayes_classifier",
            "Text_corpus",
            "Lexical_analysis",
        ),
    },
    "text-to-speech-synthesis": {
        "tags": ["text to speech synthesis", "neural speech generation", "vocoder waveform generation", "prosody modeling", "grapheme to phoneme"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Speech_synthesis",
            "Deep_learning_speech_synthesis",
            "Vocoder",
            "Prosody_(linguistics)",
            "Mel-frequency_cepstrum",
            "Spectrogram",
        ),
    },
    "voice-cloning-ml": {
        "tags": ["voice cloning", "speaker voice synthesis", "speaker embedding adaptation", "few shot voice mimicry", "audio deepfake voice"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Voice_cloning",
            "Speech_synthesis",
            "Deepfake",
            "Formant",
            "Speech_processing",
            "Vocoder",
        ),
    },
    "music-generation-ai": {
        "tags": ["music generation", "algorithmic composition", "symbolic music modeling", "generative audio synthesis", "melody sequence modeling"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Music_and_artificial_intelligence",
            "Algorithmic_composition",
            "Generative_artificial_intelligence",
            "Recurrent_neural_network",
            "Diffusion_model",
            "Spectrogram",
        ),
    },
}
