"""Game development: engines, netcode, game AI, physics, audio, and animation."""

from .common import CC_BY_SA, wiki

DOMAINS = {
    "unity-engine": {
        "tags": ["unity engine", "unity game engine", "unity3d", "unity component"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Unity_(game_engine)",
            "Game_engine",
            "Entity_component_system",
            "Scene_graph",
            "Component-based_software_engineering",
            "Cross-platform_software",
            "Real-time_computing",
        ),
    },
    "unreal-engine": {
        "tags": ["unreal engine", "unreal game engine", "epic games engine", "unreal blueprint"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Unreal_Engine",
            "Game_engine",
            "Deferred_shading",
            "Rendering_(computer_graphics)",
            "C_Sharp_(programming_language)",
            "Scene_graph",
        ),
    },
    "cryengine": {
        "tags": ["cryengine", "crytek engine", "cry engine", "sandbox editor"],
        "license": CC_BY_SA,
        "pages": wiki(
            "CryEngine",
            "Crytek",
            "Far_Cry_(video_game)",
            "Deferred_shading",
            "Rendering_(computer_graphics)",
            "Game_engine",
        ),
    },
    "gamemaker-studio": {
        "tags": ["gamemaker studio", "gamemaker language", "yoyo games", "gml scripting"],
        "license": CC_BY_SA,
        "pages": wiki(
            "GameMaker",
            "YoYo_Games",
            "GameMaker_Language",
            "2D_computer_graphics",
            "Sprite_(computer_graphics)",
            "Game_engine",
        ),
    },
    "defold-engine": {
        "tags": ["defold engine", "defold game engine", "lua game engine", "defold editor"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Defold",
            "Lua_(programming_language)",
            "Cross-platform_software",
            "Game_engine",
            "2D_computer_graphics",
            "Component-based_software_engineering",
        ),
    },
    "bevy-engine": {
        "tags": ["bevy engine", "bevy game engine", "rust game engine", "bevy ecs"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Rust_(programming_language)",
            "Entity_component_system",
            "Data-oriented_design",
            "Game_engine",
            "Object_composition",
            "Cross-platform_software",
        ),
    },
    "raylib": {
        "tags": ["raylib library", "raylib game", "c game library", "immediate mode graphics"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Raylib",
            "C_(programming_language)",
            "Immediate_mode_(computer_graphics)",
            "Game_engine",
            "2D_computer_graphics",
            "OpenGL",
        ),
    },
    "monogame": {
        "tags": ["monogame framework", "xna framework", "c sharp game framework", "monogame content"],
        "license": CC_BY_SA,
        "pages": wiki(
            "MonoGame",
            "Microsoft_XNA",
            "C_Sharp_(programming_language)",
            ".NET",
            "Cross-platform_software",
            "Game_engine",
        ),
    },
    "phaser-framework": {
        "tags": ["phaser framework", "phaser game framework", "html5 game framework", "phaser scene"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Phaser_(game_framework)",
            "HTML5",
            "JavaScript",
            "WebGL",
            "2D_computer_graphics",
            "Sprite_(computer_graphics)",
        ),
    },
    "pygame": {
        "tags": ["pygame library", "python game library", "pygame surface", "sdl python"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Pygame",
            "Simple_DirectMedia_Layer",
            "Python_(programming_language)",
            "2D_computer_graphics",
            "Sprite_(computer_graphics)",
            "Game_programming",
        ),
    },
    "love2d": {
        "tags": ["love2d framework", "love game framework", "lua game framework", "luajit game"],
        "license": CC_BY_SA,
        "pages": wiki(
            "L%C3%96VE_(game_framework)",
            "Lua_(programming_language)",
            "LuaJIT",
            "2D_computer_graphics",
            "Cross-platform_software",
            "Game_programming",
        ),
    },
    "cocos2d": {
        "tags": ["cocos2d framework", "cocos game engine", "cocos creator", "cocos2d sprite"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cocos2d",
            "Sprite_(computer_graphics)",
            "2D_computer_graphics",
            "Game_engine",
            "Cross-platform_software",
            "OpenGL",
        ),
    },
    "playcanvas": {
        "tags": ["playcanvas engine", "playcanvas webgl", "browser 3d engine", "playcanvas editor"],
        "license": CC_BY_SA,
        "pages": wiki(
            "PlayCanvas",
            "WebGL",
            "WebGPU",
            "3D_computer_graphics",
            "Game_engine",
            "JavaScript",
        ),
    },
    "babylonjs": {
        "tags": ["babylon.js", "babylonjs engine", "webgl 3d engine", "babylon scene"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Babylon.js",
            "WebGL",
            "WebGPU",
            "3D_computer_graphics",
            "WebAssembly",
            "JavaScript",
        ),
    },
    "ecs-architecture": {
        "tags": ["entity component system", "ecs architecture", "data-oriented design", "component composition"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Entity_component_system",
            "Data-oriented_design",
            "Component-based_software_engineering",
            "Object_composition",
            "Cache_prefetching",
            "Locality_of_reference",
        ),
    },
    "game-loop-timing": {
        "tags": ["game loop", "game loop timing", "frame rate loop", "delta time step"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Frame_rate",
            "Delta_timing",
            "Refresh_rate",
            "Real-time_computing",
            "Control_loop",
            "Numerical_integration",
        ),
    },
    "fixed-timestep": {
        "tags": ["fixed timestep", "fixed time step", "deterministic simulation step", "physics timestep"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Delta_time",
            "Numerical_integration",
            "Euler_method",
            "Verlet_integration",
            "Runge%E2%80%93Kutta_methods",
            "Numerical_stability",
        ),
    },
    "sprite-rendering": {
        "tags": ["sprite rendering", "sprite sheet", "texture atlas", "sprite compositing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Sprite_(computer_graphics)",
            "Texture_atlas",
            "Alpha_compositing",
            "Z-order",
            "2D_computer_graphics",
            "Software_rendering",
        ),
    },
    "tilemap": {
        "tags": ["tilemap rendering", "tile-based game", "tile map layer", "isometric tilemap"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Tile-based_video_game",
            "Isometric_video_game_graphics",
            "Scrolling",
            "Parallax_scrolling",
            "2D_computer_graphics",
            "Heightmap",
        ),
    },
    "collision-detection-2d": {
        "tags": ["collision detection", "collision response", "bounding volume", "separating axis theorem"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Collision_detection",
            "Bounding_volume",
            "Minimum_bounding_box",
            "Hyperplane_separation_theorem",
            "Collision_response",
            "Sweep_and_prune",
        ),
    },
    "spatial-partitioning": {
        "tags": ["spatial partitioning", "space partitioning", "binary space partitioning", "bounding volume hierarchy"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Space_partitioning",
            "Binary_space_partitioning",
            "Bounding_volume_hierarchy",
            "K-d_tree",
            "R-tree",
            "Sweep_and_prune",
        ),
    },
    "quadtree-octree": {
        "tags": ["quadtree structure", "octree structure", "spatial index tree", "hierarchical space subdivision"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Quadtree",
            "Octree",
            "K-d_tree",
            "R-tree",
            "Space_partitioning",
            "Bounding_volume_hierarchy",
        ),
    },
    "game-physics-engine": {
        "tags": ["physics engine", "game physics", "rigid body simulation", "physics solver"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Physics_engine",
            "Game_physics",
            "Rigid_body_dynamics",
            "Collision_response",
            "Numerical_integration",
            "Havok_(software)",
        ),
    },
    "box2d-physics": {
        "tags": ["box2d physics", "box2d engine", "2d physics library", "box2d body"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Box2D",
            "Physics_engine",
            "Rigid_body_dynamics",
            "Collision_response",
            "Impulse_(physics)",
            "Friction",
        ),
    },
    "bullet-physics": {
        "tags": ["bullet physics", "bullet physics library", "3d physics engine", "bullet collision"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Bullet_(software)",
            "Physics_engine",
            "Rigid_body_dynamics",
            "Gilbert%E2%80%93Johnson%E2%80%93Keerthi_distance_algorithm",
            "Minkowski_addition",
            "Collision_detection",
        ),
    },
    "physx": {
        "tags": ["physx engine", "nvidia physx", "gpu physics", "physx rigid body"],
        "license": CC_BY_SA,
        "pages": wiki(
            "PhysX",
            "Physics_engine",
            "Rigid_body_dynamics",
            "Collision_response",
            "Havok_(software)",
            "Game_physics",
        ),
    },
    "rigid-body-dynamics": {
        "tags": ["rigid body dynamics", "rigid body simulation", "angular velocity", "moment of inertia"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Rigid_body_dynamics",
            "Rigid_body",
            "Angular_velocity",
            "Moment_of_inertia",
            "Impulse_(physics)",
            "Coefficient_of_restitution",
        ),
    },
    "ragdoll-physics": {
        "tags": ["ragdoll physics", "ragdoll simulation", "articulated body physics", "physics-driven character"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ragdoll_physics",
            "Inverse_kinematics",
            "Rigid_body_dynamics",
            "Physics_engine",
            "Skeletal_animation",
            "Constraint_(computational_chemistry)",
        ),
    },
    "cloth-simulation": {
        "tags": ["cloth simulation", "cloth modeling", "soft-body dynamics", "mass spring cloth"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cloth_modeling",
            "Soft-body_dynamics",
            "Finite_element_method",
            "Harmonic_oscillator",
            "Hooke%27s_law",
            "Numerical_integration",
        ),
    },
    "particle-systems": {
        "tags": ["particle system", "particle emitter", "gpu particles", "particle effect"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Particle_system",
            "Point_cloud",
            "Billboard_(computer_graphics)",
            "Alpha_compositing",
            "Pseudorandom_number_generator",
            "Rendering_(computer_graphics)",
        ),
    },
    "behavior-trees": {
        "tags": ["behavior tree", "behaviour tree ai", "game ai behavior", "behavior tree node"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Behavior_tree_(artificial_intelligence,_robotics_and_control)",
            "Behavior_tree",
            "Artificial_intelligence_in_video_games",
            "Finite-state_machine",
            "Decision_tree",
            "Blackboard_system",
        ),
    },
    "goal-oriented-action-planning": {
        "tags": ["goal-oriented action planning", "goap planner", "automated planning", "action planning ai"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Automated_planning_and_scheduling",
            "Hierarchical_task_network",
            "STRIPS",
            "Artificial_intelligence_in_video_games",
            "Motion_planning",
            "Blackboard_system",
        ),
    },
    "finite-state-machine-ai": {
        "tags": ["finite state machine", "game ai state machine", "state pattern", "hierarchical state machine"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Finite-state_machine",
            "State_pattern",
            "Deterministic_finite_automaton",
            "UML_state_machine",
            "Artificial_intelligence_in_video_games",
            "Non-player_character",
        ),
    },
    "pathfinding-navmesh": {
        "tags": ["pathfinding algorithm", "navigation mesh", "a star search", "navmesh pathfinding"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Pathfinding",
            "Navigation_mesh",
            "A*_search_algorithm",
            "Dijkstra%27s_algorithm",
            "Motion_planning",
            "Artificial_intelligence_in_video_games",
        ),
    },
    "flocking-steering": {
        "tags": ["flocking behavior", "steering behaviors", "boids algorithm", "swarm steering"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Flocking_(behavior)",
            "Boids",
            "Craig_Reynolds_(computer_graphics)",
            "Swarm_intelligence",
            "Motion_planning",
            "Artificial_intelligence_in_video_games",
        ),
    },
    "procedural-generation-games": {
        "tags": ["procedural generation", "procedural content generation", "roguelike generation", "seeded generation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Procedural_generation",
            "Roguelike",
            "Random_seed",
            "Pseudorandom_number_generator",
            "L-system",
            "Cellular_automaton",
        ),
    },
    "perlin-noise": {
        "tags": ["perlin noise", "simplex noise", "gradient noise", "value noise"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Perlin_noise",
            "Simplex_noise",
            "Value_noise",
            "Gradient_noise",
            "Ken_Perlin",
            "Fractal",
        ),
    },
    "wave-function-collapse": {
        "tags": ["wave function collapse", "model synthesis", "constraint-based generation", "tile constraint solver"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Model_synthesis",
            "Wave_function_collapse",
            "Constraint_satisfaction_problem",
            "Constraint_propagation",
            "Procedural_generation",
            "Cellular_automaton",
        ),
    },
    "game-networking": {
        "tags": ["game networking", "netcode", "multiplayer networking", "network game architecture"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Netcode",
            "Network_architecture",
            "Multiplayer_video_game",
            "Client%E2%80%93server_model",
            "User_Datagram_Protocol",
            "Transmission_Control_Protocol",
        ),
    },
    "client-side-prediction": {
        "tags": ["client-side prediction", "client prediction netcode", "dead reckoning", "entity interpolation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Dead_reckoning",
            "Extrapolation",
            "Interpolation",
            "Netcode",
            "Latency_(engineering)",
            "Multiplayer_video_game",
        ),
    },
    "lag-compensation": {
        "tags": ["lag compensation", "network lag", "latency compensation", "clock synchronization netcode"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Lag",
            "Network_delay",
            "Latency_(engineering)",
            "Clock_synchronization",
            "Netcode",
            "Interpolation",
        ),
    },
    "rollback-netcode": {
        "tags": ["rollback netcode", "ggpo netcode", "deterministic rollback", "fighting game netcode"],
        "license": CC_BY_SA,
        "pages": wiki(
            "GGPO",
            "Netcode",
            "Deterministic_algorithm",
            "Determinism",
            "Interpolation",
            "Multiplayer_video_game",
        ),
    },
    "authoritative-server": {
        "tags": ["authoritative server", "server authority netcode", "client-server game", "anti-cheat server"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Client%E2%80%93server_model",
            "Server_(computing)",
            "Cheating_in_online_games",
            "Netcode",
            "Multiplayer_video_game",
            "Network_architecture",
        ),
    },
    "skeletal-animation": {
        "tags": ["skeletal animation", "skinned mesh animation", "bone rigging", "vertex skinning"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Skeletal_animation",
            "Morph_target_animation",
            "Character_animation",
            "Polygon_mesh",
            "Vertex_(computer_graphics)",
            "Motion_capture",
        ),
    },
    "inverse-kinematics-games": {
        "tags": ["inverse kinematics", "ik solver", "forward kinematics", "jacobian ik"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Inverse_kinematics",
            "Forward_kinematics",
            "Jacobian_matrix_and_determinant",
            "Robot_kinematics",
            "Denavit%E2%80%93Hartenberg_parameters",
            "Skeletal_animation",
        ),
    },
    "animation-blending": {
        "tags": ["animation blending", "animation blend tree", "keyframe interpolation", "spherical linear interpolation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Inbetweening",
            "Key_frame",
            "Linear_interpolation",
            "Slerp",
            "Blend_shape",
            "Computer_animation",
        ),
    },
    "audio-middleware": {
        "tags": ["audio middleware", "game audio engine", "adaptive audio", "interactive sound"],
        "license": CC_BY_SA,
        "pages": wiki(
            "FMOD",
            "Audiokinetic_Wwise",
            "Digital_audio",
            "Sound_effect",
            "Adaptive_music",
            "OpenAL",
        ),
    },
    "fmod-audio": {
        "tags": ["fmod audio", "fmod studio", "fmod sound engine", "fmod event"],
        "license": CC_BY_SA,
        "pages": wiki(
            "FMOD",
            "Digital_audio",
            "Adaptive_music",
            "Sound_effect",
            "Reverberation",
            "Panning_(audio)",
        ),
    },
    "wwise-audio": {
        "tags": ["wwise audio", "audiokinetic wwise", "wwise sound engine", "interactive music wwise"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Audiokinetic_Wwise",
            "Interactive_music",
            "Video_game_music",
            "Digital_audio",
            "Adaptive_music",
            "Reverberation",
        ),
    },
    "spatial-audio-games": {
        "tags": ["spatial audio", "3d audio effect", "positional audio", "hrtf audio"],
        "license": CC_BY_SA,
        "pages": wiki(
            "3D_audio_effect",
            "Head-related_transfer_function",
            "Sound_localization",
            "Ambisonics",
            "Reverberation",
            "OpenAL",
        ),
    },
    "game-input-handling": {
        "tags": ["game input handling", "game controller input", "gamepad mapping", "input device event"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Game_controller",
            "Gamepad",
            "Input_device",
            "Human_interface_device",
            "DirectInput",
            "Event_(computing)",
        ),
    },
    "save-game-serialization": {
        "tags": ["save game serialization", "saved game format", "game state persistence", "serialized save data"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Saved_game",
            "Serialization",
            "Persistence_(computer_science)",
            "Comparison_of_data-serialization_formats",
            "Protocol_Buffers",
            "MessagePack",
        ),
    },
    "level-editor-design": {
        "tags": ["level editor", "level design", "game level design", "world editor tool"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Level_editor",
            "Level_design",
            "Level_(video_games)",
            "Video_game_design",
            "Nonlinear_gameplay",
            "Game_development_tool",
        ),
    },
}
