"""Graphics APIs, image/video/audio codecs, 3D formats, and color science."""

from .common import CC_BY_SA, CC_BY_SA_25, WIKI, mdn, wiki

DOMAINS = {
    "directx-graphics": {
        "tags": ["directx api", "direct3d", "hlsl shader", "directx raytracing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "DirectX",
            "Direct3D",
            "High-Level_Shader_Language",
            "DirectX_Raytracing",
            "Direct3D_12",
            "DirectCompute",
        ),
    },
    "metal-api": {
        "tags": ["metal api", "apple metal", "metal shading language", "metal gpu"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Metal_(API)",
            "Metal_Shading_Language",
            "Apple_A11",
            "Graphics_processing_unit",
            "Shading_language",
        ),
    },
    "webgpu-api": {
        "tags": ["webgpu api", "browser gpu", "gpu compute web", "webgpu device"],
        "license": CC_BY_SA_25,
        "pages": wiki(
            "WebGPU",
            "WebGL",
            "WebAssembly",
        ) + [
            mdn("Web/API/WebGPU_API"),
            mdn("Web/API/GPUDevice"),
            mdn("Web/API/GPUBuffer"),
        ],
    },
    "wgsl-shading": {
        "tags": ["wgsl shader", "webgpu shading language", "wgsl compute", "gpu shading web"],
        "license": CC_BY_SA,
        "pages": wiki(
            "WebGPU_Shading_Language",
            "Shading_language",
            "Compute_kernel",
            "Shader",
            "WebGPU",
        ),
    },
    "hlsl-shading": {
        "tags": ["hlsl shader", "direct3d shader", "hlsl compute", "pixel shader hlsl"],
        "license": CC_BY_SA,
        "pages": wiki(
            "High-Level_Shader_Language",
            "Shading_language",
            "Vertex_shader",
            "Pixel_shader",
            "Geometry_shader",
            "Cg_(programming_language)",
        ),
    },
    "glsl-shading": {
        "tags": ["glsl shader", "opengl shading language", "fragment shader", "vertex shader glsl"],
        "license": CC_BY_SA,
        "pages": wiki(
            "OpenGL_Shading_Language",
            "Shading_language",
            "Shader",
            "Vertex_shader",
            "Pixel_shader",
            "Fixed-function",
        ),
    },
    "ray-tracing-rt": {
        "tags": ["ray tracing", "ray tracing hardware", "rtx gpu", "bvh acceleration"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ray_tracing_(graphics)",
            "Ray_tracing_hardware",
            "Nvidia_RTX",
            "Bounding_volume_hierarchy",
            "Ray_casting",
            "DirectX_Raytracing",
        ),
    },
    "path-tracing": {
        "tags": ["path tracing", "monte carlo rendering", "rendering equation", "importance sampling"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Path_tracing",
            "Monte_Carlo_method",
            "Rendering_equation",
            "Bidirectional_reflectance_distribution_function",
            "Importance_sampling",
        ),
    },
    "physically-based-rendering": {
        "tags": ["physically based rendering", "pbr material", "microfacet model", "fresnel reflectance"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Physically_based_rendering",
            "Bidirectional_scattering_distribution_function",
            "Fresnel_equations",
            "Microfacet",
            "Albedo",
            "PBR_(disambiguation)",
        ),
    },
    "global-illumination": {
        "tags": ["global illumination", "radiosity rendering", "photon mapping", "indirect lighting"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Global_illumination",
            "Radiosity_(computer_graphics)",
            "Photon_mapping",
            "Light_transport_theory",
            "Rendering_(computer_graphics)",
        ),
    },
    "ambient-occlusion": {
        "tags": ["ambient occlusion", "screen space ambient occlusion", "contact shadow", "ao map"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ambient_occlusion",
            "Screen_space_ambient_occlusion",
            "Global_illumination",
            "Depth_map",
            "Shader",
        ),
    },
    "shadow-mapping": {
        "tags": ["shadow mapping", "shadow volume", "depth map shadow", "real-time shadows"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Shadow_mapping",
            "Shadow_volume",
            "Depth_map",
            "Rendering_(computer_graphics)",
            "Pixel_shader",
        ),
    },
    "deferred-rendering": {
        "tags": ["deferred shading", "g-buffer", "deferred rendering", "tiled rendering"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Deferred_shading",
            "G-buffer",
            "Rendering_(computer_graphics)",
            "Tiled_rendering",
            "Pixel_shader",
        ),
    },
    "texture-compression": {
        "tags": ["texture compression", "s3tc block compression", "astc format", "etc texture"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Texture_compression",
            "S3_Texture_Compression",
            "Adaptive_scalable_texture_compression",
            "Ericsson_Texture_Compression",
            "PVRTC",
        ),
    },
    "mipmapping": {
        "tags": ["mipmap texture", "trilinear filtering", "anisotropic filtering", "texture filtering"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Mipmap",
            "Texture_mapping",
            "Trilinear_interpolation",
            "Anisotropic_filtering",
            "Texture_filtering",
        ),
    },
    "anti-aliasing-graphics": {
        "tags": ["anti-aliasing", "multisample anti-aliasing", "temporal anti-aliasing", "fxaa filter"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Spatial_anti-aliasing",
            "Multisample_anti-aliasing",
            "Supersampling",
            "Fast_approximate_anti-aliasing",
            "Temporal_anti-aliasing",
            "Deep_learning_super_sampling",
        ),
    },
    "level-of-detail": {
        "tags": ["level of detail", "lod mesh", "graphics impostor", "clipmap streaming"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Level_of_detail_(computer_graphics)",
            "Polygon_mesh",
            "Impostor_(computer_graphics)",
            "Clipmap",
            "Mipmap",
        ),
    },
    "tessellation": {
        "tags": ["graphics tessellation", "subdivision surface", "catmull-clark", "bezier surface"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Tessellation_(computer_graphics)",
            "Subdivision_surface",
            "Catmull%E2%80%93Clark_subdivision_surface",
            "Bezier_surface",
            "Polygon_mesh",
        ),
    },
    "compute-shaders": {
        "tags": ["compute shader", "gpgpu compute", "opencl kernel", "cuda kernel"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Compute_shader",
            "General-purpose_computing_on_graphics_processing_units",
            "OpenCL",
            "CUDA",
            "Parallel_computing",
        ),
    },
    "image-formats": {
        "tags": ["image file format", "raster graphics", "bitmap image", "image color depth"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Image_file_format",
            "Raster_graphics",
            "Bitmap",
            "Color_depth",
        ) + [
            mdn("Web/Media/Guides/Formats/Image_types"),
        ],
    },
    "png-format": {
        "tags": ["png image", "deflate compression", "lossless png", "alpha compositing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "PNG",
            "DEFLATE",
            "Lossless_compression",
            "Alpha_compositing",
            "Animated_PNG",
        ),
    },
    "jpeg-compression": {
        "tags": ["jpeg compression", "discrete cosine transform", "jpeg 2000", "lossy image"],
        "license": CC_BY_SA,
        "pages": wiki(
            "JPEG",
            "Discrete_cosine_transform",
            "JPEG_2000",
            "Quantization_(image_processing)",
            "Lossy_compression",
        ),
    },
    "webp-format": {
        "tags": ["webp image", "vp8 intra", "lossy webp", "web image format"],
        "license": CC_BY_SA,
        "pages": wiki(
            "WebP",
            "VP8",
            "Lossy_compression",
            "Lossless_compression",
            "Image_file_format",
        ),
    },
    "avif-format": {
        "tags": ["avif image", "av1 image", "avif codec", "next-gen image"],
        "license": CC_BY_SA,
        "pages": wiki(
            "AVIF",
            "AV1",
            "High_Efficiency_Image_File_Format",
            "Image_file_format",
            "Lossy_compression",
        ),
    },
    "heif-format": {
        "tags": ["heif container", "heic image", "hevc still image", "apple heif"],
        "license": CC_BY_SA,
        "pages": wiki(
            "High_Efficiency_Image_File_Format",
            "High_Efficiency_Video_Coding",
            "Image_file_format",
            "AVIF",
            "Digital_container_format",
        ),
    },
    "gif-format": {
        "tags": ["gif image", "lzw compression", "animated gif", "indexed color"],
        "license": CC_BY_SA,
        "pages": wiki(
            "GIF",
            "LZW",
            "Animated_PNG",
            "Color_depth",
            "Raster_graphics",
        ),
    },
    "svg-graphics": {
        "tags": ["svg vector", "scalable vector graphics", "svg path", "xml vector"],
        "license": CC_BY_SA_25,
        "pages": wiki(
            "Scalable_Vector_Graphics",
            "Vector_graphics",
        ) + [
            mdn("Web/SVG"),
            mdn("Web/SVG/Reference/Element/path"),
            mdn("Web/SVG/Reference/Element/rect"),
        ],
    },
    "video-codec-h264": {
        "tags": ["h.264 codec", "advanced video coding", "cabac entropy", "motion compensation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Advanced_Video_Coding",
            "Group_of_pictures",
            "Motion_compensation",
            "Inter_frame",
            "Context-adaptive_binary_arithmetic_coding",
        ),
    },
    "video-codec-h265": {
        "tags": ["h.265 codec", "high efficiency video coding", "coding tree unit", "hevc video"],
        "license": CC_BY_SA,
        "pages": wiki(
            "High_Efficiency_Video_Coding",
            "Coding_tree_unit",
            "Versatile_Video_Coding",
            "Motion_compensation",
            "Group_of_pictures",
        ),
    },
    "av1-codec": {
        "tags": ["av1 codec", "aomedia video", "royalty-free codec", "av1 encoding"],
        "license": CC_BY_SA,
        "pages": wiki(
            "AV1",
            "VP9",
            "Video_codec",
            "Inter_frame",
            "Transcoding",
        ),
    },
    "vp9-codec": {
        "tags": ["vp9 codec", "webm video", "google vp9", "vp8 predecessor"],
        "license": CC_BY_SA,
        "pages": wiki(
            "VP9",
            "VP8",
            "WebM",
            "Video_codec",
            "Group_of_pictures",
        ),
    },
    "ffmpeg": {
        "tags": ["ffmpeg tool", "libavcodec", "video transcoding", "media conversion"],
        "license": CC_BY_SA,
        "pages": wiki(
            "FFmpeg",
            "Libavcodec",
            "Transcoding",
            "Video_codec",
            "Codec",
        ),
    },
    "video-container-formats": {
        "tags": ["media container", "matroska mkv", "mp4 container", "quicktime file format"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Digital_container_format",
            "Matroska",
            "MP4_file_format",
            "QuickTime_File_Format",
            "WebM",
            "Ogg",
        ),
    },
    "streaming-hls-dash": {
        "tags": ["adaptive bitrate streaming", "http live streaming", "mpeg-dash", "rtmp streaming"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Adaptive_bitrate_streaming",
            "HTTP_Live_Streaming",
            "Dynamic_Adaptive_Streaming_over_HTTP",
            "Real-Time_Messaging_Protocol",
            "M3U",
        ) + [
            mdn("Web/Media/Guides/Streaming"),
        ],
    },
    "chroma-subsampling": {
        "tags": ["chroma subsampling", "ycbcr color", "luma chroma", "4:2:0 sampling"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Chroma_subsampling",
            "YCbCr",
            "Luma_(video)",
            "Chrominance",
            "Color_space",
        ),
    },
    "audio-codec-mp3": {
        "tags": ["mp3 codec", "mpeg audio layer", "psychoacoustic model", "audio bit rate"],
        "license": CC_BY_SA,
        "pages": wiki(
            "MP3",
            "Psychoacoustics",
            "Modified_discrete_cosine_transform",
            "Bit_rate",
            "Perceptual_coding",
        ),
    },
    "audio-codec-aac": {
        "tags": ["aac codec", "advanced audio coding", "perceptual audio", "aac encoding"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Advanced_Audio_Coding",
            "Perceptual_coding",
            "Modified_discrete_cosine_transform",
            "Psychoacoustics",
            "Bit_rate",
        ),
    },
    "opus-codec": {
        "tags": ["opus audio", "celt codec", "silk speech", "voip audio codec"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Opus_(audio_format)",
            "CELT",
            "Speex",
            "Voice_over_IP",
            "Perceptual_coding",
        ),
    },
    "flac-lossless": {
        "tags": ["flac lossless", "linear predictive coding audio", "rice coding", "lossless audio"],
        "license": CC_BY_SA,
        "pages": wiki(
            "FLAC",
            "Linear_predictive_coding",
            "Rice_coding",
            "Lossless_compression",
            "Audio_bit_depth",
        ),
    },
    "midi-protocol": {
        "tags": ["midi protocol", "general midi", "midi sequencer", "musical note event"],
        "license": CC_BY_SA,
        "pages": wiki(
            "MIDI",
            "General_MIDI",
            "Musical_note",
            "Sequencer",
            "Sound_synthesis",
        ),
    },
    "audio-synthesis": {
        "tags": ["sound synthesis", "subtractive synthesis", "fm synthesis", "wavetable synthesis"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Sound_synthesis",
            "Subtractive_synthesis",
            "Frequency_modulation_synthesis",
            "Wavetable_synthesis",
            "Additive_synthesis",
            "Oscillator_(electronics)",
        ),
    },
    "digital-audio-workstation": {
        "tags": ["digital audio workstation", "vst plugin", "audio plug-in", "multitrack recording"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Digital_audio_workstation",
            "Virtual_Studio_Technology",
            "Audio_plug-in",
            "Multitrack_recording",
            "Audio_mixing_(recorded_music)",
        ),
    },
    "waveform-audio": {
        "tags": ["wav audio", "pulse-code modulation", "audio sampling", "riff container"],
        "license": CC_BY_SA,
        "pages": wiki(
            "WAV",
            "Pulse-code_modulation",
            "Sampling_(signal_processing)",
            "Nyquist%E2%80%93Shannon_sampling_theorem",
            "Resource_Interchange_File_Format",
        ),
    },
    "gltf-format": {
        "tags": ["gltf format", "khronos gltf", "3d asset transmission", "pbr gltf"],
        "license": CC_BY_SA,
        "pages": wiki(
            "GlTF",
            "Khronos_Group",
            "PBR_(disambiguation)",
            "3D_computer_graphics",
            "Polygon_mesh",
        ),
    },
    "usd-openusd": {
        "tags": ["openusd scene", "universal scene description", "pixar usd", "3d scene interchange"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Universal_Scene_Description",
            "Pixar",
            "3D_computer_graphics",
            "3D_modeling",
            "Polygon_mesh",
        ),
    },
    "obj-3d-format": {
        "tags": ["wavefront obj", "obj mesh file", "material template library", "3d vertex data"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Wavefront_.obj_file",
            "Material_Template_Library",
            "Vertex_(computer_graphics)",
            "Polygon_mesh",
            "3D_modeling",
        ),
    },
    "fbx-format": {
        "tags": ["fbx format", "autodesk fbx", "3d model exchange", "fbx interchange"],
        "license": CC_BY_SA,
        "pages": wiki(
            "FBX",
            "Autodesk",
            "3D_modeling",
            "3D_computer_graphics",
            "Digital_container_format",
        ),
    },
    "blender-3d": {
        "tags": ["blender 3d", "blender software", "digital sculpting", "uv mapping blender"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Blender_(software)",
            "Digital_sculpting",
            "UV_mapping",
            "3D_modeling",
            "Point_cloud",
        ),
    },
    "mesh-processing": {
        "tags": ["mesh processing", "geometry processing", "delaunay triangulation", "marching cubes"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Geometry_processing",
            "Mesh_generation",
            "Delaunay_triangulation",
            "Marching_cubes",
            "Polygon_mesh",
        ),
    },
    "color-management": {
        "tags": ["color management", "icc profile", "color gamut", "cie color space"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Color_management",
            "ICC_profile",
            "Gamut",
            "CIE_1931_color_space",
            "Color_model",
        ),
    },
    "srgb-colorspace": {
        "tags": ["srgb color space", "gamma correction", "rec.709", "adobe rgb"],
        "license": CC_BY_SA,
        "pages": wiki(
            "SRGB",
            "Gamma_correction",
            "Rec._709",
            "Adobe_RGB_color_space",
            "DCI-P3",
        ),
    },
    "hdr-imaging": {
        "tags": ["high dynamic range imaging", "hdr rendering", "perceptual quantizer", "openexr format"],
        "license": CC_BY_SA,
        "pages": wiki(
            "High_dynamic_range",
            "High-dynamic-range_rendering",
            "Rec._2100",
            "Perceptual_quantizer",
            "OpenEXR",
        ),
    },
    "tone-mapping": {
        "tags": ["tone mapping", "hdr tone mapping", "dynamic range compression image", "exposure imaging"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Tone_mapping",
            "High_dynamic_range",
            "Radiance_(software)",
            "Display_device",
            "Exposure_(photography)",
            "Retinex",
        ),
    },
}
