"""Chemistry (organic/inorganic/physical/analytical) and materials science."""

from .common import CC_BY_SA, wiki

DOMAINS = {
    "organic-chemistry": {
        "tags": ["organic chemistry", "functional groups", "reaction mechanisms", "aromatic compounds"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Organic_chemistry",
            "Functional_group",
            "Reaction_mechanism",
            "Nucleophilic_substitution",
            "Stereochemistry",
            "Aromaticity",
        ),
    },
    "inorganic-chemistry": {
        "tags": ["inorganic chemistry", "transition metals", "ionic compounds", "main group elements"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Inorganic_chemistry",
            "Ionic_compound",
            "Transition_metal",
            "Crystal_field_theory",
            "Ligand",
            "Main-group_element",
        ),
    },
    "physical-chemistry": {
        "tags": ["physical chemistry", "chemical thermodynamics", "chemical potential", "colligative properties"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Physical_chemistry",
            "Chemical_thermodynamics",
            "Reaction_rate",
            "Colligative_properties",
            "Chemical_potential",
            "Fugacity",
        ),
    },
    "analytical-chemistry": {
        "tags": ["analytical chemistry", "quantitative analysis", "calibration curve", "detection limit"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Analytical_chemistry",
            "Titration",
            "Gravimetric_analysis",
            "Calibration_curve",
            "Detection_limit",
            "Wet_chemistry",
        ),
    },
    "chemical-bonding": {
        "tags": ["chemical bonding", "covalent bond", "ionic bonding", "intermolecular forces"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Chemical_bond",
            "Covalent_bond",
            "Ionic_bonding",
            "Metallic_bonding",
            "Hydrogen_bond",
            "Van_der_Waals_force",
            "Valence_bond_theory",
        ),
    },
    "molecular-orbital-theory": {
        "tags": ["molecular orbital theory", "atomic orbitals", "bond order", "frontier orbitals"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Molecular_orbital_theory",
            "Molecular_orbital",
            "Linear_combination_of_atomic_orbitals",
            "Antibonding_molecular_orbital",
            "HOMO_and_LUMO",
            "Bond_order",
        ),
    },
    "thermochemistry": {
        "tags": ["chemical thermochemistry", "enthalpy change", "heat of reaction", "bond energy"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Thermochemistry",
            "Enthalpy",
            "Hess%27s_law",
            "Standard_enthalpy_of_formation",
            "Calorimetry",
            "Bond-dissociation_energy",
        ),
    },
    "chemical-kinetics": {
        "tags": ["chemical kinetics", "reaction rate", "rate law", "activation energy"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Chemical_kinetics",
            "Rate_equation",
            "Arrhenius_equation",
            "Activation_energy",
            "Reaction_rate_constant",
            "Reaction_intermediate",
        ),
    },
    "chemical-equilibrium": {
        "tags": ["chemical equilibrium", "equilibrium constant", "reaction quotient", "solubility equilibrium"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Chemical_equilibrium",
            "Equilibrium_constant",
            "Le_Chatelier%27s_principle",
            "Reaction_quotient",
            "Solubility_equilibrium",
            "Common-ion_effect",
        ),
    },
    "acid-base-chemistry": {
        "tags": ["acid base chemistry", "acid dissociation constant", "buffer solution", "conjugate base"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Acid%E2%80%93base_reaction",
            "PH",
            "Acid_dissociation_constant",
            "Buffer_solution",
            "Bronsted%E2%80%93Lowry_acid%E2%80%93base_theory",
            "Lewis_acids_and_bases",
        ),
    },
    "redox-reactions": {
        "tags": ["redox reactions", "oxidation state", "oxidizing agent", "half reaction"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Redox",
            "Oxidation_state",
            "Reducing_agent",
            "Oxidizing_agent",
            "Half-reaction",
            "Disproportionation",
        ),
    },
    "electrochemistry": {
        "tags": ["electrochemistry cells", "galvanic cell", "electrode potential", "cell potential"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Electrochemistry",
            "Galvanic_cell",
            "Electrode_potential",
            "Nernst_equation",
            "Electrolysis",
            "Standard_electrode_potential",
        ),
    },
    "coordination-chemistry": {
        "tags": ["coordination chemistry", "coordination complex", "ligand field", "chelate ligand"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Coordination_complex",
            "Coordination_number",
            "Chelation",
            "Crystal_field_stabilization_energy",
            "Ligand_field_theory",
            "Denticity",
        ),
    },
    "organometallic-chemistry": {
        "tags": ["organometallic chemistry", "grignard reagent", "cross coupling", "metal carbon bond"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Organometallic_chemistry",
            "Grignard_reagent",
            "Metallocene",
            "Ferrocene",
            "Oxidative_addition",
            "Cross-coupling_reaction",
        ),
    },
    "stereochemistry": {
        "tags": ["molecular stereochemistry", "optical isomers", "chiral molecules", "conformational analysis"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Enantiomer",
            "Chirality_(chemistry)",
            "Diastereomer",
            "Optical_rotation",
            "Cahn%E2%80%93Ingold%E2%80%93Prelog_priority_rules",
            "Conformational_isomerism",
        ),
    },
    "reaction-mechanisms-organic": {
        "tags": ["organic reaction mechanisms", "electrophilic substitution", "elimination reaction", "reaction intermediate"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Elimination_reaction",
            "Electrophilic_aromatic_substitution",
            "Addition_reaction",
            "Pericyclic_reaction",
            "Markovnikov%27s_rule",
            "Carbocation",
        ),
    },
    "spectroscopy-nmr": {
        "tags": ["nuclear magnetic resonance", "chemical shift", "spin coupling", "nmr spectroscopy"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Nuclear_magnetic_resonance_spectroscopy",
            "Chemical_shift",
            "Spin%E2%80%93spin_coupling",
            "Two-dimensional_nuclear_magnetic_resonance_spectroscopy",
            "Carbon-13_nuclear_magnetic_resonance",
            "Nuclear_Overhauser_effect",
        ),
    },
    "mass-spectrometry-chem": {
        "tags": ["mass spectrometry", "electrospray ionization", "tandem mass spectrometry", "mass to charge ratio"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Mass_spectrometry",
            "Electrospray_ionization",
            "Quadrupole_mass_analyzer",
            "Time-of-flight_mass_spectrometry",
            "Tandem_mass_spectrometry",
            "Mass-to-charge_ratio",
        ),
    },
    "infrared-spectroscopy": {
        "tags": ["infrared spectroscopy", "molecular vibration", "vibrational modes", "raman spectroscopy"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Infrared_spectroscopy",
            "Fourier-transform_infrared_spectroscopy",
            "Molecular_vibration",
            "Raman_spectroscopy",
            "Normal_mode",
            "Near-infrared_spectroscopy",
        ),
    },
    "chromatography-methods": {
        "tags": ["chromatography methods", "liquid chromatography", "gas chromatography", "retention factor"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Chromatography",
            "High-performance_liquid_chromatography",
            "Gas_chromatography",
            "Thin-layer_chromatography",
            "Column_chromatography",
            "Retention_factor",
        ),
    },
    "crystallography": {
        "tags": ["crystallography lattices", "crystal system", "bravais lattice", "space group"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Crystallography",
            "Crystal_system",
            "Bravais_lattice",
            "Space_group",
            "Miller_index",
            "Unit_cell",
        ),
    },
    "x-ray-diffraction": {
        "tags": ["x-ray diffraction", "bragg law", "powder diffraction", "structure factor"],
        "license": CC_BY_SA,
        "pages": wiki(
            "X-ray_crystallography",
            "Bragg%27s_law",
            "Powder_diffraction",
            "Structure_factor",
            "Diffractometer",
            "Reciprocal_lattice",
        ),
    },
    "polymer-chemistry": {
        "tags": ["polymer chemistry", "glass transition", "cross linking", "molar mass distribution"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Polymer_chemistry",
            "Monomer",
            "Copolymer",
            "Cross-link",
            "Glass_transition",
            "Molar_mass_distribution",
        ),
    },
    "polymerization": {
        "tags": ["polymerization reactions", "radical polymerization", "step growth", "chain growth"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Polymerization",
            "Radical_polymerization",
            "Step-growth_polymerization",
            "Chain-growth_polymerization",
            "Ziegler%E2%80%93Natta_catalyst",
            "Emulsion_polymerization",
        ),
    },
    "materials-science": {
        "tags": ["materials science", "crystallographic defect", "grain boundary", "mechanical properties"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Materials_science",
            "Crystallographic_defect",
            "Dislocation",
            "Grain_boundary",
            "Young%27s_modulus",
            "Fracture_mechanics",
        ),
    },
    "crystal-structures": {
        "tags": ["crystal structure", "close packing", "atomic packing factor", "coordination geometry"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Crystal_structure",
            "Close-packing_of_equal_spheres",
            "Cubic_crystal_system",
            "Coordination_geometry",
            "Atomic_packing_factor",
            "Interstitial_defect",
        ),
    },
    "phase-diagrams": {
        "tags": ["phase diagram", "eutectic system", "lever rule", "phase rule"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Phase_diagram",
            "Eutectic_system",
            "Lever_rule",
            "Phase_rule",
            "Binary_phase",
            "Solidus_(chemistry)",
        ),
    },
    "metallurgy": {
        "tags": ["extractive metallurgy", "heat treating", "powder metallurgy", "metal annealing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Metallurgy",
            "Smelting",
            "Heat_treating",
            "Annealing_(materials_science)",
            "Quenching",
            "Powder_metallurgy",
        ),
    },
    "alloys": {
        "tags": ["metal alloys", "solid solution", "precipitation hardening", "intermetallic compound"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Alloy",
            "Steel",
            "Solid_solution",
            "Intermetallic",
            "Precipitation_hardening",
            "Brass",
        ),
    },
    "semiconductor-materials": {
        "tags": ["semiconductor materials", "energy band gap", "semiconductor doping", "charge carriers"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Semiconductor",
            "Band_gap",
            "Doping_(semiconductor)",
            "P%E2%80%93n_junction",
            "Gallium_arsenide",
            "Charge_carrier",
        ),
    },
    "ceramics-materials": {
        "tags": ["ceramic materials", "ceramic sintering", "refractory materials", "silicon carbide"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ceramic",
            "Sintering",
            "Refractory",
            "Silicon_carbide",
            "Alumina",
            "Piezoelectricity",
        ),
    },
    "composite-materials": {
        "tags": ["composite materials", "fiber reinforced", "carbon fiber", "laminate structure"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Composite_material",
            "Fiber-reinforced_plastic",
            "Carbon-fiber-reinforced_polymer",
            "Matrix_(composite)",
            "Laminate",
            "Fiberglass",
        ),
    },
    "nanomaterials": {
        "tags": ["engineered nanomaterials", "quantum dot", "nanoparticle synthesis", "molecular self assembly"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Nanomaterials",
            "Nanoparticle",
            "Quantum_dot",
            "Nanowire",
            "Self-assembly",
            "Nanostructure",
        ),
    },
    "graphene-materials": {
        "tags": ["graphene material", "graphene oxide", "two dimensional materials", "carbon allotrope"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Graphene",
            "Graphene_oxide",
            "Graphite",
            "Fullerene",
            "Two-dimensional_materials",
            "Graphene_nanoribbon",
        ),
    },
    "carbon-nanotubes": {
        "tags": ["carbon nanotubes", "carbon allotropes", "nanotube chirality", "field effect transistor"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Carbon_nanotube",
            "Allotropes_of_carbon",
            "Buckypaper",
            "Chirality_(mathematics)",
            "Field-effect_transistor",
            "Single-wall_carbon_nanotube",
        ),
    },
    "thin-films": {
        "tags": ["thin film deposition", "chemical vapor deposition", "physical vapor deposition", "atomic layer deposition"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Thin_film",
            "Chemical_vapor_deposition",
            "Physical_vapor_deposition",
            "Sputter_deposition",
            "Atomic_layer_deposition",
            "Epitaxy",
        ),
    },
    "superconducting-materials": {
        "tags": ["superconducting materials", "cooper pair", "meissner effect", "high temperature superconductivity"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Superconductivity",
            "Cooper_pair",
            "BCS_theory",
            "High-temperature_superconductivity",
            "Meissner_effect",
            "Type-II_superconductor",
        ),
    },
    "magnetic-materials": {
        "tags": ["magnetic materials", "ferromagnetism physics", "magnetic domain", "curie temperature"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Magnetism",
            "Ferromagnetism",
            "Antiferromagnetism",
            "Magnetic_domain",
            "Hysteresis",
            "Curie_temperature",
        ),
    },
    "dielectric-materials": {
        "tags": ["dielectric materials", "electric permittivity", "ferroelectricity phenomena", "dielectric strength"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Dielectric",
            "Permittivity",
            "Ferroelectricity",
            "Polarization_density",
            "Capacitor",
            "Dielectric_strength",
        ),
    },
    "corrosion-science": {
        "tags": ["corrosion science", "galvanic corrosion", "cathodic protection", "metal passivation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Corrosion",
            "Passivation_(chemistry)",
            "Galvanic_corrosion",
            "Cathodic_protection",
            "Rust",
            "Pitting_corrosion",
        ),
    },
    "catalysis": {
        "tags": ["chemical catalysis", "catalytic cycle", "turnover number", "reaction catalyst"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Catalyst",
            "Activation_energy",
            "Turnover_number",
            "Catalytic_cycle",
            "Autocatalysis",
            "Homogeneous_catalysis",
        ),
    },
    "heterogeneous-catalysis": {
        "tags": ["heterogeneous catalysis", "surface adsorption", "catalytic converter", "zeolite catalyst"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Heterogeneous_catalysis",
            "Adsorption",
            "Active_site",
            "Catalytic_converter",
            "Zeolite",
            "Chemisorption",
        ),
    },
    "enzyme-catalysis": {
        "tags": ["enzyme catalysis", "michaelis menten kinetics", "enzyme inhibitor", "allosteric regulation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Enzyme_catalysis",
            "Enzyme",
            "Michaelis%E2%80%93Menten_kinetics",
            "Enzyme_inhibitor",
            "Cofactor_(biochemistry)",
            "Allosteric_regulation",
        ),
    },
    "surface-chemistry": {
        "tags": ["surface chemistry", "surface tension", "adsorption isotherm", "contact angle"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Surface_science",
            "Surface_tension",
            "Wetting",
            "Langmuir_adsorption_model",
            "Contact_angle",
            "Surface_energy",
        ),
    },
    "colloid-chemistry": {
        "tags": ["colloid chemistry", "zeta potential", "colloidal emulsion", "surfactant micelle"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Colloid",
            "Emulsion",
            "Zeta_potential",
            "Micelle",
            "Brownian_motion",
            "Surfactant",
        ),
    },
    "thermodynamics-chemistry": {
        "tags": ["chemical thermodynamics", "gibbs free energy", "entropy change", "thermodynamic potential"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Thermodynamics",
            "Gibbs_free_energy",
            "Entropy",
            "Second_law_of_thermodynamics",
            "Heat_capacity",
            "Thermodynamic_potential",
        ),
    },
    "statistical-thermodynamics": {
        "tags": ["statistical thermodynamics", "partition function", "boltzmann distribution", "equipartition theorem"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Statistical_thermodynamics",
            "Partition_function_(statistical_mechanics)",
            "Boltzmann_distribution",
            "Maxwell%E2%80%93Boltzmann_statistics",
            "Microstate_(statistical_mechanics)",
            "Equipartition_theorem",
        ),
    },
    "quantum-chemistry-methods": {
        "tags": ["quantum chemistry methods", "born oppenheimer approximation", "slater determinant", "coupled cluster"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Basis_set_(chemistry)",
            "Schr%C3%B6dinger_equation",
            "Born%E2%80%93Oppenheimer_approximation",
            "Slater_determinant",
            "Configuration_interaction",
            "Coupled_cluster",
        ),
    },
    "molecular-modeling": {
        "tags": ["molecular modeling", "force field", "molecular mechanics", "potential energy surface"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Molecular_modelling",
            "Force_field_(chemistry)",
            "Molecular_mechanics",
            "Potential_energy_surface",
            "Conformational_ensemble",
            "Z-matrix_(chemistry)",
        ),
    },
    "battery-chemistry": {
        "tags": ["battery chemistry", "lithium ion battery", "battery electrolyte", "state of charge"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Electric_battery",
            "Lithium-ion_battery",
            "Electrolyte",
            "Anode",
            "Cathode",
            "State_of_charge",
        ),
    },
    "fuel-cell-chemistry": {
        "tags": ["fuel cell chemistry", "proton exchange membrane", "solid oxide fuel cell", "membrane electrode assembly"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Fuel_cell",
            "Proton-exchange_membrane_fuel_cell",
            "Solid_oxide_fuel_cell",
            "Electrocatalyst",
            "Hydrogen_fuel",
            "Membrane_electrode_assembly",
        ),
    },
    "photochemistry": {
        "tags": ["organic photochemistry", "molecular fluorescence", "jablonski diagram", "quantum yield"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Photochemistry",
            "Fluorescence",
            "Phosphorescence",
            "Jablonski_diagram",
            "Photoisomerization",
            "Quantum_yield",
        ),
    },
    "green-chemistry": {
        "tags": ["green chemistry", "atom economy", "ionic liquid", "bio based material"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Green_chemistry",
            "Atom_economy",
            "Solvent",
            "Biodegradation",
            "Bio-based_material",
            "Ionic_liquid",
        ),
    },
}
