"""Applied verticals: fintech, health IT, geospatial, e-commerce, CMS, telecom, automotive."""
from .common import CC_BY_SA, WIKI, wiki

DOMAINS = {
    "fhir-health": {
        "tags": ["fhir standard", "health interoperability", "hl7 fhir", "electronic health record"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Fast_Healthcare_Interoperability_Resources",
            "Health_Level_7",
            "Electronic_health_record",
            "Health_informatics",
            "Interoperability",
            "OpenEHR",
        ),
    },
    "hl7-messaging": {
        "tags": ["hl7 messaging", "hl7 v2", "clinical document", "health message exchange"],
        "license": CC_BY_SA,
        "pages": wiki(
            "HL7_v2",
            "Health_Level_7",
            "Clinical_Document_Architecture",
            "Continuity_of_Care_Document",
            "Health_informatics",
            "Interoperability",
        ),
    },
    "dicom-imaging": {
        "tags": ["dicom imaging", "medical imaging", "picture archiving", "radiology information"],
        "license": CC_BY_SA,
        "pages": wiki(
            "DICOM",
            "Picture_archiving_and_communication_system",
            "Medical_imaging",
            "Radiological_information_system",
            "Computed_tomography",
            "Magnetic_resonance_imaging",
        ),
    },
    "snomed-terminology": {
        "tags": ["snomed ct", "clinical terminology", "medical classification", "systematized nomenclature medicine"],
        "license": CC_BY_SA,
        "pages": wiki(
            "SNOMED_CT",
            "Systematized_Nomenclature_of_Medicine",
            "Medical_classification",
            "Terminology",
            "Controlled_vocabulary",
            "Ontology_(information_science)",
        ),
    },
    "icd-coding": {
        "tags": ["icd coding", "diagnosis code", "disease classification", "medical billing code"],
        "license": CC_BY_SA,
        "pages": wiki(
            "ICD-10",
            "International_Classification_of_Diseases",
            "ICD-11",
            "Diagnosis_code",
            "Medical_billing",
            "Medical_classification",
        ),
    },
    "quantitative-finance": {
        "tags": ["quantitative finance", "mathematical finance", "financial modeling", "derivatives pricing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Quantitative_analysis_(finance)",
            "Mathematical_finance",
            "Black%E2%80%93Scholes_model",
            "Monte_Carlo_methods_in_finance",
            "Stochastic_calculus",
            "Financial_modeling",
        ),
    },
    "algorithmic-trading": {
        "tags": ["algorithmic trading", "high frequency trading", "electronic trading", "market microstructure"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Algorithmic_trading",
            "High-frequency_trading",
            "Order_book",
            "Market_maker",
            "Electronic_trading_platform",
            "Dark_pool",
        ),
    },
    "financial-fix-protocol": {
        "tags": ["fix protocol", "financial information exchange", "trade messaging", "straight through processing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Financial_Information_eXchange",
            "FIX_protocol",
            "Straight-through_processing",
            "Electronic_trading_platform",
            "Order_book",
            "Trade_(financial_instrument)",
        ),
    },
    "swift-banking": {
        "tags": ["swift banking", "interbank messaging", "wire transfer", "bic code"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Society_for_Worldwide_Interbank_Financial_Telecommunication",
            "ISO_9362",
            "Wire_transfer",
            "Correspondent_account",
            "Payment_system",
            "Clearing_(finance)",
        ),
    },
    "iso-20022": {
        "tags": ["iso 20022", "payment messaging standard", "financial messaging", "sepa payments"],
        "license": CC_BY_SA,
        "pages": wiki(
            "ISO_20022",
            "Single_Euro_Payments_Area",
            "Real-time_gross_settlement",
            "Payment_system",
            "Wire_transfer",
            "Automated_clearing_house",
        ),
    },
    "payment-card-processing": {
        "tags": ["payment card processing", "pci dss", "emv chip", "card tokenization"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Payment_Card_Industry_Data_Security_Standard",
            "EMV",
            "Card_security_code",
            "Payment_processor",
            "Tokenization_(data_security)",
            "Credit_card",
        ),
    },
    "double-entry-accounting": {
        "tags": ["double entry bookkeeping", "general ledger", "debits credits", "chart of accounts"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Double-entry_bookkeeping",
            "General_ledger",
            "Debits_and_credits",
            "Accounting_software",
            "Trial_balance",
            "Chart_of_accounts",
        ),
    },
    "blockchain-settlement": {
        "tags": ["blockchain settlement", "distributed ledger", "smart contract", "securities settlement"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Blockchain",
            "Distributed_ledger",
            "Smart_contract",
            "Settlement_(finance)",
            "Central_securities_depository",
            "Ethereum",
        ),
    },
    "actuarial-modeling": {
        "tags": ["actuarial science", "life table", "insurance reserving", "ruin theory"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Actuarial_science",
            "Actuary",
            "Life_table",
            "Solvency_II",
            "Reserve_(accounting)",
            "Ruin_theory",
        ),
    },
    "risk-modeling-finance": {
        "tags": ["financial risk modeling", "value at risk", "credit risk", "basel regulation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Risk_management",
            "Value_at_risk",
            "Credit_risk",
            "Market_risk",
            "Basel_III",
            "Expected_shortfall",
            "Stress_test_(financial)",
        ),
    },
    "geospatial-gis": {
        "tags": ["geospatial gis", "spatial analysis", "geographic information", "digital cartography"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Geographic_information_system",
            "Spatial_analysis",
            "Geographic_data_and_information",
            "Cartography",
            "Shapefile",
            "Spatial_reference_system",
        ),
    },
    "postgis": {
        "tags": ["postgis spatial", "spatial database", "geometry storage", "well known text"],
        "license": CC_BY_SA,
        "pages": wiki(
            "PostGIS",
            "Spatial_database",
            "Well-known_text_representation_of_geometry",
            "Spatial_reference_system",
            "Simple_Features",
        ) + ["https://postgis.net/documentation/"],
    },
    "gdal-geospatial": {
        "tags": ["gdal library", "raster geospatial", "geotiff format", "geospatial abstraction"],
        "license": CC_BY_SA,
        "pages": wiki(
            "GDAL",
            "Raster_graphics",
            "GeoTIFF",
            "Geographic_data_and_information",
            "Digital_elevation_model",
        ) + ["https://gdal.org/"],
    },
    "qgis": {
        "tags": ["qgis desktop", "open source gis", "geospatial software", "grass gis"],
        "license": CC_BY_SA,
        "pages": wiki(
            "QGIS",
            "Geographic_information_system_software",
            "GRASS_GIS",
            "Web_Feature_Service",
            "Geoserver",
        ) + ["https://qgis.org/en/site/"],
    },
    "spatial-indexing-rtree": {
        "tags": ["spatial indexing", "r-tree index", "quadtree structure", "nearest neighbor search"],
        "license": CC_BY_SA,
        "pages": wiki(
            "R-tree",
            "Spatial_index",
            "Quadtree",
            "K-d_tree",
            "Geohash",
            "Nearest_neighbor_search",
        ),
    },
    "map-projections": {
        "tags": ["map projection", "mercator projection", "coordinate reference system", "geodetic datum"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Map_projection",
            "Mercator_projection",
            "Universal_Transverse_Mercator_coordinate_system",
            "Web_Mercator_projection",
            "World_Geodetic_System",
            "Geographic_coordinate_system",
        ),
    },
    "geojson-format": {
        "tags": ["geojson format", "well known binary", "spatial data format", "simple features"],
        "license": CC_BY_SA,
        "pages": wiki(
            "GeoJSON",
            "Well-known_binary",
            "Keyhole_Markup_Language",
            "GPX",
            "Simple_Features",
            "Geography_Markup_Language",
        ),
    },
    "gps-positioning": {
        "tags": ["gps positioning", "satellite navigation", "gnss positioning", "nmea sentence"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Global_Positioning_System",
            "Satellite_navigation",
            "GNSS_positioning",
            "NMEA_0183",
            "Assisted_GNSS",
            "Trilateration",
        ),
    },
    "routing-osrm": {
        "tags": ["osrm routing", "route planning", "shortest path routing", "contraction hierarchies"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Open_Source_Routing_Machine",
            "Route_planning_software",
            "Shortest_path_problem",
            "Contraction_hierarchies",
            "Travelling_salesman_problem",
        ) + ["https://www.osrm.org/"],
    },
    "openstreetmap": {
        "tags": ["openstreetmap data", "volunteered geographic information", "overpass api", "web mapping"],
        "license": CC_BY_SA,
        "pages": wiki(
            "OpenStreetMap",
            "Volunteered_geographic_information",
            "Overpass_API",
            "Tag_(metadata)",
            "Web_mapping",
            "Point_of_interest",
        ),
    },
    "ecommerce-platform": {
        "tags": ["ecommerce platform", "online shopping", "digital storefront", "sales order"],
        "license": CC_BY_SA,
        "pages": wiki(
            "E-commerce",
            "Online_shopping",
            "Digital_wallet",
            "Sales_order",
            "Checkout",
            "Session_(computer_science)",
        ),
    },
    "shopping-cart-systems": {
        "tags": ["shopping cart software", "cart checkout", "session state cart", "ecommerce cart"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Shopping_cart_software",
            "Comparison_of_shopping_cart_software",
            "Shopping_cart",
            "Checkout",
            "Session_(computer_science)",
            "HTTP_cookie",
        ),
    },
    "inventory-management": {
        "tags": ["inventory management", "stock control", "warehouse management", "economic order quantity"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Inventory_management_software",
            "Inventory_control",
            "Stock_keeping_unit",
            "Warehouse_management_system",
            "Barcode",
            "Economic_order_quantity",
        ),
    },
    "payment-gateway-integration": {
        "tags": ["payment gateway", "merchant account", "3-d secure", "chargeback handling"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Payment_gateway",
            "Merchant_account",
            "3-D_Secure",
            "Chargeback",
            "Acquiring_bank",
            "Payment_processor",
        ),
    },
    "wordpress-cms": {
        "tags": ["wordpress cms", "content management system", "wordpress plugin", "wordpress theme"],
        "license": CC_BY_SA,
        "pages": wiki(
            "WordPress",
            "Content_management_system",
            "Plugin_(computing)",
            "Theme_(computing)",
            "Blog_software",
            "PHP",
        ),
    },
    "drupal-cms": {
        "tags": ["drupal cms", "web content management", "drupal module", "content taxonomy"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Drupal",
            "Web_content_management_system",
            "Taxonomy_(general)",
            "Module_(programming)",
            "Content_management_system",
            "Content_management_framework",
        ),
    },
    "headless-cms": {
        "tags": ["headless cms", "static site generator", "jamstack architecture", "decoupled frontend"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Headless_content_management_system",
            "Static_site_generator",
            "Jamstack",
            "Front_and_back_ends",
            "Web_template_system",
            "GraphQL",
        ),
    },
    "ecommerce-magento": {
        "tags": ["magento commerce", "php ecommerce", "online storefront", "shopping cart platform"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Magento",
            "E-commerce",
            "PHP",
            "Shopping_cart_software",
            "Comparison_of_content_management_systems",
            "Object%E2%80%93relational_mapping",
        ),
    },
    "erp-systems": {
        "tags": ["enterprise resource planning", "material requirements planning", "manufacturing resource planning", "business process software"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Enterprise_resource_planning",
            "Business_process",
            "Material_requirements_planning",
            "Manufacturing_resource_planning",
            "Business_software",
            "Business_intelligence",
        ),
    },
    "sap-erp": {
        "tags": ["sap erp", "sap hana", "abap language", "sap enterprise software"],
        "license": CC_BY_SA,
        "pages": wiki(
            "SAP_ERP",
            "SAP_SE",
            "SAP_HANA",
            "ABAP",
            "Enterprise_resource_planning",
            "SAP_NetWeaver",
        ),
    },
    "crm-systems": {
        "tags": ["customer relationship management", "sales force automation", "marketing automation", "lead management"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Customer_relationship_management",
            "Sales_force_management_system",
            "Marketing_automation",
            "Lead_management",
            "Contact_manager",
            "Sales_pipeline",
        ),
    },
    "salesforce-platform": {
        "tags": ["salesforce platform", "apex language", "multitenant saas", "platform as a service"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Salesforce",
            "Apex_(programming_language)",
            "Platform_as_a_service",
            "Multitenancy",
            "Customer_relationship_management",
            "Cloud_computing",
        ),
    },
    "supply-chain-software": {
        "tags": ["supply chain management", "demand forecasting", "logistics software", "bullwhip effect"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Supply_chain_management",
            "Logistics",
            "Demand_forecasting",
            "Procurement",
            "Bullwhip_effect",
            "Warehouse",
        ),
    },
    "telecom-5g": {
        "tags": ["5g network", "5g new radio", "network slicing", "millimeter wave 5g"],
        "license": CC_BY_SA,
        "pages": wiki(
            "5G",
            "5G_NR",
            "Network_slicing",
            "Millimeter_wave",
            "MIMO",
            "Beamforming",
            "Radio_access_network",
        ),
    },
    "lte-networks": {
        "tags": ["lte network", "4g mobile", "evolved packet core", "ofdm modulation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "LTE_(telecommunication)",
            "4G",
            "Orthogonal_frequency-division_multiplexing",
            "Evolved_Packet_Core",
            "Handover",
            "Carrier_aggregation",
            "Quadrature_amplitude_modulation",
        ),
    },
    "voip-systems": {
        "tags": ["voice over ip", "rtp transport", "voice over lte", "voip codec"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Voice_over_IP",
            "Real-time_Transport_Protocol",
            "Voice_over_LTE",
            "G.711",
            "Jitter",
            "Real-time_Transport_Control_Protocol",
            "Codec",
        ),
    },
    "sip-telephony": {
        "tags": ["sip protocol", "session initiation protocol", "ip multimedia subsystem", "session border controller"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Session_Initiation_Protocol",
            "Session_Description_Protocol",
            "IP_Multimedia_Subsystem",
            "Session_border_controller",
            "User_agent",
            "H.323",
        ),
    },
    "sms-gateways": {
        "tags": ["sms gateway", "short message service", "smsc center", "ss7 signalling"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Short_Message_Service",
            "Short_message_service_center",
            "Multimedia_Messaging_Service",
            "Signalling_System_No._7",
            "GSM",
            "Mobile_country_code",
        ),
    },
    "automotive-autosar": {
        "tags": ["autosar architecture", "automotive software", "electronic control unit", "automotive rtos"],
        "license": CC_BY_SA,
        "pages": wiki(
            "AUTOSAR",
            "Automotive_electronics",
            "Electronic_control_unit",
            "Embedded_software",
            "Real-time_operating_system",
            "Hardware_abstraction",
        ),
    },
    "iso-26262-safety": {
        "tags": ["iso 26262", "functional safety automotive", "automotive safety integrity level", "safety integrity level"],
        "license": CC_BY_SA,
        "pages": wiki(
            "ISO_26262",
            "Functional_safety",
            "Automotive_Safety_Integrity_Level",
            "Failure_mode_and_effects_analysis",
            "Safety_integrity_level",
            "Fault_tree_analysis",
            "Verification_and_validation",
        ),
    },
    "can-bus-automotive": {
        "tags": ["can bus", "automotive networking", "flexray protocol", "obd diagnostics"],
        "license": CC_BY_SA,
        "pages": wiki(
            "CAN_bus",
            "FlexRay",
            "Local_Interconnect_Network",
            "OBD-II_PIDs",
            "Automotive_Ethernet",
            "Vehicle_bus",
            "On-board_diagnostics",
        ),
    },
    "adas-systems": {
        "tags": ["advanced driver assistance", "adaptive cruise control", "lane departure warning", "sensor fusion adas"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Advanced_driver-assistance_system",
            "Adaptive_cruise_control",
            "Lane_departure_warning_system",
            "Automotive_night_vision",
            "Sensor_fusion",
            "Lidar",
        ),
    },
    "digital-twin": {
        "tags": ["digital twin", "cyber physical system", "simulation model", "predictive maintenance twin"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Digital_twin",
            "Simulation",
            "Cyber-physical_system",
            "Product_lifecycle",
            "Predictive_maintenance",
            "Internet_of_things",
        ),
    },
    "industrial-iot": {
        "tags": ["industrial internet of things", "industry 4.0", "opc ua", "mqtt telemetry"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Industrial_internet_of_things",
            "Industry_4.0",
            "OPC_Unified_Architecture",
            "MQTT",
            "Edge_computing",
            "Wireless_sensor_network",
            "Fieldbus",
        ),
    },
    "mes-manufacturing": {
        "tags": ["manufacturing execution system", "isa-95 standard", "shop floor control", "overall equipment effectiveness"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Manufacturing_execution_system",
            "ISA-95",
            "Programmable_logic_controller",
            "Overall_equipment_effectiveness",
            "Shop_floor",
            "Automation",
        ),
    },
    "scada-security": {
        "tags": ["scada security", "industrial control system", "modbus protocol", "distributed control system"],
        "license": CC_BY_SA,
        "pages": wiki(
            "SCADA",
            "Modbus",
            "Stuxnet",
            "Industrial_control_system",
            "Distributed_control_system",
            "Remote_terminal_unit",
            "DNP3",
        ),
    },
    "hvac-building-automation": {
        "tags": ["hvac control system", "building automation", "bacnet protocol", "knx standard"],
        "license": CC_BY_SA,
        "pages": wiki(
            "HVAC_control_system",
            "Building_automation",
            "BACnet",
            "KNX_(standard)",
            "LonWorks",
            "Heating,_ventilation,_and_air_conditioning",
        ),
    },
}
