"""The named-algorithm catalog: sorting, graph, string, numerical, geometric, crypto, ML."""

from .common import CC_BY_SA, wiki

DOMAINS = {
    "quicksort-algorithm": {
        "tags": ["quicksort algorithm", "divide and conquer", "partition scheme", "quickselect algorithm"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Quicksort",
            "Quickselect",
            "Dutch_national_flag_problem",
            "Median_of_medians",
            "Partition_(database)",
            "Divide-and-conquer_algorithm",
            "In-place_algorithm",
            "Comparison_sort",
        ),
    },
    "merge-sort-algorithm": {
        "tags": ["merge sort", "stable sort", "external sorting", "merge algorithm"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Merge_sort",
            "Merge_algorithm",
            "External_sorting",
            "Stable_sort",
            "Divide-and-conquer_algorithm",
            "Sorting_network",
            "Comparison_sort",
        ),
    },
    "heapsort-algorithm": {
        "tags": ["heapsort algorithm", "binary heap", "priority queue", "in place sorting"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Heapsort",
            "Binary_heap",
            "Priority_queue",
            "Fibonacci_heap",
            "In-place_algorithm",
            "Comparison_sort",
            "Adaptive_sort",
        ),
    },
    "radix-sort-algorithm": {
        "tags": ["radix sort", "non comparison sort", "least significant digit", "bucket distribution"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Radix_sort",
            "Least_significant_digit",
            "Bucket_sort",
            "Counting_sort",
            "Pigeonhole_sort",
            "Time_complexity",
        ),
    },
    "counting-sort-algorithm": {
        "tags": ["counting sort", "integer sorting", "stable sort", "pigeonhole principle"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Counting_sort",
            "Pigeonhole_sort",
            "Bucket_sort",
            "Stable_sort",
            "Radix_sort",
            "Non-comparison_sort",
        ),
    },
    "bucket-sort-algorithm": {
        "tags": ["bucket sort", "distribution sort", "uniform distribution", "insertion sort"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Bucket_sort",
            "Insertion_sort",
            "Counting_sort",
            "Radix_sort",
            "Sorting_algorithm",
            "Time_complexity",
        ),
    },
    "timsort-algorithm": {
        "tags": ["timsort algorithm", "adaptive sort", "merge sort", "stable sort"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Timsort",
            "Adaptive_sort",
            "Merge_sort",
            "Insertion_sort",
            "Stable_sort",
            "Best,_worst_and_average_case",
        ),
    },
    "introsort-algorithm": {
        "tags": ["introsort algorithm", "quicksort algorithm", "heapsort algorithm", "worst case bound"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Introsort",
            "Quicksort",
            "Heapsort",
            "Insertion_sort",
            "Best,_worst_and_average_case",
            "Comparison_sort",
        ),
    },
    "shellsort-algorithm": {
        "tags": ["shellsort algorithm", "gap sequence", "insertion sort", "in place algorithm"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Shellsort",
            "Insertion_sort",
            "Bubble_sort",
            "In-place_algorithm",
            "Comparison_sort",
            "Time_complexity",
        ),
    },
    "elementary-sorts": {
        "tags": ["insertion sort", "selection sort", "bubble sort", "cocktail shaker sort"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Insertion_sort",
            "Selection_sort",
            "Bubble_sort",
            "Cocktail_shaker_sort",
            "Cycle_sort",
            "Pancake_sorting",
            "Sorting_algorithm",
        ),
    },
    "binary-search-algorithm": {
        "tags": ["binary search", "sorted array", "logarithmic search", "search algorithm"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Binary_search",
            "Sorted_array",
            "Exponential_search",
            "Ternary_search",
            "Jump_search",
            "Fibonacci_search_technique",
            "Search_algorithm",
        ),
    },
    "interpolation-search-algorithm": {
        "tags": ["interpolation search", "binary search", "uniform distribution", "sorted array"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Interpolation_search",
            "Binary_search",
            "Exponential_search",
            "Sorted_array",
            "Jump_search",
            "Search_algorithm",
        ),
    },
    "dijkstra-shortest-path": {
        "tags": ["dijkstra algorithm", "shortest path", "graph traversal", "priority queue"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Dijkstra's_algorithm",
            "Shortest_path_problem",
            "Priority_queue",
            "Graph_traversal",
            "Weighted_graph",
            "K_shortest_path_routing",
        ),
    },
    "bellman-ford-algorithm": {
        "tags": ["bellman ford algorithm", "shortest path", "negative cycle", "relaxation step"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Bellman–Ford_algorithm",
            "Shortest_path_problem",
            "Negative_cycle",
            "Johnson's_algorithm",
            "Weighted_graph",
            "Directed_graph",
        ),
    },
    "floyd-warshall-algorithm": {
        "tags": ["floyd warshall algorithm", "all pairs shortest path", "dynamic programming", "transitive closure"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Floyd–Warshall_algorithm",
            "Shortest_path_problem",
            "Johnson's_algorithm",
            "Dynamic_programming",
            "Widest_path_problem",
            "Weighted_graph",
        ),
    },
    "a-star-search": {
        "tags": ["a star search", "admissible heuristic", "pathfinding algorithm", "best first search"],
        "license": CC_BY_SA,
        "pages": wiki(
            "A*_search_algorithm",
            "Admissible_heuristic",
            "Heuristic_(computer_science)",
            "Best-first_search",
            "Iterative_deepening_A*",
            "Pathfinding",
            "Motion_planning",
        ),
    },
    "breadth-first-search-algorithm": {
        "tags": ["breadth first search", "graph traversal", "shortest path", "queue data structure"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Breadth-first_search",
            "Graph_traversal",
            "Queue_(abstract_data_type)",
            "Shortest_path_problem",
            "Tree_traversal",
            "Component_(graph_theory)",
        ),
    },
    "depth-first-search-algorithm": {
        "tags": ["depth first search", "graph traversal", "backtracking search", "stack data structure"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Depth-first_search",
            "Graph_traversal",
            "Stack_(abstract_data_type)",
            "Tree_traversal",
            "Iterative_deepening_depth-first_search",
            "Cycle_(graph_theory)",
        ),
    },
    "topological-sort-algorithm": {
        "tags": ["topological sorting", "directed acyclic graph", "kahn algorithm", "dependency graph"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Topological_sorting",
            "Kahn's_algorithm",
            "Directed_acyclic_graph",
            "Dependency_graph",
            "Depth-first_search",
            "Cycle_(graph_theory)",
        ),
    },
    "kruskal-mst": {
        "tags": ["kruskal algorithm", "minimum spanning tree", "greedy algorithm", "disjoint set"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Kruskal's_algorithm",
            "Minimum_spanning_tree",
            "Spanning_tree",
            "Greedy_algorithm",
            "Disjoint-set_data_structure",
            "Reverse-delete_algorithm",
        ),
    },
    "prim-mst": {
        "tags": ["prim algorithm", "minimum spanning tree", "greedy algorithm", "priority queue"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Prim's_algorithm",
            "Minimum_spanning_tree",
            "Borůvka's_algorithm",
            "Spanning_tree",
            "Greedy_algorithm",
            "Cut_(graph_theory)",
        ),
    },
    "tarjan-scc": {
        "tags": ["tarjan algorithm", "strongly connected component", "depth first search", "directed graph"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Tarjan's_strongly_connected_components_algorithm",
            "Strongly_connected_component",
            "Path-based_strong_component_algorithm",
            "Depth-first_search",
            "Directed_graph",
            "Component_(graph_theory)",
        ),
    },
    "kosaraju-scc": {
        "tags": ["kosaraju algorithm", "strongly connected component", "graph transpose", "directed graph"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Kosaraju's_algorithm",
            "Strongly_connected_component",
            "Tarjan's_strongly_connected_components_algorithm",
            "Depth-first_search",
            "Directed_graph",
            "Connected_component_(graph_theory)",
        ),
    },
    "ford-fulkerson-maxflow": {
        "tags": ["ford fulkerson algorithm", "maximum flow", "flow network", "augmenting path"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ford–Fulkerson_algorithm",
            "Maximum_flow_problem",
            "Flow_network",
            "Augmenting_path",
            "Residual_graph",
            "Max-flow_min-cut_theorem",
        ),
    },
    "edmonds-karp-algorithm": {
        "tags": ["edmonds karp algorithm", "maximum flow", "breadth first search", "shortest augmenting path"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Edmonds–Karp_algorithm",
            "Ford–Fulkerson_algorithm",
            "Maximum_flow_problem",
            "Breadth-first_search",
            "Flow_network",
            "Augmenting_path",
        ),
    },
    "dinic-algorithm": {
        "tags": ["dinic algorithm", "maximum flow", "blocking flow", "level graph"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Dinic's_algorithm",
            "Maximum_flow_problem",
            "Push–relabel_maximum_flow_algorithm",
            "Flow_network",
            "Residual_graph",
            "Max-flow_min-cut_theorem",
        ),
    },
    "hungarian-algorithm": {
        "tags": ["hungarian algorithm", "assignment problem", "bipartite matching", "combinatorial optimization"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Hungarian_algorithm",
            "Assignment_problem",
            "Bipartite_graph",
            "Matching_(graph_theory)",
            "Kőnig's_theorem_(graph_theory)",
            "Maximum_cardinality_matching",
        ),
    },
    "hopcroft-karp-algorithm": {
        "tags": ["hopcroft karp algorithm", "bipartite matching", "augmenting path", "maximum cardinality matching"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Hopcroft–Karp_algorithm",
            "Maximum_cardinality_matching",
            "Bipartite_graph",
            "Matching_(graph_theory)",
            "Blossom_algorithm",
            "Augmenting_path",
        ),
    },
    "kmp-string-matching": {
        "tags": ["knuth morris pratt", "string searching algorithm", "prefix function", "pattern matching"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Knuth–Morris–Pratt_algorithm",
            "String-searching_algorithm",
            "Finite-state_machine",
            "Boyer–Moore_string-search_algorithm",
            "Rabin–Karp_algorithm",
        ),
    },
    "boyer-moore-string": {
        "tags": ["boyer moore algorithm", "string searching algorithm", "bad character rule", "pattern matching"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Boyer–Moore_string-search_algorithm",
            "String-searching_algorithm",
            "Knuth–Morris–Pratt_algorithm",
            "Aho–Corasick_algorithm",
            "Substring_index",
        ),
    },
    "rabin-karp-algorithm": {
        "tags": ["rabin karp algorithm", "rolling hash", "string searching algorithm", "rabin fingerprint"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Rabin–Karp_algorithm",
            "Rolling_hash",
            "Rabin_fingerprint",
            "String-searching_algorithm",
            "Hash_function",
            "Knuth–Morris–Pratt_algorithm",
        ),
    },
    "aho-corasick-algorithm": {
        "tags": ["aho corasick algorithm", "multi pattern matching", "trie data structure", "finite state machine"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Aho–Corasick_algorithm",
            "Trie",
            "Finite-state_machine",
            "String-searching_algorithm",
            "Deterministic_finite_automaton",
            "Boyer–Moore_string-search_algorithm",
        ),
    },
    "suffix-array-algorithm": {
        "tags": ["suffix array", "substring index", "longest common prefix array", "string matching"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Suffix_array",
            "LCP_array",
            "Substring_index",
            "Suffix_tree",
            "Burrows–Wheeler_transform",
            "Longest_common_substring",
        ),
    },
    "suffix-tree-algorithm": {
        "tags": ["suffix tree", "ukkonen algorithm", "substring index", "generalized suffix tree"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Suffix_tree",
            "Ukkonen's_algorithm",
            "Generalized_suffix_tree",
            "Suffix_automaton",
            "Substring_index",
            "Longest_common_substring",
        ),
    },
    "levenshtein-distance": {
        "tags": ["levenshtein distance", "edit distance", "hamming distance", "wagner fischer algorithm"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Levenshtein_distance",
            "Edit_distance",
            "Hamming_distance",
            "Wagner–Fischer_algorithm",
            "Dynamic_programming",
        ),
    },
    "longest-common-subsequence": {
        "tags": ["longest common subsequence", "sequence alignment", "dynamic programming", "diff algorithm"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Longest_common_subsequence",
            "Longest_common_substring",
            "Sequence_alignment",
            "Dynamic_programming",
            "Edit_distance",
        ),
    },
    "sequence-alignment-dp": {
        "tags": ["sequence alignment", "needleman wunsch algorithm", "smith waterman algorithm", "dynamic programming"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Sequence_alignment",
            "Needleman–Wunsch_algorithm",
            "Smith–Waterman_algorithm",
            "Levenshtein_distance",
            "Dynamic_programming",
        ),
    },
    "knapsack-dp": {
        "tags": ["knapsack problem", "dynamic programming", "combinatorial optimization", "change making problem"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Knapsack_problem",
            "Dynamic_programming",
            "Change-making_problem",
            "Optimal_substructure",
            "Overlapping_subproblems",
            "Greedy_algorithm",
        ),
    },
    "dynamic-programming-foundations": {
        "tags": ["dynamic programming", "memoization technique", "optimal substructure", "bellman equation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Dynamic_programming",
            "Memoization",
            "Optimal_substructure",
            "Overlapping_subproblems",
            "Bellman_equation",
            "Cutting_stock_problem",
        ),
    },
    "matrix-chain-multiplication": {
        "tags": ["matrix chain multiplication", "dynamic programming", "parenthesization order", "optimal substructure"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Matrix_chain_multiplication",
            "Dynamic_programming",
            "Optimal_substructure",
            "Matrix_multiplication_algorithm",
            "Time_complexity",
        ),
    },
    "euclidean-gcd": {
        "tags": ["euclidean algorithm", "greatest common divisor", "modular arithmetic", "number theory"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Euclidean_algorithm",
            "Greatest_common_divisor",
            "Continued_fraction",
            "Modular_arithmetic",
            "Number_theory",
        ),
    },
    "extended-euclidean": {
        "tags": ["extended euclidean algorithm", "bezout identity", "modular multiplicative inverse", "chinese remainder theorem"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Extended_Euclidean_algorithm",
            "Bézout's_identity",
            "Modular_multiplicative_inverse",
            "Chinese_remainder_theorem",
            "Greatest_common_divisor",
        ),
    },
    "fast-exponentiation": {
        "tags": ["exponentiation by squaring", "modular exponentiation", "binary exponentiation", "fermat little theorem"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Exponentiation_by_squaring",
            "Modular_exponentiation",
            "Modular_arithmetic",
            "Fermat's_little_theorem",
            "Euler's_totient_function",
        ),
    },
    "miller-rabin-primality": {
        "tags": ["miller rabin primality test", "probabilistic primality test", "fermat little theorem", "carmichael number"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Miller–Rabin_primality_test",
            "Primality_test",
            "Solovay–Strassen_primality_test",
            "Fermat's_little_theorem",
            "Carmichael_number",
            "AKS_primality_test",
        ),
    },
    "prime-sieve-algorithms": {
        "tags": ["sieve of eratosthenes", "sieve of atkin", "wheel factorization", "prime generation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Sieve_of_Eratosthenes",
            "Sieve_of_Atkin",
            "Wheel_factorization",
            "Generation_of_primes",
            "Prime-counting_function",
            "Trial_division",
        ),
    },
    "karatsuba-multiplication": {
        "tags": ["karatsuba algorithm", "fast multiplication", "toom cook multiplication", "divide and conquer"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Karatsuba_algorithm",
            "Multiplication_algorithm",
            "Toom–Cook_multiplication",
            "Schönhage–Strassen_algorithm",
            "Divide-and-conquer_algorithm",
        ),
    },
    "strassen-matrix": {
        "tags": ["strassen algorithm", "matrix multiplication", "divide and conquer", "coppersmith winograd"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Strassen_algorithm",
            "Matrix_multiplication_algorithm",
            "Coppersmith–Winograd_algorithm",
            "Divide-and-conquer_algorithm",
            "Time_complexity",
        ),
    },
    "fft-algorithm": {
        "tags": ["fast fourier transform", "cooley tukey algorithm", "discrete fourier transform", "convolution theorem"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Fast_Fourier_transform",
            "Cooley–Tukey_FFT_algorithm",
            "Discrete_Fourier_transform",
            "Convolution_theorem",
            "Butterfly_diagram",
            "Bluestein's_FFT_algorithm",
            "Number-theoretic_transform",
        ),
    },
    "gaussian-elimination-algo": {
        "tags": ["gaussian elimination", "system of linear equations", "lu decomposition", "row echelon form"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Gaussian_elimination",
            "System_of_linear_equations",
            "LU_decomposition",
            "Row_echelon_form",
            "Pivot_element",
            "Cramer's_rule",
        ),
    },
    "matrix-decompositions": {
        "tags": ["lu decomposition", "cholesky decomposition", "qr decomposition", "numerical stability"],
        "license": CC_BY_SA,
        "pages": wiki(
            "LU_decomposition",
            "Cholesky_decomposition",
            "QR_decomposition",
            "Conjugate_gradient_method",
            "Numerical_stability",
        ),
    },
    "newton-raphson-method": {
        "tags": ["newton method", "root finding algorithm", "secant method", "rate of convergence"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Newton's_method",
            "Root-finding_algorithm",
            "Secant_method",
            "Bisection_method",
            "Fixed-point_iteration",
            "Halley's_method",
            "Rate_of_convergence",
        ),
    },
    "simplex-algorithm": {
        "tags": ["simplex algorithm", "linear programming", "interior point method", "duality theorem"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Simplex_algorithm",
            "Linear_programming",
            "Interior-point_method",
            "Duality_(optimization)",
            "Karmarkar's_algorithm",
            "Ellipsoid_method",
            "Linear_inequality",
        ),
    },
    "gradient-descent-algo": {
        "tags": ["gradient descent", "stochastic gradient descent", "backpropagation algorithm", "convex optimization"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Gradient_descent",
            "Stochastic_gradient_descent",
            "Backpropagation",
            "Loss_function",
            "Learning_rate",
            "Convex_optimization",
        ),
    },
    "metaheuristic-optimization": {
        "tags": ["simulated annealing", "genetic algorithm", "ant colony optimization", "cutting plane method"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Simulated_annealing",
            "Genetic_algorithm",
            "Ant_colony_optimization_algorithms",
            "Cutting-plane_method",
            "Mathematical_optimization",
        ),
    },
    "expectation-maximization": {
        "tags": ["expectation maximization algorithm", "gaussian mixture model", "maximum likelihood estimation", "latent variable"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Expectation–maximization_algorithm",
            "Gaussian_mixture_model",
            "Mixture_model",
            "Maximum_likelihood_estimation",
            "Latent_variable",
            "Jensen's_inequality",
        ),
    },
    "viterbi-algorithm": {
        "tags": ["viterbi algorithm", "hidden markov model", "dynamic programming", "forward algorithm"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Viterbi_algorithm",
            "Hidden_Markov_model",
            "Baum–Welch_algorithm",
            "Forward_algorithm",
            "Dynamic_programming",
            "Convolutional_code",
        ),
    },
    "pagerank-algorithm": {
        "tags": ["pagerank algorithm", "link analysis", "power iteration", "markov chain"],
        "license": CC_BY_SA,
        "pages": wiki(
            "PageRank",
            "Link_analysis",
            "Power_iteration",
            "Eigenvector_centrality",
            "Markov_chain",
            "Random_walk",
            "Centrality",
        ),
    },
    "union-find-algorithm": {
        "tags": ["disjoint set data structure", "union by rank", "amortized analysis", "connected components"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Disjoint-set_data_structure",
            "Amortized_analysis",
            "Connected_component_(graph_theory)",
            "Ackermann_function",
            "Kruskal's_algorithm",
        ),
    },
    "reservoir-sampling": {
        "tags": ["reservoir sampling", "streaming algorithm", "simple random sample", "online algorithm"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Reservoir_sampling",
            "Streaming_algorithm",
            "Simple_random_sample",
            "Online_algorithm",
            "Sampling_(statistics)",
        ),
    },
    "bloom-filter-algorithm": {
        "tags": ["bloom filter", "probabilistic data structure", "cuckoo filter", "false positive rate"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Bloom_filter",
            "Cuckoo_filter",
            "Count–min_sketch",
            "HyperLogLog",
            "Hash_function",
            "False_positives_and_false_negatives",
        ),
    },
    "consistent-hashing-algo": {
        "tags": ["consistent hashing", "distributed hash table", "rendezvous hashing", "load balancing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Consistent_hashing",
            "Distributed_hash_table",
            "Rendezvous_hashing",
            "Hash_table",
            "Load_balancing_(computing)",
        ),
    },
    "probabilistic-sketches": {
        "tags": ["minhash sketch", "locality sensitive hashing", "hyperloglog estimator", "feature hashing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "MinHash",
            "Locality-sensitive_hashing",
            "HyperLogLog",
            "Feature_hashing",
            "Count–min_sketch",
        ),
    },
    "rsa-algorithm-steps": {
        "tags": ["rsa cryptosystem", "public key cryptography", "integer factorization", "trapdoor function"],
        "license": CC_BY_SA,
        "pages": wiki(
            "RSA_(cryptosystem)",
            "Public-key_cryptography",
            "Integer_factorization",
            "Euler's_totient_function",
            "Optimal_asymmetric_encryption_padding",
            "Trapdoor_function",
        ),
    },
    "diffie-hellman-exchange": {
        "tags": ["diffie hellman key exchange", "discrete logarithm", "elliptic curve diffie hellman", "forward secrecy"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Diffie–Hellman_key_exchange",
            "Discrete_logarithm",
            "Elliptic-curve_Diffie–Hellman",
            "Key_exchange",
            "Forward_secrecy",
            "Man-in-the-middle_attack",
        ),
    },
}
