"""AI model architectures, training/inference techniques, and serving."""

from .common import CC_BY_SA, WIKI, wiki

DOMAINS = {
    "bert-model": {
        "tags": ["bert model", "bidirectional transformer", "masked language model", "pretrained encoder"],
        "license": CC_BY_SA,
        "pages": wiki(
            "BERT_(language_model)",
            "Transformer_(deep_learning_architecture)",
            "Language_model",
            "Word_embedding",
            "Fine-tuning_(deep_learning)",
            "Natural_language_processing",
        ),
    },
    "gpt-architecture": {
        "tags": ["gpt architecture", "generative pretrained transformer", "autoregressive language model", "decoder only model"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Generative_pre-trained_transformer",
            "GPT-2",
            "GPT-3",
            "GPT-4",
            "Large_language_model",
            "Autoregressive_model",
        ),
    },
    "t5-model": {
        "tags": ["t5 model", "text to text transformer", "sequence to sequence model", "transfer learning"],
        "license": CC_BY_SA,
        "pages": wiki(
            "T5_(language_model)",
            "Seq2seq",
            "Transformer_(deep_learning_architecture)",
            "Transfer_learning",
            "Natural_language_generation",
            "Language_model",
        ),
    },
    "vision-transformer": {
        "tags": ["vision transformer", "image classification model", "patch embedding", "self attention vision"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Vision_transformer",
            "Convolutional_neural_network",
            "Computer_vision",
            "Image_classification",
            "Attention_(machine_learning)",
            "Transformer_(deep_learning_architecture)",
        ),
    },
    "clip-model": {
        "tags": ["clip model", "contrastive language image", "multimodal embedding", "zero shot classification"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Contrastive_Language-Image_Pretraining",
            "Contrastive_learning",
            "Multimodal_learning",
            "Zero-shot_learning",
            "Computer_vision",
            "Word_embedding",
        ),
    },
    "whisper-asr": {
        "tags": ["whisper model", "automatic speech recognition", "audio transcription", "speech to text"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Whisper_(speech_recognition_system)",
            "Speech_recognition",
            "Automatic_speech_recognition",
            "Connectionist_temporal_classification",
            "Transformer_(deep_learning_architecture)",
            "OpenAI",
        ),
    },
    "segment-anything": {
        "tags": ["segment anything", "promptable image segmentation", "object detection model", "semantic segmentation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Image_segmentation",
            "Semantic_segmentation",
            "Object_detection",
            "Computer_vision",
            "Vision_transformer",
            "Mask_(computing)",
        ),
    },
    "stable-diffusion-model": {
        "tags": ["stable diffusion", "latent diffusion model", "text to image generation", "denoising diffusion"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Stable_Diffusion",
            "Latent_diffusion_model",
            "Diffusion_model",
            "Text-to-image_model",
            "U-Net",
            "Generative_artificial_intelligence",
        ),
    },
    "dalle-model": {
        "tags": ["dalle model", "text to image generation", "generative image model", "multimodal generation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "DALL-E",
            "Text-to-image_generation",
            "Text-to-image_model",
            "Variational_autoencoder",
            "Generative_artificial_intelligence",
            "OpenAI",
        ),
    },
    "llama-model": {
        "tags": ["llama model", "open weight language model", "meta ai model", "foundation model"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Llama_(language_model)",
            "LLaMA",
            "Large_language_model",
            "Meta_AI",
            "Open-source_artificial_intelligence",
            "Foundation_model",
        ),
    },
    "mixtral-model": {
        "tags": ["mixtral model", "sparse mixture of experts", "mistral ai model", "sparse expert routing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Mistral_AI",
            "Mixture_of_experts",
            "Large_language_model",
            "Transformer_(deep_learning_architecture)",
            "Open-source_artificial_intelligence",
            "Foundation_model",
        ),
    },
    "diffusion-models": {
        "tags": ["diffusion model", "denoising diffusion", "score based model", "generative markov process"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Diffusion_model",
            "Diffusion_model_(machine_learning)",
            "Latent_diffusion_model",
            "Markov_chain",
            "Variational_autoencoder",
            "Generative_artificial_intelligence",
        ),
    },
    "flow-matching": {
        "tags": ["flow matching", "continuous normalizing flow", "optimal transport", "generative ode"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Flow_matching",
            "Normalizing_flow",
            "Neural_ordinary_differential_equation",
            "Ordinary_differential_equation",
            "Optimal_transport",
            "Diffusion_model",
        ),
    },
    "autoregressive-models": {
        "tags": ["autoregressive model", "sequential prediction", "next token prediction", "time series model"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Autoregressive_model",
            "Autoregressive_integrated_moving_average",
            "Recurrent_neural_network",
            "Language_model",
            "Markov_chain",
            "Sampling_(statistics)",
        ),
    },
    "lora-peft": {
        "tags": ["low rank adaptation", "parameter efficient tuning", "adapter fine tuning", "rank decomposition"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Fine-tuning_(deep_learning)",
            "Transfer_learning",
            "Rank_(linear_algebra)",
            "Large_language_model",
            "Regularization_(mathematics)",
            "Backpropagation",
        ),
    },
    "dpo-alignment": {
        "tags": ["direct preference optimization", "preference learning", "human feedback alignment", "model alignment"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Direct_preference_optimization",
            "Preference_learning",
            "Reinforcement_learning_from_human_feedback",
            "AI_alignment",
            "Loss_function",
            "Fine-tuning_(deep_learning)",
        ),
    },
    "ppo-algorithm": {
        "tags": ["proximal policy optimization", "policy gradient method", "on policy learning", "reinforcement learning"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Proximal_policy_optimization",
            "Policy_gradient_method",
            "Reinforcement_learning",
            "Actor-critic_method",
            "Markov_decision_process",
            "Reinforcement_learning_from_human_feedback",
        ),
    },
    "dqn-algorithm": {
        "tags": ["deep q network", "value based learning", "experience replay", "temporal difference"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Deep_Q-learning",
            "Q-learning",
            "Temporal_difference_learning",
            "Deep_reinforcement_learning",
            "Bellman_equation",
            "Markov_decision_process",
        ),
    },
    "actor-critic": {
        "tags": ["actor critic method", "policy gradient method", "advantage estimation", "value function"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Actor-critic_algorithm",
            "Actor-critic_method",
            "Policy_gradient_method",
            "Reinforcement_learning",
            "Bellman_equation",
            "Markov_decision_process",
        ),
    },
    "soft-actor-critic": {
        "tags": ["soft actor critic", "maximum entropy learning", "off policy method", "stochastic policy"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Actor-critic_method",
            "Entropy_(information_theory)",
            "Model-free_(reinforcement_learning)",
            "Reinforcement_learning",
            "Policy_gradient_method",
            "Markov_decision_process",
        ),
    },
    "deep-reinforcement-learning": {
        "tags": ["deep reinforcement learning", "reward maximization", "policy learning", "agent environment loop"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Deep_reinforcement_learning",
            "Reinforcement_learning",
            "Q-learning",
            "Markov_decision_process",
            "AlphaGo",
            "Bellman_equation",
        ),
    },
    "multi-armed-bandit": {
        "tags": ["multi armed bandit", "exploration exploitation tradeoff", "thompson sampling", "regret minimization"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Multi-armed_bandit",
            "Thompson_sampling",
            "Exploration-exploitation_dilemma",
            "Regret_(decision_theory)",
            "Reinforcement_learning",
            "Bayesian_inference",
        ),
    },
    "bayesian-inference": {
        "tags": ["bayesian inference", "posterior probability", "prior distribution", "probabilistic reasoning"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Bayesian_inference",
            "Bayes'_theorem",
            "Prior_probability",
            "Posterior_probability",
            "Markov_chain_Monte_Carlo",
            "Variational_Bayesian_methods",
        ),
    },
    "probabilistic-programming": {
        "tags": ["probabilistic programming", "probabilistic graphical model", "bayesian network", "posterior inference"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Probabilistic_programming",
            "Probabilistic_graphical_model",
            "Graphical_model",
            "Bayesian_network",
            "Markov_chain_Monte_Carlo",
            "Bayesian_inference",
        ),
    },
    "pymc-sampling": {
        "tags": ["pymc library", "hamiltonian monte carlo", "bayesian modeling", "markov chain sampling"],
        "license": CC_BY_SA,
        "pages": wiki(
            "PyMC",
            "Hamiltonian_Monte_Carlo",
            "Markov_chain_Monte_Carlo",
            "Bayesian_inference",
            "Probabilistic_programming",
            "Variational_Bayesian_methods",
        ),
    },
    "stan-language": {
        "tags": ["stan language", "statistical modeling language", "hamiltonian monte carlo", "bayesian estimation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Stan_(software)",
            "Hamiltonian_Monte_Carlo",
            "Bayesian_inference",
            "Markov_chain_Monte_Carlo",
            "Probabilistic_programming",
            "Posterior_probability",
        ),
    },
    "gaussian-process": {
        "tags": ["gaussian process", "kernel method", "covariance function", "nonparametric regression"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Gaussian_process",
            "Kernel_method",
            "Covariance_function",
            "Nonparametric_statistics",
            "Regression_analysis",
            "Bayesian_inference",
        ),
    },
    "causal-inference": {
        "tags": ["causal inference", "confounding variable", "instrumental variable", "counterfactual reasoning"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Causal_inference",
            "Causality",
            "Confounding",
            "Instrumental_variables_estimation",
            "Randomized_controlled_trial",
            "Bayesian_network",
        ),
    },
    "contrastive-learning": {
        "tags": ["contrastive learning", "representation learning", "self supervised pretraining", "similarity objective"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Contrastive_learning",
            "Self-supervised_learning",
            "Representation_learning",
            "Contrastive_Language-Image_Pretraining",
            "Word_embedding",
            "Unsupervised_learning",
        ),
    },
    "self-supervised-learning": {
        "tags": ["self supervised learning", "pretext task", "representation learning", "unlabeled pretraining"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Self-supervised_learning",
            "Representation_learning",
            "Unsupervised_learning",
            "Contrastive_learning",
            "Autoencoder",
            "Transfer_learning",
        ),
    },
    "transfer-learning": {
        "tags": ["transfer learning", "pretrained model reuse", "domain adaptation", "feature transfer"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Transfer_learning",
            "Fine-tuning_(deep_learning)",
            "Representation_learning",
            "Foundation_model",
            "Supervised_learning",
            "Few-shot_learning",
        ),
    },
    "curriculum-learning": {
        "tags": ["curriculum learning", "ordered training examples", "difficulty scheduling", "staged training"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Curriculum_learning",
            "Supervised_learning",
            "Transfer_learning",
            "Gradient_descent",
            "Meta-learning_(computer_science)",
            "Overfitting",
        ),
    },
    "meta-learning": {
        "tags": ["meta learning", "learning to learn", "few shot adaptation", "task distribution"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Meta-learning_(computer_science)",
            "Few-shot_learning",
            "Transfer_learning",
            "Representation_learning",
            "Supervised_learning",
            "Gradient_descent",
        ),
    },
    "active-learning": {
        "tags": ["active learning", "query strategy", "sample selection", "labeling budget"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Active_learning_(machine_learning)",
            "Supervised_learning",
            "Statistical_classification",
            "Cross-validation_(statistics)",
            "Feature_selection",
            "Regression_analysis",
        ),
    },
    "ensemble-learning": {
        "tags": ["ensemble learning", "bootstrap aggregating", "model averaging", "weak learner combination"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ensemble_learning",
            "Bootstrap_aggregating",
            "Boosting_(machine_learning)",
            "Random_forest",
            "Decision_tree_learning",
            "Overfitting",
        ),
    },
    "gradient-boosting": {
        "tags": ["gradient boosting", "boosted decision trees", "additive model training", "xgboost library"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Gradient_boosting",
            "XGBoost",
            "Boosting_(machine_learning)",
            "AdaBoost",
            "Decision_tree_learning",
            "Loss_function",
        ),
    },
    "random-forest": {
        "tags": ["random forest", "decision tree ensemble", "bootstrap aggregating", "feature bagging"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Random_forest",
            "Decision_tree_learning",
            "Bootstrap_aggregating",
            "Ensemble_learning",
            "Overfitting",
            "Statistical_classification",
        ),
    },
    "support-vector-machine": {
        "tags": ["support vector machine", "maximum margin classifier", "kernel trick", "separating hyperplane"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Support_vector_machine",
            "Kernel_method",
            "Kernel_(statistics)",
            "Statistical_classification",
            "Hyperplane",
            "Regression_analysis",
        ),
    },
    "k-means-clustering": {
        "tags": ["k means clustering", "centroid assignment", "cluster analysis", "unsupervised partitioning"],
        "license": CC_BY_SA,
        "pages": wiki(
            "K-means_clustering",
            "Cluster_analysis",
            "Centroid",
            "DBSCAN",
            "Unsupervised_learning",
            "Dimensionality_reduction",
        ),
    },
    "dimensionality-reduction": {
        "tags": ["dimensionality reduction", "manifold learning", "feature projection", "low dimensional embedding"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Dimensionality_reduction",
            "Manifold_learning",
            "Nonlinear_dimensionality_reduction",
            "Feature_selection",
            "Principal_component_analysis",
            "Representation_learning",
        ),
    },
    "principal-component-analysis": {
        "tags": ["principal component analysis", "singular value decomposition", "eigenvalue decomposition", "variance projection"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Principal_component_analysis",
            "Singular_value_decomposition",
            "Eigenvalues_and_eigenvectors",
            "Covariance_matrix",
            "Dimensionality_reduction",
            "Feature_(machine_learning)",
        ),
    },
    "t-sne-embedding": {
        "tags": ["t sne embedding", "stochastic neighbor embedding", "high dimensional visualization", "nonlinear projection"],
        "license": CC_BY_SA,
        "pages": wiki(
            "T-distributed_stochastic_neighbor_embedding",
            "Nonlinear_dimensionality_reduction",
            "Dimensionality_reduction",
            "Data_visualization",
            "Perplexity",
            "Manifold_learning",
        ),
    },
    "umap-embedding": {
        "tags": ["umap projection", "manifold approximation", "topological embedding", "neighbor graph"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Uniform_manifold_approximation_and_projection",
            "Manifold_learning",
            "Topological_data_analysis",
            "Nearest_neighbor_graph",
            "Dimensionality_reduction",
            "Data_visualization",
        ),
    },
    "attention-variants": {
        "tags": ["attention mechanism", "multi head attention", "flash attention", "scaled dot product"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Attention_(machine_learning)",
            "Self-attention",
            "Multi-head_attention",
            "FlashAttention",
            "Softmax_function",
            "Transformer_(deep_learning_architecture)",
        ),
    },
    "positional-encoding": {
        "tags": ["positional encoding", "rotary position embedding", "sequence order signal", "sinusoidal encoding"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Rotary_positional_embedding",
            "Sinusoid",
            "Transformer_(deep_learning_architecture)",
            "Attention_(machine_learning)",
            "Word_embedding",
            "Self-attention",
        ),
    },
    "tokenization-nlp": {
        "tags": ["tokenization nlp", "lexical analysis", "subword units", "text preprocessing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Lexical_analysis",
            "Byte_pair_encoding",
            "N-gram",
            "Word_n-gram_language_model",
            "Natural_language_processing",
            "Language_model",
        ),
    },
    "byte-pair-encoding": {
        "tags": ["byte pair encoding", "subword tokenization", "vocabulary merging", "compression tokenizer"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Byte_pair_encoding",
            "Byte-pair_encoding",
            "Lexical_analysis",
            "N-gram",
            "Natural_language_processing",
            "Language_model",
        ),
    },
    "beam-search-decoding": {
        "tags": ["beam search decoding", "nucleus sampling", "greedy decoding", "sequence generation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Beam_search",
            "Nucleus_sampling",
            "Top-p_sampling",
            "Greedy_algorithm",
            "Viterbi_algorithm",
            "Natural_language_generation",
        ),
    },
    "model-serving": {
        "tags": ["model serving", "inference deployment", "request batching", "prediction endpoint"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Inference_engine",
            "Web_server",
            "Representational_state_transfer",
            "Load_balancing_(computing)",
            "Microservices",
            "Docker_(software)",
        ),
    },
    "tensorrt-llm": {
        "tags": ["tensorrt inference", "gpu kernel optimization", "half precision inference", "cuda acceleration"],
        "license": CC_BY_SA,
        "pages": wiki(
            "TensorRT",
            "CUDA",
            "Half-precision_floating-point_format",
            "General-purpose_computing_on_graphics_processing_units",
            "Quantization_(signal_processing)",
            "Nvidia",
        ),
    },
    "text-generation-inference": {
        "tags": ["text generation inference", "token streaming server", "continuous batching", "throughput optimization"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Text_generation",
            "Natural_language_generation",
            "Inference_engine",
            "Throughput",
            "Latency_(engineering)",
            "Application_checkpointing",
        ),
    },
    "mlir-compiler": {
        "tags": ["mlir compiler", "intermediate representation", "compiler optimization", "domain specific dialect"],
        "license": CC_BY_SA,
        "pages": wiki(
            "MLIR_(software)",
            "LLVM",
            "Intermediate_representation",
            "Compiler",
            "Compiler_optimization",
            "Domain-specific_language",
        ),
    },
    "xla-compiler": {
        "tags": ["xla compiler", "linear algebra compilation", "just in time compilation", "kernel fusion"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Accelerated_Linear_Algebra",
            "Just-in-time_compilation",
            "Basic_Linear_Algebra_Subprograms",
            "Compiler_optimization",
            "TensorFlow",
            "Graph_(abstract_data_type)",
        ),
    },
    "model-evaluation-metrics": {
        "tags": ["model evaluation metrics", "precision and recall", "confusion matrix", "cross validation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Precision_and_recall",
            "F-score",
            "Receiver_operating_characteristic",
            "Confusion_matrix",
            "Cross-validation_(statistics)",
            "BLEU",
        ),
    },
    "hallucination-mitigation": {
        "tags": ["hallucination mitigation", "retrieval augmented grounding", "fact checking", "factual consistency"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Hallucination_(artificial_intelligence)",
            "Retrieval-augmented_generation",
            "Fact-checking",
            "Symbol_grounding_problem",
            "Large_language_model",
            "Natural_language_generation",
        ),
    },
    "ai-guardrails": {
        "tags": ["ai guardrails", "content moderation", "prompt injection defense", "safety filtering"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Guardrail",
            "AI_safety",
            "AI_alignment",
            "Content_moderation",
            "Prompt_injection",
            "Hallucination_(artificial_intelligence)",
        ),
    },
    "model-context-protocol": {
        "tags": ["model context protocol", "tool calling standard", "json rpc interface", "llm interoperability"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Model_Context_Protocol",
            "Anthropic",
            "Application_programming_interface",
            "JSON-RPC",
            "Interoperability",
            "Large_language_model",
        ),
    },
    "reasoning-language-model": {
        "tags": ["reasoning language model", "chain of thought prompting", "inference time compute", "step by step reasoning"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Reasoning_language_model",
            "Chain-of-thought_prompting",
            "Large_language_model",
            "Prompt_engineering",
            "DeepSeek",
            "Foundation_model",
        ),
    },
}
