"""Platform APIs (Win32/Cocoa/Android/iOS), Linux distributions, packaging, and boot."""

from .common import CC_BY_SA, wiki

DOMAINS = {
    "win32-api": {
        "tags": ["win32 api", "windows api", "windows programming", "dynamic-link library"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Windows_API",
            "Microsoft_Windows",
            "Dynamic-link_library",
            "Windows_Runtime",
            "Microsoft_Foundation_Class_Library",
            "Windows_Presentation_Foundation",
            "Handle_(computing)",
        ),
    },
    "windows-registry": {
        "tags": ["windows registry", "registry editor", "registry hive", "group policy"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Windows_Registry",
            "Regedit",
            "Group_Policy",
            "INI_file",
            "Microsoft_Windows",
            "Configuration_file",
        ),
    },
    "powershell-dsc": {
        "tags": ["powershell scripting", "desired state configuration", "windows automation", "cmdlet pipeline"],
        "license": CC_BY_SA,
        "pages": wiki(
            "PowerShell",
            "Windows_Management_Instrumentation",
            "Cmdlet",
            "Configuration_management",
            "Infrastructure_as_code",
            "Scripting_language",
        ),
    },
    "windows-services": {
        "tags": ["windows service", "service control manager", "svchost process", "task scheduler"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Windows_service",
            "Service_Control_Manager",
            "Svchost.exe",
            "Windows_Task_Scheduler",
            "Daemon_(computing)",
            "Background_process",
        ),
    },
    "wsl-subsystem": {
        "tags": ["windows subsystem for linux", "wsl subsystem", "subsystem for android", "windows terminal"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Windows_Subsystem_for_Linux",
            "Windows_Subsystem_for_Android",
            "Cygwin",
            "Windows_Terminal",
            "Hyper-V",
            "Compatibility_layer",
        ),
    },
    "com-automation": {
        "tags": ["component object model", "ole automation", "distributed com", "activex control"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Component_Object_Model",
            "OLE_Automation",
            "Distributed_Component_Object_Model",
            "ActiveX",
            "Object_Linking_and_Embedding",
            "Interface_(object-oriented_programming)",
        ),
    },
    "dotnet-clr": {
        "tags": ["common language runtime", "dotnet framework", "common intermediate language", "managed code"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Common_Language_Runtime",
            ".NET_Framework",
            "Common_Intermediate_Language",
            "Common_Type_System",
            "Just-in-time_compilation",
            "Garbage_collection_(computer_science)",
            ".NET",
        ),
    },
    "cocoa-framework": {
        "tags": ["cocoa framework", "cocoa api", "objective-c runtime", "interface builder"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cocoa_(API)",
            "Objective-C",
            "Core_Foundation",
            "Interface_Builder",
            "Model%E2%80%93view%E2%80%93controller",
            "Cocoa_Touch",
        ),
    },
    "appkit-macos": {
        "tags": ["appkit framework", "macos gui", "aqua interface", "quartz compositor"],
        "license": CC_BY_SA,
        "pages": wiki(
            "AppKit",
            "Aqua_(user_interface)",
            "Quartz_(graphics_layer)",
            "Core_Animation",
            "MacOS",
            "Graphical_widget",
        ),
    },
    "core-foundation": {
        "tags": ["core foundation", "toll-free bridging", "opaque type", "property list"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Core_Foundation",
            "Objective-C",
            "Property_list",
            "Reference_counting",
            "Opaque_data_type",
            "Application_programming_interface",
        ),
    },
    "grand-central-dispatch": {
        "tags": ["grand central dispatch", "dispatch queue", "thread pool", "task parallelism"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Grand_Central_Dispatch",
            "Thread_pool",
            "Concurrency_(computer_science)",
            "Futures_and_promises",
            "Task_parallelism",
            "Parallel_computing",
        ),
    },
    "xpc-services": {
        "tags": ["xpc services", "cross-process communication", "process sandbox", "privilege separation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "XPC",
            "Inter-process_communication",
            "Sandbox_(computer_security)",
            "Privilege_separation",
            "Mach_(kernel)",
            "Message_passing",
        ),
    },
    "launchd": {
        "tags": ["launchd daemon", "macos init", "service management", "property list config"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Launchd",
            "Init",
            "Property_list",
            "Daemon_(computing)",
            "Watchdog_timer",
            "Darwin_(operating_system)",
        ),
    },
    "android-runtime-art": {
        "tags": ["android runtime", "dalvik virtual machine", "ahead-of-time compilation", "dex bytecode"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Android_Runtime",
            "Dalvik_(software)",
            "Ahead-of-time_compilation",
            "Bytecode",
            "Java_virtual_machine",
            "Android_(operating_system)",
        ),
    },
    "android-binder-ipc": {
        "tags": ["android binder", "binder ipc", "interface description language", "remote procedure call"],
        "license": CC_BY_SA,
        "pages": wiki(
            "OpenBinder",
            "Interface_description_language",
            "Remote_procedure_call",
            "Marshalling_(computer_science)",
            "Stub_(distributed_computing)",
            "Inter-process_communication",
        ),
    },
    "android-jni": {
        "tags": ["java native interface", "android jni", "native development kit", "foreign function interface"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Java_Native_Interface",
            "Foreign_function_interface",
            "Native_Development_Kit",
            "Language_binding",
            "Marshalling_(computer_science)",
            "Bytecode",
        ),
    },
    "jetpack-compose": {
        "tags": ["jetpack compose", "declarative ui", "kotlin language", "android development"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Jetpack_Compose",
            "Declarative_programming",
            "Kotlin_(programming_language)",
            "Android_software_development",
            "Graphical_widget",
            "Reactive_programming",
        ),
    },
    "uikit-ios": {
        "tags": ["uikit framework", "ios interface", "storyboard layout", "event-driven programming"],
        "license": CC_BY_SA,
        "pages": wiki(
            "UIKit",
            "IOS",
            "Storyboard",
            "Event-driven_programming",
            "Cocoa_Touch",
            "Model%E2%80%93view%E2%80%93controller",
        ),
    },
    "swiftui-framework": {
        "tags": ["swiftui framework", "swift language", "declarative ui", "data binding"],
        "license": CC_BY_SA,
        "pages": wiki(
            "SwiftUI",
            "Swift_(programming_language)",
            "Declarative_programming",
            "Reactive_programming",
            "Data_binding",
            "Graphical_widget",
        ),
    },
    "core-data": {
        "tags": ["core data", "object graph", "object-relational mapping", "persistence layer"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Core_Data",
            "Object%E2%80%93relational_mapping",
            "SQLite",
            "Persistence_(computer_science)",
            "Object_graph",
            "Cocoa_(API)",
        ),
    },
    "metal-compute": {
        "tags": ["metal api", "compute kernel", "gpu computing", "shader program"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Metal_(API)",
            "Compute_kernel",
            "General-purpose_computing_on_graphics_processing_units",
            "Shader",
            "Graphics_processing_unit",
            "Vulkan",
        ),
    },
    "debian-linux": {
        "tags": ["debian linux", "apt package manager", "dpkg tool", "debian release"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Debian",
            "APT_(software)",
            "Dpkg",
            "Debian_version_history",
            "Linux_distribution",
            "Deb_(file_format)",
        ),
    },
    "ubuntu-linux": {
        "tags": ["ubuntu linux", "canonical company", "ubuntu release", "long-term support"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ubuntu",
            "Canonical_(company)",
            "Ubuntu_version_history",
            "Long-term_support",
            "GNOME",
            "APT_(software)",
        ),
    },
    "red-hat-linux": {
        "tags": ["red hat enterprise linux", "yum package manager", "dnf tool", "centos rebuild"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Red_Hat_Enterprise_Linux",
            "Red_Hat",
            "Yum_(software)",
            "DNF_(software)",
            "CentOS",
            "RPM_Package_Manager",
        ),
    },
    "arch-linux": {
        "tags": ["arch linux", "pacman package manager", "arch user repository", "rolling release"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Arch_Linux",
            "Pacman_(package_manager)",
            "Arch_User_Repository",
            "Rolling_release",
            "Linux_distribution",
            "Source_code",
        ),
    },
    "alpine-linux": {
        "tags": ["alpine linux", "musl libc", "busybox utilities", "openrc init"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Alpine_Linux",
            "Musl",
            "BusyBox",
            "OpenRC",
            "Linux_distribution",
            "Package_manager",
        ),
    },
    "gentoo-linux": {
        "tags": ["gentoo linux", "portage tree", "source-based distribution", "rolling release"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Gentoo_Linux",
            "Portage_(software)",
            "Source_code",
            "Rolling_release",
            "Linux_distribution",
            "Compiler",
        ),
    },
    "fedora-linux": {
        "tags": ["fedora linux", "dnf package manager", "rpm packaging", "ostree tree"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Fedora_Linux",
            "DNF_(software)",
            "RPM_Package_Manager",
            "OSTree",
            "GNOME",
            "Red_Hat",
        ),
    },
    "opensuse": {
        "tags": ["opensuse distribution", "zypper package manager", "yast tool", "suse enterprise"],
        "license": CC_BY_SA,
        "pages": wiki(
            "OpenSUSE",
            "ZYpp",
            "YaST",
            "SUSE_Linux_Enterprise",
            "RPM_Package_Manager",
            "Linux_distribution",
        ),
    },
    "deb-packaging": {
        "tags": ["debian package format", "dpkg tool", "apt repository", "package signing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Deb_(file_format)",
            "Dpkg",
            "APT_(software)",
            "Software_repository",
            "Digital_signature",
            "Software_versioning",
        ),
    },
    "rpm-packaging": {
        "tags": ["rpm package manager", "yum repository", "dnf resolver", "package signing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "RPM_Package_Manager",
            "Yum_(software)",
            "DNF_(software)",
            "Software_repository",
            "Digital_signature",
            "Package_format",
        ),
    },
    "apk-alpine-packaging": {
        "tags": ["alpine package keeper", "apk package format", "musl libc", "software repository"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Alpine_Linux",
            "Apk_(file_format)",
            "Musl",
            "Package_manager",
            "Software_repository",
            "BusyBox",
        ),
    },
    "flatpak": {
        "tags": ["flatpak sandbox", "application sandboxing", "ostree tree", "freedesktop runtime"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Flatpak",
            "Sandbox_(computer_security)",
            "OSTree",
            "Application_streaming",
            "Freedesktop.org",
            "Package_format",
        ),
    },
    "snap-packages": {
        "tags": ["snap package", "snapd daemon", "confined application", "canonical company"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Snap_(software)",
            "Software_deployment",
            "Sandbox_(computer_security)",
            "Canonical_(company)",
            "Package_manager",
            "Ubuntu",
        ),
    },
    "appimage": {
        "tags": ["appimage format", "portable application", "self-extracting archive", "software deployment"],
        "license": CC_BY_SA,
        "pages": wiki(
            "AppImage",
            "Portable_application",
            "Self-extracting_archive",
            "Software_deployment",
            "Package_format",
            "Linux_distribution",
        ),
    },
    "homebrew-macos": {
        "tags": ["homebrew package manager", "macports tool", "formula recipe", "ruby language"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Homebrew_(package_manager)",
            "MacPorts",
            "Ruby_(programming_language)",
            "Package_manager",
            "Software_repository",
            "MacOS",
        ),
    },
    "uefi-firmware": {
        "tags": ["uefi firmware", "bios firmware", "guid partition table", "system firmware"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Unified_Extensible_Firmware_Interface",
            "BIOS",
            "Booting",
            "Firmware",
            "GUID_Partition_Table",
            "Power-on_self-test",
        ),
    },
    "grub-bootloader": {
        "tags": ["grub bootloader", "boot loader", "master boot record", "multi-boot menu"],
        "license": CC_BY_SA,
        "pages": wiki(
            "GNU_GRUB",
            "Bootloader",
            "Master_boot_record",
            "Multi-booting",
            "Booting",
            "GUID_Partition_Table",
        ),
    },
    "coreboot": {
        "tags": ["coreboot firmware", "libreboot project", "open-source bios", "firmware payload"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Coreboot",
            "Libreboot",
            "Payload_(computing)",
            "BIOS",
            "Free_and_open-source_software",
            "Power-on_self-test",
        ),
    },
    "secure-boot-uefi": {
        "tags": ["uefi secure boot", "chain of trust", "public key infrastructure", "trusted platform module"],
        "license": CC_BY_SA,
        "pages": wiki(
            "UEFI_secure_boot",
            "Chain_of_trust",
            "Public_key_infrastructure",
            "Trusted_Platform_Module",
            "Digital_signature",
            "Booting",
        ),
    },
    "init-systems": {
        "tags": ["init system", "systemd manager", "sysvinit scripts", "process identifier"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Init",
            "Systemd",
            "Runit",
            "Unix_System_V",
            "Process_identifier",
            "Daemon_(computing)",
        ),
    },
    "dbus-ipc": {
        "tags": ["dbus message bus", "message-oriented middleware", "freedesktop standard", "inter-process communication"],
        "license": CC_BY_SA,
        "pages": wiki(
            "D-Bus",
            "Message-oriented_middleware",
            "Freedesktop.org",
            "Message_broker",
            "Inter-process_communication",
            "Remote_procedure_call",
        ),
    },
    "x11-windowing": {
        "tags": ["x window system", "x.org server", "window manager", "display server"],
        "license": CC_BY_SA,
        "pages": wiki(
            "X_Window_System",
            "X.Org_Server",
            "X_Window_System_protocols_and_architecture",
            "Window_manager",
            "Compositing_window_manager",
            "Graphical_widget",
        ),
    },
    "wayland-protocol": {
        "tags": ["wayland protocol", "wayland compositor", "weston reference", "display server"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Wayland_(protocol)",
            "Weston_(software)",
            "Mutter_(software)",
            "KWin",
            "Compositing_window_manager",
            "Freedesktop.org",
        ),
    },
    "pipewire-audio": {
        "tags": ["pipewire server", "jack audio connection kit", "audio latency", "multimedia routing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "PipeWire",
            "JACK_Audio_Connection_Kit",
            "Digital_audio",
            "Latency_(audio)",
            "Sound_server",
            "Freedesktop.org",
        ),
    },
    "pulseaudio": {
        "tags": ["pulseaudio server", "alsa sound", "sound server", "open sound system"],
        "license": CC_BY_SA,
        "pages": wiki(
            "PulseAudio",
            "Advanced_Linux_Sound_Architecture",
            "Sound_server",
            "Open_Sound_System",
            "Digital_audio",
            "Latency_(audio)",
        ),
    },
    "mesa-graphics-stack": {
        "tags": ["mesa graphics library", "opengl implementation", "direct rendering manager", "gallium driver"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Mesa_(computer_graphics)",
            "OpenGL",
            "Direct_Rendering_Manager",
            "Gallium3D",
            "Free_and_open-source_graphics_device_driver",
            "Vulkan",
        ),
    },
    "wine-compatibility-layer": {
        "tags": ["wine compatibility layer", "windows api reimplementation", "dxvk translation", "compatibility layer"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Wine_(software)",
            "Compatibility_layer",
            "DXVK",
            "Windows_API",
            "Dynamic-link_library",
            "Direct3D",
        ),
    },
    "proton-gaming": {
        "tags": ["proton compatibility tool", "steam deck", "wine gaming layer", "dxvk translation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Proton_(software)",
            "Steam_(service)",
            "Steam_Deck",
            "Wine_(software)",
            "DXVK",
            "Compatibility_layer",
        ),
    },
    "containerd-runtime": {
        "tags": ["containerd runtime", "open container initiative", "runc executor", "container orchestration"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Containerd",
            "Open_Container_Initiative",
            "Runc",
            "Kubernetes",
            "OS-level_virtualization",
            "Docker_(software)",
        ),
    },
}
