"""Azure, GCP, and other cloud provider service catalogs."""

from .common import CC_BY_SA, wiki

DOMAINS = {
    # ---- Microsoft Azure ----------------------------------------------------
    "azure-aks": {
        "tags": ["azure aks", "azure kubernetes service", "managed kubernetes azure", "aks cluster"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Microsoft_Azure",
            "Kubernetes",
            "Container_orchestration",
            "OS-level_virtualization",
            "Cloud-native_computing",
            "Microservices",
        ),
    },
    "azure-app-service": {
        "tags": ["azure app service", "azure web app", "platform as a service azure", "managed web hosting"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Platform_as_a_service",
            "Web_hosting_service",
            "Web_application",
            "Application_server",
            "Continuous_deployment",
            "Autoscaling",
        ),
    },
    "azure-sql-database": {
        "tags": ["azure sql database", "managed sql azure", "relational database azure", "database as a service"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Microsoft_SQL_Server",
            "Relational_database",
            "Database_as_a_service",
            "Transact-SQL",
            "ACID",
            "Database_transaction",
        ),
    },
    "azure-service-bus": {
        "tags": ["azure service bus", "message broker azure", "message queue azure", "enterprise messaging"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Message_broker",
            "Message_queue",
            "Enterprise_service_bus",
            "Publish–subscribe_pattern",
            "Message-oriented_middleware",
            "Advanced_Message_Queuing_Protocol",
        ),
    },
    "azure-event-hubs": {
        "tags": ["azure event hubs", "event streaming azure", "event ingestion azure", "big data streaming"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Event_stream_processing",
            "Streaming_data",
            "Apache_Kafka",
            "Data_pipeline",
            "Complex_event_processing",
            "Real-time_computing",
        ),
    },
    "azure-data-factory": {
        "tags": ["azure data factory", "data pipeline azure", "etl azure", "data integration service"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Extract,_transform,_load",
            "Data_integration",
            "Pipeline_(computing)",
            "Data_warehouse",
            "Orchestration_(computing)",
            "Data_transformation_(computing)",
        ),
    },
    "azure-synapse": {
        "tags": ["azure synapse analytics", "analytics warehouse azure", "big data analytics azure", "data warehousing service"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Data_warehouse",
            "Online_analytical_processing",
            "Massively_parallel_processing",
            "Big_data",
            "Column-oriented_DBMS",
            "Business_intelligence",
        ),
    },
    "azure-databricks": {
        "tags": ["azure databricks", "spark analytics azure", "lakehouse azure", "collaborative data science"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Databricks",
            "Apache_Spark",
            "Data_lakehouse",
            "Distributed_computing",
            "Machine_learning",
            "Notebook_interface",
        ),
    },
    "azure-key-vault": {
        "tags": ["azure key vault", "secret management azure", "key management service", "hardware security module"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Key_management",
            "Hardware_security_module",
            "Secret_sharing",
            "Public_key_infrastructure",
            "Encryption",
            "Certificate_authority",
        ),
    },
    "azure-active-directory": {
        "tags": ["azure active directory", "cloud directory service", "identity provider azure", "single sign on azure"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Active_Directory",
            "Directory_service",
            "Single_sign-on",
            "Lightweight_Directory_Access_Protocol",
            "Security_Assertion_Markup_Language",
            "Federated_identity",
        ),
    },
    "azure-entra-id": {
        "tags": ["microsoft entra id", "entra identity", "cloud identity platform", "conditional access azure"],
        "license": CC_BY_SA,
        "pages": wiki(
            "OpenID_Connect",
            "OAuth",
            "Multi-factor_authentication",
            "Identity_management",
            "Zero_trust_security_model",
            "Access_token",
        ),
    },
    "azure-monitor": {
        "tags": ["azure monitor", "cloud observability azure", "metrics and logs azure", "infrastructure monitoring"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Observability_(software)",
            "Network_monitoring",
            "System_monitor",
            "Log_management",
            "Time_series_database",
            "Alarm_device",
        ),
    },
    "azure-application-insights": {
        "tags": ["azure application insights", "apm azure", "application telemetry azure", "distributed tracing azure"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Application_performance_management",
            "Tracing_(software)",
            "Telemetry",
            "Profiling_(computer_programming)",
            "Software_analytics",
            "Instrumentation_(computer_programming)",
        ),
    },
    "azure-container-apps": {
        "tags": ["azure container apps", "serverless containers azure", "managed containers azure", "microservices runtime"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Serverless_computing",
            "Docker_(software)",
            "Containerization",
            "Service_mesh",
            "Event-driven_architecture",
            "Continuous_delivery",
        ),
    },
    "azure-openai-service": {
        "tags": ["azure openai service", "managed llm azure", "generative ai azure", "gpt on azure"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Large_language_model",
            "Generative_artificial_intelligence",
            "GPT-4",
            "Transformer_(deep_learning_architecture)",
            "Prompt_engineering",
            "Foundation_model",
        ),
    },
    "azure-machine-learning": {
        "tags": ["azure machine learning", "mlops azure", "model training azure", "ml lifecycle service"],
        "license": CC_BY_SA,
        "pages": wiki(
            "MLOps",
            "Automated_machine_learning",
            "Feature_engineering",
            "Hyperparameter_optimization",
            "Model_selection",
            "Training,_validation,_and_test_data_sets",
        ),
    },
    "azure-logic-apps": {
        "tags": ["azure logic apps", "workflow automation azure", "integration workflow azure", "low code integration"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Workflow_engine",
            "Business_process_automation",
            "Enterprise_application_integration",
            "Low-code_development_platform",
            "Web_API",
            "Event-driven_programming",
        ),
    },
    "azure-api-management": {
        "tags": ["azure api management", "api gateway azure", "api governance azure", "developer portal azure"],
        "license": CC_BY_SA,
        "pages": wiki(
            "API_management",
            "API_gateway",
            "Rate_limiting",
            "Representational_state_transfer",
            "OpenAPI_Specification",
            "Reverse_proxy",
        ),
    },
    "azure-front-door": {
        "tags": ["azure front door", "global load balancer azure", "application delivery azure", "edge routing azure"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Load_balancing_(computing)",
            "Application_delivery_network",
            "Anycast",
            "Web_application_firewall",
            "Transport_Layer_Security",
            "Reverse_proxy",
        ),
    },
    "azure-cdn": {
        "tags": ["azure cdn", "content delivery network azure", "edge caching azure", "static content delivery"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Content_delivery_network",
            "Web_cache",
            "Edge_computing",
            "Point_of_presence",
            "HTTP_caching",
            "Cache_(computing)",
        ),
    },

    # ---- Google Cloud Platform ---------------------------------------------
    "gcp-gke": {
        "tags": ["google kubernetes engine", "gke cluster", "managed kubernetes gcp", "gke autopilot"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cluster_(computing)",
            "Google_Cloud_Platform",
            "Kubernetes",
            "Container_orchestration",
            "Cloud_computing",
            "Managed_services",
        ),
    },
    "gcp-cloud-run": {
        "tags": ["gcp cloud run", "serverless containers gcp", "knative runtime", "stateless containers gcp"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Serverless_computing",
            "Cloud_Native_Computing_Foundation",
            "OS-level_virtualization",
            "Stateless_protocol",
            "Function_as_a_service",
            "Autoscaling",
        ),
    },
    "gcp-cloud-sql": {
        "tags": ["gcp cloud sql", "managed relational database gcp", "mysql postgres gcp", "database service google"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Relational_database_management_system",
            "MySQL",
            "PostgreSQL",
            "Database_as_a_service",
            "Replication_(computing)",
            "High_availability",
        ),
    },
    "gcp-spanner": {
        "tags": ["gcp cloud spanner", "globally distributed database", "newsql database gcp", "horizontally scalable sql"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Spanner_(database)",
            "Distributed_database",
            "NewSQL",
            "Consistency_model",
            "Two-phase_commit_protocol",
            "Partition_(database)",
        ),
    },
    "gcp-firestore": {
        "tags": ["gcp cloud firestore", "document database gcp", "nosql firestore", "realtime database google"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Document-oriented_database",
            "NoSQL",
            "Firebase",
            "Eventual_consistency",
            "Real-time_database",
            "Mobile_backend_as_a_service",
        ),
    },
    "gcp-bigtable": {
        "tags": ["gcp cloud bigtable", "wide column store gcp", "bigtable nosql", "petabyte scale database"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Bigtable",
            "Wide-column_store",
            "Apache_HBase",
            "Key–value_database",
            "Sharding",
            "Log-structured_merge-tree",
        ),
    },
    "gcp-dataflow": {
        "tags": ["gcp cloud dataflow", "stream batch processing gcp", "apache beam runner", "data pipeline google"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Apache_Beam",
            "Stream_processing",
            "Batch_processing",
            "Dataflow_programming",
            "MapReduce",
            "Watermark_(data_synchronization)",
        ),
    },
    "gcp-dataproc": {
        "tags": ["gcp cloud dataproc", "managed hadoop spark gcp", "big data cluster gcp", "spark on google cloud"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Apache_Hadoop",
            "Apache_Spark",
            "Apache_Hive",
            "Cluster_manager",
            "Data_processing",
            "Parallel_computing",
        ),
    },
    "gcp-vertex-ai": {
        "tags": ["gcp vertex ai", "unified ml platform gcp", "model deployment vertex", "ml pipelines google"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Machine_learning",
            "Deep_learning",
            "Artificial_neural_network",
            "Transfer_learning",
            "Software_deployment",
            "Data_labeling",
        ),
    },
    "gcp-cloud-tasks": {
        "tags": ["gcp cloud tasks", "task queue gcp", "asynchronous execution gcp", "distributed task dispatch"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Scheduling_(computing)",
            "Task_(computing)",
            "Asynchronous_method_invocation",
            "Producer–consumer_problem",
            "Job_queue",
            "Exponential_backoff",
        ),
    },
    "gcp-cloud-scheduler": {
        "tags": ["gcp cloud scheduler", "managed cron gcp", "job scheduling gcp", "cron as a service"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cron",
            "Job_scheduler",
            "Scheduling_(computing)",
            "Fault_tolerance",
            "Idempotence",
            "Periodic_function",
        ),
    },
    "gcp-secret-manager": {
        "tags": ["gcp secret manager", "secret storage gcp", "credential management gcp", "api key management"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Key_management",
            "Credential",
            "Envelope_encryption",
            "Key_derivation_function",
            "Access_control_list",
            "Audit_trail",
        ),
    },
    "gcp-iam": {
        "tags": ["gcp cloud iam", "identity access management gcp", "resource permissions gcp", "service accounts google"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Identity_and_access_management",
            "Principle_of_least_privilege",
            "Role-based_access_control",
            "Authorization",
            "Service_account",
            "Policy-based_management",
        ),
    },
    "gcp-cloud-armor": {
        "tags": ["gcp cloud armor", "ddos protection gcp", "web application firewall gcp", "edge security google"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Denial-of-service_attack",
            "Web_application_firewall",
            "Application_firewall",
            "Rate_limiting",
            "Cross-site_scripting",
            "SQL_injection",
        ),
    },
    "gcp-anthos": {
        "tags": ["gcp anthos", "hybrid multicloud gcp", "anthos service mesh", "kubernetes fleet management"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Multicloud",
            "Hybrid_cloud",
            "Service_mesh",
            "Cluster_(computing)",
            "GitOps",
            "Configuration_management",
        ),
    },
    "gcp-apigee": {
        "tags": ["gcp apigee", "api platform gcp", "api proxy apigee", "api lifecycle management"],
        "license": CC_BY_SA,
        "pages": wiki(
            "API",
            "Proxy_server",
            "Web_service",
            "Software_development_kit",
            "Monetization",
            "Service-oriented_architecture",
        ),
    },
    "gcp-looker": {
        "tags": ["gcp looker", "business intelligence gcp", "looker analytics", "embedded analytics platform"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Business_intelligence",
            "Data_visualization",
            "Dashboard_(computing)",
            "Semantic_layer",
            "Reporting",
            "Analytics",
        ),
    },
    "gcp-pubsub-lite": {
        "tags": ["gcp pubsub lite", "low cost messaging gcp", "partitioned messaging google", "cost optimized pubsub"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Publish–subscribe_pattern",
            "Message_passing",
            "Data_stream",
            "Fan-out_(software)",
            "Queueing_theory",
            "Throughput",
        ),
    },

    # ---- Oracle / IBM / Alibaba / Tencent (major non-hyperscaler clouds) ----
    "oracle-cloud-infrastructure": {
        "tags": ["oracle cloud infrastructure", "oci compute", "oracle cloud database", "enterprise cloud oracle"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Oracle_Cloud",
            "Oracle_Corporation",
            "Oracle_Database",
            "Infrastructure_as_a_service",
            "Bare-metal_server",
            "Virtual_private_network",
        ),
    },
    "ibm-cloud": {
        "tags": ["ibm cloud platform", "ibm cloud watson", "ibm cloud compute", "enterprise cloud ibm"],
        "license": CC_BY_SA,
        "pages": wiki(
            "IBM_cloud_computing",
            "IBM",
            "Watson_(computer)",
            "OpenShift",
            "Quantum_computing",
            "Mainframe_computer",
        ),
    },
    "alibaba-cloud": {
        "tags": ["alibaba cloud", "aliyun compute", "alibaba cloud ecs", "chinese cloud provider alibaba"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Alibaba_Cloud",
            "Alibaba_Group",
            "Cloud_computing",
            "Content_delivery_network",
            "Elastic_computing",
            "Data_center",
        ),
    },
    "tencent-cloud": {
        "tags": ["tencent cloud", "tencent cloud compute", "tencent cloud database", "chinese cloud provider tencent"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Tencent",
            "Tencent_QQ",
            "WeChat",
            "Gaming_as_a_service",
            "Live_streaming",
            "Object_storage",
        ),
    },

    # ---- Independent / regional hosting & VPS providers --------------------
    "linode-akamai": {
        "tags": ["linode cloud", "akamai connected cloud", "linode vps", "developer cloud linode"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Linode",
            "Akamai_Technologies",
            "Virtual_private_server",
            "Solid-state_drive",
            "Bandwidth_(computing)",
            "Data_center",
        ),
    },
    "ovhcloud": {
        "tags": ["ovhcloud", "ovh dedicated server", "ovh public cloud", "european cloud provider ovh"],
        "license": CC_BY_SA,
        "pages": wiki(
            "OVHcloud",
            "Dedicated_hosting_service",
            "Colocation_centre",
            "Watercooling",
            "Internet_service_provider",
            "Server_(computing)",
        ),
    },
    "hetzner-cloud": {
        "tags": ["hetzner cloud", "hetzner dedicated server", "hetzner vps", "budget cloud provider hetzner"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Hetzner",
            "Cloud_computing",
            "Virtualization",
            "Green_computing",
            "Uptime",
            "Backup",
        ),
    },
    "scaleway": {
        "tags": ["scaleway cloud", "scaleway elements", "scaleway bare metal", "european cloud scaleway"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Scaleway",
            "Iliad_(company)",
            "ARM_architecture_family",
            "Block-level_storage",
            "Kubernetes",
            "Serverless_computing",
        ),
    },

    # ---- Managed-database & serverless-platform startups -------------------
    "supabase-platform": {
        "tags": ["supabase platform", "supabase postgres", "firebase alternative supabase", "backend as a service supabase"],
        "license": CC_BY_SA,
        "pages": wiki(
            "PostgreSQL",
            "Backend_as_a_service",
            "Representational_state_transfer",
            "Row-level_security",
            "WebSocket",
            "Open-source_software",
        ),
    },
    "planetscale-db": {
        "tags": ["planetscale database", "vitess mysql planetscale", "serverless mysql planetscale", "database branching"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Database_sharding",
            "MySQL",
            "Database_schema",
            "Horizontal_scaling",
            "Connection_pool",
            "Online_transaction_processing",
        ),
    },
    "upstash-serverless": {
        "tags": ["upstash serverless", "serverless redis upstash", "upstash kafka", "pay per request database"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Redis",
            "In-memory_database",
            "Serverless_computing",
            "Data_structure",
            "Cache_(computing)",
            "Rate_limiting",
        ),
    },
    "railway-platform": {
        "tags": ["railway platform", "railway app deploy", "railway paas", "instant deployment railway"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Platform_as_a_service",
            "DevOps",
            "Software_deployment",
            "Environment_variable",
            "Version_control",
            "Build_automation",
        ),
    },
    "render-cloud": {
        "tags": ["render cloud platform", "render web service", "render static site", "unified cloud render"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cloud_computing",
            "Web_server",
            "Static_web_page",
            "Background_process",
            "Transport_Layer_Security",
            "Managed_hosting",
        ),
    },
    "deno-deploy": {
        "tags": ["deno deploy", "deno edge runtime", "typescript edge functions", "v8 isolate deploy"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Deno_(software)",
            "TypeScript",
            "V8_(JavaScript_engine)",
            "Edge_computing",
            "JavaScript_engine",
            "WebAssembly",
        ),
    },
    "cloudflare-workers-ai": {
        "tags": ["cloudflare workers ai", "edge inference cloudflare", "serverless gpu cloudflare", "ai on the edge"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Edge_computing",
            "Inference_engine",
            "Graphics_processing_unit",
            "Serverless_computing",
            "Machine_learning",
            "Content_delivery_network",
        ),
    },
}
