"""Desktop GUI and cross-platform UI toolkits."""

from .common import CC_BY_SA, wiki

DOMAINS = {
    "qt-framework": {
        "tags": ["qt framework", "qt widgets", "signal slot mechanism", "cross-platform toolkit"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Qt_(software)",
            "Widget_(GUI)",
            "Graphical_user_interface",
            "Signals_and_slots",
            "Model%E2%80%93view%E2%80%93controller",
            "Event-driven_programming",
            "Software_framework",
        ) + [
            "https://doc.qt.io/qt-6/qtwidgets-index.html",
        ],
    },
    "qt-quick-qml": {
        "tags": ["qt quick", "qml declarative ui", "scene graph rendering", "fluid animation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "QML",
            "Qt_Quick",
            "Declarative_programming",
            "Scene_graph",
            "JavaScript",
            "Reactive_programming",
        ) + [
            "https://doc.qt.io/qt-6/qmlapplications.html",
        ],
    },
    "gtk-toolkit": {
        "tags": ["gtk toolkit", "gobject type system", "glib library", "gnome widgets"],
        "license": CC_BY_SA,
        "pages": wiki(
            "GTK",
            "GObject",
            "GLib",
            "Cairo_(graphics)",
            "Pango",
            "GIMP",
        ) + [
            "https://docs.gtk.org/gobject/",
        ],
    },
    "gtk4": {
        "tags": ["gtk4 toolkit", "gtk widgets", "gnome application", "libadwaita styling"],
        "license": CC_BY_SA,
        "pages": wiki(
            "GTK_4",
            "GNOME",
            "Vala_(programming_language)",
            "Wayland_(protocol)",
            "Desktop_environment",
        ) + [
            "https://docs.gtk.org/gtk4/getting_started.html",
            "https://docs.gtk.org/glib/",
        ],
    },
    "wxwidgets": {
        "tags": ["wxwidgets library", "native widget toolkit", "cross-platform gui", "c plus plus ui"],
        "license": CC_BY_SA,
        "pages": wiki(
            "WxWidgets",
            "Cross-platform_software",
            "Native_(computing)",
            "Widget_toolkit",
            "Look_and_feel",
            "Software_framework",
        ),
    },
    "fltk-toolkit": {
        "tags": ["fltk toolkit", "lightweight gui library", "cross-platform widgets", "opengl windowing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "FLTK",
            "Widget_toolkit",
            "OpenGL",
            "Graphics_library",
            "Cross-platform_software",
            "Window_(computing)",
        ),
    },
    "tk-tkinter": {
        "tags": ["tk toolkit", "tkinter binding", "tcl scripting", "python gui"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Tk_(software)",
            "Tkinter",
            "Tcl",
            "Python_(programming_language)",
            "Widget_(GUI)",
            "Event_loop",
        ),
    },
    "dear-imgui": {
        "tags": ["dear imgui", "immediate mode gui", "bloat-free interface", "debug tooling overlay"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Immediate_mode_(computer_graphics)",
            "Immediate_mode_GUI",
            "Retained_mode",
            "OpenGL",
            "Framebuffer",
            "Rendering_(computer_graphics)",
        ),
    },
    "egui-rust": {
        "tags": ["egui library", "rust immediate mode", "pure rust gui", "web assembly ui"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Rust_(programming_language)",
            "Immediate_mode_GUI",
            "WebAssembly",
            "Memory_safety",
            "Graphics_library",
            "2D_computer_graphics",
        ),
    },
    "slint-ui": {
        "tags": ["slint toolkit", "declarative ui markup", "embedded gui rust", "native rendering backend"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Rust_(programming_language)",
            "Declarative_programming",
            "Cross-platform_software",
            "Widget_toolkit",
            "OpenGL_ES",
            "Software_framework",
        ),
    },
    "iced-rust": {
        "tags": ["iced toolkit", "elm architecture", "rust reactive gui", "cross-platform rendering"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Elm_(programming_language)",
            "Reactive_programming",
            "Rust_(programming_language)",
            "Model%E2%80%93view%E2%80%93controller",
            "Retained_mode",
            "WebGPU",
        ),
    },
    "druid-rust": {
        "tags": ["druid toolkit", "data-oriented ui", "rust widget tree", "reactive data binding"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Rust_(programming_language)",
            "Data_binding",
            "Widget_toolkit",
            "Reactive_programming",
            "Separation_of_concerns",
            "Graphical_widget",
        ),
    },
    "electron-framework": {
        "tags": ["electron framework", "chromium desktop app", "node desktop runtime", "web technology packaging"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Electron_(software_framework)",
            "Chromium_(web_browser)",
            "Node.js",
            "V8_(JavaScript_engine)",
            "Visual_Studio_Code",
            "Inter-process_communication",
        ),
    },
    "tauri-framework": {
        "tags": ["tauri framework", "rust desktop shell", "webview app", "lightweight bundle"],
        "license": CC_BY_SA,
        "pages": wiki(
            "WebView",
            "WebKit",
            "Rust_(programming_language)",
            "Sandbox_(computer_security)",
            "Single-page_application",
            "Cross-platform_software",
        ),
    },
    "neutralinojs": {
        "tags": ["neutralino framework", "lightweight webview app", "portable desktop binary", "native browser shell"],
        "license": CC_BY_SA,
        "pages": wiki(
            "WebView",
            "JavaScript",
            "Cross-platform_software",
            "Single-page_application",
            "Document_Object_Model",
            "Software_framework",
        ),
    },
    "nwjs": {
        "tags": ["nw framework", "node webkit runtime", "chromium application shell", "desktop javascript app"],
        "license": CC_BY_SA,
        "pages": wiki(
            "NW.js",
            "Chromium_(web_browser)",
            "Node.js",
            "Blink_(browser_engine)",
            "Web_widget",
            "Windowing_system",
        ),
    },
    "webview-native": {
        "tags": ["native webview", "embedded browser control", "system web renderer", "hybrid app shell"],
        "license": CC_BY_SA,
        "pages": wiki(
            "WebView",
            "WebKit",
            "Blink_(browser_engine)",
            "Hybrid_app",
            "HTML",
            "Cascading_Style_Sheets",
        ),
    },
    "wpf-xaml": {
        "tags": ["wpf xaml", "windows presentation foundation", "xaml markup", "data binding pipeline"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Windows_Presentation_Foundation",
            "Extensible_Application_Markup_Language",
            ".NET_Framework",
            "Data_binding",
            "DirectX",
            "Model-view-viewmodel",
        ),
    },
    "winui": {
        "tags": ["winui toolkit", "fluent design controls", "windows native ui", "modern app controls"],
        "license": CC_BY_SA,
        "pages": wiki(
            "WinUI",
            "Windows_Runtime",
            "Universal_Windows_Platform",
            "Microsoft_Store",
            "Direct3D",
            "Material_Design",
        ),
    },
    "uwp-apps": {
        "tags": ["universal windows platform", "uwp sandbox", "windows store app", "adaptive layout"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Universal_Windows_Platform",
            "Windows_Runtime",
            "Sandbox_(computer_security)",
            "Responsive_web_design",
            "Windows_API",
            "Progressive_web_app",
        ),
    },
    "windows-forms": {
        "tags": ["windows forms", "winforms controls", "dotnet desktop gui", "event handler wiring"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Windows_Forms",
            "Common_Language_Runtime",
            "Windows_API",
            "Event-driven_programming",
            "Callback_(computer_programming)",
            "Message_loop_in_Microsoft_Windows",
        ),
    },
    "avalonia-ui": {
        "tags": ["avalonia toolkit", "cross-platform xaml", "skia rendering ui", "dotnet desktop framework"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Extensible_Application_Markup_Language",
            ".NET",
            "Skia_Graphics_Engine",
            "Model-view-viewmodel",
            "Cross-platform_software",
            "Data_binding",
        ),
    },
    "maui-dotnet": {
        "tags": ["dotnet maui", "multi-platform app ui", "xamarin successor", "native mobile controls"],
        "license": CC_BY_SA,
        "pages": wiki(
            ".NET_MAUI",
            "Xamarin",
            "Mobile_app_development",
            "C_Sharp_(programming_language)",
            "Cross-platform_software",
            "Extensible_Application_Markup_Language",
        ),
    },
    "uno-platform": {
        "tags": ["uno platform", "webassembly dotnet ui", "pixel-perfect cross-platform", "single codebase app"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Uno_Platform",
            "WebAssembly",
            "C_Sharp_(programming_language)",
            "WinUI",
            "Skia_Graphics_Engine",
            "Cross-platform_software",
        ),
    },
    "gtk-sharp": {
        "tags": ["gtk sharp binding", "mono gtk wrapper", "dotnet gnome binding", "managed widget wrapper"],
        "license": CC_BY_SA,
        "pages": wiki(
            "GtkSharp",
            "Mono_(software)",
            "GTK",
            "Language_binding",
            "C_Sharp_(programming_language)",
            "GObject",
        ),
    },
    "javafx": {
        "tags": ["javafx toolkit", "fxml markup", "scene graph ui", "java rich client"],
        "license": CC_BY_SA,
        "pages": wiki(
            "JavaFX",
            "Java_(programming_language)",
            "Java_(software_platform)",
            "Scene_graph",
            "Declarative_programming",
            "Data_binding",
        ),
    },
    "java-swing": {
        "tags": ["java swing", "swing components", "pluggable look and feel", "lightweight java widgets"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Swing_(Java)",
            "Standard_Widget_Toolkit",
            "Look_and_feel",
            "Model%E2%80%93view%E2%80%93controller",
            "Event-driven_programming",
            "Widget_(GUI)",
        ),
    },
    "java-awt": {
        "tags": ["abstract window toolkit", "java awt", "native peer widgets", "heavyweight components"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Abstract_Window_Toolkit",
            "Java_(programming_language)",
            "Windowing_system",
            "Event_loop",
            "Graphical_widget",
            "Foreign_function_interface",
        ),
    },
    "kivy-framework": {
        "tags": ["kivy framework", "python multitouch ui", "opengl es rendering", "kv language layout"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Kivy_(framework)",
            "Python_(programming_language)",
            "OpenGL_ES",
            "Multi-touch",
            "Cross-platform_software",
            "Declarative_programming",
        ),
    },
    "pyqt-binding": {
        "tags": ["pyqt binding", "python qt wrapper", "sip generated binding", "qt widgets python"],
        "license": CC_BY_SA,
        "pages": wiki(
            "PyQt",
            "Qt_(software)",
            "Python_(programming_language)",
            "Language_binding",
            "Signals_and_slots",
            "Widget_(GUI)",
        ),
    },
    "pyside-binding": {
        "tags": ["pyside binding", "qt for python", "shiboken generator", "official qt python"],
        "license": CC_BY_SA,
        "pages": wiki(
            "PySide",
            "Qt_(software)",
            "QML",
            "Python_(programming_language)",
            "Language_binding",
            "Foreign_function_interface",
        ),
    },
    "wxpython": {
        "tags": ["wxpython binding", "phoenix wrapper", "native python widgets", "wxwidgets python"],
        "license": CC_BY_SA,
        "pages": wiki(
            "WxPython",
            "WxWidgets",
            "Python_(programming_language)",
            "Language_binding",
            "Native_(computing)",
            "Cross-platform_software",
        ),
    },
    "dearpygui": {
        "tags": ["dear pygui", "python immediate mode", "gpu accelerated widgets", "imgui python wrapper"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Immediate_mode_GUI",
            "Python_(programming_language)",
            "Graphics_processing_unit",
            "Retained_mode",
            "Rendering_(computer_graphics)",
            "Language_binding",
        ),
    },
    "flet-framework": {
        "tags": ["flet framework", "flutter python ui", "server-driven ui", "reactive python app"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Python_(programming_language)",
            "Reactive_programming",
            "Cross-platform_software",
            "Material_Design",
            "Single-page_application",
            "Software_framework",
        ),
    },
    "beeware-toga": {
        "tags": ["beeware toga", "native python widgets", "toga cross-platform", "python native app"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Python_(programming_language)",
            "Native_(computing)",
            "Cross-platform_software",
            "Widget_toolkit",
            "Cocoa_(API)",
            "Mobile_app_development",
        ),
    },
    "gnome-libadwaita": {
        "tags": ["libadwaita library", "gnome human interface", "adwaita styling", "adaptive gnome widgets"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Libadwaita",
            "GNOME",
            "GNOME_Shell",
            "Human_interface_guidelines",
            "GTK_4",
            "Desktop_environment",
        ) + [
            "https://developer.gnome.org/documentation/tutorials/beginners/getting_started.html",
        ],
    },
    "kde-frameworks": {
        "tags": ["kde frameworks", "plasma desktop libraries", "kirigami convergent ui", "qt kde modules"],
        "license": CC_BY_SA,
        "pages": wiki(
            "KDE_Frameworks",
            "KDE",
            "KDE_Plasma",
            "Qt_(software)",
            "Desktop_environment",
            "Widget_toolkit",
        ),
    },
    "cocoa-appkit-deep": {
        "tags": ["cocoa appkit", "objective-c runtime", "interface builder", "macos native ui"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cocoa_(API)",
            "AppKit",
            "Objective-C",
            "Interface_Builder",
            "Foundation_Kit",
            "Aqua_(user_interface)",
        ),
    },
    "catalyst-mac": {
        "tags": ["mac catalyst", "uikit on mac", "ipad app port", "apple platform bridge"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Mac_Catalyst",
            "UIKit",
            "MacOS",
            "IPadOS",
            "Cocoa_(API)",
            "SwiftUI",
        ),
    },
    "compose-multiplatform": {
        "tags": ["compose multiplatform", "kotlin shared ui", "declarative composable", "skia backed rendering"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Jetpack_Compose",
            "Kotlin_(programming_language)",
            "Declarative_programming",
            "Skia_Graphics_Engine",
            "Reactive_programming",
            "Cross-platform_software",
        ),
    },
    "react-native": {
        "tags": ["react native", "javascript native bridge", "mobile component tree", "hot reload workflow"],
        "license": CC_BY_SA,
        "pages": wiki(
            "React_Native",
            "React_(software)",
            "JavaScript",
            "Android_(operating_system)",
            "IOS",
            "Native_(computing)",
        ),
    },
    "ionic-framework": {
        "tags": ["ionic framework", "hybrid mobile toolkit", "web component controls", "cordova capacitor shell"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ionic_(mobile_app_framework)",
            "Apache_Cordova",
            "Angular_(web_framework)",
            "Progressive_web_app",
            "Hybrid_app",
            "HTML",
        ),
    },
    "capacitor-native": {
        "tags": ["capacitor runtime", "native bridge plugin", "web app container", "cross-platform native shell"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Apache_Cordova",
            "Hybrid_app",
            "WebView",
            "Progressive_web_app",
            "Inter-process_communication",
            "Mobile_app_development",
        ),
    },
    "nativescript": {
        "tags": ["nativescript framework", "javascript native access", "direct native api", "cross-platform mobile js"],
        "license": CC_BY_SA,
        "pages": wiki(
            "NativeScript",
            "JavaScript",
            "TypeScript",
            "Native_(computing)",
            "Foreign_function_interface",
            "Mobile_app_development",
        ),
    },
    "quasar-framework": {
        "tags": ["quasar framework", "vue component library", "single codebase deploy", "material vue controls"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Quasar_Framework",
            "Vue.js",
            "Material_Design",
            "Progressive_web_app",
            "Single-page_application",
            "Cross-platform_software",
        ),
    },
    "sciter-ui": {
        "tags": ["sciter engine", "html css ui", "embeddable interface engine", "lightweight html renderer"],
        "license": CC_BY_SA,
        "pages": wiki(
            "HTML",
            "Cascading_Style_Sheets",
            "WebView",
            "Document_Object_Model",
            "Graphics_library",
            "Software_framework",
        ),
    },
    "cef-embedded": {
        "tags": ["chromium embedded framework", "off-screen browser render", "embedded chromium control", "native browser embedding"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Chromium_Embedded_Framework",
            "Chromium_(web_browser)",
            "Blink_(browser_engine)",
            "WebView",
            "Inter-process_communication",
            "Rendering_(computer_graphics)",
        ),
    },
    "ultralight-ui": {
        "tags": ["ultralight renderer", "lightweight html gui", "gpu html rendering", "embeddable web ui"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ultralight",
            "WebKit",
            "HTML",
            "Graphics_processing_unit",
            "2D_computer_graphics",
            "Software_framework",
        ),
    },
    "raygui": {
        "tags": ["raygui library", "raylib immediate mode", "simple game ui", "portable c controls"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Raylib",
            "Immediate_mode_GUI",
            "OpenGL",
            "Graphics_library",
            "2D_computer_graphics",
            "Ray_casting",
        ),
    },
    "nuklear-ui": {
        "tags": ["nuklear library", "single header gui", "immediate mode c", "minimal state ui"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Immediate_mode_(computer_graphics)",
            "Immediate_mode_GUI",
            "Framebuffer",
            "Vector_graphics",
            "Graphics_library",
            "Font_rasterization",
        ),
    },
    "microui": {
        "tags": ["microui library", "tiny immediate mode", "minimal ui core", "atlas driven rendering"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Immediate_mode_GUI",
            "Immediate_mode_(computer_graphics)",
            "Retained_mode",
            "Bitmap",
            "Graphical_widget",
            "Layout_(computing)",
        ),
    },
    "blend2d-graphics": {
        "tags": ["blend2d engine", "vector rasterizer", "jit rendering pipeline", "2d graphics library"],
        "license": CC_BY_SA,
        "pages": wiki(
            "2D_computer_graphics",
            "Rasterisation",
            "Vector_graphics",
            "Anti-aliasing",
            "Alpha_compositing",
            "Just-in-time_compilation",
        ),
    },
}
