"""Advanced mathematics: algebraic topology, representation theory, algebraic geometry, analysis, probability."""
from .common import CC_BY_SA, wiki

DOMAINS = {
    "algebraic-topology": {
        "tags": ["algebraic topology", "homotopy theory", "homology group", "fundamental group"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Algebraic_topology",
            "Homotopy",
            "Homology_(mathematics)",
            "Fundamental_group",
            "Cohomology",
            "Simplicial_complex",
            "CW_complex",
            "Homotopy_groups_of_spheres",
        ),
    },
    "homological-algebra": {
        "tags": ["homological algebra", "chain complex", "exact sequence", "derived functor"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Homological_algebra",
            "Chain_complex",
            "Exact_sequence",
            "Derived_functor",
            "Tor_functor",
            "Ext_functor",
            "Spectral_sequence",
            "Abelian_category",
        ),
    },
    "representation-theory": {
        "tags": ["representation theory", "group representation", "character theory", "irreducible representation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Representation_theory",
            "Group_representation",
            "Character_theory",
            "Irreducible_representation",
            "Schur's_lemma",
            "Maschke's_theorem",
            "Representation_theory_of_finite_groups",
            "Weight_(representation_theory)",
        ),
    },
    "algebraic-geometry": {
        "tags": ["algebraic geometry", "algebraic variety", "zariski topology", "scheme theory"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Algebraic_geometry",
            "Algebraic_variety",
            "Scheme_(mathematics)",
            "Projective_variety",
            "Zariski_topology",
            "Divisor_(algebraic_geometry)",
            "Sheaf_(mathematics)",
            "Morphism_of_schemes",
        ),
    },
    "differential-topology": {
        "tags": ["differential topology", "smooth manifold", "morse theory", "de rham cohomology"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Differential_topology",
            "Differentiable_manifold",
            "Tangent_space",
            "Vector_field",
            "Morse_theory",
            "Transversality_(mathematics)",
            "Cobordism",
            "De_Rham_cohomology",
        ),
    },
    "homotopy-type-theory": {
        "tags": ["homotopy type theory", "intuitionistic type theory", "univalent foundations", "identity type"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Homotopy_type_theory",
            "Intuitionistic_type_theory",
            "Univalent_foundations",
            "Identity_type",
            "Higher_inductive_type",
            "Constructive_proof",
            "Proof_assistant",
        ),
    },
    "sheaf-theory": {
        "tags": ["sheaf theory", "sheaf cohomology", "grothendieck topology", "ringed space"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Sheaf_(mathematics)",
            "Sheaf_cohomology",
            "Presheaf_(category_theory)",
            "Topos",
            "Stalk_(sheaf)",
            "Sheafification",
            "Locally_ringed_space",
            "Grothendieck_topology",
        ),
    },
    "lie-groups": {
        "tags": ["lie group", "lie theory", "compact group", "maximal torus"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Lie_group",
            "Exponential_map_(Lie_theory)",
            "One-parameter_group",
            "Compact_group",
            "Maximal_torus",
            "Root_system",
            "Dynkin_diagram",
        ),
    },
    "lie-algebras": {
        "tags": ["lie algebra", "semisimple lie algebra", "cartan subalgebra", "killing form"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Lie_algebra",
            "Semisimple_Lie_algebra",
            "Universal_enveloping_algebra",
            "Nilpotent_Lie_algebra",
            "Killing_form",
            "Cartan_subalgebra",
        ),
    },
    "galois-theory": {
        "tags": ["galois theory", "galois group", "field extension", "solvable group"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Galois_theory",
            "Galois_group",
            "Galois_extension",
            "Fundamental_theorem_of_Galois_theory",
            "Separable_extension",
            "Solvable_group",
            "Abel%E2%80%93Ruffini_theorem",
        ),
    },
    "commutative-algebra": {
        "tags": ["commutative algebra", "noetherian ring", "krull dimension", "grobner basis"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Commutative_algebra",
            "Noetherian_ring",
            "Localization_(commutative_algebra)",
            "Krull_dimension",
            "Primary_decomposition",
            "Hilbert's_Nullstellensatz",
            "Gr%C3%B6bner_basis",
        ),
    },
    "module-theory": {
        "tags": ["module theory", "projective module", "injective module", "flat module"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Module_(mathematics)",
            "Free_module",
            "Projective_module",
            "Injective_module",
            "Tensor_product_of_modules",
            "Finitely_generated_module",
            "Flat_module",
        ),
    },
    "k-theory": {
        "tags": ["topological k-theory", "algebraic k-theory", "grothendieck group", "vector bundle"],
        "license": CC_BY_SA,
        "pages": wiki(
            "K-theory",
            "Topological_K-theory",
            "Algebraic_K-theory",
            "Grothendieck_group",
            "Vector_bundle",
            "Bott_periodicity_theorem",
            "Chern_class",
        ),
    },
    "spectral-theory": {
        "tags": ["spectral theory", "spectral theorem", "self-adjoint operator", "sturm-liouville theory"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Spectral_theory",
            "Spectrum_(functional_analysis)",
            "Self-adjoint_operator",
            "Spectral_theorem",
            "Resolvent_formalism",
            "Compact_operator",
            "Sturm%E2%80%93Liouville_theory",
            "Eigenfunction",
        ),
    },
    "operator-algebras": {
        "tags": ["operator algebra", "von neumann algebra", "banach algebra", "gelfand representation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Operator_algebra",
            "C*-algebra",
            "Von_Neumann_algebra",
            "Banach_algebra",
            "Gelfand_representation",
            "Hilbert_space",
            "Positive_operator",
        ),
    },
    "harmonic-analysis": {
        "tags": ["harmonic analysis", "fourier transform", "fourier series", "pontryagin duality"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Harmonic_analysis",
            "Fourier_transform",
            "Fourier_series",
            "Convolution",
            "Plancherel_theorem",
            "Pontryagin_duality",
            "Wavelet",
        ),
    },
    "ergodic-theory": {
        "tags": ["ergodic theory", "measure-preserving system", "ergodic theorem", "topological entropy"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ergodic_theory",
            "Ergodicity",
            "Measure-preserving_dynamical_system",
            "Birkhoff%27s_ergodic_theorem",
            "Mixing_(mathematics)",
            "Poincar%C3%A9_recurrence_theorem",
            "Ergodic_theorem",
            "Topological_entropy",
        ),
    },
    "dynamical-systems-math": {
        "tags": ["dynamical system", "phase space", "bifurcation theory", "lyapunov stability"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Dynamical_system",
            "Phase_space",
            "Attractor",
            "Bifurcation_theory",
            "Limit_cycle",
            "Lyapunov_stability",
            "Poincar%C3%A9_map",
            "Hamiltonian_system",
        ),
    },
    "chaos-mathematics": {
        "tags": ["chaos theory", "butterfly effect", "lyapunov exponent", "strange attractor"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Chaos_theory",
            "Butterfly_effect",
            "Lyapunov_exponent",
            "Logistic_map",
            "Strange_attractor",
            "Lorenz_system",
            "Feigenbaum_constants",
        ),
    },
    "fractal-geometry": {
        "tags": ["fractal geometry", "fractal dimension", "hausdorff dimension", "iterated function system"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Fractal",
            "Fractal_dimension",
            "Mandelbrot_set",
            "Julia_set",
            "Hausdorff_dimension",
            "Self-similarity",
            "Iterated_function_system",
        ),
    },
    "differential-equations-ode": {
        "tags": ["ordinary differential equation", "initial value problem", "laplace transform", "linear differential equation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ordinary_differential_equation",
            "Linear_differential_equation",
            "Initial_value_problem",
            "Wronskian",
            "Frobenius_method",
            "Laplace_transform",
            "Picard%E2%80%93Lindel%C3%B6f_theorem",
        ),
    },
    "partial-differential-equations-theory": {
        "tags": ["partial differential equation", "heat equation", "wave equation", "sobolev space"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Partial_differential_equation",
            "Heat_equation",
            "Wave_equation",
            "Laplace's_equation",
            "Navier%E2%80%93Stokes_equations",
            "Method_of_characteristics",
            "Weak_solution",
            "Sobolev_space",
        ),
    },
    "calculus-of-variations": {
        "tags": ["calculus of variations", "euler-lagrange equation", "principle of least action", "isoperimetric inequality"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Calculus_of_variations",
            "Euler%E2%80%93Lagrange_equation",
            "Functional_(mathematics)",
            "Principle_of_least_action",
            "Noether's_theorem",
            "Isoperimetric_inequality",
            "Brachistochrone_curve",
        ),
    },
    "functional-equations": {
        "tags": ["functional equation", "cauchy functional equation", "recurrence relation", "generating function"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Functional_equation",
            "Cauchy's_functional_equation",
            "Recurrence_relation",
            "Generating_function",
            "Gamma_function",
            "Riemann_zeta_function",
        ),
    },
    "martingale-theory": {
        "tags": ["martingale theory", "stopping time", "conditional expectation", "optional stopping theorem"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Martingale_(probability_theory)",
            "Filtration_(probability_theory)",
            "Stopping_time",
            "Doob's_martingale_inequality",
            "Conditional_expectation",
            "Optional_stopping_theorem",
            "Submartingale",
        ),
    },
    "stochastic-calculus": {
        "tags": ["stochastic calculus", "stochastic differential equation", "wiener process", "feynman-kac formula"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Stochastic_calculus",
            "Stochastic_differential_equation",
            "Wiener_process",
            "Stratonovich_integral",
            "Feynman%E2%80%93Kac_formula",
            "Girsanov_theorem",
            "Local_martingale",
        ),
    },
    "ito-calculus": {
        "tags": ["ito calculus", "ito lemma", "quadratic variation", "stochastic integral"],
        "license": CC_BY_SA,
        "pages": wiki(
            "It%C3%B4_calculus",
            "It%C3%B4's_lemma",
            "Quadratic_variation",
            "Stochastic_integral",
            "It%C3%B4_diffusion",
            "Semimartingale",
        ),
    },
    "brownian-motion": {
        "tags": ["brownian motion", "diffusion process", "fokker-planck equation", "ornstein-uhlenbeck process"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Brownian_motion",
            "Geometric_Brownian_motion",
            "Fractional_Brownian_motion",
            "Diffusion_process",
            "Fokker%E2%80%93Planck_equation",
            "Ornstein%E2%80%93Uhlenbeck_process",
        ),
    },
    "random-walk-theory": {
        "tags": ["random walk", "self-avoiding walk", "markov chain", "gambler's ruin"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Random_walk",
            "Simple_random_walk",
            "Gambler's_ruin",
            "Markov_chain",
            "First-hitting-time_model",
            "Loop-erased_random_walk",
            "Self-avoiding_walk",
        ),
    },
    "queueing-theory-math": {
        "tags": ["queueing theory", "little's law", "poisson point process", "birth-death process"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Queueing_theory",
            "M/M/1_queue",
            "Little's_law",
            "Poisson_point_process",
            "Birth%E2%80%93death_process",
            "Kendall's_notation",
        ),
    },
    "extremal-combinatorics": {
        "tags": ["extremal combinatorics", "probabilistic method", "dilworth's theorem", "turan theorem"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Extremal_combinatorics",
            "Sperner's_theorem",
            "Erd%C5%91s%E2%80%93Ko%E2%80%93Rado_theorem",
            "Tur%C3%A1n's_theorem",
            "Probabilistic_method",
            "Dilworth's_theorem",
        ),
    },
    "ramsey-theory": {
        "tags": ["ramsey theory", "ramsey's theorem", "van der waerden's theorem", "szemeredi theorem"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ramsey_theory",
            "Ramsey's_theorem",
            "Van_der_Waerden's_theorem",
            "Schur's_theorem",
            "Hales%E2%80%93Jewett_theorem",
            "Szemer%C3%A9di's_theorem",
        ),
    },
    "algebraic-combinatorics": {
        "tags": ["algebraic combinatorics", "young tableau", "symmetric function", "association scheme"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Algebraic_combinatorics",
            "Young_tableau",
            "Symmetric_function",
            "Partially_ordered_set",
            "M%C3%B6bius_function",
            "Association_scheme",
        ),
    },
    "generating-functions": {
        "tags": ["generating function", "formal power series", "catalan number", "binomial coefficient"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Formal_power_series",
            "Ordinary_generating_function",
            "Exponential_generating_function",
            "Catalan_number",
            "Binomial_coefficient",
            "Stirling_numbers_of_the_second_kind",
            "Partition_(number_theory)",
        ),
    },
    "analytic-number-theory": {
        "tags": ["analytic number theory", "prime number theorem", "dirichlet series", "riemann hypothesis"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Analytic_number_theory",
            "Prime_number_theorem",
            "Dirichlet_series",
            "Riemann_hypothesis",
            "Dirichlet's_theorem_on_arithmetic_progressions",
            "Arithmetic_function",
            "Prime-counting_function",
        ),
    },
    "algebraic-number-theory": {
        "tags": ["algebraic number theory", "ring of integers", "ideal class group", "dedekind domain"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Algebraic_number_theory",
            "Ring_of_integers",
            "Ideal_class_group",
            "Dedekind_domain",
            "Minkowski's_theorem",
            "Dirichlet's_unit_theorem",
            "Ramification_(mathematics)",
        ),
    },
    "elliptic-curves-math": {
        "tags": ["elliptic curve", "mordell-weil theorem", "weierstrass elliptic function", "elliptic integral"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Elliptic_curve",
            "Weierstrass_elliptic_function",
            "Elliptic_curve_point_multiplication",
            "Mordell%E2%80%93Weil_theorem",
            "Rank_of_an_elliptic_curve",
            "Elliptic_integral",
        ),
    },
    "modular-forms": {
        "tags": ["modular form", "modular group", "eisenstein series", "hecke operator"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Modular_form",
            "Modular_group",
            "Eisenstein_series",
            "Hecke_operator",
            "Cusp_form",
            "Modularity_theorem",
        ),
    },
    "diophantine-equations": {
        "tags": ["diophantine equation", "pell's equation", "fermat's last theorem", "pythagorean triple"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Diophantine_equation",
            "Pell's_equation",
            "Fermat's_Last_Theorem",
            "Hilbert's_tenth_problem",
            "Pythagorean_triple",
            "Continued_fraction",
        ),
    },
    "p-adic-analysis": {
        "tags": ["p-adic analysis", "p-adic number", "hensel's lemma", "local field"],
        "license": CC_BY_SA,
        "pages": wiki(
            "P-adic_number",
            "P-adic_analysis",
            "P-adic_valuation",
            "Hensel's_lemma",
            "Ostrowski's_theorem",
            "Profinite_integer",
            "Local_field",
        ),
    },
    "model-theory": {
        "tags": ["model theory", "compactness theorem", "elementary equivalence", "quantifier elimination"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Model_theory",
            "First-order_theory",
            "Compactness_theorem",
            "L%C3%B6wenheim%E2%80%93Skolem_theorem",
            "Elementary_equivalence",
            "Ultraproduct",
            "Quantifier_elimination",
        ),
    },
    "proof-theory-logic": {
        "tags": ["proof theory", "sequent calculus", "natural deduction", "cut-elimination theorem"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Proof_theory",
            "Sequent_calculus",
            "Natural_deduction",
            "Cut-elimination_theorem",
            "Gentzen's_consistency_proof",
            "Ordinal_analysis",
            "Peano_axioms",
        ),
    },
    "recursion-theory": {
        "tags": ["computability theory", "turing degree", "halting problem", "arithmetical hierarchy"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Computability_theory",
            "Turing_degree",
            "Halting_problem",
            "Recursively_enumerable_set",
            "Arithmetical_hierarchy",
            "Post's_theorem",
            "Kleene's_recursion_theorem",
        ),
    },
    "ordinal-arithmetic": {
        "tags": ["ordinal arithmetic", "ordinal number", "transfinite induction", "cantor normal form"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ordinal_arithmetic",
            "Ordinal_number",
            "Transfinite_induction",
            "Cardinal_number",
            "Epsilon_number",
            "Well-order",
            "Cantor_normal_form",
        ),
    },
    "forcing-set-theory": {
        "tags": ["forcing method", "continuum hypothesis", "constructible universe", "large cardinal"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Forcing_(mathematics)",
            "Continuum_hypothesis",
            "Generic_filter",
            "Constructible_universe",
            "Zermelo%E2%80%93Fraenkel_set_theory",
            "Large_cardinal",
            "Axiom_of_choice",
        ),
    },
    "non-euclidean-geometry": {
        "tags": ["non-euclidean geometry", "hyperbolic geometry", "elliptic geometry", "parallel postulate"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Non-Euclidean_geometry",
            "Hyperbolic_geometry",
            "Elliptic_geometry",
            "Parallel_postulate",
            "Gaussian_curvature",
            "Poincar%C3%A9_disk_model",
        ),
    },
    "projective-geometry": {
        "tags": ["projective geometry", "projective plane", "homogeneous coordinates", "desargues theorem"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Projective_geometry",
            "Projective_plane",
            "Homogeneous_coordinates",
            "Cross-ratio",
            "Duality_(projective_geometry)",
            "Desargues's_theorem",
            "Pappus's_hexagon_theorem",
        ),
    },
    "convex-geometry": {
        "tags": ["convex geometry", "convex polytope", "supporting hyperplane", "helly's theorem"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Convex_geometry",
            "Convex_set",
            "Convex_polytope",
            "Supporting_hyperplane",
            "Minkowski_addition",
            "Helly's_theorem",
            "Carath%C3%A9odory's_theorem_(convex_hull)",
        ),
    },
    "discrete-geometry": {
        "tags": ["discrete geometry", "sphere packing", "kissing number", "geometric lattice"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Discrete_geometry",
            "Sphere_packing",
            "Lattice_(group)",
            "Polytope",
            "Incidence_(geometry)",
            "Tessellation",
            "Kissing_number",
        ),
    },
    "tensor-analysis": {
        "tags": ["tensor calculus", "covariant derivative", "metric tensor", "christoffel symbols"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Tensor",
            "Tensor_field",
            "Tensor_calculus",
            "Covariant_derivative",
            "Ricci_calculus",
            "Metric_tensor",
            "Christoffel_symbols",
        ),
    },
    "exterior-algebra": {
        "tags": ["exterior algebra", "differential form", "wedge product", "exterior derivative"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Exterior_algebra",
            "Differential_form",
            "Wedge_product",
            "Exterior_derivative",
            "Multivector",
            "Hodge_star_operator",
        ),
    },
    "clifford-algebra": {
        "tags": ["clifford algebra", "geometric algebra", "spinor field", "gamma matrices"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Clifford_algebra",
            "Geometric_algebra",
            "Spinor",
            "Pin_group",
            "Gamma_matrices",
            "Bivector",
        ),
    },
    "quaternions-octonions": {
        "tags": ["quaternion algebra", "octonion algebra", "cayley-dickson construction", "spatial rotation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Quaternion",
            "Octonion",
            "Cayley%E2%80%93Dickson_construction",
            "Versor",
            "Quaternions_and_spatial_rotation",
            "Split-quaternion",
        ),
    },
    "knot-theory": {
        "tags": ["knot theory", "knot invariant", "jones polynomial", "braid group"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Knot_theory",
            "Knot_invariant",
            "Jones_polynomial",
            "Alexander_polynomial",
            "Knot_group",
            "Reidemeister_move",
            "Braid_group",
        ),
    },
    "graph-minors": {
        "tags": ["graph minor", "robertson-seymour theorem", "tree decomposition", "forbidden minor"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Graph_minor",
            "Robertson%E2%80%93Seymour_theorem",
            "Tree_decomposition",
            "Treewidth",
            "Planar_graph",
            "Wagner's_theorem",
        ),
    },
    "matroid-theory": {
        "tags": ["matroid theory", "oriented matroid", "tutte polynomial", "matroid intersection"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Matroid",
            "Matroid_theory",
            "Greedy_algorithm",
            "Matroid_intersection",
            "Oriented_matroid",
            "Tutte_polynomial",
            "Dual_matroid",
        ),
    },
}
