"""Advanced CS theory: complexity classes, approximation/online/streaming algorithms, proofs."""

from .common import CC_BY_SA, wiki

DOMAINS = {
    "approximation-algorithms": {
        "tags": ["approximation algorithm", "approximation ratio", "polynomial-time approximation scheme", "hardness of approximation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Approximation_algorithm",
            "APX",
            "Polynomial-time_approximation_scheme",
            "Vertex_cover",
            "Set_cover_problem",
            "Hardness_of_approximation",
            "Christofides_algorithm",
        ),
    },
    "online-algorithms": {
        "tags": ["online algorithm", "competitive analysis", "ski rental problem", "list update problem"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Online_algorithm",
            "Competitive_analysis_(online_algorithm)",
            "Ski_rental_problem",
            "K-server_problem",
            "Adversary_(online_algorithm)",
            "List_update_problem",
            "Page_replacement_algorithm",
        ),
    },
    "streaming-algorithms": {
        "tags": ["streaming algorithm", "data stream model", "frequency moment", "misra gries summary"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Streaming_algorithm",
            "Data_stream_management_system",
            "Count%E2%80%93min_sketch",
            "Misra%E2%80%93Gries_summary",
            "Flajolet%E2%80%93Martin_algorithm",
            "Reservoir_sampling",
            "HyperLogLog",
        ),
    },
    "sublinear-algorithms": {
        "tags": ["sublinear time algorithm", "query complexity", "sublinear approximation", "estimation query"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Sublinear_function",
            "Time_complexity",
            "Query_complexity",
            "Property_testing",
            "Estimation_theory",
            "Sampling_(statistics)",
        ),
    },
    "randomized-algorithms-deep": {
        "tags": ["randomized algorithm", "monte carlo algorithm", "probabilistic method", "chernoff bound"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Randomized_algorithm",
            "Monte_Carlo_algorithm",
            "Probabilistic_method",
            "Chernoff_bound",
            "Random_self-reducibility",
            "Randomized_rounding",
            "Yao's_principle",
        ),
    },
    "las-vegas-algorithms": {
        "tags": ["las vegas algorithm", "expected running time", "randomized quicksort", "monte carlo algorithm"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Las_Vegas_algorithm",
            "Monte_Carlo_algorithm",
            "Expected_value",
            "Atlantic_City_algorithm",
            "Randomized_algorithm",
            "Quickselect",
        ),
    },
    "derandomization": {
        "tags": ["derandomization technique", "pseudorandom generator", "method of conditional probabilities", "small bias sample space"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Randomized_algorithm",
            "Pseudorandom_generator",
            "Method_of_conditional_probabilities",
            "K-independent_hashing",
            "Small-bias_sample_space",
            "Cryptographically_secure_pseudorandom_number_generator",
        ),
    },
    "parameterized-complexity": {
        "tags": ["parameterized complexity", "fixed parameter tractable", "w hierarchy", "treewidth parameter"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Parameterized_complexity",
            "Parameterized_approximation_algorithm",
            "W_hierarchy",
            "Treewidth",
            "Bidimensionality",
            "Courcelle's_theorem",
        ),
    },
    "fixed-parameter-tractable": {
        "tags": ["fixed parameter tractable", "bounded search tree", "iterative compression", "color coding technique"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Fixed-parameter_tractability",
            "Iterative_compression",
            "Color-coding",
            "Vertex_cover",
            "Feedback_vertex_set",
            "Longest_path_problem",
        ),
    },
    "kernelization": {
        "tags": ["kernelization technique", "problem kernel", "data reduction rule", "vertex cover kernel"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Kernelization",
            "Independent_set_(graph_theory)",
            "Vertex_cover",
            "Data_reduction",
            "Parameterized_complexity",
            "Dominating_set",
        ),
    },
    "exponential-time-algorithms": {
        "tags": ["exponential time algorithm", "exponential time hypothesis", "held karp algorithm", "measure and conquer"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Exponential_time_hypothesis",
            "Held%E2%80%93Karp_algorithm",
            "Time_complexity",
            "Analysis_of_parallel_algorithms",
            "Subset_sum_problem",
            "Travelling_salesman_problem",
        ),
    },
    "exact-algorithms": {
        "tags": ["exact algorithm", "branch and bound", "branch and cut", "dynamic programming over subsets"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Branch_and_bound",
            "Branch_and_cut",
            "Branch_and_price",
            "Cutting-plane_method",
            "Integer_programming",
            "Combinatorial_optimization",
        ),
    },
    "fine-grained-complexity": {
        "tags": ["fine grained complexity", "fine grained reduction", "strong exponential time hypothesis", "3sum conjecture"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Fine-grained_reduction",
            "3SUM",
            "Exponential_time_hypothesis",
            "Reduction_(complexity)",
            "NP-hardness",
            "Time_hierarchy_theorem",
            "Diameter_(graph_theory)",
        ),
    },
    "circuit-complexity": {
        "tags": ["circuit complexity", "circuit lower bound", "ac0 class", "natural proofs barrier"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Circuit_complexity",
            "AC0",
            "TC0",
            "Parity_function",
            "Natural_proof",
            "Boolean_circuit",
        ),
    },
    "boolean-circuit": {
        "tags": ["boolean circuit", "logic gate network", "circuit satisfiability", "monotone circuit"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Boolean_circuit",
            "Logic_gate",
            "Circuit_satisfiability_problem",
            "Monotone_circuit",
            "Combinational_logic",
            "Boolean_function",
        ),
    },
    "communication-complexity": {
        "tags": ["communication complexity", "two party protocol", "fooling set", "discrepancy method"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Communication_complexity",
            "Discrepancy_of_hypergraphs",
            "Information_theory",
            "Rectangle_method",
            "Yao's_principle",
            "Randomized_algorithm",
        ),
    },
    "descriptive-complexity": {
        "tags": ["descriptive complexity", "second order logic", "fagin theorem", "finite model theory"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Descriptive_complexity_theory",
            "Fagin's_theorem",
            "Second-order_logic",
            "Finite_model_theory",
            "First-order_logic",
            "Immerman%E2%80%93Szelepcs%C3%A9nyi_theorem",
        ),
    },
    "proof-complexity": {
        "tags": ["proof complexity", "resolution refutation", "propositional proof system", "frege system"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Proof_complexity",
            "Resolution_(logic)",
            "Propositional_proof_system",
            "Frege_system",
            "Cutting-plane_method",
            "Boolean_satisfiability_problem",
        ),
    },
    "interactive-proofs": {
        "tags": ["interactive proof system", "arthur merlin protocol", "ip pspace theorem", "public coin protocol"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Interactive_proof_system",
            "IP_(complexity)",
            "Arthur%E2%80%93Merlin_protocol",
            "PSPACE",
            "Zero-knowledge_proof",
            "Soundness",
        ),
    },
    "probabilistically-checkable-proofs": {
        "tags": ["probabilistically checkable proof", "pcp theorem", "proof verification", "hardness of approximation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Probabilistically_checkable_proof",
            "PCP_theorem",
            "Hardness_of_approximation",
            "Interactive_proof_system",
            "Unique_games_conjecture",
            "Gap_reduction",
        ),
    },
    "zero-knowledge-proofs-theory": {
        "tags": ["zero knowledge proof", "soundness property", "completeness property", "sigma protocol"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Zero-knowledge_proof",
            "Non-interactive_zero-knowledge_proof",
            "Proof_of_knowledge",
            "Commitment_scheme",
            "Fiat%E2%80%93Shamir_heuristic",
            "Soundness",
        ),
    },
    "quantum-complexity-theory": {
        "tags": ["quantum complexity theory", "quantum query complexity", "quantum supremacy", "qma class"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Quantum_complexity_theory",
            "Quantum_supremacy",
            "QMA",
            "Quantum_query_complexity",
            "Postselection",
            "Hidden_subgroup_problem",
        ),
    },
    "bqp-class": {
        "tags": ["bounded error quantum polynomial", "quantum turing machine", "shor algorithm", "grover algorithm"],
        "license": CC_BY_SA,
        "pages": wiki(
            "BQP",
            "Quantum_Turing_machine",
            "Shor's_algorithm",
            "Grover's_algorithm",
            "Quantum_circuit",
            "Deutsch%E2%80%93Jozsa_algorithm",
        ),
    },
    "counting-complexity": {
        "tags": ["counting complexity", "permanent computation", "toda theorem", "counting problem"],
        "license": CC_BY_SA,
        "pages": wiki(
            "%E2%99%AFP",
            "Permanent_(mathematics)",
            "Toda's_theorem",
            "Counting_problem_(complexity)",
            "Valiant%E2%80%93Vazirani_theorem",
            "Holographic_algorithm",
        ),
    },
    "sharp-p": {
        "tags": ["sharp p complete", "counting solutions", "permanent of matrix", "sharp sat solver"],
        "license": CC_BY_SA,
        "pages": wiki(
            "%E2%99%AFP-complete",
            "%E2%99%AFP",
            "Permanent_(mathematics)",
            "Sharp-SAT",
            "Boolean_satisfiability_problem",
            "Matrix_permanent",
        ),
    },
    "polynomial-hierarchy": {
        "tags": ["polynomial hierarchy", "oracle machine", "quantified boolean formula", "sigma level"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Polynomial_hierarchy",
            "Oracle_machine",
            "True_quantified_Boolean_formula",
            "Alternating_Turing_machine",
            "PH_(complexity)",
            "Karp%E2%80%93Lipton_theorem",
        ),
    },
    "space-complexity-classes": {
        "tags": ["space complexity", "savitch theorem", "space hierarchy theorem", "reachability problem"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Space_complexity",
            "Savitch's_theorem",
            "Space_hierarchy_theorem",
            "DSPACE",
            "NSPACE",
            "Immerman%E2%80%93Szelepcs%C3%A9nyi_theorem",
        ),
    },
    "pspace": {
        "tags": ["polynomial space", "pspace complete", "quantified boolean formula problem", "generalized geography"],
        "license": CC_BY_SA,
        "pages": wiki(
            "PSPACE",
            "PSPACE-complete",
            "True_quantified_Boolean_formula",
            "Generalized_geography",
            "Savitch's_theorem",
            "Reconfiguration",
        ),
    },
    "logspace": {
        "tags": ["logarithmic space", "log space reduction", "undirected connectivity", "symmetric turing machine"],
        "license": CC_BY_SA,
        "pages": wiki(
            "L_(complexity)",
            "NL_(complexity)",
            "SL_(complexity)",
            "Log-space_reduction",
            "NL-complete",
            "Reachability",
        ),
    },
    "nc-class": {
        "tags": ["nick class parallel", "parallel random access machine", "circuit depth", "efficiently parallelizable"],
        "license": CC_BY_SA,
        "pages": wiki(
            "NC_(complexity)",
            "Parallel_RAM",
            "Boolean_circuit",
            "P-complete",
            "Circuit_complexity",
            "Analysis_of_parallel_algorithms",
        ),
    },
    "parallel-complexity": {
        "tags": ["parallel complexity", "work span model", "brent theorem", "p complete problem"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Analysis_of_parallel_algorithms",
            "P-complete",
            "Parallel_RAM",
            "Speedup",
            "Amdahl's_law",
            "Cost_efficiency",
        ),
    },
    "average-case-complexity": {
        "tags": ["average case complexity", "distributional problem", "planted clique problem", "smoothed analysis"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Average-case_complexity",
            "NP-completeness",
            "Best,_worst_and_average_case",
            "One-way_function",
            "Planted_clique",
            "Smoothed_analysis",
        ),
    },
    "cryptographic-hardness": {
        "tags": ["cryptographic hardness assumption", "computational hardness", "learning with errors", "discrete logarithm assumption"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Computational_hardness_assumption",
            "Learning_with_errors",
            "Discrete_logarithm",
            "Integer_factorization",
            "Decisional_Diffie%E2%80%93Hellman_assumption",
            "Lattice_problem",
        ),
    },
    "one-way-functions": {
        "tags": ["one way function", "trapdoor function", "hard core predicate", "computational indistinguishability"],
        "license": CC_BY_SA,
        "pages": wiki(
            "One-way_function",
            "Trapdoor_function",
            "Hard-core_predicate",
            "Cryptographic_hash_function",
            "Computational_indistinguishability",
            "Pseudorandom_generator",
        ),
    },
    "pseudorandomness": {
        "tags": ["pseudorandomness theory", "pseudorandom generator", "randomness extractor", "expander construction"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Pseudorandomness",
            "Pseudorandom_generator",
            "Randomness_extractor",
            "Pseudorandom_generators_for_polynomials",
            "Applications_of_randomness",
            "Expander_graph",
        ),
    },
    "expander-graphs": {
        "tags": ["expander graph", "spectral gap", "cheeger inequality", "ramanujan graph"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Expander_graph",
            "Cheeger_constant_(graph_theory)",
            "Ramanujan_graph",
            "Zig-zag_product",
            "Algebraic_connectivity",
            "Spectral_gap",
        ),
    },
    "spectral-graph-theory": {
        "tags": ["spectral graph theory", "graph laplacian", "adjacency matrix spectrum", "algebraic connectivity"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Spectral_graph_theory",
            "Laplacian_matrix",
            "Adjacency_matrix",
            "Algebraic_connectivity",
            "Spectral_clustering",
            "Conductance_(graph)",
        ),
    },
    "property-testing": {
        "tags": ["property testing", "sublinear verification", "locally testable code", "graph property tester"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Property_testing",
            "Sublinear_function",
            "Locally_testable_code",
            "Graph_property",
            "Randomized_algorithm",
            "PCP_theorem",
        ),
    },
    "learning-theory-pac": {
        "tags": ["probably approximately correct", "sample complexity", "pac learnable", "concept class"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Probably_approximately_correct_learning",
            "Sample_complexity",
            "Concept_class",
            "Occam_learning",
            "Vapnik%E2%80%93Chervonenkis_dimension",
            "Empirical_risk_minimization",
        ),
    },
    "vc-dimension": {
        "tags": ["vapnik chervonenkis dimension", "shattering set", "growth function", "sauer shelah lemma"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Vapnik%E2%80%93Chervonenkis_dimension",
            "Sauer%E2%80%93Shelah_lemma",
            "Shattered_set",
            "Growth_function",
            "Rademacher_complexity",
            "Generalization_error",
        ),
    },
    "computational-learning": {
        "tags": ["computational learning theory", "mistake bound model", "query learning", "statistical learning theory"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Computational_learning_theory",
            "Statistical_learning_theory",
            "Winnow_(algorithm)",
            "Version_space_learning",
            "Bias%E2%80%93variance_tradeoff",
            "Structural_risk_minimization",
        ),
    },
    "boosting-theory": {
        "tags": ["boosting meta algorithm", "weak learner", "adaboost algorithm", "margin theory"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Boosting_(machine_learning)",
            "AdaBoost",
            "Gradient_boosting",
            "Weak_learnability",
            "Ensemble_learning",
            "Margin_classifier",
        ),
    },
    "online-learning-theory": {
        "tags": ["online learning theory", "sequential prediction", "perceptron mistake bound", "multiplicative weights"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Online_machine_learning",
            "Multiplicative_weight_update_method",
            "Perceptron",
            "Weighted_majority_algorithm",
            "Winnow_(algorithm)",
            "Stochastic_gradient_descent",
        ),
    },
    "regret-minimization": {
        "tags": ["regret minimization", "multi armed bandit", "no regret dynamics", "thompson sampling"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Regret_(decision_theory)",
            "Multi-armed_bandit",
            "Thompson_sampling",
            "Exponential_mechanism",
            "Reinforcement_learning",
            "Online_optimization",
        ),
    },
    "mechanism-design": {
        "tags": ["mechanism design", "incentive compatibility", "vickrey clarke groves", "revelation principle"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Mechanism_design",
            "Incentive_compatibility",
            "Vickrey%E2%80%93Clarke%E2%80%93Groves_mechanism",
            "Revelation_principle",
            "Vickrey_auction",
            "Myerson_ironing",
        ),
    },
    "algorithmic-game-theory": {
        "tags": ["algorithmic game theory", "computational equilibrium", "combinatorial auction", "selfish routing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Algorithmic_game_theory",
            "Combinatorial_auction",
            "Congestion_game",
            "Braess's_paradox",
            "Potential_game",
            "Cooperative_game_theory",
        ),
    },
    "price-of-anarchy": {
        "tags": ["price of anarchy", "price of stability", "congestion game", "braess paradox"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Price_of_anarchy",
            "Price_of_stability",
            "Braess's_paradox",
            "Congestion_game",
            "Nash_equilibrium",
            "Potential_game",
        ),
    },
    "nash-equilibrium-computation": {
        "tags": ["nash equilibrium computation", "lemke howson algorithm", "ppad complete", "fixed point argument"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Nash_equilibrium",
            "Lemke%E2%80%93Howson_algorithm",
            "PPAD_(complexity)",
            "Brouwer_fixed-point_theorem",
            "Correlated_equilibrium",
            "Sperner's_lemma",
        ),
    },
    "fair-division-algorithms": {
        "tags": ["fair division", "envy free allocation", "cake cutting", "proportional share"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Fair_division",
            "Envy-free_cake-cutting",
            "Proportional_cake-cutting",
            "Adjusted_winner_procedure",
            "Rental_harmony",
            "Fair_item_allocation",
        ),
    },
    "stable-matching": {
        "tags": ["stable matching", "gale shapley algorithm", "stable marriage problem", "hospital residents problem"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Stable_marriage_problem",
            "Gale%E2%80%93Shapley_algorithm",
            "National_Resident_Matching_Program",
            "Stable_roommates_problem",
            "Lattice_of_stable_matchings",
            "Assignment_problem",
        ),
    },
    "social-choice-theory": {
        "tags": ["social choice theory", "arrow impossibility theorem", "voting rule", "gibbard satterthwaite theorem"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Social_choice_theory",
            "Arrow's_impossibility_theorem",
            "Gibbard%E2%80%93Satterthwaite_theorem",
            "Condorcet_paradox",
            "Voting_criteria",
            "Computational_social_choice",
        ),
    },
    "distributed-algorithms-theory": {
        "tags": ["distributed algorithm", "consensus problem", "byzantine fault tolerance", "leader election"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Distributed_algorithm",
            "Consensus_(computer_science)",
            "Byzantine_fault",
            "Leader_election",
            "Dining_philosophers_problem",
            "Logical_clock",
        ),
    },
    "self-stabilization": {
        "tags": ["self stabilizing system", "fault tolerant convergence", "dijkstra token ring", "closure property"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Self-stabilization",
            "Distributed_algorithm",
            "Fault_tolerance",
            "Dining_philosophers_problem",
            "Leader_election",
            "Byzantine_fault",
        ),
    },
}
