"""More applied verticals: aerospace, energy, manufacturing, autonomous systems, agtech."""
from .common import CC_BY_SA, wiki

DOMAINS = {
    # ------------------------------------------------------------------ aerospace / avionics
    "avionics-systems": {
        "tags": ["avionics", "flight control systems", "aircraft systems", "fly-by-wire"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Avionics",
            "Flight_control_system",
            "Fly-by-wire",
            "Aircraft_flight_control_system",
            "Inertial_navigation_system",
            "Air_data_computer",
            "Cockpit",
            "Head-up_display",
        ),
    },
    "flight-management-systems": {
        "tags": ["flight management system", "area navigation", "autothrottle", "flight planning"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Flight_management_system",
            "Aircraft_flight_manual",
            "Autothrottle",
            "Flight_planning",
            "Area_navigation",
            "Required_navigation_performance",
            "Multi-function_display",
        ),
    },
    "autopilot-systems": {
        "tags": ["autopilot", "yaw damper", "autoland", "attitude heading reference"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Autopilot",
            "Aircraft_principal_axes",
            "Yaw_damper",
            "Autoland",
            "Attitude_and_heading_reference_system",
            "Servomechanism",
            "Control_theory",
        ),
    },
    "aircraft-navigation": {
        "tags": ["air navigation", "instrument landing system", "vhf omnidirectional range", "distance measuring equipment"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Air_navigation",
            "VHF_omnidirectional_range",
            "Instrument_landing_system",
            "Distance_measuring_equipment",
            "Non-directional_beacon",
            "Automatic_dependent_surveillance%E2%80%93broadcast",
            "Radio_direction_finder",
        ),
    },
    "satellite-systems": {
        "tags": ["satellite systems", "communications satellite", "geostationary orbit", "cubesat"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Satellite",
            "Communications_satellite",
            "Geostationary_orbit",
            "Attitude_control",
            "CubeSat",
            "Transponder_(satellite_communications)",
            "Satellite_bus",
            "Reaction_wheel",
        ),
    },
    "spacecraft-guidance": {
        "tags": ["spacecraft guidance", "star tracker", "attitude control", "reaction control system"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Spacecraft",
            "Guidance,_navigation,_and_control",
            "Star_tracker",
            "Spacecraft_attitude_control",
            "Kalman_filter",
            "Reaction_control_system",
            "Sun_sensor",
        ),
    },
    "orbital-mechanics-applied": {
        "tags": ["orbital mechanics", "hohmann transfer", "orbital maneuver", "lagrange point"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Orbital_mechanics",
            "Kepler%27s_laws_of_planetary_motion",
            "Hohmann_transfer_orbit",
            "Delta-v",
            "Orbital_maneuver",
            "Two-body_problem",
            "Lagrange_point",
            "Escape_velocity",
        ),
    },
    "rocket-propulsion": {
        "tags": ["rocket propulsion", "specific impulse", "ion thruster", "rocket engine"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Rocket_engine",
            "Spacecraft_propulsion",
            "Specific_impulse",
            "Ion_thruster",
            "Liquid-propellant_rocket",
            "Solid-propellant_rocket",
            "Tsiolkovsky_rocket_equation",
            "Nozzle",
        ),
    },
    "ground-station-systems": {
        "tags": ["ground station", "telemetry", "deep space network", "uplink"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Ground_station",
            "Telemetry",
            "Satellite_ground_station",
            "Antenna_(radio)",
            "Deep_Space_Network",
            "Uplink",
            "Mission_control_center",
        ),
    },
    "gnss-positioning-deep": {
        "tags": ["gnss positioning", "real-time kinematic", "differential gps", "gps signals"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Satellite_navigation",
            "GPS_signals",
            "Real-time_kinematic_positioning",
            "Differential_GPS",
            "Satellite-based_augmentation_system",
            "Precise_Point_Positioning",
            "Multilateration",
        ),
    },
    "radar-systems": {
        "tags": ["radar systems", "pulse-doppler radar", "synthetic-aperture radar", "phased array"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Radar",
            "Pulse-Doppler_radar",
            "Synthetic-aperture_radar",
            "Phased_array",
            "Radar_cross-section",
            "Continuous-wave_radar",
            "Radar_tracker",
            "Weather_radar",
        ),
    },
    "sonar-systems": {
        "tags": ["sonar systems", "passive sonar", "underwater acoustics", "hydrophone"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Sonar",
            "Passive_sonar",
            "Echo_sounding",
            "Hydrophone",
            "Underwater_acoustics",
            "Side-scan_sonar",
            "Beamforming",
        ),
    },
    "electronic-warfare": {
        "tags": ["electronic warfare", "radar jamming", "electronic countermeasure", "signals intelligence"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Electronic_warfare",
            "Radar_jamming_and_deception",
            "Electronic_countermeasure",
            "Direction_finding",
            "Signals_intelligence",
            "Chaff_(countermeasure)",
            "Electronic_warfare_support_measures",
        ),
    },
    "defense-c4isr": {
        "tags": ["c4isr", "command and control", "situation awareness", "link 16"],
        "license": CC_BY_SA,
        "pages": wiki(
            "C4ISR",
            "Command_and_control",
            "Intelligence,_surveillance,_target_acquisition,_and_reconnaissance",
            "Situation_awareness",
            "Data_link",
            "Link_16",
            "Battle_command",
        ),
    },
    # ------------------------------------------------------------------ autonomous systems
    "autonomous-vehicles": {
        "tags": ["autonomous vehicles", "self-driving car", "vehicular automation", "automated driving"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Self-driving_car",
            "Vehicular_automation",
            "Autonomous_car",
            "Waymo",
            "Advanced_driver-assistance_system",
            "Vehicle-to-everything",
            "Automated_driving_system",
        ),
    },
    "self-driving-perception": {
        "tags": ["self-driving perception", "object detection", "semantic segmentation", "simultaneous localization mapping"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Computer_vision",
            "Object_detection",
            "Semantic_segmentation",
            "Simultaneous_localization_and_mapping",
            "Lidar",
            "Depth_perception",
            "Optical_flow",
        ),
    },
    "sensor-fusion-autonomous": {
        "tags": ["sensor fusion", "extended kalman filter", "particle filter", "dead reckoning"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Sensor_fusion",
            "Kalman_filter",
            "Extended_Kalman_filter",
            "Particle_filter",
            "Data_fusion",
            "Dead_reckoning",
            "Bayesian_inference",
        ),
    },
    "path-planning-autonomous": {
        "tags": ["motion planning", "rapidly exploring random tree", "occupancy grid", "trajectory optimization"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Motion_planning",
            "Rapidly_exploring_random_tree",
            "A*_search_algorithm",
            "Occupancy_grid_mapping",
            "Probabilistic_roadmap",
            "Dijkstra%27s_algorithm",
            "Trajectory_optimization",
        ),
    },
    "vehicle-dynamics-control": {
        "tags": ["vehicle dynamics", "electronic stability control", "anti-lock braking", "traction control"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Vehicle_dynamics",
            "Electronic_stability_control",
            "Anti-lock_braking_system",
            "Traction_control_system",
            "Steering",
            "Suspension_(vehicle)",
            "Tire_model",
        ),
    },
    "drone-uav-systems": {
        "tags": ["unmanned aerial vehicle", "quadcopter", "first-person view", "ground control station"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Unmanned_aerial_vehicle",
            "Quadcopter",
            "First-person_view_(radio_control)",
            "Ground_control_station",
            "Gimbal",
            "Micro_air_vehicle",
            "Payload_(air_and_space_craft)",
        ),
    },
    "uav-flight-control": {
        "tags": ["uav flight control", "pid controller", "inertial measurement unit", "attitude control"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Attitude_control",
            "PID_controller",
            "Inertial_measurement_unit",
            "Flight_dynamics",
            "Sensor_fusion",
            "Accelerometer",
            "Gyroscope",
        ),
    },
    "swarm-robotics": {
        "tags": ["swarm robotics", "swarm intelligence", "ant colony optimization", "particle swarm optimization"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Swarm_robotics",
            "Swarm_intelligence",
            "Multi-agent_system",
            "Ant_colony_optimization_algorithms",
            "Particle_swarm_optimization",
            "Boids",
            "Distributed_artificial_intelligence",
        ),
    },
    # ------------------------------------------------------------------ agriculture / agtech
    "agricultural-robotics": {
        "tags": ["agricultural robot", "fruit picking", "automated guided vehicle", "machine vision farming"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Agricultural_robot",
            "Agricultural_machinery",
            "Weeding",
            "Fruit_picking",
            "Automated_guided_vehicle",
            "Mechanised_agriculture",
            "Machine_vision",
        ),
    },
    "precision-agriculture": {
        "tags": ["precision agriculture", "variable-rate application", "yield monitoring", "agricultural drones"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Precision_agriculture",
            "Variable-rate_application",
            "Yield_monitoring",
            "Agricultural_drones",
            "Fertilizer",
            "Geographic_information_system",
            "Global_Positioning_System",
        ),
    },
    "crop-monitoring-remote": {
        "tags": ["crop monitoring", "normalized difference vegetation index", "multispectral imaging", "leaf area index"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Remote_sensing",
            "Normalized_difference_vegetation_index",
            "Multispectral_imaging",
            "Hyperspectral_imaging",
            "Satellite_imagery",
            "Leaf_area_index",
            "Crop_yield",
        ),
    },
    "irrigation-automation": {
        "tags": ["irrigation automation", "drip irrigation", "soil moisture", "evapotranspiration"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Irrigation",
            "Drip_irrigation",
            "Center_pivot_irrigation",
            "Soil_moisture",
            "Evapotranspiration",
            "Irrigation_scheduling",
            "Tensiometer",
        ),
    },
    "livestock-monitoring": {
        "tags": ["precision livestock farming", "animal husbandry", "electronic identification", "automatic milking"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Precision_livestock_farming",
            "Animal_husbandry",
            "Livestock",
            "Electronic_identification",
            "Ear_tag",
            "Biosensor",
            "Automatic_milking",
        ),
    },
    "smart-farming-iot": {
        "tags": ["digital agriculture", "wireless sensor network", "lora", "farm management"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Digital_agriculture",
            "Wireless_sensor_network",
            "Internet_of_things",
            "LoRa",
            "Precision_agriculture",
            "Farm_management",
            "Edge_computing",
        ),
    },
    # ------------------------------------------------------------------ energy / power
    "power-grid-systems": {
        "tags": ["electrical grid", "power transmission", "power distribution", "power-system protection"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Electrical_grid",
            "Electric_power_transmission",
            "Electric_power_distribution",
            "Power-system_protection",
            "Load_management",
            "Power-flow_study",
            "Grid_energy_storage",
        ),
    },
    "transmission-distribution": {
        "tags": ["power transmission line", "high-voltage direct current", "overhead power line", "distribution transformer"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Electric_power_transmission",
            "High-voltage_direct_current",
            "Overhead_power_line",
            "Electrical_substation",
            "Power_transformer",
            "Distribution_transformer",
            "Transmission_line",
        ),
    },
    "substation-automation": {
        "tags": ["substation automation", "iec 61850", "protective relay", "intelligent electronic device"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Electrical_substation",
            "IEC_61850",
            "Intelligent_electronic_device",
            "Protective_relay",
            "Remote_terminal_unit",
            "SCADA",
            "Circuit_breaker",
        ),
    },
    "renewable-integration": {
        "tags": ["variable renewable energy", "grid connection", "duck curve", "frequency regulation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Variable_renewable_energy",
            "Grid_connection",
            "Duck_curve",
            "Frequency_regulation",
            "Grid_balancing",
            "Curtailment_(electricity)",
            "Ancillary_services_(electric_power)",
        ),
    },
    "solar-pv-systems": {
        "tags": ["photovoltaic system", "maximum power point tracking", "solar inverter", "net metering"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Photovoltaic_system",
            "Solar_panel",
            "Maximum_power_point_tracking",
            "Solar_inverter",
            "Solar_cell",
            "Net_metering",
            "Photovoltaics",
        ),
    },
    "wind-turbine-control": {
        "tags": ["wind turbine control", "blade pitch", "yaw system", "wind farm"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Wind_turbine",
            "Wind_turbine_design",
            "Pitch_control",
            "Yaw_system",
            "Wind_farm",
            "Blade_pitch",
            "Gearbox",
        ),
    },
    "battery-storage-grid": {
        "tags": ["battery storage power station", "battery management system", "state of charge", "grid energy storage"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Battery_storage_power_station",
            "Grid_energy_storage",
            "Lithium-ion_battery",
            "Battery_management_system",
            "State_of_charge",
            "Depth_of_discharge",
            "Frequency_regulation",
        ),
    },
    "microgrid-control": {
        "tags": ["microgrid", "distributed generation", "islanding", "virtual power plant"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Microgrid",
            "Distributed_generation",
            "Islanding",
            "Virtual_power_plant",
            "Droop_speed_control",
            "Energy_management_system",
            "Combined_heat_and_power",
        ),
    },
    "demand-response-systems": {
        "tags": ["demand response", "smart meter", "peak demand", "electricity pricing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Demand_response",
            "Load_management",
            "Smart_meter",
            "Electricity_pricing",
            "Peak_demand",
            "Automated_demand_response",
            "Dynamic_pricing",
        ),
    },
    "hvac-control-systems": {
        "tags": ["hvac control", "thermostat", "variable air volume", "economizer"],
        "license": CC_BY_SA,
        "pages": wiki(
            "HVAC",
            "Thermostat",
            "Variable_air_volume",
            "Chiller",
            "Air_handler",
            "Economizer",
            "Damper_(flow)",
        ),
    },
    "building-energy-management": {
        "tags": ["building management system", "energy management system", "energy audit", "occupancy sensor"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Building_management_system",
            "Energy_management_system",
            "Building_automation",
            "Energy_audit",
            "Energy_efficiency_in_buildings",
            "Building_energy_simulation",
            "Occupancy_sensor",
        ),
    },
    # ------------------------------------------------------------------ manufacturing / industrial
    "manufacturing-execution-systems": {
        "tags": ["manufacturing execution system", "isa-95", "overall equipment effectiveness", "statistical process control"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Manufacturing_execution_system",
            "ISA-95",
            "Overall_equipment_effectiveness",
            "Statistical_process_control",
            "Production_planning",
            "Shop_floor",
            "Work_order",
        ),
    },
    "industry-4-0": {
        "tags": ["industry 4.0", "smart factory", "cyber-physical system", "digital transformation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Industry_4.0",
            "Cyber-physical_system",
            "Smart_factory",
            "Digital_transformation",
            "Industrial_internet_of_things",
            "Additive_manufacturing",
            "Big_data",
        ),
    },
    "additive-manufacturing": {
        "tags": ["additive manufacturing", "fused filament fabrication", "selective laser sintering", "stereolithography"],
        "license": CC_BY_SA,
        "pages": wiki(
            "3D_printing",
            "Fused_filament_fabrication",
            "Selective_laser_sintering",
            "Stereolithography",
            "Rapid_prototyping",
            "3D_printing_processes",
            "Direct_metal_laser_sintering",
        ),
    },
    "cnc-machining": {
        "tags": ["numerical control", "g-code", "machining", "computer-aided manufacturing"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Numerical_control",
            "G-code",
            "Machining",
            "Milling_(machining)",
            "Turning",
            "Machine_tool",
            "Computer-aided_manufacturing",
        ),
    },
    "robotic-process-automation": {
        "tags": ["robotic process automation", "business process automation", "workflow automation", "intelligent automation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Robotic_process_automation",
            "Business_process_automation",
            "Workflow_automation",
            "Screen_scraping",
            "Bot",
            "Intelligent_automation",
            "Optical_character_recognition",
        ),
    },
    "warehouse-automation": {
        "tags": ["automated storage and retrieval", "warehouse management system", "order picking", "conveyor system"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Automated_storage_and_retrieval_system",
            "Warehouse_management_system",
            "Order_picking",
            "Conveyor_system",
            "Automated_guided_vehicle",
            "Kiva_Systems",
            "Palletizer",
        ),
    },
    "logistics-optimization": {
        "tags": ["logistics optimization", "vehicle routing problem", "operations research", "supply chain optimization"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Logistics",
            "Vehicle_routing_problem",
            "Operations_research",
            "Linear_programming",
            "Travelling_salesman_problem",
            "Supply_chain_optimization",
            "Combinatorial_optimization",
        ),
    },
    "fleet-management": {
        "tags": ["fleet management", "telematics", "vehicle tracking", "electronic logging device"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Fleet_management",
            "Telematics",
            "Vehicle_tracking_system",
            "GPS_tracking_unit",
            "Electronic_logging_device",
            "Route_optimization",
            "Fuel_management_systems",
        ),
    },
    "supply-chain-visibility": {
        "tags": ["supply chain visibility", "track and trace", "radio-frequency identification", "bullwhip effect"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Supply_chain_management",
            "Track_and_trace",
            "Supply_chain",
            "Inventory",
            "Radio-frequency_identification",
            "Bullwhip_effect",
            "Distribution_(marketing)",
        ),
    },
    "cold-chain-monitoring": {
        "tags": ["cold chain", "refrigerated container", "temperature data logger", "reefer ship"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cold_chain",
            "Refrigerated_container",
            "Temperature_data_logger",
            "Refrigerator_truck",
            "Vaccine",
            "Reefer_ship",
            "Perishable",
        ),
    },
    # ------------------------------------------------------------------ construction / infrastructure
    "construction-bim": {
        "tags": ["building information modeling", "industry foundation classes", "construction management", "4d bim"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Building_information_modeling",
            "Computer-aided_design",
            "Industry_Foundation_Classes",
            "4D_BIM",
            "Construction_management",
            "Constructability",
            "Autodesk_Revit",
        ),
    },
    "structural-health-monitoring": {
        "tags": ["structural health monitoring", "non-destructive testing", "strain gauge", "modal analysis"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Structural_health_monitoring",
            "Non-destructive_testing",
            "Strain_gauge",
            "Modal_analysis",
            "Acoustic_emission",
            "Fatigue_(material)",
            "Accelerometer",
        ),
    },
    "water-treatment-control": {
        "tags": ["water treatment", "sewage treatment", "activated sludge", "reverse osmosis"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Water_treatment",
            "Water_purification",
            "Sewage_treatment",
            "Activated_sludge",
            "Reverse_osmosis",
            "Coagulation_(water_treatment)",
            "Disinfection",
        ),
    },
    "mining-automation": {
        "tags": ["automated mining", "surface mining", "haul truck", "drilling rig"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Automated_mining",
            "Mining",
            "Surface_mining",
            "Underground_mining_(hard_rock)",
            "Haul_truck",
            "Drilling_rig",
            "Loader_(equipment)",
        ),
    },
    "oil-gas-scada": {
        "tags": ["oil gas scada", "pipeline transport", "wellhead", "christmas tree oil well"],
        "license": CC_BY_SA,
        "pages": wiki(
            "SCADA",
            "Petroleum_industry",
            "Pipeline_transport",
            "Wellhead",
            "Distributed_control_system",
            "Programmable_logic_controller",
            "Christmas_tree_(oil_well)",
        ),
    },
}
