"""Serialization formats, RPC, messaging, query languages, and identity/federation protocols."""
from .common import CC_BY_SA, WIKI, wiki

DOMAINS = {
    "json-schema": {
        "tags": ["json schema", "schema validation", "json validation", "data contract"],
        "license": CC_BY_SA,
        "pages": wiki(
            "JSON",
            "XML_schema",
            "Data_exchange",
            "Type_system",
        ) + [
            "https://json-schema.org/understanding-json-schema/",
            "https://json-schema.org/understanding-json-schema/reference/type",
        ],
    },
    "apache-avro": {
        "tags": ["apache avro", "avro serialization", "row-oriented format", "schema evolution"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Apache_Avro",
            "Serialization",
            "Apache_Hadoop",
            "Schema_evolution",
            "Data_serialization",
            "Comparison_of_data-serialization_formats",
        ),
    },
    "apache-thrift": {
        "tags": ["apache thrift", "thrift idl", "cross-language rpc", "interface definition language"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Apache_Thrift",
            "Remote_procedure_call",
            "Interface_description_language",
            "Stub_(distributed_computing)",
            "Marshalling_(computer_science)",
            "Wire_protocol",
        ),
    },
    "messagepack": {
        "tags": ["messagepack format", "binary json", "compact serialization", "binary encoding"],
        "license": CC_BY_SA,
        "pages": wiki(
            "MessagePack",
            "Serialization",
            "Binary-to-text_encoding",
            "Endianness",
            "Data_exchange",
            "Comparison_of_data-serialization_formats",
        ),
    },
    "cbor-format": {
        "tags": ["cbor format", "concise binary object representation", "binary data format", "iot serialization"],
        "license": CC_BY_SA,
        "pages": wiki(
            "CBOR",
            "Serialization",
            "Data_serialization",
            "Type_system",
            "Character_encoding",
            "Comparison_of_data-serialization_formats",
        ),
    },
    "bson-format": {
        "tags": ["bson format", "binary json document", "mongodb encoding", "document serialization"],
        "license": CC_BY_SA,
        "pages": wiki(
            "BSON",
            "MongoDB",
            "Document-oriented_database",
            "Serialization",
            "Endianness",
            "Data_exchange",
        ),
    },
    "apache-parquet-format": {
        "tags": ["apache parquet", "columnar storage format", "column-oriented storage", "analytics file format"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Apache_Parquet",
            "Column-oriented_DBMS",
            "Apache_Hadoop",
            "Data_compression",
            "Nested_set_model",
            "Serialization",
        ),
    },
    "flatbuffers": {
        "tags": ["google flatbuffers", "zero-copy serialization", "flatbuffers schema", "memory-efficient format"],
        "license": CC_BY_SA,
        "pages": wiki(
            "FlatBuffers",
            "Zero-copy",
            "Serialization",
            "Interface_description_language",
            "Endianness",
            "Type_system",
        ),
    },
    "capnproto": {
        "tags": ["capn proto", "cap n proto", "zero-copy format", "capability-based rpc"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cap%27n_Proto",
            "Zero-copy",
            "Remote_procedure_call",
            "Serialization",
            "Interface_description_language",
            "Wire_protocol",
        ),
    },
    "edn-format": {
        "tags": ["edn format", "extensible data notation", "clojure data format", "extensible notation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Extensible_Data_Notation",
            "Clojure",
            "Serialization",
            "Data_exchange",
            "Type_system",
            "Record_(computer_science)",
        ),
    },
    "hocon-config": {
        "tags": ["hocon config", "human-optimized config object notation", "typesafe config", "configuration format"],
        "license": CC_BY_SA,
        "pages": wiki(
            "HOCON",
            "Configuration_file",
            "JSON",
            "YAML",
            "Environment_variable",
            "Data_exchange",
        ),
    },
    "ini-format": {
        "tags": ["ini file format", "ini configuration", "key-value config", "windows configuration file"],
        "license": CC_BY_SA,
        "pages": wiki(
            "INI_file",
            "Configuration_file",
            "TOML",
            "Property_list",
            "Environment_variable",
            "Character_encoding",
        ),
    },
    "csv-tsv": {
        "tags": ["csv format", "comma-separated values", "tab-separated values", "tabular text format"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Comma-separated_values",
            "Tab-separated_values",
            "Delimiter-separated_values",
            "Flat-file_database",
            "Character_encoding",
            "Data_exchange",
        ),
    },
    "ndjson": {
        "tags": ["newline-delimited json", "ndjson format", "json streaming", "line-delimited records"],
        "license": CC_BY_SA,
        "pages": wiki(
            "JSON_streaming",
            "JSON",
            "Log_file",
            "Data_stream",
            "Delimiter-separated_values",
            "Serialization",
        ),
    },
    "jsonlines": {
        "tags": ["json lines", "jsonl format", "record-per-line", "streaming json records"],
        "license": CC_BY_SA,
        "pages": wiki(
            "JSON_streaming",
            "JSON",
            "Record_(computer_science)",
            "Flat-file_database",
            "Log_file",
            "Data_exchange",
        ),
    },
    "json-rpc": {
        "tags": ["json rpc", "json-rpc protocol", "lightweight remote procedure call", "stateless rpc"],
        "license": CC_BY_SA,
        "pages": wiki(
            "JSON-RPC",
            "Remote_procedure_call",
            "JSON",
            "Client%E2%80%93server_model",
            "Wire_protocol",
            "Web_service",
        ),
    },
    "xml-rpc": {
        "tags": ["xml rpc", "xml-rpc protocol", "http remote procedure call", "xml messaging"],
        "license": CC_BY_SA,
        "pages": wiki(
            "XML-RPC",
            "Remote_procedure_call",
            "XML",
            "HTTP",
            "Web_service",
            "Marshalling_(computer_science)",
        ),
    },
    "soap-protocol": {
        "tags": ["soap protocol", "simple object access protocol", "wsdl service", "xml web service"],
        "license": CC_BY_SA,
        "pages": wiki(
            "SOAP",
            "Web_Services_Description_Language",
            "Universal_Description_Discovery_and_Integration",
            "XML",
            "Web_service",
            "Remote_procedure_call",
        ),
    },
    "odata-protocol": {
        "tags": ["odata protocol", "open data protocol", "restful query protocol", "queryable rest api"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Open_Data_Protocol",
            "Representational_state_transfer",
            "Web_API",
            "Query_language",
            "Content_negotiation",
            "Web_service",
        ),
    },
    "jsonapi-spec": {
        "tags": ["json api spec", "json:api specification", "hypermedia json", "api response format"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Representational_state_transfer",
            "HATEOAS",
            "JSON",
            "Web_API",
            "Content_negotiation",
            "Media_type",
        ),
    },
    "hal-hypermedia": {
        "tags": ["hal hypermedia", "hypertext application language", "hypermedia api format", "hyperlinked resources"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Hypertext_Application_Language",
            "HATEOAS",
            "Hyperlink",
            "Representational_state_transfer",
            "Media_type",
            "Web_API",
        ),
    },
    "problem-details-rfc": {
        "tags": ["problem details format", "http api error format", "machine-readable errors", "error response schema"],
        "license": CC_BY_SA,
        "pages": wiki(
            "List_of_HTTP_status_codes",
            "Media_type",
            "Representational_state_transfer",
            "Web_API",
            "Content_negotiation",
            "JSON",
        ),
    },
    "asyncapi-spec": {
        "tags": ["asyncapi specification", "event-driven api spec", "message-driven api", "async api contract"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Event-driven_architecture",
            "Publish%E2%80%93subscribe_pattern",
            "Message_queue",
            "OpenAPI_Specification",
            "Message-oriented_middleware",
            "Event-driven_messaging",
        ),
    },
    "cloudevents": {
        "tags": ["cloudevents spec", "cloud events format", "event envelope format", "portable event metadata"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Event-driven_architecture",
            "Event_(computing)",
            "Serverless_computing",
            "Complex_event_processing",
            "Publish%E2%80%93subscribe_pattern",
            "Function_as_a_service",
        ),
    },
    "server-sent-events": {
        "tags": ["server-sent events", "sse streaming", "eventsource api", "http push stream"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Server-sent_events",
            "Push_technology",
            "Comet_(programming)",
            "Long_polling",
            "HTTP",
            "Event-driven_programming",
        ),
    },
    "webhooks-pattern": {
        "tags": ["webhook pattern", "http callback", "reverse api", "event notification callback"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Webhook",
            "Push_technology",
            "Event-driven_architecture",
            "Web_API",
            "HTTP",
            "Publish%E2%80%93subscribe_pattern",
        ),
    },
    "webtransport": {
        "tags": ["webtransport protocol", "quic web transport", "low-latency web transport", "browser datagram transport"],
        "license": CC_BY_SA,
        "pages": wiki(
            "QUIC",
            "HTTP/3",
            "Datagram",
            "Transport_Layer_Security",
            "Network_socket",
            "Real-time_communication",
        ),
    },
    "webrtc-datachannel": {
        "tags": ["webrtc datachannel", "peer-to-peer data channel", "browser peer connection", "webrtc data transfer"],
        "license": CC_BY_SA,
        "pages": wiki(
            "WebRTC",
            "Datagram_Transport_Layer_Security",
            "Peer-to-peer",
            "Interactive_Connectivity_Establishment",
            "Session_Description_Protocol",
            "Real-time_communication",
        ),
    },
    "amqp-protocol": {
        "tags": ["amqp protocol", "advanced message queuing protocol", "message broker protocol", "queue-based messaging"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Advanced_Message_Queuing_Protocol",
            "RabbitMQ",
            "Message_broker",
            "Message-oriented_middleware",
            "Message_queue",
            "Publish%E2%80%93subscribe_pattern",
        ),
    },
    "stomp-protocol": {
        "tags": ["stomp protocol", "streaming text oriented messaging protocol", "text messaging protocol", "simple broker protocol"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Streaming_Text_Oriented_Messaging_Protocol",
            "Apache_ActiveMQ",
            "Message_broker",
            "Message-oriented_middleware",
            "Message_queue",
            "Wire_protocol",
        ),
    },
    "dds-protocol": {
        "tags": ["dds protocol", "data distribution service", "real-time pub-sub", "omg data distribution"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Data_Distribution_Service",
            "Object_Management_Group",
            "Publish%E2%80%93subscribe_pattern",
            "Real-time_computing",
            "Message-oriented_middleware",
            "Message_passing",
        ),
    },
    "sparql-query": {
        "tags": ["sparql query language", "rdf query language", "semantic web query", "triple pattern query"],
        "license": CC_BY_SA,
        "pages": wiki(
            "SPARQL",
            "Resource_Description_Framework",
            "Semantic_Web",
            "Query_language",
            "Graph_database",
            "JSON-LD",
        ),
    },
    "cypher-query": {
        "tags": ["cypher query language", "neo4j cypher", "graph pattern query", "property graph query"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Cypher_(query_language)",
            "Neo4j",
            "Graph_database",
            "Query_language",
            "SQL",
            "Nested_set_model",
        ),
    },
    "gremlin-traversal": {
        "tags": ["gremlin traversal", "apache tinkerpop", "graph traversal language", "property graph traversal"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Gremlin_(query_language)",
            "Apache_TinkerPop",
            "Graph_database",
            "Query_language",
            "Reactive_programming",
            "Neo4j",
        ),
    },
    "promql": {
        "tags": ["promql query", "prometheus query language", "time-series query", "metrics query language"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Prometheus_(software)",
            "Time_series_database",
            "Query_language",
            "Regular_expression",
            "Complex_event_processing",
            "Data_stream",
        ),
    },
    "kusto-kql": {
        "tags": ["kusto query language", "azure data explorer kql", "log analytics query", "tabular query language"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Azure_Data_Explorer",
            "Analytics",
            "Time_series_database",
            "Query_language",
            "Log_file",
            "Data_stream",
        ),
    },
    "jsonpath": {
        "tags": ["jsonpath expression", "json path query", "json selector syntax", "json document query"],
        "license": CC_BY_SA,
        "pages": wiki(
            "JSONPath",
            "JSON",
            "XPath",
            "Query_language",
            "Regular_expression",
            "Data_exchange",
        ),
    },
    "xpath-query": {
        "tags": ["xpath query", "xml path language", "xml node selection", "xpath expression"],
        "license": CC_BY_SA,
        "pages": wiki(
            "XPath",
            "XML",
            "XQuery",
            "Document_Object_Model",
            "Namespace",
            "Query_language",
        ),
    },
    "xslt-transform": {
        "tags": ["xslt transformation", "xsl transformations", "xml transformation language", "stylesheet transformation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "XSLT",
            "XPath",
            "XML",
            "XSL_Formatting_Objects",
            "Document_Type_Definition",
            "XQuery",
        ),
    },
    "datalog-query": {
        "tags": ["datalog query language", "deductive database query", "logic query language", "declarative rule language"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Datalog",
            "Deductive_database",
            "Logic_programming",
            "Prolog",
            "Query_language",
            "Graph_database",
        ),
    },
    "openid-connect": {
        "tags": ["openid connect", "oidc protocol", "id token authentication", "oauth identity layer"],
        "license": CC_BY_SA,
        "pages": wiki(
            "OpenID_Connect",
            "OAuth",
            "Single_sign-on",
            "Identity_provider",
            "Federated_identity",
            "Authentication_protocol",
        ),
    },
    "saml-federation": {
        "tags": ["saml federation", "security assertion markup language", "saml assertion", "browser sso federation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Security_Assertion_Markup_Language",
            "Federated_identity",
            "Single_sign-on",
            "Identity_provider",
            "XML",
            "Identity_management",
        ),
    },
    "scim-provisioning": {
        "tags": ["scim provisioning", "cross-domain identity management", "user provisioning protocol", "identity lifecycle api"],
        "license": CC_BY_SA,
        "pages": wiki(
            "System_for_Cross-domain_Identity_Management",
            "Provisioning_(technology)",
            "Identity_management",
            "Directory_service",
            "Federated_identity",
            "Web_API",
        ),
    },
    "ldap-protocol": {
        "tags": ["ldap protocol", "lightweight directory access protocol", "directory service query", "x500 directory"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Lightweight_Directory_Access_Protocol",
            "Directory_service",
            "X.500",
            "Identity_management",
            "Authentication_protocol",
            "Access_control",
        ),
    },
    "kerberos-protocol": {
        "tags": ["kerberos protocol", "kerberos authentication", "ticket granting ticket", "network authentication protocol"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Kerberos_(protocol)",
            "Ticket_Granting_Ticket",
            "Authentication_protocol",
            "Single_sign-on",
            "Access_control",
            "Identity_management",
        ),
    },
    "activitypub": {
        "tags": ["activitypub protocol", "fediverse protocol", "decentralized social protocol", "federated social networking"],
        "license": CC_BY_SA,
        "pages": wiki(
            "ActivityPub",
            "Fediverse",
            "Mastodon_(social_network)",
            "WebFinger",
            "JSON-LD",
            "Publish%E2%80%93subscribe_pattern",
        ),
    },
    "xmpp-protocol": {
        "tags": ["xmpp protocol", "extensible messaging and presence protocol", "jabber messaging", "xml streaming protocol"],
        "license": CC_BY_SA,
        "pages": wiki(
            "XMPP",
            "Extensible_Messaging_and_Presence_Protocol",
            "Instant_messaging",
            "XML",
            "Publish%E2%80%93subscribe_pattern",
            "Federated_identity",
        ),
    },
    "sip-protocol": {
        "tags": ["sip protocol", "session initiation protocol", "voip signaling", "voice over ip signaling"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Session_Initiation_Protocol",
            "Voice_over_IP",
            "Session_Description_Protocol",
            "Real-time_Transport_Protocol",
            "Real-time_communication",
            "Instant_messaging",
        ),
    },
    "rtp-streaming": {
        "tags": ["rtp streaming", "real-time transport protocol", "media streaming protocol", "audio video transport"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Real-time_Transport_Protocol",
            "Real-time_Transport_Control_Protocol",
            "Streaming_media",
            "Codec",
            "Voice_over_IP",
            "Session_Description_Protocol",
        ),
    },
    "dns-over-https": {
        "tags": ["dns over https", "encrypted dns resolution", "doh protocol", "private dns query"],
        "license": CC_BY_SA,
        "pages": wiki(
            "DNS_over_HTTPS",
            "DNS_over_TLS",
            "Domain_Name_System",
            "Transport_Layer_Security",
            "HTTP/2",
            "Network_address_translation",
        ),
    },
    "well-known-uri": {
        "tags": ["well-known uri", "well-known resource path", "site metadata discovery", "webfinger discovery"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Well-known_URI",
            "WebFinger",
            "Robots.txt",
            "Uniform_Resource_Identifier",
            "Content_negotiation",
            "HTTP",
        ),
    },
}
