"""Mathematics for computing: from linear algebra to category theory. Atlas-matching names
where entries exist (linear-algebra, calculus, discrete-mathematics, number-theory,
numerical-methods, floating-point, statistics-fundamentals)."""

from .common import CC_BY, CC_BY_SA, wiki

DOMAINS = {
    "linear-algebra": {
        "tags": ["linear algebra", "matrix algebra", "matrices", "eigenvalue", "vector space", "dot product"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Linear_algebra",
            "Matrix_(mathematics)",
            "Matrix_multiplication",
            "Determinant",
            "Eigenvalues_and_eigenvectors",
            "Vector_space",
            "Dot_product",
            "Cross_product",
            "Gaussian_elimination",
            "Singular_value_decomposition",
            "Linear_map",
        ),
    },
    "calculus": {
        "tags": ["calculus", "differential calculus", "integral calculus", "differentiation", "antiderivative"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Calculus",
            "Derivative",
            "Integral",
            "Limit_(mathematics)",
            "Taylor_series",
            "Partial_derivative",
            "Chain_rule",
            "Fundamental_theorem_of_calculus",
            "Differential_equation",
            "Gradient",
        ),
    },
    "discrete-mathematics": {
        "tags": ["discrete math", "discrete mathematics", "combinatorics", "graph theory", "set theory", "permutation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Discrete_mathematics",
            "Graph_theory",
            "Combinatorics",
            "Set_theory",
            "Mathematical_induction",
            "Permutation",
            "Combination",
            "Pigeonhole_principle",
            "Binary_relation",
            "Recurrence_relation",
            "Tree_(graph_theory)",
        ),
    },
    "number-theory": {
        "tags": ["number theory", "modular arithmetic", "prime number", "gcd"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Number_theory",
            "Modular_arithmetic",
            "Prime_number",
            "Greatest_common_divisor",
            "Euclidean_algorithm",
            "Fermat's_little_theorem",
            "Chinese_remainder_theorem",
            "Euler's_totient_function",
            "Sieve_of_Eratosthenes",
        ),
    },
    "numerical-methods": {
        "tags": ["numerical analysis", "numerical method", "root finding", "polynomial interpolation", "numerical integration"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Numerical_analysis",
            "Newton's_method",
            "Bisection_method",
            "Runge%E2%80%93Kutta_methods",
            "Interpolation",
            "Numerical_integration",
            "Finite_difference",
            "Monte_Carlo_method",
            "Root-finding_algorithm",
            "Condition_number",
        ),
    },
    "floating-point": {
        "tags": ["floating point", "ieee 754", "rounding error", "double precision", "machine epsilon"],
        "license": CC_BY_SA + " / " + CC_BY + " (floating-point-gui.de)",
        "pages": wiki(
            "IEEE_754",
            "Floating-point_arithmetic",
            "Rounding",
            "Machine_epsilon",
            "Fixed-point_arithmetic",
            "Arbitrary-precision_arithmetic",
            "Catastrophic_cancellation",
        ) + [
            "https://floating-point-gui.de/basic/",
            "https://floating-point-gui.de/errors/comparison/",
        ],
    },
    "statistics-fundamentals": {
        "tags": ["statistics fundamentals", "probability", "statistical inference", "hypothesis testing", "probability distribution"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Statistics",
            "Probability",
            "Probability_distribution",
            "Normal_distribution",
            "Bayes'_theorem",
            "Standard_deviation",
            "Statistical_hypothesis_test",
            "Regression_analysis",
            "Central_limit_theorem",
            "Correlation",
            "Variance",
        ),
    },
    "logic-foundations": {
        "tags": ["propositional logic", "first-order logic", "boolean algebra", "truth table", "mathematical proof"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Propositional_calculus",
            "First-order_logic",
            "Boolean_algebra",
            "Truth_table",
            "De_Morgan's_laws",
            "Mathematical_proof",
            "Proof_by_contradiction",
            "G%C3%B6del's_incompleteness_theorems",
            "Predicate_(logic)",
        ),
    },
    "lambda-type-theory": {
        "tags": ["lambda calculus", "type theory", "type system", "type inference", "hindley-milner", "dependent type"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Lambda_calculus",
            "Type_theory",
            "Type_system",
            "Hindley%E2%80%93Milner_type_system",
            "Curry%E2%80%93Howard_correspondence",
            "Dependent_type",
            "Polymorphism_(computer_science)",
            "Type_inference",
            "Algebraic_data_type",
        ),
    },
    "category-theory": {
        "tags": ["category theory", "functor", "monad", "morphism", "natural transformation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Category_theory",
            "Category_(mathematics)",
            "Functor",
            "Monad_(category_theory)",
            "Morphism",
            "Natural_transformation",
        ),
    },
    "information-theory": {
        "tags": ["information theory", "shannon entropy", "channel capacity", "error correction", "hamming code"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Information_theory",
            "Entropy_(information_theory)",
            "Channel_capacity",
            "Error_detection_and_correction",
            "Hamming_code",
            "Reed%E2%80%93Solomon_error_correction",
            "Kolmogorov_complexity",
            "Shannon%E2%80%93Hartley_theorem",
            "Cyclic_redundancy_check",
            "Checksum",
        ),
    },
    "computational-geometry": {
        "tags": ["computational geometry", "convex hull", "voronoi", "triangulation", "point in polygon"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Computational_geometry",
            "Convex_hull",
            "Voronoi_diagram",
            "Delaunay_triangulation",
            "Point_in_polygon",
            "Ray_casting",
            "Sweep_line_algorithm",
            "Closest_pair_of_points_problem",
        ),
    },
    "optimization": {
        "tags": ["mathematical optimization", "linear programming", "convex optimization", "simplex", "lagrange multiplier"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Mathematical_optimization",
            "Linear_programming",
            "Convex_optimization",
            "Simplex_algorithm",
            "Lagrange_multiplier",
            "Integer_programming",
            "Combinatorial_optimization",
            "Knapsack_problem",
            "Travelling_salesman_problem",
        ),
    },
}
