"""Design beyond GoF: architecture patterns, concurrency patterns, code quality,
process (agile/devops/SRE), and the canonical books of the craft."""

from .common import CC_BY_SA, wiki

DOMAINS = {
    "architecture-patterns": {
        "tags": ["event-driven architecture", "cqrs", "message broker", "publish-subscribe", "service-oriented", "hexagonal architecture"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Software_architecture",
            "Event-driven_architecture",
            "Command_Query_Responsibility_Segregation",
            "Service-oriented_architecture",
            "Message_broker",
            "Publish%E2%80%93subscribe_pattern",
            "Model%E2%80%93view%E2%80%93viewmodel",
            "Multitier_architecture",
            "Monolithic_application",
            "Hexagonal_architecture_(software)",
            "Enterprise_service_bus",
            "Architectural_pattern",
        ),
    },
    "concurrency-patterns": {
        "tags": ["thread pool", "lock-free", "compare-and-swap", "coroutine", "synchronization primitive", "atomic operation"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Thread_pool",
            "Readers%E2%80%93writer_lock",
            "Compare-and-swap",
            "Lock_(computer_science)",
            "Non-blocking_algorithm",
            "Software_transactional_memory",
            "Coroutine",
            "Green_thread",
            "Double-checked_locking",
            "Monitor_(synchronization)",
            "Memory_barrier",
            "Spinlock",
        ),
    },
    "code-quality": {
        "tags": ["refactoring", "code smell", "technical debt", "cyclomatic complexity", "coupling", "clean code"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Code_refactoring",
            "Code_smell",
            "Technical_debt",
            "Cyclomatic_complexity",
            "Coupling_(computer_programming)",
            "Cohesion_(computer_science)",
            "Don't_repeat_yourself",
            "KISS_principle",
            "You_aren't_gonna_need_it",
            "Separation_of_concerns",
            "Defensive_programming",
            "Naming_convention_(programming)",
        ),
    },
    "agile-devops": {
        "tags": ["agile", "scrum", "kanban", "devops", "continuous delivery", "pair programming"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Agile_software_development",
            "Scrum_(software_development)",
            "Kanban_(development)",
            "DevOps",
            "Continuous_delivery",
            "Extreme_programming",
            "Pair_programming",
            "Waterfall_model",
            "Software_development_process",
            "Infrastructure_as_code",
        ),
    },
    "sre-observability": {
        "tags": ["site reliability", "sre", "observability", "monitoring", "high availability", "fault tolerance", "chaos engineering"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Site_reliability_engineering",
            "Service-level_objective",
            "Service-level_agreement",
            "High_availability",
            "Fault_tolerance",
            "IT_disaster_recovery",
            "Chaos_engineering",
            "Application_performance_management",
            "Tracing_(software)",
            "Log_management",
            "Incident_management",
            "Single_point_of_failure",
        ),
    },
    "swe-practice": {
        "tags": ["semantic versioning", "software license", "technical documentation", "twelve-factor", "code convention"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Software_versioning",
            "Software_license",
            "Open-source_license",
            "Software_documentation",
            "Twelve-Factor_App_methodology",
            "Software_maintenance",
            "Software_deployment",
            "Legacy_system",
            "Software_rot",
        ) + ["https://semver.org/"],
    },
    "canonical-books": {
        "tags": ["sicp", "programming book", "mythical man-month", "pragmatic programmer", "design patterns book", "taocp"],
        "license": CC_BY_SA,
        "pages": wiki(
            "Structure_and_Interpretation_of_Computer_Programs",
            "The_Art_of_Computer_Programming",
            "Design_Patterns",
            "The_Mythical_Man-Month",
            "The_Pragmatic_Programmer",
            "Code_Complete",
            "The_C_Programming_Language",
            "Compilers:_Principles,_Techniques,_and_Tools",
            "Introduction_to_Algorithms",
            "Clean_Code",
            "The_Cathedral_and_the_Bazaar",
            "Peopleware:_Productive_Projects_and_Teams",
        ),
    },
}
